microsoft/LightGBM

include/LightGBM/config.h, include/LightGBM/utils/log.h, include/LightGBM/utils/lru_pool.h, src/io/config.cpp, src/treelearner/data_parallel_tree_learner.cpp, src/treelearner/serial_tree_learner.cpp, src/treelearner/serial_tree_learner.h, windows/LightGBM.vcxproj, windows/LightGBM.vcxproj.filters
=> add lru pool to reduce memory usage when #feature is large(#4)

src/application/application.cpp, src/metric/dcg_calculator.cpp
update for correct Init in DCGCalculator.
=> update for correct Init in DCGCalculator.

include/LightGBM/boosting.h, include/LightGBM/config.h, include/LightGBM/dataset.h, include/LightGBM/utils/common.h, include/LightGBM/utils/pipeline_reader.h, include/LightGBM/utils/text_reader.h, src/application/application.cpp, src/application/predictor.hpp, src/boosting/gbdt.cpp, src/boosting/gbdt.h, src/io/config.cpp, src/io/dataset.cpp, src/io/metadata.cpp, src/io/parser.cpp, src/io/parser.hpp, src/network/linkers_socket.cpp, src/objective/rank_objective.hpp
=> To solve #41

include/LightGBM/c_api.h, include/LightGBM/config.h, include/LightGBM/dataset.h, src/application/application.cpp, src/boosting/boosting.cpp, src/c_api.cpp, src/io/config.cpp, src/io/dataset.cpp, src/io/metadata.cpp, src/io/sparse_bin.hpp, windows/LightGBM.vcxproj, windows/LightGBM.vcxproj.filters
In progress now. Open this to discuss during development.
=> [in progress] c_api

src/io/bin.cpp
The logic of assigning 'big count' value first and using is_big_count_value is actually correct. 
Problem about current bin finder: the algorithm is not 'symmetric'. For a distribution with big count small value and small count big value, big count small value becomes unique bins at the beginning and mean_bin_size decreases, then small count big value is built into bins with size << static_mean_bin_size. On the other hand, for a distribution with small count small value and big count big value, small count small value is built into bins with size = static_mean_bin_size at the beginning. But these two cases should be almost symmetric.
Solution: calculate is_big_count_value at the beginning and update mean_bin_size.
=> fix problem in bin finder

examples/python-guide/README.md, examples/python-guide/advanced_example.py, examples/python-guide/simple_example.py, examples/python-guide/sklearn_example.py, python-package/lightgbm/basic.py, python-package/lightgbm/callback.py, python-package/lightgbm/engine.py, python-package/lightgbm/sklearn.py
Include:
- Set feature names
- Directly use categorical features without one-hot encoding
- Load model file to continue training
- Decay learning rates (with lambda function)
- Self-defined objective function
- Self-defined eval metric
- Callback function
Also clean some error message.
=> add an advanced python example

docs/Python_API.md, docs/autodoc.py, docs/css/extra.css, mkdocs.yml, python-package/lightgbm/basic.py, python-package/lightgbm/engine.py, python-package/lightgbm/sklearn.py
I write  a script `autodoc.py`, it will generate `Python_API.md` in docs according to `__doc__` in python-packages. Part of `Python_API.md` is altered by hand. (I think I only change `LGBMModel` to `Common methods`.)
@guolinke I don't know where you plan to put these docs. You can try install mkdocs with pip, then run `mkdocs serve` under lightGBM home directory and open `http://127.0.0.1:8000/Python_API/` with browser to take a look.
=> add python docs

examples/python-guide/sklearn_example.py, python-package/lightgbm/libpath.py
=> add gridsearch example for python sklearn

docs/Parameters.md, examples/python-guide/advanced_example.py, python-package/lightgbm/engine.py, src/boosting/dart.hpp, tests/python_package_test/test_sklearn.py
=> add learning rate to dart

.travis.yml, docs/Python-API.md, python-package/README.rst, python-package/lightgbm/basic.py, python-package/lightgbm/callback.py, python-package/lightgbm/sklearn.py, tests/python_package_test/test_engine.py, tests/python_package_test/test_sklearn.py
@guolinke there are 3 unittests cannot pass. Can you help check the reasons? I use `@unittest.skip("Can't pass yet")` to denote them.
=> rewrite test with unittest

docs/Parameters.md, include/LightGBM/config.h, python-package/lightgbm/basic.py, src/boosting/dart.hpp, src/io/config.cpp
also provide a dart version from xgboost
=> Adapt learning rate to DART

python-package/lightgbm/basic.py
=> add is_numeric for param_dict_to_str

src/boosting/gbdt.cpp
This commit fixes https://github.com/Microsoft/LightGBM/issues/154#issuecomment-269908741.
=> Fix the initializer list of GBDT

docs/Python-API.md, examples/python-guide/sklearn_example.py, python-package/lightgbm/basic.py, python-package/lightgbm/sklearn.py, src/metric/binary_metric.hpp, tests/python_package_test/test_engine.py, tests/python_package_test/test_sklearn.py
related to #154 
In sklearn, feature_importance_ is an attribute rather than a method. It will be dumped and loaded by pickle/joblib.
Also clean some codes in fit().
1. params["objective"] already equals to self.objective with self.get_params(), make sure it's not a callable function
2. eval_metric can have other options(such as set), let params_to_dict check it
3. the following code seems not necessary, what's it for
```
for val in evals_result.items(): 
evals_result_key = list(val[1].keys())[0]
evals_result[val[0]][evals_result_key] = val[1][evals_result_key]
```
=> add @property to sklearn interface

docs/Python-API.md, python-package/lightgbm/sklearn.py
=> add more config to sklearn

python-package/lightgbm/basic.py, python-package/lightgbm/sklearn.py, tests/c_api_test/test.py
What I did is to move _InnerDataset.__int__ into Dataset as _lazy_init, turn every _InnerDataset(...) into _lazy_init(...).
=> simplify Dataset class

python-package/lightgbm/callback.py, python-package/lightgbm/engine.py, tests/python_package_test/test_engine.py
@guolinke I think CVBooster is also not needed in lightgbm, because we already store dataset in Booster.
=> fix reset parameter; re-define CVBooster

docs/FAQ.md, python-package/FAQ.md, python-package/README.rst, python-package/lightgbm/basic.py, python-package/lightgbm/callback.py, python-package/lightgbm/engine.py, python-package/lightgbm/sklearn.py, python-package/setup.py, tests/python_package_test/test_engine.py
`_is_constructed` -> `handle is not None` to avoid method call overhead.
I move python troubleshooting to docs, and add an explanation about dataset lazy init.
=> `_is_constructed` -> `handle is not None`; add FAQ for docs

docs/Parameters.md, docs/Python-API.md, include/LightGBM/config.h, python-package/lightgbm/sklearn.py, src/io/config.cpp, src/metric/metric.cpp, src/metric/regression_metric.hpp, src/objective/objective_function.cpp, src/objective/regression_objective.hpp
Add [Huber loss](https://en.wikipedia.org/wiki/Huber_loss).
Thanks!
=> Add Huber loss

pmml/README.md, pmml/pmml.py
We don't need to convert the float values read from LightGBM_model.txt to Decimal objects. We 
aren't doing any computation with the float values. Whatever the script reads from the model file, it
prints out to the pmml file.
=> Removing the string to decimal conversion for float values

docs/Parameters.md, include/LightGBM/utils/common.h, src/objective/objective_function.cpp, src/objective/regression_objective.hpp
=> Add L1 objective function

docs/Parameters.md, docs/Python-API.md, include/LightGBM/config.h, python-package/lightgbm/sklearn.py, src/io/config.cpp, src/metric/metric.cpp, src/metric/regression_metric.hpp, src/objective/objective_function.cpp, src/objective/regression_objective.hpp
http://research.microsoft.com/en-us/um/people/zhang/INRIA/Publis/Tutorial-Estim/node24.html
TODO:
=> Add Fair loss

.travis.yml, pmml/pmml.py, tests/python_package_test/test_basic.py
=> refine pmml.py

docs/FAQ.md, python-package/setup.py
https://github.com/dmlc/xgboost/pull/1947
the solution from this pr should work, it did use relative path in SOURCE.txt
related to #135 #141
=> solve libpath issue

python-package/lightgbm/basic.py, python-package/lightgbm/callback.py, python-package/lightgbm/compat.py, python-package/lightgbm/engine.py, python-package/lightgbm/sklearn.py
move all compatibility to compat.py
=> refine compatibility

R-package/R/lgb.Booster.R
This fixes the R package which does not compile (commit reference: 0ddb3ef).
One can test compiling with my changes (with success) using:
```r
devtools::install_github("Laurae2/LightGBM", subdir = "R-package", ref = "patch-2")
```
=> Fix R package compilation error

README.md
Just a couple of wording tweaks to make sentences easier to read. 
Seeing some promising signs during initial testing! Thanks for building such a great package.
=> Minor fixes and clarifications

.travis.yml, docs/Python-API.md, python-package/lightgbm/basic.py, python-package/lightgbm/engine.py, python-package/lightgbm/sklearn.py, tests/python_package_test/test_engine.py, tests/python_package_test/test_sklearn.py
#192 
also support categorical str
=> suppprt pandas categorical

python-package/lightgbm/sklearn.py, src/io/config.cpp
=> do not check metrics w/o eval set

docs/Python-intro.md, python-package/lightgbm/compat.py
=> fix sklearn interface compat

python-package/lightgbm/callback.py
1. use list instead of dict
2. use operator(gt, lt) instead of multiplication
3. use best_msg_buffer, only join best_msg once per iter
=> refine callback

python-package/lightgbm/basic.py, python-package/lightgbm/engine.py, tests/python_package_test/test_engine.py
=> fix bug for pandas auto categorical_feature

.github/ISSUE_TEMPLATE.md, docs/Python-intro.md, python-package/lightgbm/basic.py
=> fix warning; fix doc bug

include/LightGBM/boosting.h, src/boosting/boosting.cpp, src/boosting/gbdt.cpp, src/boosting/gbdt.h
I've added checks to know whether LoadFileToBoosting and SaveModelToFile succeeded.
=> Added success return value to LoadFileToBoosting and SaveModelToFile

include/LightGBM/boosting.h, src/boosting/gbdt.cpp, src/boosting/gbdt.h
Added `SaveModelToString` and modified `SaveModelToFile` to use it.
To be merged after https://github.com/Microsoft/LightGBM/pull/234
=> Add SaveModelToString()

.travis.yml, docs/Python-API.md, examples/python-guide/README.md, examples/python-guide/plot_example.py, python-package/lightgbm/__init__.py, python-package/lightgbm/basic.py, python-package/lightgbm/plotting.py, tests/python_package_test/test_plotting.py
=> [python-package] add plot importance

src/boosting/gbdt.cpp
`feature_infos_` was not used when loading a model, which can cause problems when trying to save it, as it will crash when trying to access it.
=> Add `feature_infos` to LoadModelFromString()

python-package/lightgbm/basic.py, python-package/lightgbm/compat.py, tests/python_package_test/test_engine.py
=> use json instead of repr/eval for pandas_categorical

.travis.yml, docs/Python-API.md, examples/python-guide/plot_example.py, python-package/lightgbm/__init__.py, python-package/lightgbm/plotting.py, tests/python_package_test/test_plotting.py
=> [python-package] add plot tree

python-package/lightgbm/engine.py
=> fix cv bug

docs/Python-API.md, examples/python-guide/plot_example.py, python-package/lightgbm/__init__.py, python-package/lightgbm/plotting.py, tests/python_package_test/test_plotting.py
=> [python-package] add plot metrics

docs/Parameters.md, docs/Python-API.md, include/LightGBM/config.h, python-package/lightgbm/sklearn.py, src/io/config.cpp, src/metric/metric.cpp, src/metric/regression_metric.hpp, src/objective/objective_function.cpp, src/objective/regression_objective.hpp
=> Support Poisson regression

docs/Python-API.md, examples/python-guide/simple_example.py, include/LightGBM/boosting.h, include/LightGBM/c_api.h, python-package/lightgbm/basic.py, src/boosting/gbdt.h, src/c_api.cpp, tests/python_package_test/test_engine.py
=> add feature name to Booster

docker/README.md, docker/dockerfile-python
I already test it. pls give another test before merge it.
=> add dockerfile

docs/Python-API.md, docs/Readme.md, python-package/lightgbm/basic.py, python-package/lightgbm/compat.py, python-package/lightgbm/plotting.py, tests/python_package_test/test_plotting.py
=> refine plotting library

.gitignore, docs/Python-API.md, python-package/lightgbm/engine.py, tests/python_package_test/test_engine.py
=> add data_splitter to cv

include/LightGBM/tree.h, src/io/tree.cpp
=> output shrinkage for trees

src/objective/multiclass_objective.hpp
=> add un_balance to multi class

examples/python-guide/advanced_example.py, examples/python-guide/plot_example.py, examples/python-guide/simple_example.py, examples/python-guide/sklearn_example.py
remove annoying warnings in example #341
=> fix python warning

docs/Parameters.md
thx to #356 
the link of ```Fair loss``` is not so good yet, I am going to find if there is a better link
=> [WIP] fix broken links

python-package/lightgbm/basic.py
=> [WIP] fix getstate in _InnerPredictor

docs/Python-API.md, examples/python-guide/README.md, examples/python-guide/advanced_example.py, examples/python-guide/simple_example.py
It's very helpful to show how to use the saved model for a predict task. 
The existing example only shows how to save or dump models and how to continue training with init model.
I'm not pretty sure whether `Booster(model_file)` is the most proper method to load a saved model, but at least it works.
=> Add Python examples on how to load models

R-package/README.md
README change to tell user to ignore warning message due to submodule usage (Boost).
=> [R-package] User can safely ignore warning message

docs/Python-API.md, examples/python-guide/plot_example.py, python-package/lightgbm/plotting.py
also add a example with graphviz :)
=> python-package: add graphviz.Digraph parameters

docs/Parameters.md
Reflects changes from Microsoft/LightGBM@18d6a90 to documentation.
=> Update documentation for default parameters

python-package/lightgbm/basic.py, python-package/lightgbm/callback.py, python-package/lightgbm/engine.py, python-package/lightgbm/sklearn.py, tests/python_package_test/test_engine.py
related to #329 #360 
not only apply for early stopping
=> [python-package] add best score

docs/Python-API.md, python-package/lightgbm/sklearn.py
=> python-package: support valid_names in scikit-learn API

.travis.yml, CMakeLists.txt, include/LightGBM/bin.h, include/LightGBM/boosting.h, include/LightGBM/dataset.h, include/LightGBM/meta.h, include/LightGBM/objective_function.h, include/LightGBM/tree_learner.h, src/boosting/dart.hpp, src/boosting/gbdt.cpp, src/boosting/gbdt.h, src/boosting/goss.hpp, src/c_api.cpp, src/io/dataset.cpp, src/io/dense_bin.hpp, src/io/dense_nbits_bin.hpp, src/io/ordered_sparse_bin.hpp, src/io/sparse_bin.hpp, src/objective/binary_objective.hpp, src/objective/multiclass_objective.hpp, src/objective/rank_objective.hpp, src/objective/regression_objective.hpp, src/treelearner/gpu_tree_learner.cpp, src/treelearner/gpu_tree_learner.h, src/treelearner/leaf_splits.hpp, src/treelearner/serial_tree_learner.cpp, src/treelearner/serial_tree_learner.h, src/treelearner/voting_parallel_tree_learner.cpp, windows/LightGBM.vcxproj, windows/LightGBM.vcxproj.filters
Reverts Microsoft/LightGBM#418 .
Found this will drop on accuracy when testing it on more data sets.
And only gains little speed-up.
=> Revert "[WIP]faster histogram sum up"

python-package/lightgbm/basic.py, python-package/lightgbm/sklearn.py
=> [python-package] sklearn interface: free dataset after fit 

include/LightGBM/dataset.h, python-package/lightgbm/basic.py, src/io/dataset_loader.cpp, tests/python_package_test/test_engine.py
=> replace whitespaces with underlines in feature name

CMakeLists.txt, src/treelearner/gpu_tree_learner.cpp, src/treelearner/gpu_tree_learner.h, src/treelearner/ocl/histogram16.cl, src/treelearner/ocl/histogram256.cl, src/treelearner/ocl/histogram64.cl
This PR is trying to fix compilation problems in GPU code with MSVC 2015, in issue #439.
@tt83 Can you test if it removes all warnings?
For the long string literal problem I am still trying to figure out a clean resolution.
=> Fix compilation problems with MSVC

python-package/lightgbm/basic.py, python-package/lightgbm/compat.py, python-package/lightgbm/engine.py, tests/python_package_test/test_engine.py, tests/python_package_test/test_sklearn.py
#390 
it's strange that it sometimes causes segmentation fault (1 of 3 times), cannot figure out why yet
=> [python-package] lambdarank cv split by group

src/io/tree.cpp
#462 
the reason is, there exists tree with only one node
=> fix dump tree

python-package/lightgbm/basic.py
=> [python-package] fix feature importance

include/LightGBM/application.h, include/LightGBM/boosting.h, include/LightGBM/config.h, include/LightGBM/tree.h, src/application/application.cpp, src/boosting/gbdt.cpp, src/boosting/gbdt.h, src/io/config.cpp, src/io/tree.cpp
#466 
checklist:
new config:
task : convert_model
convert_model_language : cpp
if convert_model_language is set when task = train, the model will also be converted after training stops
convert_model : filename of output convert_model
=> [MRG] translate model to if-else

docs/Python-API.md, python-package/lightgbm/engine.py
=> fix cv function metric bug

tests/python_package_test/test_engine.py, tests/python_package_test/test_sklearn.py
The test cases are not quite readable with global template, it's unfriendly for new contributors. And it sometimes messes up with global variables unexpectedly.
=> [MRG] re-write test cases: remove global template

docs/FAQ.md, docs/Parameters-tuning.md, docs/Parameters.md, docs/Python-API.md, docs/Quick-Start.md, docs/index.rst
https://github.com/Microsoft/LightGBM/issues/485
=> docs: add basic contents to table of contetns

R-package/R/lgb.Booster.R, R-package/src/lightgbm_R.cpp, R-package/src/lightgbm_R.h
Changes to lgb.Booster.R:
Added method to call LGBM_BoosterLoadModelFromString_R if model_str is provided for initialization, added option to load from model_str in lgb.load
Changes to lightgbm_r.cpp:  Added LGBM_BoosterLoadModelFromString_R to call the C api
=> Adding ability to load model from string in R

docs/conf.py, docs/index.rst, docs/python/lightgbm.rst
This PR allows us to build python documents from source files automatically :)
https://github.com/Microsoft/LightGBM/issues/485
=> docs: build python docs from source files

README.md
=> Add documentation status badge to README.md

docs/conf.py, python-package/lightgbm/basic.py, python-package/lightgbm/libpath.py
https://github.com/Microsoft/LightGBM/issues/485
=> docs: fix loading library

docs/Python-API.md, python-package/lightgbm/engine.py, tests/python_package_test/test_engine.py, tests/python_package_test/test_sklearn.py
https://github.com/Microsoft/LightGBM/pull/479#issuecomment-298356703
=> [python-package] change default best_iteration to 0

docs/python/lightgbm.rst
=> docs: improve python api documents on Read the Docs

docs/conf.py
http://www.sphinx-doc.org/en/stable/ext/autodoc.html#confval-autoclass_content
=> docs: show __init__ docstrings

README.md, docs/GPU-Targets.md, docs/GPU-Windows.md, docs/Parameters.md
Some more for #511:
* Add link to interactive docs
* Add link to Read The Docs on main page
* Add link to interactive parameters on parameters page
=> Add external links and some news

include/LightGBM/bin.h, include/LightGBM/dataset.h, include/LightGBM/feature_group.h, include/LightGBM/meta.h, include/LightGBM/tree.h, include/LightGBM/utils/common.h, src/boosting/gbdt.cpp, src/io/bin.cpp, src/io/config.cpp, src/io/dataset.cpp, src/io/dense_bin.hpp, src/io/dense_nbits_bin.hpp, src/io/sparse_bin.hpp, src/io/tree.cpp, src/treelearner/data_partition.hpp, src/treelearner/feature_histogram.hpp, src/treelearner/serial_tree_learner.cpp, src/treelearner/split_info.hpp, src/treelearner/voting_parallel_tree_learner.cpp
Refer to #122 
will try following three treatments for missing values, and auto choose the best one.
1. min(feature_values)
2. 0
3. max(feature_values)
How to use: 
1. The zero feature values (```-1e-20f < value <= 1e-20f```) will be treated as missing values,
2. If you want to keep both zero values and missing values, please convert zero values manually ( absolute value should greater than ```1e-20f```) .
=> Support learn the best direction for missing value

CMakeLists.txt
=> Add -Wextra to compile options

docs/Key-Events.md
Add four key events:
* If-Then-Else C++ Trees code generation
* Read the docs
* Interactive website for parameters
* Missing values support
=> Update Key Events file

python-package/setup.py
is master currently in v0.2 or 0.1?
=> version 0.2?

docs/Key-Events.md
To keep up with the current LightGBM improvements.
=> Add missing values key events

R-package/R/lgb.Booster.R, R-package/R/readRDS.lgb.Booster.R, R-package/man/lgb.load.Rd, R-package/man/lgb.save.Rd, R-package/man/readRDS.lgb.Booster.Rd
Fix https://github.com/Microsoft/LightGBM/issues/538
Fix also broken example.
Passing RDS test:
```r
test <- agaricus.test
dtest <- lgb.Dataset.create.valid(dtrain, test$data, label = test$label)
valids <- list(test = dtest)
model <- lgb.train(params,
dtrain,
100,
valids,
min_data = 1,
learning_rate = 1,
early_stopping_rounds = 10)
saveRDS.lgb.Booster(model, "model.rds")
new_model <- readRDS.lgb.Booster("model.rds")
mean(predict(new_model, test$data) - test$label)
```
```r
> library(lightgbm)
Loading required package: R6
Warning message:
package ‘R6’ was …
```
=> [R-package] Stop using temporary model files

python-package/lightgbm/sklearn.py
This commit follows Microsoft/LightGBM@3abff37
=> python-package: add use_missing parameter

docs/FAQ.md
Add to FAQ about GPU giving non reproducible results: https://github.com/Microsoft/LightGBM/issues/559
=> Add reproducible warn for Microsoft/LightGBM#559

R-package/R/lgb.prepare.R, R-package/R/lgb.prepare2.R, R-package/R/lgb.prepare_rules.R, R-package/R/lgb.prepare_rules2.R, R-package/man/lgb.prepare.Rd, R-package/man/lgb.prepare2.Rd, R-package/man/lgb.prepare_rules.Rd, R-package/man/lgb.prepare_rules2.Rd
Full integers don't work in LightGBM.
=> [WIP] Swap integers/numerics naming

docs/FAQ.md
=> Recommend first gpu_use_dp = true

docs/FAQ.md
Recommend several strategies to lower RAM used.
Fixes https://github.com/Microsoft/LightGBM/issues/562.
=> Add strategies to lower RAM used to FAQ

python-package/lightgbm/sklearn.py
=> support kwargs for sklearn

include/LightGBM/config.h, python-package/lightgbm/sklearn.py
Give a warning when meet "invalid" parameters. Can help avoid typos.
=> check invalid parameters

README.md
=> LightGBM Slack team is available.

R-package/src/install.libs.R
Fixes #607 `paste0` ambiguity.
=> [R-package] Remove paste0 ambiguity for paths

R-package/README.md
Fixes #610 ([R-package] Docs: add warning for MSVCP140.dll missing)
=> [R-package] Add warning for MSVCP140.dll missing

python-package/lightgbm/basic.py, src/io/tree.cpp
=> [python] fix dump model with infinite threshold

python-package/lightgbm/basic.py
#621 
@vivekk-ezdi any suggestions on this change? 1-d list will convert to numpy first, then check dimension with the same procedure as numpy.
=> [python] handle list for prediction

R-package/demo/cross_validation.R
=> Minor typo in comments

python-package/lightgbm/sklearn.py
eval_at has been broken after e465f92aa389b42da3cd596a2df4a59ae5032de7.
This commit will fix eval_at.
=> python-package: fix eval_at

.travis.yml, .travis/setup.sh, .travis/test.sh
=> travis osx support

.travis.yml, .travis/setup.sh, .travis/test.sh, python-package/README.rst, python-package/setup.py
=> [MRG] [python] setup.py custom install & sdist

docker/dockerfile-python
=> Fix dockerfile

docs/Parameters-tuning.md
=> Fixes english mistakes in Parameters-tuning.md

python-package/lightgbm/callback.py
thanks for building in early_stopping! super useful.
=> minor update to language for early stopping

python-package/lightgbm/basic.py, python-package/lightgbm/engine.py
=> [python] add keep_training_booster

python-package/lightgbm/basic.py
=> [python] fix subset params

docs/Parameters.md, docs/Quick-Start.md, src/boosting/boosting.cpp, src/boosting/dart.hpp, src/boosting/gbdt.cpp, src/boosting/gbdt.h, src/boosting/gbdt_prediction.cpp, src/boosting/rf.hpp, src/boosting/score_updater.hpp, src/io/config.cpp, tests/python_package_test/test_engine.py
fix #47. 
Set ```boosting_type=rf``` to enable.
=> Random Forest Mode

python-package/MANIFEST.in, python-package/setup.py
This PR simply includes the license file in the `MANIFEST.in` so that it is included in the source distribution.
=> Update MANIFEST.in to include LICENSE

docs/FAQ.md
Fixes https://github.com/Microsoft/LightGBM/issues/691 and for new users who try LightGBM and unexpectedly get their R/Python kernel session down.
=> Add Random Forest FAQ crash solution

docs/Key-Events.md
Anything to add?
@guolinke @wxchan
=> Update key events to 15th July 2017

include/LightGBM/utils/common.h, src/metric/metric.cpp, src/metric/xentropy_metric.hpp, src/objective/objective_function.cpp, src/objective/xentropy_objective.hpp
Extension to the objective and metric options
(sort-of merged classification on outcomes/regression on probabilities)
- standard cross entropy, evaluates on continuous labels in [0, 1]
- standard cross entropy with offset term (Kullback-Leibler divergence)
- special-weight cross-entropy that can be used to learn intensity functions (weights are lengths/duration)
=> cross entropy metrics and objective

docs/Parameters.md
https://github.com/Microsoft/LightGBM/issues/705#issuecomment-315976423
=> Add `gaussian_eta` to Parameters.md

docs/FAQ.md
Fixes https://github.com/Microsoft/LightGBM/issues/698 and any related issues.
=> [R-package] Add lgb.unloader to FAQ

python-package/lightgbm/basic.py
missing parameter "self" in signature of Booster.get_leaf_output
=> [python package] function get_leaf_output bugfixed

R-package/R/callback.R, R-package/R/lgb.Booster.R
Attempt to add best score to R package.
~~(wait for my request to merge)~~
fixes Microsoft/LightGBM#686
=> [R-package] Add best score

python-package/lightgbm/engine.py
@wxchan opinions?
Fixes https://github.com/Microsoft/LightGBM/issues/724 inconsistency of CV behavior.
=> Python CV should be stratified by default

src/objective/xentropy_objective.hpp
See the following for the reason: https://github.com/Microsoft/LightGBM/commit/a3c63ff76df6d681cef5ad8af6bfc3afe1edbb3b#commitcomment-23336357
=> Fix issue found on a3c63ff

python-package/lightgbm/basic.py
attempt to resolve #711 as suggested by replacing the previous numeric check in is_1d_list in basics.py with a call to is_numeric
=> python package: use is_numeric check in is_1d_list in basics.py

R-package/README.md, docs/FAQ.md
Fixes https://github.com/Microsoft/LightGBM/issues/749
=> Add warning for many core systems in Windows

docs/Parameters.md, include/LightGBM/bin.h, include/LightGBM/config.h, include/LightGBM/dataset.h, include/LightGBM/feature_group.h, include/LightGBM/meta.h, include/LightGBM/tree.h, include/LightGBM/utils/common.h, src/boosting/gbdt.cpp, src/boosting/rf.hpp, src/c_api.cpp, src/io/bin.cpp, src/io/config.cpp, src/io/dataset.cpp, src/io/dataset_loader.cpp, src/io/dense_bin.hpp, src/io/dense_nbits_bin.hpp, src/io/parser.hpp, src/io/sparse_bin.hpp, src/io/tree.cpp, src/treelearner/data_partition.hpp, src/treelearner/feature_histogram.hpp, src/treelearner/serial_tree_learner.cpp, src/treelearner/split_info.hpp, src/treelearner/voting_parallel_tree_learner.cpp, tests/python_package_test/test_engine.py
Refer to #744 
add a parameter ```zero_as_missing```, True will use zeros to represent missing, otherwise will use `na` .
=> Better missing value handle

docs/GPU-Performance.md, docs/GPU-Tutorial.md
This PR simply adds a link to our paper on GPU acceleration in documentations, providing more details on the algorithm and benchmarks. Please kindly merge. Thanks!
=> Add a reference to our GPU acceleration paper

python-package/lightgbm/basic.py
in reference to comment by @wxchan on issue #745
=> [python package] now use set instead of list in python package basic.Dataset.get_ref_chain

appveyor.yml, src/boosting/gbdt.cpp, src/boosting/gbdt.h
=> fix model feature importances

R-package/R/lgb.Booster.R, R-package/R/lgb.Dataset.R, R-package/R/lgb.Predictor.R, R-package/R/utils.R, src/lightgbm_R.cpp
=> fix R crash problem.

python-package/lightgbm/basic.py, python-package/lightgbm/engine.py
to fix #775 , @guolinke can you help check the logic?
=> [python] Dataset params back up before training

python-package/lightgbm/basic.py
to fix #773 
@j-mark-hou can you also help check if this works?
=> [python] fix categorical_feature in Dataset

R-package/R/lgb.Booster.R
Fixes https://github.com/Microsoft/LightGBM/issues/795
This PR also does not bypass the current stop mechanisms. When R encounters a `stop` inside a `try`, the `stop` should take precedence over `try`.
The expected error appears:
```r
Error in .subset2(public_bind_env, "initialize")(...) : 
lgb.Booster: cannot create Booster handle
```
Reproducible code:
```r
test <- agaricus.test
dtest <- lgb.Dataset.create.valid(dtrain, test$data, label = test$label)
valids <- list(test = dtest)
dtrain$construct()
dtest$construct()
model <- lgb.train(params,
dtrain, …
```
=> [R-package] Unhandled errors must error properly

python-package/lightgbm/plotting.py
Changes made to stop the Invalid decision type in tree model exception while plotting tree in Python
=> Fix Invalid decision type error while plotting tree in Python

python-package/setup.py
Fixed typo in printed message during setup.
=> [Python] Fixed typo

python-package/lightgbm/engine.py, tests/python_package_test/test_engine.py
=> [MRG] [python] check params for num_boost_round & early_stopping_rounds

python-package/lightgbm/basic.py, python-package/lightgbm/engine.py
=> [python] fix python memory leak

docs/GPU-Targets.md, docs/GPU-Windows.md
Update link for AMD APP SDK download.
=> Update link for AMD APP SDK download.

include/LightGBM/tree.h, src/boosting/gbdt.cpp, src/boosting/rf.hpp, src/io/tree.cpp
=> support constant tree (one-leaf tree) .

tests/python_package_test/test_sklearn.py
As discussed in https://github.com/Microsoft/LightGBM/pull/847, I'm sending a test-only version of that PR, rebased on master.
=> TST a test for #851

src/objective/regression_objective.hpp
PR to fix Poisson regression objective gradient/hessian issues.
=> Attempt to address issue #807 Poisson regression objective.

R-package/README.md, README.md, docs/GPU-Tutorial.md, docs/GPU-Windows.md, examples/binary_classification/README.md, examples/lambdarank/README.md, examples/multiclass_classification/README.md, examples/parallel_learning/README.md, examples/python-guide/README.md, examples/regression/README.md, python-package/README.rst
This PR fixes capital letters and formatting in `examples` folder.
=> [docs] fixed capital letters and formating

R-package/R/lgb.model.dt.tree.R
This PR will fix the `lgb.model.dt.tree` function so that `lgb.interprete` function can use column: leaf_parent.
I'm sorry @Laurae2 , I saw your PR very late.
=> Fix R Tree Parse

docs/Parameters.md
Fixes https://github.com/Microsoft/LightGBM/issues/883
=> Add without resampling for bagging

.travis.yml, appveyor.yml, python-package/MANIFEST.in, python-package/lightgbm/libpath.py, python-package/setup.py
This PR moves source files into another directory and it allows perform clean installation (without source files)
Before:
After:
Maybe I forgot to list in `libpath.py` some folders where library file could be located (or remove excess ones), however, all tests and installation cases from README are covered.
=> [python] [setup] removing source files

src/io/config.cpp
=> fix reset parameters

R-package/README.md
The example comes from https://github.com/Microsoft/LightGBM/issues/912#issuecomment-329496254
=> Visual installation example for R-package (Windows + VS)

python-package/lightgbm/basic.py
=> [docs] [python] fixed typo in docstring

include/LightGBM/utils/common.h, src/metric/xentropy_metric.hpp, src/objective/regression_objective.hpp, src/objective/xentropy_objective.hpp
Function names must be in the "Pascal Case" style.
* check_elements_interval_closed to CheckElementsIntervalClosed
* obtain_min_max_sum to ObtainMinMaxSum
=> Fix coding style (#969)

docs/Key-Events.md
Post all links to useful pull requests so we can add more.
=> Update Key Events to September 2017

.travis/test.sh, python-package/README.rst
Refer to https://github.com/Microsoft/LightGBM/pull/976#issuecomment-337606989.
=> [docs] added validation of rst-files into python-package folder

CMakeLists.txt, R-package/README.md, R-package/src/install.libs.R, docs/Installation-Guide.rst, python-package/README.rst, python-package/setup.py
=> [docs][installation] change minimum version of Visual Studio to 2015

docs/Parameters.rst, include/LightGBM/config.h, src/io/config.cpp, src/metric/metric.cpp, src/metric/regression_metric.hpp, src/objective/objective_function.cpp, src/objective/regression_objective.hpp
=> quantile objective function &  metric

include/LightGBM/utils/common.h
=> trivial refine CheckElementsIntervalClosed & ObtainMinMaxSum

include/LightGBM/boosting.h, include/LightGBM/tree.h, src/application/predictor.hpp, src/boosting/gbdt.h, src/boosting/gbdt_model_text.cpp, src/boosting/gbdt_prediction.cpp, src/io/tree.cpp
=> Add func to handle sparse testing data

docs/Parameters.rst, include/LightGBM/config.h, python-package/lightgbm/sklearn.py, src/metric/metric.cpp
=> [python] [docs] fixed objective in sklearn wrapper; added missed objectives & metrics to docs

include/LightGBM/utils/common.h
add feature value handle 'null'
=> add 'null' to missing value

docs/Parameters.rst
=> [docs] added note about max label in rank task

R-package/demo/cross_validation.R
Get rid of unknown file comment in R package demo as outlined in #1085
=> [R] Fix Microsoft/LightGBM#1085

python-package/lightgbm/basic.py
fix #1093 
I tested some cases, should work fine.
=> [python] add try/except in __del__

include/LightGBM/dataset.h, include/LightGBM/meta.h, include/LightGBM/metric.h, src/boosting/gbdt.cpp, src/c_api.cpp, src/io/dataset.cpp, src/io/dataset_loader.cpp, src/io/metadata.cpp, src/metric/binary_metric.hpp, src/metric/dcg_calculator.cpp, src/metric/map_metric.hpp, src/metric/multiclass_metric.hpp, src/metric/rank_metric.hpp, src/metric/regression_metric.hpp, src/metric/xentropy_metric.hpp, src/objective/binary_objective.hpp, src/objective/multiclass_objective.hpp, src/objective/rank_objective.hpp, src/objective/regression_objective.hpp, src/objective/xentropy_objective.hpp
=> support label as double type

.travis/amd_sdk.sh, R-package/R/callback.R, python-package/lightgbm/callback.py, tests/python_package_test/test_engine.py
=> fix early stopping edge case

docs/Parameters.rst
=> Metric parameter doc fix

python-package/lightgbm/compat.py, python-package/lightgbm/sklearn.py
Fixed #1107.
Should we somehow take into account `scale_pos_weight` and `is_unbalance` parameters?
=> [python] added class_weight parameter in sklearn wrapper

src/io/config.cpp
=> fixed typos in checks

docs/Python-Intro.rst
=> [docs] Typo on #119

include/LightGBM/network.h, src/network/linker_topo.cpp, src/network/linkers_socket.cpp, src/network/network.cpp
update network for non powers of 2 workers
=> update network for non powers of 2 workers

docs/GPU-Targets.rst, docs/GPU-Tutorial.rst, docs/GPU-Windows.rst
Better description for GPU and platform IDs in documentation, as suggested by @StrikerRUS in #1185
=> [docs] Update GPU-Tutorial.rst

docs/Experiments.rst
fix the error in the number of experiments
=> fix the error in the number of experiments

include/LightGBM/utils/array_args.h
=> fix a bug in `ArgMaxAtK`

docs/Parameters-Tuning.rst
=> fix a typo in the docs

python-package/lightgbm/basic.py, tests/python_package_test/test_engine.py
=> try to fix problem with multi-dimensional sliced object.

python-package/lightgbm/basic.py, python-package/lightgbm/sklearn.py
Updated objective in LGBMClassifier according to new aliases.
Refer to #1209.
=> [python] updated multiclass objective in sklearn

docs/Installation-Guide.rst
replace the typo “reed" by "read".
=> [docs] Update Installation-Guide.rst

R-package/R/lgb.Booster.R, python-package/lightgbm/basic.py, src/boosting/gbdt.cpp
=> Auto set `objective=None` when using fobj

docs/Installation-Guide.rst
=> [docs] added info about SWIG Java wrapper

docs/Installation-Guide.rst, python-package/README.rst, python-package/setup.py
=> [python][docs] added info about and possibility to install Python-package HDFS version

R-package/R/lgb.Dataset.R, R-package/R/utils.R, R-package/tests/testthat/test_dataset.R, src/io/file_io.cpp
Initializing handle with 0.0 then checking if handle == 0.0 to determine null handle is not a safe way and might cause problems in some systems. Using NA_real_ to initialize handle and using is.na to check null handle are recommended.
=> [R package] Use NA_real_ to initialize handle

include/LightGBM/config.h, python-package/lightgbm/basic.py
Hi, 
Small contribution, :-) Thanks.
=> Typo in the spelling of "overridden"

README.md, docs/Parameters.rst, python-package/README.rst
If it's only my browser's problem, then close this PR.
=> [docs] fixed PyPI version badge

CMakeLists.txt, docs/Parameters.rst, include/LightGBM/config.h, include/LightGBM/dataset.h, include/LightGBM/utils/array_args.h, src/io/config.cpp, src/io/dataset.cpp, src/io/dataset_loader.cpp, src/treelearner/data_parallel_tree_learner.cpp, src/treelearner/feature_histogram.hpp, src/treelearner/gpu_tree_learner.cpp, src/treelearner/leaf_splits.hpp, src/treelearner/serial_tree_learner.cpp, src/treelearner/split_info.hpp, src/treelearner/voting_parallel_tree_learner.cpp, tests/python_package_test/test_engine.py
for #14 
ping @alexvorobiev @AbdealiJK @aldanor @redditur for the tests.
=> Support monotone constraint

include/LightGBM/utils/common.h
Small fix to keep the code consistent
=> Replaced tabs with spaces

docs/Parameters.rst, python-package/lightgbm/sklearn.py
This is an update of the python package docs as well as of parameter description attempting to improve the info on metric usage in evaluation. 
The PR follows the discussion in #1318
=> Metric doc update

README.md, python-package/README.rst
=> [docs] actualized PEP 8 description and links to PyPI

docs/Advanced-Topics.rst, docs/Experiments.rst, docs/FAQ.rst, docs/Features.rst, docs/Parameters-Tuning.rst, docs/Parameters.rst, docs/Python-Intro.rst
No big intentional content changes here. If you find this useful, I might be able to do this on a few other of the docs pages. Let me know if there's a strong preference for having them one file at a time versus all at once in a single pull request.
=> [docs] Edits for grammer and clarity

python-package/lightgbm/basic.py
This PR is a hotfix for #1395.
@guolinke I'm not sure, should the original issue be closed or left open till complete pandas support refine?
=> [python] added check for pandas DataFrame dimensions

CMakeLists.txt, R-package/README.md, README.md, docs/GPU-Tutorial.rst, docs/Key-Events.md, docs/Python-Intro.rst, examples/README.md, examples/python-guide/README.md, examples/python-guide/logistic_regression.py, examples/python-guide/plot_example.py, helper/parameter_generator.py, include/LightGBM/config.h, pmml/README.md, python-package/README.rst, python-package/lightgbm/libpath.py, python-package/setup.py, tests/c_api_test/test_.py
Changed `os.name == 'nt'` to `platform.system() in ('Windows', 'Microsoft')` in Python-package.
Fixed consistency of `Language-package` naming, added description of `parameter_generator.py` and missed contents of `plot_example.py` in README file.
=> [docs][python] made OS detection more reliable and little docs improvements

.travis/test.sh, include/LightGBM/config.h, src/io/config.cpp, src/io/config_auto.cpp
This is continuation of #1409.
=> [docs] generate parameters description from config file. Stage 2

docs/Quick-Start.rst, include/LightGBM/config.h
This is the continuation of #1413.
=> [docs] generate parameters description from config file. Stage 3

include/LightGBM/config.h, src/boosting/gbdt.cpp
This is continuation of #1415.
=> [docs] generate parameters description from config file. Stage 4

include/LightGBM/config.h
This is continuation of #1416.
=> [docs] generate parameters description from config file. Stage 5

docs/Parameters.rst, docs/README.rst, helper/parameter_generator.py, src/io/config_auto.cpp
This is continuation of #1417.
=> [docs] generate parameters description from config file. Final stage

.travis/test.sh
=> [ci] run all python-guide examples at Travis side

docs/.linkcheckerrc
Aghhh!..
Now libsvm site is down.
I remember it was already happened. Need to wait they repair.
=> [ci] ignore tableau site

.travis/setup.sh
All things we need are already installed on Travis's trusty images.
=> [ci] simplified and speeded up Travis

.travis/setup.sh
Reverts Microsoft/LightGBM#1429
=> Revert "[ci] simplified and speeded up Travis"

docs/Parameters.rst, include/LightGBM/config.h
=> [docs] clarified CLI-only params in docs

.travis.yml, .travis/setup.sh, .travis/test.sh
- Moved GPU requirements installation from `test.sh` to `setup.sh`.
- Unified usage of variables (`${variable}` -> `$variable`).
- Removed several excess `cd`s.
=> [ci] refined Travis commands allocation

.travis/test.sh
@huanzhang12 Is it safe to use the latest `compute` submodule in LightGBM? The current one is one year old and 100 commits behind.
=> updated Boost Compute submodule

.travis/setup.sh, .travis/test.sh
I've uploaded a new version of AMD APP SDK, as pointed by @huanzhang12 in https://github.com/Microsoft/LightGBM/issues/1342#issuecomment-396119206 .
But something seems to be wrong: https://travis-ci.org/Microsoft/LightGBM/jobs/390738317#L938
Can you guys help me please? Or maybe it's not worth it to spend time on making it works?..
=> [ci] update AMD APP SDK version

docs/Parameters.rst, include/LightGBM/config.h, include/LightGBM/dataset.h, include/LightGBM/utils/array_args.h, src/io/config_auto.cpp, src/io/dataset.cpp, src/io/dataset_loader.cpp, src/treelearner/feature_histogram.hpp, src/treelearner/voting_parallel_tree_learner.cpp
for #1379 
@rgranvil , would you like to test it ?
=> add per-feature-penalites

src/objective/objective_function.cpp
=> fix load model bug from mape objective

.travis/test.sh, examples/python-guide/plot_example.py, python-package/lightgbm/compat.py, python-package/lightgbm/plotting.py, tests/python_package_test/test_basic.py, tests/python_package_test/test_engine.py, tests/python_package_test/test_plotting.py, tests/python_package_test/test_sklearn.py
Added tests for plotting tree functions and moved all checks of installed modules to `compat.py`.
Refer to #261.
=> [python] tests for plot tree functions and module_INSTALLED variables

.appveyor.yml
The second modified line is some encoding problems,
=> [ci] updated Appveyor version

docs/Features.rst
Previous link is dead (maybe temporarily, as it usually happens).
=> [docs] fixed link

python-package/lightgbm/basic.py, python-package/lightgbm/engine.py, python-package/lightgbm/sklearn.py
Refer to #1483, #1373.
Unified descriptions of all occurrences of `feval` parameter.
@guolinke Please check them for the truth.
=> [docs] clarified feval parameter

python-package/lightgbm/basic.py
This PR documents the enhancement introduced in #1474.
=> [docs] updated docstring according to new possible type of input data

docs/Installation-Guide.rst
Refer to https://github.com/Microsoft/LightGBM/commit/65e63967e786fe6797f79ba515e39b47ad870dbc#comments
=> [docs] formatting hotfix

python-package/lightgbm/basic.py
Use `numpy.zeros` instead of list comprehensions.
=> [python] simplified code with np.zeros

.travis/setup.sh
Fixes #1558.
Suppresses #1559.
=> [ci] fix macOS builds at Travis

examples/python-guide/simple_example.py
=> [python] remove useless import from example

python-package/lightgbm/engine.py
Refer to https://github.com/Microsoft/LightGBM/pull/1505#issuecomment-404659815.
=> [docs] fix feval description

docs/Advanced-Topics.rst, docs/Parameters.rst, docs/Quick-Start.rst, include/LightGBM/config.h, python-package/lightgbm/basic.py, python-package/lightgbm/engine.py, python-package/lightgbm/sklearn.py
Add a note about negative values in category columns in docstrings of Python-package.
=> [docs] negative values in category columns

docs/Features.rst
Current link to MPICH article fails with timeout error (and setting timeout up to 180 sec doesn't help):
=> [ci][docs] replaced problem link

include/LightGBM/R_object_helper.h, include/LightGBM/bin.h, include/LightGBM/c_api.h, include/LightGBM/lightgbm_R.h, include/LightGBM/metric.h, include/LightGBM/utils/file_io.h, src/c_api.cpp, src/io/bin.cpp, src/io/dataset_loader.cpp, src/io/file_io.cpp, src/io/parser.hpp, src/lightgbm_R.cpp, src/metric/binary_metric.hpp, src/metric/map_metric.hpp, src/metric/multiclass_metric.hpp, src/metric/rank_metric.hpp, src/metric/regression_metric.hpp, src/metric/xentropy_metric.hpp, src/network/linkers.h, src/objective/regression_objective.hpp, src/objective/xentropy_objective.hpp, src/treelearner/parallel_tree_learner.h, src/treelearner/serial_tree_learner.cpp, src/treelearner/serial_tree_learner.h, src/treelearner/split_info.hpp, src/treelearner/voting_parallel_tree_learner.cpp
=> fix include

src/treelearner/serial_tree_learner.cpp
=> fix-parallel-quantile

examples/python-guide/advanced_example.py, python-package/lightgbm/basic.py, python-package/lightgbm/engine.py, python-package/lightgbm/sklearn.py
Refer to https://github.com/Microsoft/LightGBM/pull/1565#issuecomment-415022270 .
=> [python] return self in most functions in basic.py module and fix docstrings

R-package/README.md
@Laurae2 Please consider this small PR which fixes minor typos in the `R-package` README.
=> Fixed typos in R-package README

python-package/lightgbm/basic.py, python-package/lightgbm/compat.py
=> [python] add possibility to predict dataset with nrow > max_int32

R-package/README.md
Ping @jameslamb and @Laurae2 for the review.
=> [docs] removed duplicated info about gcc setup in R README

docs/Parameters.rst, include/LightGBM/config.h, python-package/lightgbm/basic.py, python-package/lightgbm/sklearn.py
Refer to https://github.com/Microsoft/LightGBM/issues/1350#issuecomment-395903942 and ping @slundberg.
=> [docs] added note about shap package

docs/FAQ.rst
=> [docs] updated collaborators list

tests/python_package_test/test_basic.py, tests/python_package_test/test_engine.py
Added regression test for #1646.
=> added regression test for subsetting with group and cv with group-based metrics

src/boosting/rf.hpp, tests/python_package_test/test_engine.py
=> fix RF's bug with MAPE & support RF with multi-class

docs/Advanced-Topics.rst
=> [docs] added info that categorical features better to start from zero

python-package/README.rst, python-package/lightgbm/__init__.py, python-package/lightgbm/plotting.py, src/objective/binary_objective.hpp
=> [docs] updated target LightGBM version in warnings

python-package/lightgbm/sklearn.py
It appeared to be 200000, not 50000
=> [python] fix the doc of subsample_for_bin default value

src/boosting/rf.hpp
=> fix warnings

python-package/lightgbm/basic.py
=> fix indices type in csr and csc

docs/conf.py
=> [docs] Remove ugly color from code pieces background

python-package/lightgbm/basic.py, python-package/lightgbm/engine.py, python-package/lightgbm/sklearn.py, tests/python_package_test/test_engine.py
=> [python] do not modify users params

docs/Features.rst
Signed-off-by: Marcela Morales Quispe <marcela.morales.quispe@gmail.com>
=> [Docs] Format documentation list.

docs/FAQ.rst, include/LightGBM/objective_function.h, src/boosting/gbdt.cpp, src/boosting/gbdt.h, src/c_api.cpp, src/io/dataset.cpp, src/io/dataset_loader.cpp, src/objective/binary_objective.hpp, src/objective/multiclass_objective.hpp, src/objective/regression_objective.hpp, src/objective/xentropy_objective.hpp, tests/python_package_test/test_engine.py
=> average predictions for constant features

include/LightGBM/utils/common.h, src/boosting/gbdt_model_text.cpp, src/io/bin.cpp, src/io/dataset.cpp, src/metric/dcg_calculator.cpp, src/metric/map_metric.hpp, src/objective/rank_objective.hpp, src/objective/regression_objective.hpp, tests/python_package_test/test_sklearn.py
=> fix ranking tasks consistency

.ci/setup.sh, .ci/test.sh, .vsts-ci.yml
refer to https://docs.microsoft.com/zh-cn/azure/devops/pipelines/agents/hosted?view=vsts&tabs=yaml#hosted-linux-preview-pool-deprecation
> We're deprecating the Hosted Linux Preview pool. We recommend that you begin moving your pipelines to the Hosted Ubuntu 1604 pool now. We plan to remove the Hosted Linux Preview from Azure Pipelines on December 1, 2018.
=> [Azure Pipeline] switch to Hosted Ubuntu 1604

docs/FAQ.rst
@guolinke Can you please invite James in Slack?
=> [docs] added real names of LightGBM maintainers

.appveyor.yml
It was my personal request to leave this artifact. However, with new artifact publishing condition on Azure it's not actual anymore.
=> [ci] remove artifacts from Appveyor

.appveyor.yml, .ci/test.sh, .vsts-ci.yml
Alphabetically sorted modules are quicker to read and searchable.
=> [ci] sort package installation

python-package/lightgbm/plotting.py
This parameter is used only in case of `gain` and controls the number of digits after decimal point (as in `create_tree_digraph`).
=> [python] added precision param to plot_importance function

.vsts-ci.yml
Refer to https://github.com/Microsoft/LightGBM/pull/1780#issuecomment-432969227.
Non-containerized `Linux_gpu` task needs this fix too.
=> [ci] Fixed conda permission error on Azure Pipelines

src/treelearner/serial_tree_learner.cpp
=> fix problems with null json node, in forced split

README.md
Added MIT License information and License link to Readme.MD
=> [docs] Added License information in Readme.MD

README.md, docs/index.rst
=> [docs] fixed consistency of lists

python-package/setup.py
Use LightGBM custom logger instead of root one:
https://github.com/Microsoft/LightGBM/blob/a0efb07bb8ef9d8a80f246a933c623e253a8a0a3/python-package/setup.py#L260-L261
Compare:
=> [python] fixed logging during installation

README.md
=> [docs] updated list of external repos in README

docs/Parameters.rst, include/LightGBM/config.h
=> [docs] added note about valid format of ignoring columns

docs/Parameters.rst, include/LightGBM/config.h
=> [docs] fixed seed param default value and description

.appveyor.yml
scikit-learn 0.20.1 has fixed the warning passed to stderr.
=> [ci] removed temp fix

src/objective/binary_objective.hpp
fix bugs in https://github.com/Microsoft/LightGBM/pull/1869#issuecomment-441436173
=> fix bug for one-class binary-classification task

src/boosting/rf.hpp
=> Allow feature_fraction=1.0 in random forest mode

docs/FAQ.rst
=> [docs] added FAQ entry about random segfaults

include/LightGBM/objective_function.h, include/LightGBM/tree_learner.h, src/boosting/gbdt.cpp, src/boosting/gbdt.h, src/boosting/gbdt_model_text.cpp, src/boosting/gbdt_prediction.cpp, src/boosting/rf.hpp, src/objective/regression_objective.hpp, src/treelearner/serial_tree_learner.cpp, src/treelearner/serial_tree_learner.h, tests/python_package_test/test_engine.py
=> Fix bugs in RF

include/LightGBM/bin.h, src/io/bin.cpp, src/io/dataset.cpp, src/treelearner/gpu_tree_learner.cpp
Tried to find how LightGBM deals with trivial features, and realized it was spelled wrongly
=> Fix typo trival -> trivial

.travis.yml, .vsts-ci.yml
About `sudo` for Travis: https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration.
=> [ci] removed temp brew hotfix and deprecated sudo option

src/io/dataset.cpp, src/io/dataset_loader.cpp, src/metric/dcg_calculator.cpp
Refer to https://github.com/Microsoft/LightGBM/pull/1881#issuecomment-455035916.
=> removed warnings about types in comparison ([-Wsign-compare])

R-package/R/lgb.Dataset.R, include/LightGBM/c_api.h, include/LightGBM/dataset.h, include/LightGBM/lightgbm_R.h, python-package/lightgbm/basic.py, src/c_api.cpp, src/io/dataset.cpp, src/io/dataset_loader.cpp, src/lightgbm_R.cpp
=> support to override some parameters in Dataset

src/objective/regression_objective.hpp
=> fix more edge cases in mape

R-package/DESCRIPTION
=> 2.2.3 release

R-package/demo/categorical_features_rules.R
Fixes #1988 last error found definitely.
=> [R-package] Fix #1988 missing file issue

python-package/lightgbm/__init__.py
Closing version file after read🙃
=> [python] Minor fix: close open file pointer

examples/python-guide/advanced_example.py, examples/python-guide/sklearn_example.py
I remember, I saw a question about this, but unfortunately cannot find it at StackOverflow now.
=> [python][examples] add examples of training with multiple custom metrics

swig/lightgbmlib.i
native changes required for this PR: https://github.com/Azure/mmlspark/pull/504
resolves issue: https://github.com/Azure/mmlspark/issues/435
=> lightgbm SWIG Java wrapper changes needed to add early stopping in mmlspark

.appveyor.yml, .ci/test.sh, .ci/test_windows.ps1
=> [ci] removed compatibility temp hotfix

docs/Parallel-Learning-Guide.rst
Refer to https://github.com/Microsoft/LightGBM/pull/2061#issuecomment-475497052.
=> [docs] fixed broken link

include/LightGBM/tree.h, include/LightGBM/utils/common.h, src/boosting/gbdt_model_text.cpp, src/io/file_io.cpp, src/io/json11.cpp, src/io/tree.cpp, src/metric/xentropy_metric.hpp, src/network/socket_wrapper.hpp, src/objective/regression_objective.hpp, src/objective/xentropy_objective.hpp, src/treelearner/gpu_tree_learner.cpp
Refer to #1990 and http://google.github.io/styleguide/cppguide.html#Casting.
Please review **attentively**, because I'm not a cpp coder.
- Is `static_cast<label_t*>(nullptr)` OK?
- What can be done with `R_object_helper.h`? E.g.
https://github.com/Microsoft/LightGBM/blob/7a89d0054bcf0db9f96af3c53a078b6aa3152efe/include/LightGBM/R_object_helper.h#L121-L125
- How to rewrite `(void*)`? E.g.
https://github.com/Microsoft/LightGBM/blob/7a89d0054bcf0db9f96af3c53a078b6aa3152efe/src/io/dataset.cpp#L808
=> addressed cpplint error about C-style cast

.appveyor.yml, .ci/dockers/ubuntu-14.04/Dockerfile, .ci/setup.sh, .travis.yml, .vsts-ci.yml
- Use our Ubuntu 14.04 Docker for GPU test on Azure Pipelines.
- Update CMake and Clang in Docker to new stable versions.
- Install `libomp-dev` inside Docker instead of via the setup script for Clang.
- Update MinGW-w64 on Appveyor.
- Update Boost library.
- Update Boost submodule.
Also, this PR resolves the issue about GPU test described in https://github.com/Microsoft/LightGBM/pull/2078#issuecomment-479605231
=> [ci] update CI stuff

.ci/test.sh, .travis.yml
It seems to me that macOS users tent to use the latest software, so we should run our tests on Mojave. Fortunately, Mojave on Travis is not beta anymore: https://changelog.travis-ci.com/xcode-10-2-gm-is-now-available-95717.
=> [ci] update macOS on Travis to Mojave

.gitignore
Refer to https://github.com/Microsoft/LightGBM/pull/2089#pullrequestreview-225012556.
=> add IntelliJ IDEA to .gitignore

docs/Parameters.rst, include/LightGBM/config.h, python-package/lightgbm/sklearn.py
What about `sample_weight`/`weight_column` params?
=> [docs] added note about the spoiled probabilities

.appveyor.yml, .ci/test_windows.ps1, docs/Features.rst
- Fix broken link in docs.
- Fix graphviz not in PATH. Refer to https://github.com/xflr6/graphviz/issues/65, https://github.com/conda-forge/python-graphviz-feedstock/issues/25.
=> [ci] hotfixes

src/io/tree.cpp
=> dump_model() bug with num_leaves=1

include/LightGBM/json11.hpp, include/LightGBM/meta.h
https://github.com/Microsoft/LightGBM/blob/739c2635f4084e07f5b57666bd7f2fdd929bf30e/CMakeLists.txt#L34-L36
Refer to #819, #1027.
=> Removed legacy code

src/treelearner/gpu_tree_learner.cpp
This code didn't build due to a change to the Feature4 struct.
=> Fix build of GPU debugging code

python-package/lightgbm/sklearn.py
Refer to https://github.com/scikit-learn/scikit-learn/pull/8022, https://github.com/scikit-learn/scikit-learn/pull/13550, https://scikit-learn.org/0.21/developers/contributing.html#estimator-tags.
=> [python][sklearn] added estimator's tags

.appveyor.yml, .ci/test.sh, .vsts-ci.yml
Scikit-learn finally dropped `nose` dependency in their tests.
=> [ci][tests] nose is not needed anymore

include/LightGBM/objective_function.h, include/LightGBM/tree_learner.h, src/boosting/gbdt.cpp, src/boosting/rf.hpp, src/objective/regression_objective.hpp, src/treelearner/serial_tree_learner.cpp, src/treelearner/serial_tree_learner.h
to fix #2144, and some code cleans.
=> fix a bug when bagging with reset_config

build_r.R
@Laurae2 this PR removes any external dependencies in `build_r.R`. It's now just pure R code.
Tested on my Mac (running Mojave, using `gcc/g++`) and didn't have any issues. Would appreciate if you could try in a windows environment before we merge.
=> removed external dependencies in build_r.R (fixes #2122)

src/treelearner/voting_parallel_tree_learner.cpp
Refer to https://github.com/microsoft/LightGBM/pull/2154#issuecomment-490716927.
=> use stable_sort for splits

.ci/test.sh, .travis.yml, docs/FAQ.rst
Refer to https://github.com/Homebrew/homebrew-core/pull/39563/files.
Compare:
=> [ci][docs] updated fix for OpenMP conflicts

docs/Parameters.rst, include/LightGBM/config.h
minor doc fix - gamma param misspelled
=> [doc] minor doc fix for gamma param

src/io/config.cpp
=> fix unsorted eval_at

helpers/parameter_generator.py, python-package/lightgbm/sklearn.py
Found by https://lgtm.com/projects/g/microsoft/LightGBM/alerts/?mode=list.
=> [python] removed unused import and variable

python-package/lightgbm/sklearn.py, tests/python_package_test/test_sklearn.py
=> [python] fix class_weight

src/io/config.cpp, src/treelearner/serial_tree_learner.cpp
=> consider max_depth for histogram_pool_size

R-package/src/install.libs.R
This PR is related to https://github.com/microsoft/LightGBM/issues/2026
=> mojave install r openmp fix

docs/Parameters.rst, include/LightGBM/config.h, include/LightGBM/objective_function.h, src/boosting/gbdt.cpp, src/boosting/gbdt.h, src/io/config_auto.cpp, src/objective/binary_objective.hpp
This may work for imbalanced binary-class data.
=> balanced bagging

.vsts-ci.yml
=> [ci] turn on release notes

python-package/lightgbm/basic.py
=> fix refit decay rate in python

python-package/lightgbm/basic.py, tests/python_package_test/test_engine.py
=> fix init_model with subset

src/io/bin.cpp
=> fix MissingType::Zero in categorical features.

.appveyor.yml, .ci/setup.sh, .vsts-ci.yml
Refer to #2245, https://github.com/conda/conda/issues/8973, https://github.com/conda/conda/issues/8865.
=> [ci] remove temp fix and fix activation for conda

include/LightGBM/config.h, include/LightGBM/tree.h, src/boosting/gbdt.cpp, src/c_api.cpp, src/io/config.cpp, src/io/dataset_loader.cpp, src/io/tree.cpp, src/metric/multiclass_metric.hpp, src/objective/regression_objective.hpp, swig/lightgbmlib.i
=> fixed cpplint errors about spaces and indents

docs/FAQ.rst, docs/README.rst
Added the discussion from #2270 to our documentation. Thanks again for the question @NicolasHug
=> [docs] added FAQ on early stopping (fixes #2270)

python-package/lightgbm/basic.py
=> change the priority of init_score and init_model.

docs/.linkcheckerrc
=> [ci][docs] update the list of ignoring sites for linkchecker

docker/README.md, docker/dockerfile-r
Hi! I've added a Dockerfile for using LightGBM in R.
=> add Dockerfile for R

R-package/DESCRIPTION
I am leaving my current job at the end of this week, so cleaning up references to my email from that company. I'd like to just use my personal email in `DESCRIPTION`.
=> updated R-package authors

docker/README.md, docker/dockerfile-cli, docker/dockerfile-python, docker/dockerfile-r, docker/gpu/README.md, docker/gpu/dockerfile.gpu
Closed #2279.
Also, updated docker related links, Python 3.5 -> 3.6, using `stable` tag for all images and some minor formatting changes.
=> updated docker folder

build_r.R
See the linked issue for details.
=> Fixed keep-empty-dirs flag in build_r.R (fixes #2332)

R-package/R/callback.R, R-package/R/lgb.cv.R, R-package/R/lgb.train.R
This is a whitespace-only R which cleans up trailing horizontal whitespace in the R package code. The diff in #2334 had a decent amount of these changes, putting them here so they aren't a distraction on PRs like that that change how the code in the R package actually functions.
=> trimmed whitespace in R code

src/boosting/rf.hpp
=> informative error for custom obj in RF

.gitignore, tests/python_package_test/test_engine.py
Also, fixed warning about that param is overridden.
`.bin` artifact was introduced in #2252.
=> [tests] simplified test and added dumped data to gitignore

README.md
Hi, thanks for this awesome library! Thanks to the C API, there are now Ruby bindings for LightGBM 🎉 
Announcement: https://ankane.org/xgboost-lightgbm-come-to-ruby
Code: https://github.com/ankane/lightgbm
Feel free to create an issue on the project if you have any feedback. Thanks!
=> Ruby Library

README.md
Announcement (in Russian): https://habr.com/en/post/423495.
@dmitryikh
=> [docs] added reference to leaves Go package

python-package/lightgbm/engine.py
lgb.Dataset.get_group() colud return the list type.
=> [python] fix group type in lgb.cv

python-package/lightgbm/basic.py, tests/python_package_test/test_basic.py
Refer to https://github.com/microsoft/LightGBM/pull/2377#issuecomment-528434787.
=> [python] keep consistent state for Dataset fields

src/treelearner/serial_tree_learner.cpp
refer to https://github.com/microsoft/LightGBM/pull/2381#issuecomment-531489387
=> at least 2 features are chosen in subcolumn

.ci/test.sh
Refer to https://github.com/microsoft/LightGBM/issues/1990#issuecomment-482695889, https://github.com/microsoft/LightGBM/issues/1990#issuecomment-482776312.
=> [ci] added build/include_subdir check to filter for cpplint

.appveyor.yml, .ci/test_windows.ps1
Refer to https://github.com/microsoft/LightGBM/pull/2437#issuecomment-534529093.
=> [ci] temp fix for missing dependency on Windows

R-package/R/lgb.cv.R, R-package/R/lgb.train.R, docs/Parameters.rst, include/LightGBM/config.h, python-package/lightgbm/engine.py, src/io/config_auto.cpp
Scikit-learn uses it:
- https://scikit-learn.org/stable/glossary.html#term-n-iter-no-change,
- https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingClassifier.html#sklearn.ensemble.GradientBoostingClassifier.
=> added new early_stopping param alias

src/io/config.cpp
refer to
https://github.com/microsoft/LightGBM/issues/2371#issuecomment-533887739
=> remove the duplicate data path

swig/lightgbmlib.i
fixes the warnings as described in https://github.com/microsoft/LightGBM/issues/2360
by @chris-smith-zocdoc
FYI @eisber
=> [Java] add missing JNI exception checks to fix warnings

src/io/bin.cpp, src/io/dataset.cpp, src/io/dataset_loader.cpp, src/network/linkers_socket.cpp, src/treelearner/cost_effective_gradient_boosting.hpp
=> fixed cpplint errors about spaces and newlines

R-package/R/callback.R, R-package/R/lgb.Dataset.R, R-package/R/lgb.interprete.R, R-package/R/lightgbm.R, R-package/demo/boost_from_prediction.R, R-package/man/lgb.interprete.Rd, R-package/man/lightgbm.Rd, R-package/man/slice.Rd, docs/GPU-Tutorial.rst, docs/Parameters.rst, include/LightGBM/application.h, include/LightGBM/bin.h, include/LightGBM/c_api.h, include/LightGBM/config.h, include/LightGBM/dataset.h, include/LightGBM/lightgbm_R.h, include/LightGBM/meta.h, include/LightGBM/metric.h, include/LightGBM/network.h, include/LightGBM/tree.h, include/LightGBM/tree_learner.h, include/LightGBM/utils/array_args.h, include/LightGBM/utils/common.h, src/network/linkers.h, src/treelearner/gpu_tree_learner.h
This is what happens when I'm on a long flight with no internet 😂 
This PR fixes a variety of minor typos and grammar issues in the code base. Please let me know if there are any other documentation files I need to regenerate as a result of changing some comments on the C++ side.
=> fixed miscellaneous typos in documentation

docker/dockerfile-python, docker/gpu/dockerfile.gpu
Fixed #2458.
- Respect `CONDA_DIR` argument.
- Move Jupyter config from `root` to `HOME` directory.
=> updated dockers

python-package/lightgbm/plotting.py
Demo:
https://gist.github.com/jkotra/ca4dee988e34666eca2c005a0e0b3403
=> [python] DPI arg in plotting functions

docs/FAQ.rst, docs/Parameters.rst, docs/Python-Intro.rst, docs/Quick-Start.rst, include/LightGBM/config.h
Refer to https://github.com/microsoft/LightGBM/issues/2457#issuecomment-540043236.
=> [docs] clarified support of LibSVM zero-based format files

.ci/setup.sh
Fix current `master` failures.
Refer to:
https://github.com/ContinuumIO/anaconda-issues/issues/11148
https://stackoverflow.com/a/57390520
=> [ci] miniconda installer hotfix

.appveyor.yml, .travis.yml
Minor change. We could slightly speed up CI by only pulling the most recent commit when cloning this project's source code during CI builds.
=> [ci] reduced number of commits cloned to CI environments

src/io/dataset_loader.cpp
Refer to https://github.com/microsoft/LightGBM/pull/2485#issuecomment-542383741.
=> fixed casting warning

docs/Installation-Guide.rst
=> [docs] update MS-MPI link

src/boosting/gbdt.cpp, src/boosting/rf.hpp, src/c_api.cpp, src/io/dense_bin.hpp, src/io/dense_nbits_bin.hpp, src/io/parser.hpp, src/io/sparse_bin.hpp, src/objective/multiclass_objective.hpp, src/treelearner/feature_histogram.hpp, src/treelearner/voting_parallel_tree_learner.cpp
=> renamed variables from bias to offset

.appveyor.yml, .ci/test_windows.ps1
Refer to #2132, https://github.com/ContinuumIO/anaconda-issues/issues/11338.
=> [ci] removed temp fix for Graphviz from conda

.ci/test.sh, docs/Installation-Guide.rst
macOS Catalina was released in October.
https://en.wikipedia.org/wiki/MacOS_Catalina
=> support Catalina

docker/dockerfile-cli, docker/dockerfile-python
`wget` and `git` fail to fetch files due to missing certificates
=> install ca certificates package on ubuntu image

include/LightGBM/dataset.h, include/LightGBM/utils/common.h, src/io/config.cpp
=> check feature names for special JSON chars

include/LightGBM/config.h, src/boosting/gbdt_model_text.cpp, src/io/config.cpp
=> Fix detecting alias of objective in loading model from strings

include/LightGBM/config.h, include/LightGBM/utils/text_reader.h, src/application/application.cpp, src/io/dataset_loader.cpp, src/metric/dcg_calculator.cpp, src/treelearner/serial_tree_learner.cpp
1) Add file load progress after every 10 GBs. 2) Print number of data points in the validation set(s) as well. Update the text for the log line with number train set data points to be consistent with it. 3) Fix printf format string in a label range error message.
=> Add more debug logging to show data load progress.

src/io/file_io.cpp
Refer to https://github.com/microsoft/LightGBM/pull/2540#issuecomment-557579831.
=> fix compile warning for HDFS version

README.md, docs/Parallel-Learning-Guide.rst
=> [docs] added link to kubeflow fairing and enhanced parallel guide

R-package/demo/cross_validation.R, R-package/demo/early_stopping.R, R-package/tests/testthat/test_custom_objective.R, examples/python-guide/advanced_example.py, python-package/lightgbm/sklearn.py, tests/python_package_test/test_sklearn.py
=> [python][R-package] warn users about untransformed values in case of custom obj

python-package/lightgbm/sklearn.py, tests/python_package_test/test_sklearn.py
=> [python][sklearn] do not modify args in fit function and minor code cleanup

docs/Parameters.rst, include/LightGBM/config.h
Refer to https://github.com/microsoft/LightGBM/issues/2616#issuecomment-563835390.
More details are presented in Python param description itself.
https://github.com/microsoft/LightGBM/blob/b6aa5ee82f61847f8511178047c21024335b4e93/python-package/lightgbm/basic.py#L744
=> [docs] enhanced description of cat features param

docs/Installation-Guide.rst
Help users to find from search engines what they want.
=> [docs] added search key words for artifacts

README.md
https://rapidsai.github.io/projects/cuml/en/0.11.0/api.html#forest-inferencing
=> [docs] added link to cuML in external repos section of README

.travis.yml
=> [ci] bump XCode version for Travis

R-package/R/lgb.Dataset.R, R-package/man/lgb.Dataset.save.Rd, docs/Parameters.rst, include/LightGBM/config.h, python-package/lightgbm/basic.py, src/io/metadata.cpp
=> warning for init_score in save_binary

include/LightGBM/utils/random.h
refer to https://www.nowherenearithaca.com/2013/05/robert-floyds-tiny-and-beautiful.html
=> more efficient sampling k from n

CMakeLists.txt, include/LightGBM/meta.h, src/io/dense_bin.hpp, src/io/dense_nbits_bin.hpp, src/io/ordered_sparse_bin.hpp
continued to improve #2677
benchmark: almost the same as master
=> check _mm_prefetch in cmake

.nuget/create_nuget.py
=> [ci] use raw strings in NuGet helper script

.travis.yml, .vsts-ci.yml
Refer to https://github.com/microsoft/LightGBM/pull/2699#issuecomment-581093911.
=> [ci] swap compilers back for CI services

R-package/R/utils.R, docs/Parameters.rst, include/LightGBM/config.h, python-package/lightgbm/engine.py
=> [python][R-package][docs] fix support of XE_NDCG_MART obj in language wrappers and docs

include/LightGBM/utils/openmp_wrapper.h, src/application/application.cpp
=> no omp_set_nested

include/LightGBM/feature_group.h, src/treelearner/feature_histogram.hpp, src/treelearner/monotone_constraints.hpp, src/treelearner/serial_tree_learner.h, src/treelearner/voting_parallel_tree_learner.cpp
=> fixed cpplint issues

docs/GPU-Performance.rst, docs/GPU-Tutorial.rst, include/LightGBM/feature_group.h
This param was removed in #2699.
=> [docs] removed mentions of sparse_threshold

python-package/lightgbm/sklearn.py
Fixed #2759.
Now more appropriate warning is shown.
=> [python] in sklearn wrapper pass cat features to Dataset constructor

src/treelearner/cost_effective_gradient_boosting.hpp
=> fix max_depth in CEGB

docs/Parameters.rst, include/LightGBM/bin.h, include/LightGBM/config.h, include/LightGBM/dataset.h, src/io/bin.cpp, src/io/dataset.cpp, src/io/multi_val_dense_bin.hpp, src/io/multi_val_sparse_bin.hpp, src/treelearner/gpu_tree_learner.cpp, src/treelearner/serial_tree_learner.cpp, src/treelearner/serial_tree_learner.h
=> speed up sub-feature in row-wise parallelism

R-package/R/aliases.R, R-package/R/lgb.Dataset.R, R-package/tests/testthat/test_dataset.R, R-package/tests/testthat/test_parameters.R
@StrikerRUS @guolinke please see this PR for my proposed R changes for #2594
=> [R-package] centralize Dataset parameter aliases and add tests on parameter updating

R-package/R/aliases.R, R-package/tests/testthat/test_parameters.R
=> [R-package] fixed R Dataset aliases

docs/Parameters.rst, examples/binary_classification/predict.conf, examples/binary_classification/train.conf, examples/lambdarank/predict.conf, examples/lambdarank/train.conf, examples/parallel_learning/predict.conf, examples/parallel_learning/train.conf, examples/regression/predict.conf, examples/regression/train.conf, examples/xendcg/train.conf, include/LightGBM/config.h, include/LightGBM/dataset.h, include/LightGBM/dataset_loader.h, src/application/application.cpp, src/c_api.cpp, src/io/config.cpp, src/io/config_auto.cpp, src/io/dataset_loader.cpp, src/io/metadata.cpp
=> remove init-score parameter 

docs/GPU-Windows.rst
Fix current `master` failures.
=> [docs] fixed broken links

.vsts-ci.yml, src/treelearner/gpu_tree_learner.cpp, src/treelearner/ocl/histogram16.cl, src/treelearner/ocl/histogram256.cl, src/treelearner/ocl/histogram64.cl
=> fix clang warning for GPU

src/io/dense_bin.hpp, src/io/dense_nbits_bin.hpp, src/io/sparse_bin.hpp, tests/python_package_test/test_engine.py
to fix #2797
BTW, there are many duplicated codes for `Bin::Split`, maybe the code refactoring over them is need.
=> fix bug when nan bin is most freq bin

src/boosting/gbdt.cpp, src/boosting/goss.hpp, src/treelearner/feature_histogram.hpp
Refer to https://github.com/microsoft/LightGBM/pull/2769#pullrequestreview-363118368.
=> fix index and remove unused includes

include/LightGBM/tree.h, include/LightGBM/utils/log.h, src/application/predictor.hpp, src/boosting/gbdt.cpp, src/boosting/gbdt_model_text.cpp, src/c_api.cpp, src/io/bin.cpp, src/io/dataset.cpp, src/io/dataset_loader.cpp, src/metric/dcg_calculator.cpp, src/metric/regression_metric.hpp, src/treelearner/feature_histogram.hpp, src/treelearner/serial_tree_learner.cpp
Refer to https://github.com/microsoft/LightGBM/issues/1990#issuecomment-533010905.
Implementation was borrowed from https://code.woboq.org/llvm/libcxx/utils/google-benchmark/src/check.h.html#_M/CHECK_EQ.
I'll update auto-config code in a separate PR.
=> introduced specific CHECKs

include/LightGBM/config.h, src/application/application.cpp, src/io/config.cpp, src/treelearner/data_parallel_tree_learner.cpp, src/treelearner/serial_tree_learner.cpp, src/treelearner/serial_tree_learner.h, src/treelearner/voting_parallel_tree_learner.cpp
=> fix bug in parallel learning

include/LightGBM/bin.h, include/LightGBM/dataset.h, src/io/dataset.cpp, src/io/dense_bin.hpp, src/io/dense_nbits_bin.hpp, src/io/multi_val_dense_bin.hpp, src/io/multi_val_sparse_bin.hpp, src/io/sparse_bin.hpp
for row-wise parallelism, constant hessian will be slower, so disable it.
=> speed up for const hessian

README.md
[markdownlint](https://github.com/markdownlint/markdownlint)
=> [docs] Fix description according to markdownlint

docs/Installation-Guide.rst
=> [docs] update link to MS MPI

src/c_api.cpp
Refer to https://github.com/microsoft/LightGBM/pull/2816#issuecomment-591230105.
=> fix warnings in debug mode about that not all control paths return a value

helpers/parameter_generator.py, src/io/config_auto.cpp
=> use specific checks in auto config

include/LightGBM/tree.h
=> shrinkage to internal values

include/LightGBM/utils/common.h, include/LightGBM/utils/threading.h, src/io/dataset.cpp, src/treelearner/serial_tree_learner.cpp, src/treelearner/voting_parallel_tree_learner.cpp
=> fix possible bug related num_threads

include/LightGBM/tree_learner.h, src/boosting/gbdt.h, src/io/dataset_loader.cpp, src/treelearner/col_sampler.hpp, src/treelearner/feature_histogram.hpp, src/treelearner/serial_tree_learner.cpp, windows/LightGBM.vcxproj, windows/LightGBM.vcxproj.filters
=> fixed cpplint errors and VS project files

docs/Parameters-Tuning.rst
Add Optuna link for automated hyperparameter tuning.
=> [docs] add link to blog post about Optuna to Parameters-Tuning.rst

.github/release-drafter.yml
refer to https://github.com/marketplace/actions/release-drafter
the previous config seems wrong.
=> fix release-drafter.yml

R-package/src/install.libs.R
per https://github.com/microsoft/LightGBM/pull/2909#discussion_r392756954, sorry for merging too fast @StrikerRUS
=> [R-package] removed duplicated code figuring out build_dir in install.libs.R

python-package/lightgbm/basic.py, tests/python_package_test/test_engine.py
=> [python] Fix continued train by reusing the same dataset

windows/LightGBM.vcxproj, windows/LightGBM.vcxproj.filters
=> [ci] fix VS project files

include/LightGBM/tree.h
IsZero(x) is now symmetrical around 0.
=> [fix] Fix IsZero in tree.h

docs/Advanced-Topics.rst, docs/Features.rst
Old site with free pdf is down now and seems will not be recovered in the future.
=> [ci][docs] fixed broken link

include/LightGBM/utils/json11.h, src/boosting/gbdt.cpp, src/io/dataset_loader.cpp, src/io/json11.cpp
=> fix cpp lint in json11

docs/FAQ.rst
Sorry, I forgot to update this doc in #2996.
=> [docs] updated core team list

docs/conf.py, docs/requirements.txt, docs/requirements_base.txt
Refer to #2982 and https://github.com/michaeljones/breathe/issues/500#issuecomment-612869739.
=> [ci][docs] be compatible with Sphinx 3

README.md
Closed #3008.
I think we came to the agreement that no one is against of transferring Julia package development to the new repo.
@yalwan-iqvia @Allardvm @wakakusa
=> [docs] update link to Julia wrapper

R-package/tests/testthat/test_lgb.Booster.R
This PR is a part of #2944. Currently, we do not test the call from LightGBM's R package to the C++ function `LGBM_BoosterMerge_R`. This PR proposes such a test.
=> [R-package] Added tests on creating a Booster from a Dataset

python-package/lightgbm/basic.py, python-package/lightgbm/engine.py, python-package/lightgbm/sklearn.py
Closed #3029.
Also refer to #2278, #1530 and #2611.
=> [docs] updated docs about output values

docs/FAQ.rst
Trying to fix the `linkchecker` issue discussed in https://github.com/microsoft/LightGBM/pull/2965#issuecomment-628332703
=> [docs] update link to GitHub anchor conventions

.travis.yml
`AppleClang 11.0.3.11030032` works fine.
We are on Catalina now, BTW!
=> [ci] bump XCode version at Travis

src/treelearner/feature_histogram.hpp, src/treelearner/voting_parallel_tree_learner.cpp
=> fix refactoring bug in voting parallel

src/io/tree.cpp
=> fix str2double for `leaf_weights`

python-package/lightgbm/engine.py, python-package/lightgbm/sklearn.py
to fix #3203
also, ping @jameslamb to check (and fix) the corresponding problem in R packages.
=> [python] fix early_stopping_round = 0

docs/Installation-Guide.rst
I tried to improve the phrasing of the guide while keeping the actual semantics exactly the same.
@StrikerRUS perhaps you could review this since you seem to be active in this area?
=> [docs] Improve some phrasing in the installation guide

include/LightGBM/dataset.h
This is to fix the problem in Issue #3151.
=> set num_threads of share_state (#3151)

swig/lightgbmlib.i
Sorry, overlooked this in #2992.
cc @AlbertoEAF
=> [SWIG] removed commented code

.gitignore
update gitignore to ignore files created by clion
=> update gitignore to ignore files created by clion

R-package/R/utils.R, R-package/tests/testthat/test_utils.R
Fixes https://github.com/microsoft/LightGBM/pull/3235#discussion_r459138574 and https://github.com/microsoft/LightGBM/pull/3235#discussion_r459139165, small mistakes introduced  in #3235. Thanks for catching these @StrikerRUS !
=> [R-package] remove duplicated test

.ci/setup.sh
GitHub Actions image has been updated.
=> [ci] partly remove macOS temp CI fix

src/io/parser.cpp
=> fix possible problem in getting number of columns from libsvm file.

src/treelearner/cost_effective_gradient_boosting.hpp, src/treelearner/serial_tree_learner.cpp
=> fix bug in CEGB when reset training data or config

docs/Parameters.rst, include/LightGBM/config.h
=> [docs] improve params docs

examples/README.md
Added winning solution using LightGBM for M5 forecasting competition
=> Added winning solution using LightGBM

examples/python-guide/advanced_example.py, examples/python-guide/sklearn_example.py
After merging #3254 it is possible to simplify `feval` argument with multiple custom metrics significantly and remove proxy functions.
cc @gramirezespinoza
=> [python][examples] updated examples with multiple custom metrics

src/boosting/gbdt.cpp
Fix typo. See comment on #3373
=> Fix typo in ResetConfig

CMakeLists.txt, R-package/src/install.libs.R
Refer to https://github.com/microsoft/LightGBM/pull/3144#discussion_r487533033.
=> [R-package] mark CMake option for building R package as private

R-package/R/callback.R
Addresses part of #3390. Also added `isTRUE()` for some of the logical checks, please advise if this is okay
I also had issues with generating the roxygen2 documentation: was not able to run the roxygenize step due to this error: 
```
Error in .f(.x[[i]], ...) : 
R6 class (lgb.Booster) without source references. If you use the `installed` load method in `DESCRIPTION`, then try re-installing the package with option '--with-keep.source'. E.g. `install.packages(..., INSTALL_OPTS = "--with-keep.source")`.
```
The steps I did are as follows:
1. open LightGBM as R project in RStudio 
2. latest roxygen2 version on CRAN is 7.1.1 -> `install.packages("roxygen2")` works
3. regular 'sh' did not work: to workaround, in R console, run `system("./build-cran-package.sh")`. Did this on WSL2. 
4. build …
=> Update callback.R with keyword arguments

swig/StringArray.hpp
https://github.com/microsoft/LightGBM/blob/2903ca0c9fc4b5cb55dbb6ef79c3a53f8fd413a2/swig/StringArray.hpp#L28-L33
=> fix type casting warning

README.md
Sorry, forgot to do it in #3429.
=> [docs] update GitHub Actions badge

.ci/lint_r_code.R
=> [R-package] Improves logging in lint_r_code.R (fixes #3471)

docs/Parameters.rst, include/LightGBM/config.h
Fix link rendering and enhance markup.
=> [docs] fix param docs

tests/python_package_test/test_basic.py
There was deleted excess initialisation and iteration
=> [tests][python] remove excess iterations

examples/README.md
It is the second place solution. https://github.com/microsoft/LightGBM/issues/3357
=> [docs] added Data Science Bowl Comp Solution 2019

docs/Parameters.rst, include/LightGBM/config.h, src/io/config.cpp, src/io/config_auto.cpp, src/treelearner/leaf_splits.hpp, src/treelearner/serial_tree_learner.cpp, src/treelearner/voting_parallel_tree_learner.cpp
=> Support deterministic 

docs/Parameters.rst, include/LightGBM/config.h, src/io/dataset_loader.cpp
=> better document for bin_construct_sample_cnt

CMakeLists.txt
Also, add a small comment for `set` command to prevent moving in a wrong place in the future.
=> move APPLE_OUTPUT_DYLIB option closer to the rest options

include/LightGBM/feature_group.h
=> fix warning

src/objective/binary_objective.hpp, src/objective/regression_objective.hpp, src/objective/xentropy_objective.hpp
=> fix deterministic, part2

R-package/R/lgb.model.dt.tree.R
Addresses part of #3390. I have regenerated the documents, but `git diff` shows no differences in `.Rd` files.
=> [R-package] Update lgb.model.dt.tree.R to use keyword arguments

README.md, docs/Parallel-Learning-Guide.rst
Refer to https://github.com/kubeflow/xgboost-operator/pull/103.
=> [docs] add Kubeflow operator repo and link to example

README.md
=> add 'mlr3learners.lightgbm' to README

README.md
=> [docs] add link to optuna examples

.ci/install_opencl.ps1, .ci/test_r_package_windows.ps1, .ci/test_windows.ps1, .vsts-ci.yml
So weird...
Refer to https://stackoverflow.com/a/43477248.
@tpboudreau Now everything is OK with OpenCL downloading speed 😄
=> [ci] speed up files downloading for Windows CI

.github/workflows/r_package.yml
TBH, I'm tired to rerun each PR multiple times to pass this flaky job and finally be able to merge PR. In addition, GitHub doesn't allow to rerun each job separately, you can rerun only all jobs. It takes a lot of time. So I'd suggest comment out flaky job till issue #3469 will be fixed.
=> [ci] remove flaky MinGW job for R

src/io/config.cpp
=> move CheckParamConflict() after LogLevel processing

include/LightGBM/cuda/vector_cudahost.h
@StrikerRUS @austinpagan Fix for [#3450](https://github.com/microsoft/LightGBM/issues/3450)
=> Ensure CUDA vector length is consistent with AlignedSize

.ci/test.sh
Linkchecker has been finally released on PyPI!
https://github.com/linkchecker/linkchecker/pull/527
=> [ci][docs] update linkchecker

tests/python_package_test/test_consistency.py
=> [python][tests] remove unused import

.vsts-ci.yml, tests/python_package_test/test_dual.py
Sorry, I completely forgot about `gpu_use_dp` param in #3660.
cc @tpboudreau
=> [python][tests] use default tolerance for dual GPU+CPU test

R-package/R/lgb.Dataset.R, R-package/man/slice.Rd
=> [R-package] Remove duplicated return values from docs

src/network/linkers_socket.cpp
This PR is intended to fix #3839 by creating new TcpSocket instance when trying to recover from a connection failure. This uses a new socket handle every time to avoid broken file descriptor error.
=> Create a new TcpSocket when connection failed

python-package/lightgbm/dask.py, python-package/lightgbm/sklearn.py
`get()` can handle multiple param names at one call. 
https://github.com/microsoft/LightGBM/blob/066720eff680606abca17a9b34d95905337d8afd/python-package/lightgbm/basic.py#L348-L353
=> [python] simplify param aliases handling

tests/python_package_test/test_dask.py
Refer to https://github.com/microsoft/LightGBM/pull/3866#issuecomment-769760478.
=> [dask][tests] increase client close timeout for Dask tests

docs/GPU-Tutorial.rst, docs/Installation-Guide.rst, python-package/README.rst
Refer to https://github.com/microsoft/LightGBM/pull/3428#discussion_r498949838 and https://github.com/microsoft/LightGBM/pull/3428#discussion_r498950692.
=> [docs] improve wordings and code style

.ci/test.sh, .github/workflows/linkchecker.yml
=> [ci] install Linkchecker only for check-links job

python-package/lightgbm/dask.py
[Live demo](https://lightgbm.readthedocs.io/en/docs_client_type/pythonapi/lightgbm.DaskLGBMClassifier.html#lightgbm.DaskLGBMClassifier.client_)
=> [docs][dask] Add type of client_ property to docs

.ci/run_rhub_solaris_checks.R, .github/workflows/r_solaris.yml
Refer to https://github.com/microsoft/LightGBM/pull/3913#discussion_r571504731.
=> [ci] update e-mail and token for R Hub builds

.vsts-ci.yml
=> [ci] remove unused variable from PATH

.ci/setup.sh, .ci/test_r_package.sh, docker/dockerfile-python, docker/gpu/dockerfile.gpu
Simplify CI scripts by not installing `wget`.
=> [ci] prefer curl to wget

R-package/R/lgb.Dataset.R, R-package/man/dimnames.lgb.Dataset.Rd, R-package/man/getinfo.Rd, R-package/man/setinfo.Rd
=> [R-package] fix duplicated return values in docs

README.md
Found this young project in Twitter.
cc @vaaaaanquish @paq
=> [docs] add reference to Rust binding

docs/conf.py
see https://github.com/microsoft/LightGBM/issues/3958
=> [ci][python] apply isort to docs/conf.py (#3958)

examples/python-guide/advanced_example.py
=> [ci][python] apply isort to examples/python-guide/advanced_example.py #3958

examples/python-guide/logistic_regression.py
=> [ci][python] apply isort to examples/python-guide/logistic_regression.py #3958

examples/python-guide/plot_example.py
=> [ci][python] apply isort to examples/python-guide/plot_example.py #3958

examples/python-guide/simple_example.py
=> [ci][python] apply isort to examples/python-guide/simple_example.py #3958

python-package/lightgbm/dask.py
=> [ci][python] apply isort to python-package/lightgbm/dask.py #3958

examples/python-guide/sklearn_example.py
=> [ci][python] apply isort to examples/python-guide/sklearn_example.py #3958

tests/python_package_test/test_dask.py
=> [ci][python] apply isort to tests/python_package_test/test_dask.py #3958

python-package/lightgbm/libpath.py
=> [ci][python] apply isort to python-package/lightgbm/libpath.py #3958

tests/python_package_test/test_dual.py
=> [ci][python] apply isort to tests/python_package_test/test_dual.py #3958

tests/c_api_test/test_.py
=> [ci][python] apply isort to tests/c_api_test/test_.py #3958

tests/cpp_test/test.py
=> [ci][python] apply isort to tests/cpp_test/test.py #3958

python-package/lightgbm/plotting.py
=> [ci][python] apply isort to python-package/lightgbm/plotting.py #3958

tests/python_package_test/test_utilities.py
=> [ci][python] apply isort to tests/python_package_test/test_utilities.py #3958

tests/python_package_test/test_plotting.py
=> [ci][python] apply isort to tests/python_package_test/test_plotting.py #3958

tests/python_package_test/test_consistency.py
=> [ci][python] apply isort to tests/python_package_test/test_consistency.py #3958

tests/python_package_test/test_basic.py
=> [ci][python] apply isort to tests/python_package_test/test_basic.py #3958

python-package/lightgbm/sklearn.py
=> [ci][python] apply isort to python-package/lightgbm/sklearn.py #3958

python-package/lightgbm/__init__.py
=> [ci][python] apply isort to python-package/lightgbm/__init__.py #3958

python-package/lightgbm/basic.py
=> [ci][python] apply isort to python-package/lightgbm/basic.py #3958

tests/python_package_test/test_engine.py
=> [ci][python] apply isort to tests/python_package_test/test_engine.py #3958

python-package/lightgbm/engine.py
=> [ci][python] apply isort to python-package/lightgbm/engine.py #3958

python-package/lightgbm/compat.py
=> [ci][python] apply isort to python-package/lightgbm/compat.py #3958

tests/python_package_test/test_dask.py
Hotfix for merging conflict in current `master`.
=> [ci][python] hotfix imports order

docs/Parameters-Tuning.rst
Add alt text to Leaf-wise growth image, as part of #4028
=> [docs] Add alt text to image in Parameters-Tuning.rst

docs/index.rst
Add alt text to logo image, as part of #4028
=> [docs] Add alt text on images in index.rst

python-package/lightgbm/callback.py, python-package/lightgbm/compat.py
Related to https://github.com/microsoft/LightGBM/issues/3867.
Fixes some mypy false-positives.
Mypy is not smart enough to detect some things like alternative definitions to imports. Some type ignores are required.
=> [python-package] Some mypy fixes

.vsts-ci.yml, tests/python_package_test/test_dask.py
- create ranking data via the general function `_create_data()`
- use multiple `with` statements at one line to not make the code over-indented (https://github.com/microsoft/LightGBM/pull/3994#discussion_r581319427)
=> [tests][dask] simplify code in Dask tests

README.md
https://www.notion.so/Hummingbird-blog-draft-EXTERNAL-db78e37de06d42e6b4ae1f0051b51acd
=> [docs] add Hummingbird to the list of external projects

README.md
https://github.com/parrt/dtreeviz/releases/tag/1.2
=> [docs] add dtreeviz to the list of external projects

python-package/lightgbm/libpath.py
=> [ci] use f-strings in `libpath.py`

.github/workflows/cuda.yml
This reverts commit 36454a3b74c4941027d14df76687993f566efbe7.
Closed #4165.
Refer to #4167.
=> [ci] Restore CUDA jobs at CI

docs/Installation-Guide.rst
This reverts commit e98da99d88aaee09a8dbd5204c5355fc099fe5f0.
Refer to #4122 and https://github.com/microsoft/LightGBM/pull/3872#issuecomment-819803019.
=> [docs] bring back macOS installation method with Homebrew formula in docs

docs/gcc-Tips.rst
Sorry, overlooked this in #4187.
=> [docs] fix markdown in docs

R-package/R/lgb.Dataset.R
=> [R-package] fix grammar in comments

docs/requirements.txt
This reverts commit 536946e303ee1e89ccd84fd19a3520f7698efe2d.
Refer to #4168.
=> [ci][docs] Unpin Breathe version in requirements.txt

python-package/lightgbm/sklearn.py
Address https://github.com/microsoft/LightGBM/issues/3018#issuecomment-828867332.
=> [docs][python][scikit-learn] added note for LGBMRanker

python-package/lightgbm/basic.py, python-package/lightgbm/engine.py, python-package/lightgbm/sklearn.py
Supersedes #3502.
Closed #3149.
=> [docs][python] update some docs related to custom objective

docs/requirements_base.txt
Refer to https://github.com/microsoft/LightGBM/pull/4256#issuecomment-835785341 and https://github.com/sphinx-doc/sphinx/issues/9188.
=> [ci][docs] Restrict Sphinx version

python-package/lightgbm/plotting.py
Added a specification to restart the session to the import error message regarding Graphviz.
=> [python-package] Improve Graphviz import error message (fixes #4299)

tests/python_package_test/test_basic.py
I have made changes to seven lines in the file : tests/python_package_test/test_basic.py. 
I am contributing to #4136 
@jameslamb
=> [python] improving the syntax of the fstring in the file : tests/python_package_test/test_basic.py

docs/_static/js/script.js
=> [docs] make building of C++ tests section collapsable

tests/python_package_test/test_consistency.py
Updated the strings were catenation had been done using using + to the new fstring format. 
Contributing to the issue #4136
=> [python-package] updated test_consistency.py to use f-strings

tests/python_package_test/test_plotting.py
=> Updated tests/python_package_test/test_plotting.py to use f-strings

tests/python_package_test/test_dask.py
I have updated the old python syntax with the fstrings in the file : tests/python_package_test/test_dask.py
The pull request is contributing to #4136
=> [python] improving the syntax of the fstring in the file : tests/python_package_test/test_dask.py

tests/python_package_test/test_dask.py
Error was introduced in #4358.
=> [tests][python] fix f-string in test_dask.py

python-package/lightgbm/engine.py
Close #3580.
Refer to https://github.com/microsoft/LightGBM/issues/3949#issuecomment-808810679.
=> [docs][python] enhance `keep_training_booster` param description

python-package/setup.py
Added type hints for python-package/setup.py as per #3756
=> [python] add type hints to python-package/setup.py

helpers/check_dynamic_dependencies.py
This PR adds type hints to helpers/check_dynamic_dependencies.py.
=> [python] add type hints to check_dynamic_dependencies.py

R-package/DESCRIPTION
As per suggestion https://github.com/microsoft/LightGBM/pull/4291#issuecomment-841701659.
=> [docs][R-package] add authors in R-package description

examples/python-guide/advanced_example.py
I have changed a string that had + concatenation to fstring format. 
Contributing to the issue #4136
=> [python] Improving the syntax of the fstrings in the file: .\examples\python-guide\advanced_example.py

README.md
> Compatible with most of sklearn, **lightgbm**, catboost, xgboost models
https://github.com/MAIF/shapash/blob/master/docs/index.rst#shapash-features
=> [docs] Add shapash to the list of related projects

.nuget/create_nuget.py
=> [python] migrate to pathlib in create_nuget.py

README.md
=> [docs] add lleaves to README

examples/python-guide/notebooks/interactive_plot_example.ipynb
=> [python] migrate to f-strings in interactive_plot_example.ipynb

helpers/check_dynamic_dependencies.py, helpers/parameter_generator.py
=> [python] migrate to pathlib in helper scripts

python-package/lightgbm/basic.py
=> [docs][python] add versionadded to Sequence class in Python wrapper

python-package/lightgbm/basic.py, python-package/lightgbm/callback.py, python-package/lightgbm/dask.py, tests/python_package_test/test_basic.py, tests/python_package_test/test_sklearn.py
=> [python] minor refactoring of Python code

tests/distributed/_test_distributed.py, tests/distributed/conftest.py
=> [python] migrate to pathlib in distributed tests

docs/Parameters.rst, include/LightGBM/config.h
https://github.com/microsoft/LightGBM/blob/f83180883a51729af9562ccac7b450c6da79a04a/src/application/predictor.hpp#L43-L58
https://github.com/microsoft/LightGBM/blob/d517ba12f2e7862ac533908304dddbd770655d2b/include/LightGBM/boosting.h#L282-L283
https://github.com/microsoft/LightGBM/blob/8116d880f79967d339783e5e9597351639232015/include/LightGBM/objective_function.h#L61-L62
=> [docs] clarify description of prediction early stopping

python-package/setup.py
=> [python] parallelize MinGW make similarly to Unix make command

python-package/lightgbm/basic.py, tests/python_package_test/test_basic.py
=> [python][tests] refactor tests with Sequence input

docs/Installation-Guide.rst, python-package/README.rst
Supersedes #4517 (https://github.com/microsoft/LightGBM/pull/4517#issuecomment-898448540).
Closes #4484.
=> [docs] Add notes in installation guide, including ones about OpenMP

.ci/test_r_package.sh, .ci/test_r_package_windows.ps1
=> [ci] Check for MM_PREFETCH and MM_MALLOC not only in CRAN builds

.github/CODEOWNERS, docs/FAQ.rst
This shield says @jmoralez has accepted the invitation. Thank you very much and welcome! 🎉 
@jmoralez Please feel free to push directly to the `jmoralez` branch if you want to change something.
@guolinke Could you please invite @jmoralez to our dev Slack?
=> [docs] add José Morales to repo maintainers

docs/Parameters.rst, include/LightGBM/config.h, python-package/lightgbm/basic.py, python-package/lightgbm/sklearn.py
Improve docs according to the suggestion in https://github.com/microsoft/LightGBM/issues/4706#issuecomment-949979204.
=> [docs] improve docs about `nthreads` parameter

docs/Parallel-Learning-Guide.rst
They can't stop changing structure of the repository 😄 
#4712
=> [docs] fix broken SynapseML link

docs/conf.py
Refer to https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html.
=> [docs][python] simplify mocking in docs

python-package/lightgbm/dask.py, python-package/lightgbm/sklearn.py, tests/python_package_test/test_dask.py, tests/python_package_test/test_plotting.py, tests/python_package_test/test_sklearn.py
=> [python][sklearn] remove `verbose` argument from `fit()` method

.ci/setup.sh, .ci/test.sh, .vsts-ci.yml, python-package/README.rst
=> [ci] migrate CI from macOS 10.14 to 10.15 and drop support of Mojave

python-package/lightgbm/basic.py, python-package/lightgbm/engine.py, tests/python_package_test/test_engine.py
Refer to https://github.com/microsoft/LightGBM/pull/4577#discussion_r698828755.
=> [python] remove `verbose` argument of `model_from_string()` method of Booster class

src/treelearner/gpu_tree_learner.cpp
num_data_ is int_32, when 8000000(800w)* 275, it's overflow,  please fix
=> gpu allocate memory overflow

R-package/R/lgb.cv.R, R-package/tests/testthat/test_basic.R, R-package/tests/testthat/test_learning_to_rank.R
Refer to https://github.com/microsoft/LightGBM/pull/4902#discussion_r773553163.
=> [tests][R-package] use one `#` symbol for comments

docs/FAQ.rst, python-package/README.rst
=> [docs] document `conda-forge` channel preference over `default` one and describe possible workaround for OpenMP conflicts in FAQ

python-package/lightgbm/basic.py, python-package/lightgbm/engine.py
Changed `train_data` to `eval_data` in engine.py as well as basic.py
closes #4759
=> Change docs for feval

.appveyor.yml, .vsts-ci.yml
Use strings instead of floats for exact matching.
Refer to https://github.com/microsoft/LightGBM/pull/3880#discussion_r566841420.
=> [ci] Enclose Python versions in quotes in config yml files

python-package/lightgbm/basic.py
**Context**
This PR closes #5046
=> [python-package][docs] Booster eval methods accept list of callables

docs/_static/js/script.js
Fixed #5073.
Corresponding RTD build: https://lightgbm.readthedocs.io/en/docs/pythonapi/lightgbm.LGBMModel.html#lightgbm.LGBMModel.best_iteration_
=> [docs] Improve rendering of class properties in docs

.appveyor.yml, .ci/test_windows.ps1
=> [ci] Remove temp workaround for graphviz installation

docs/Parameters.rst, include/LightGBM/config.h
=> [docs] Document behaviour of the first linear estimator

docs/Parameters.rst, include/LightGBM/config.h
fixes #5139 
Very simple change, just 1 line to docs.
=> [docs] Fix formula in path smoothing docs (fixes #5139)

docs/_static/js/script.js
Linking #3763.
Refer to
https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/list?view=azure-devops-rest-7.1
https://docs.microsoft.com/en-us/rest/api/azure/devops/build/artifacts/get-artifact?view=azure-devops-rest-7.1
=> [ci] Update version of Azure REST API

tests/python_package_test/test_engine.py
Linking #5052.
More strict tests can help to spot some bugs or inconsistencies between different LightGBM versions like https://github.com/microsoft/LightGBM/pull/4630#discussion_r825490038.
=> [tests] replace `fobj` with `custom objective` in test comments and make tests stricter

src/application/application.cpp, src/io/config.cpp, src/io/dataset_loader.cpp, src/network/linkers_socket.cpp
Reported by https://lgtm.com/projects/g/microsoft/LightGBM?mode=tree&ruleFocus=2160310550.
=> fix some wrong format specifiers

include/LightGBM/utils/common.h, src/io/tree.cpp
=> Remove leftovers after the drop of Solaris support

R-package/R/utils.R, R-package/inst/make-r-def.R, R-package/src/install.libs.R, build_r.R
Refer to https://github.com/microsoft/LightGBM/pull/5249#discussion_r889447818.
Continuation of #5294.
=> [R-package] Specify concrete linting rule that is being ignored via `nolint` mark

python-package/lightgbm/basic.py, python-package/lightgbm/engine.py
Adds type hints on `Booster.update()` and the inner method `Booster.__boost()` used to perform boosting with a custom objective function.
=> [python-package] add type hints on Booster.update()

python-package/README.rst
I've edited the Readme to make clear a few minor things that caught me by surprise.
=> [python-package] Improve readme on experimental cuda usage

python-package/lightgbm/basic.py
=> [python-package] prefix NUMERIC_TYPES with _ to make it a internal object

docs/GPU-Windows.rst, docs/Parallel-Learning-Guide.rst
```
URL        `https://www.rpmfind.net/linux/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/m/mingw64-boost-static-1.75.0-7.fc37.noarch.rpm'
Name       `Prebuilt Boost x86_64'
Parent URL file:///home/runner/work/LightGBM/LightGBM/docs/_build/html/GPU-Windows.html, line 176, col 14
Real URL   https://www.rpmfind.net/linux/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/m/mingw64-boost-static-1.75.0-7.fc37.noarch.rpm
Check time 0.488 seconds
Size       196B
URL        `https://www.rpmfind.net/linux/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/m/mingw32-boost-static-1.75.0-7.fc37.noarch.rpm'
Name       `Prebuilt Boost i686'
Parent URL file:///home/runner/work/LightGBM/LightGBM/docs/_build/html/GPU-Windows.html, …
```
=> [docs] Fix links

docs/Features.rst
fix a typo in docs/Features.rst
=> [docs]fix a typo in docs/Features.rst

python-package/lightgbm/basic.py
Refer to
https://github.com/microsoft/LightGBM/blob/c8712a9e083bfa0922f6e860f49a8a374816f43e/python-package/lightgbm/basic.py#L1559-L1564
https://github.com/microsoft/LightGBM/blob/c8712a9e083bfa0922f6e860f49a8a374816f43e/python-package/lightgbm/basic.py#L1582-L1583
https://github.com/microsoft/LightGBM/blob/c8712a9e083bfa0922f6e860f49a8a374816f43e/python-package/lightgbm/basic.py#L1586-L1587
=> [python] Fix typehints in Sequence API

src/objective/cuda/cuda_multiclass_objective.cpp, src/objective/cuda/cuda_multiclass_objective.cu, src/objective/cuda/cuda_multiclass_objective.hpp, src/objective/multiclass_objective.hpp, src/objective/objective_function.cpp
Add multiclass objective for cuda_exp. `MulticlassOVA` for `cuda_exp` will be added after this PR is merged.
=> [CUDA] Add multiclass objective for cuda_exp

src/io/bin.cpp
`tmp_num_sample_values` is unclear in what it means, renamed for explicitness.
=> renamed tmp_num_sample_values to non_na_cnt

python-package/lightgbm/basic.py
Contributes to https://github.com/microsoft/LightGBM/issues/5313
=> [python-package] prefix is_numpy_column_array with _

tests/cpp_tests/test_stream.cpp
Based on https://github.com/microsoft/LightGBM/pull/5427#discussion_r956649785.
=> [tests] Fix cpp streaming data tests

CMakeLists.txt, include/LightGBM/cuda/cuda_metric.hpp, include/LightGBM/cuda/cuda_objective_function.hpp, include/LightGBM/objective_function.h, src/cuda/cuda_algorithms.cu, src/metric/cuda/cuda_regression_metric.cpp, src/metric/cuda/cuda_regression_metric.cu, src/metric/cuda/cuda_regression_metric.hpp, src/metric/metric.cpp, src/metric/regression_metric.hpp, src/objective/cuda/cuda_binary_objective.cu, src/objective/cuda/cuda_binary_objective.hpp, src/objective/cuda/cuda_multiclass_objective.cpp, src/objective/cuda/cuda_multiclass_objective.cu, src/objective/cuda/cuda_multiclass_objective.hpp, src/objective/cuda/cuda_regression_objective.cu, src/objective/cuda/cuda_regression_objective.hpp
Add rmse metric for new CUDA version.
=> [CUDA] Add rmse metric for new CUDA version

python-package/lightgbm/basic.py
Contributes to #5313.
Proposes prefixing the following attributes with `_`, to indicate that user code isn't intended to rely on them.
* `Dataset.need_slice`
* `Dataset.params_back_up`
* `Booster.network`
And removing one unused attribute.
* `Dataset.monotone_constraints`
You can see that it's unused by running the following:
```shell
git grep -E '\.monotone_constraints'
```
See https://github.com/microsoft/LightGBM/issues/5313#issuecomment-1368084618 for reasons supporting this. That comment mentions a few other properties, but I think making those private will be a bit more controversial and generate more discussion, so I'd like to defer them to a later PR.
=> [python-package] make some Booster and Dataset attributes private

python-package/lightgbm/basic.py
Adds type hints on the inner functions in `Booster.trees_to_dataframe()`. This improves `mypy`'s ability to catch bugs, and makes it a bit easier to understand the flow of data through those multiple levels of function calls.
=> [python-package] add type annotations on Booster.trees_to_dataframe() inner functions

.ci/test_r_package.sh
Fixes #6038.
See that issue for details. References:
* https://github.com/usbarmory/usbarmory-debian-base_image/issues/9#issuecomment-451635505
* https://github.com/usbarmory/usbarmory-debian-base_image/issues/9#issuecomment-529991242
* https://askubuntu.com/a/1259808/1651890
=> [ci] fix GPG key download for R Linux jobs (fixes #6038)

.ci/test.sh
Issue identified in https://github.com/microsoft/LightGBM/pull/6034#discussion_r1322255882.
=> [ci] Fix typo in dependencies

docs/FAQ.rst, docs/GPU-Targets.rst, docs/GPU-Tutorial.rst, docs/GPU-Windows.rst, docs/Quick-Start.rst
=> Fix small typo and grammar in docs

README.md
Added LightGBMLSS to external repos
=> [docs] Add LightGBMLSS to README

CONTRIBUTING.md
=> [docs] remove link to Roadmap (fixes #6556)

README.md
=> [docs] Update badge for Link checks workflow

README.md
Updates Rust bindings to a maintainable library
=> [doc] Updates Rust bindings library link in README.md

CMakeLists.txt
... and fix typo in LightGBM name.
=> [cmake] group sanitizer options together

.pre-commit-config.yaml, examples/parallel_learning/train.conf, examples/regression/train.conf, examples/xendcg/train.conf, python-package/lightgbm/basic.py, python-package/lightgbm/callback.py, python-package/lightgbm/dask.py, python-package/lightgbm/plotting.py, src/treelearner/parallel_tree_learner.h, tests/python_package_test/test_arrow.py, tests/python_package_test/test_engine.py, tests/python_package_test/test_sklearn.py, tests/python_package_test/utils.py
Updates `pre-commit` hooks to their latest versions.
The new `ruff` made a few small formatting changes, and the new `typos` caught a few more typos.
=> [ci] [python-package] update pre-commit hooks to latest versions

tests/python_package_test/test_basic.py
Towards https://github.com/microsoft/LightGBM/issues/7031
Increases coverage for:
https://github.com/microsoft/LightGBM/blob/8946151905aa4b16636e2259ad06981c071b3c43/python-package/lightgbm/basic.py#L2754-L2765
=> [python-package] Add unit test for Dataset.set_field and no data

R-package/README.md, R-package/configure.win, R-package/src/Makevars.win.in, R-package/src/install.libs.R, R-package/tests/testthat/helper.R
=> [R-package] small cleanup after R 3.x drop
