microsoft/LightGBM

- include/LightGBM/config.h
- include/LightGBM/tree.h
- src/io/config.cpp
- src/io/tree.cpp
- src/treelearner/serial_tree_learner.cpp
- src/treelearner/serial_tree_learner.h
To solve https://github.com/Microsoft/LightGBM/issues/33
> support max_depth option, to solve (#33)

- src/boosting/gbdt.cpp
Although this combination of parameters is (or should be) uncommon, the resultant error is quite ambiguous. This fix results in the expected behavior; `early_stopping` round doesn't result in an error or in a change of the program's behavior when `> num_iterations`.
This only fixes the current bug. A more robust fix would be to either throw an explicit warning when `num_iterations > early_stopping_round` and abort, or to set `is_early_stopping` to `false`.
> Fixed bug when num_iterations > early_stopping_round

- include/LightGBM/utils/text_reader.h
This error was a bit difficult to figure out: `terminate called after throwing an instance of 'std::length_error' what():  basic_string::_M_create`. It sometimes occurs when loading data because of the following bug:
At the end of a file, `fread` (in [pipeline_reader.h](https://github.com/Microsoft/LightGBM/blob/b23a2c31040131bb63dcff228d427b43bca5570e/include/LightGBM/utils/pipeline_reader.h)) often only partially fills `buffer_process` with new data because it reaches the end of the file. This leaves old data in the part of the buffer that extends beyond the size of the file. When the data file ends with a `\n` or a `\r`, the last index of `buffer_process` that was filled with new data will also contain a `\n` or a `\r`.
In rare cases, the next index (that contains old data from a …
> Fixed bug where text_reader could attempt reads beyond `read_cnt`

- include/LightGBM/utils/common.h
Travis didn't catch this, but on OSX (using GNU 6.2.0) I get the following compilation error:
`error: 'exp' is not a member of 'std'
rec[i] = std::exp(rec[i] - wmax);`
Indeed, `exp` is in `<cmath>`.
> Fixed compilation error on OSX with GNU 6.2.0

- README.md
- include/LightGBM/config.h
- include/LightGBM/utils/common.h
- include/LightGBM/utils/text_reader.h
- src/application/application.cpp
- src/application/predictor.hpp
- src/boosting/boosting.cpp
- src/boosting/gbdt.cpp
- src/io/config.cpp
- src/io/dataset.cpp
- src/io/dense_bin.hpp
- src/io/metadata.cpp
- src/io/parser.cpp
- src/io/parser.hpp
- src/io/sparse_bin.hpp
- src/io/tree.cpp
- src/metric/binary_metric.hpp
- src/metric/dcg_calculator.cpp
- src/metric/rank_metric.hpp
- src/network/linkers_socket.cpp
- src/network/network.cpp
- src/network/socket_wrapper.hpp
- src/objective/binary_objective.hpp
- src/objective/multiclass_objective.hpp
- src/objective/rank_objective.hpp
- src/treelearner/serial_tree_learner.cpp
- src/treelearner/split_info.hpp
While familiarizing myself with the source code, I took the liberty to make the wording of LightGBM's logs and documentation more consistent. I also corrected any spelling errors that caught my eye. I'd say it's better to do this now, rather than later. When LightGBM sees more common use, it will be assumed to have a stable output format and changing it is more likely to lead to serious issues. Packages that parse LightGBM’s logs will require minor changes to their parsing logic to work correctly after this pull request, but any failures resulting from this pull request should be obvious and easily fixed.
The change that is most likely to require some adjustments is that a `:` is now always followed by a space, and there is never a space before it:
`[LightGBM] [Info] Iteration:1, …
> Improved consistency and wording of user-facing logs and documentation

- include/LightGBM/config.h
- src/io/config.cpp
- src/io/dataset.cpp
- src/treelearner/feature_histogram.hpp
- src/treelearner/serial_tree_learner.cpp
- src/treelearner/serial_tree_learner.h
These commits add three regularization parameters that discourage or constrain the complexity of the boosting trees. The parameters can reduce the degree of overfitting and have the added benefit of speeding up training because they limits the number of leaves. The parameters follow (as closely as possible) the implementation of XGBoost's regularization parameters (`alpha`, `lambda`, and `gamma`) to fit with users' expectations about appropriate values.
1. `lambda_l1 (default = 0.0f)` controls the L1 weights regularization by setting the strength of an L1 regularization term in the objective function (i.e. `lambda_l1 * |weights|`). This term is implemented by pushing `sum_gradients` towards zero in the weights calculations.
2. `lambda_l2 (default = 0.0f)` controls the L2 weights …
> Added complexity regularization parameters (L1, L2, min_gain_to_split)

- src/boosting/gbdt.h
It seems like this bug went unnoticed for a while now, even though it has been broken since 4e29145993371cba4b32c4d61ea36e721a0ccdb1. These kinds of bugs are quite serious since they do not cause a crash, but lead to erroneous results. It would be great if we could implement some automated testing once there's a bit of time.
> Fixed prediction bug when num_used_model = NO_LIMIT /  -1

- include/LightGBM/c_api.h
Contains two C-API documentation improvements:
1. The documentation for the parameter `predict_type` in the predict functions now matches what it actually does.
2. Documented that negative values for `n_used_trees` and `num_used_model` indicate "no limit".
> Fixed inconsistencies and missing C-API documentation

- docs/Python-API.md
- examples/python-guide/sklearn_example.py
- python-package/lightgbm/__init__.py
- python-package/lightgbm/callback.py
- python-package/lightgbm/engine.py
- python-package/lightgbm/libpath.py
refer to #129 
@guolinke I test some other parameters, it is indeed also not efficient.
> reset_learning_rate->reset_parameter

- docs/Python-API.md
- python-package/lightgbm/sklearn.py
- tests/python_package_test/test_sklearn.py
@guolinke move from #140 , you can close that thread
1. I suggest adding them one by one in the end of `init`
in [sklearn.base.BaseEstimator](http://scikit-learn.org/stable/modules/generated/sklearn.base.BaseEstimator.html):
> Notes
> All estimators should specify all the parameters that can be set at the class level in their __init__ as explicit keyword arguments (no *args or **kwargs).
2. do we really need override get_params? I suggest move `if self.nthread <= 0: params.pop('nthread', None)` to fit() and delete this method.
> add dart parameter to sklearn interface

- docs/Python-API.md
- python-package/lightgbm/sklearn.py
`eval_sample_weight`, `eval_init_score` and `eval_group` are list, not dict, and list doesn't have `get` method.
> fix creating valid_sets

- .travis.yml
- examples/python-guide/advanced_example.py
- examples/python-guide/simple_example.py
- python-package/README.rst
- python-package/lightgbm/__init__.py
- python-package/lightgbm/basic.py
- python-package/lightgbm/callback.py
- python-package/lightgbm/engine.py
- python-package/lightgbm/libpath.py
- python-package/lightgbm/sklearn.py
- tests/c_api_test/test.py
- tests/python_package_test/test_basic.py
- tests/python_package_test/test_engine.py
- tests/python_package_test/test_sklearn.py
I formatted python code with [pep8](https://www.python.org/dev/peps/pep-0008/) and added it to travis.
The main change:
E1 Indentation
E225 missing whitespace around operator
E226 missing whitespace around arithmetic operator
E261 at least two spaces before inline comment
E301 expected 1 blank line in front of and at the end of a method
E302 expected 2 blank lines in front of and at the end of a function or a class
ignore:
E501 line too long
> python code style with pep8

- pmml/README.md
- pmml/pmml.py
This pull request is for issue Microsoft/LightGBM#31. I created a script pmml.py located inside the pmml directory. It takes the LightGBM_model.txt file generated by the lightGBM executable and translates each tree description inside to a pmml file. The script creates a directory if it does not exist and puts the files there. If the directory does exist then it asks the user to move it. The pmml files have been validated with it's xsd schema. More information on the schema can be found [here](http://dmg.org/pmml/v4-3/GeneralStructure.html). I also ran one of the pmml files as an input model to jpmml-evaluator. And it successfully took an input csv file and processed and scored each row inside. For more information how to use jpmml-evaluator, please look at the README.md file inside the …
> Script to translate the model file to PMML

- R-package/README.md
Provide better documentation for installing the R package:
* To install directly from R using devtools
* To install directly a specific LightGBM commit from R using devtools
* The pre-requisites for Windows (Rtools)
* A quick test to run to check if LightGBM installed correctly
Old PR:
> This allows to fix issue #176.
> 
> Source / R-package folders must not be separated when installing the R package.
> 
> The edit: a lot of details are added for compiling LightGBM successfully in Windows.
> Allow easier installation for R package via devtools

- include/LightGBM/utils/common.h
- src/objective/objective_function.cpp
- src/objective/regression_objective.hpp
> Fix huber loss

- include/LightGBM/boosting.h
- include/LightGBM/c_api.h
- include/LightGBM/config.h
- include/LightGBM/dataset.h
- include/LightGBM/dataset_loader.h
- include/LightGBM/export.h
- include/LightGBM/metric.h
- include/LightGBM/objective_function.h
- src/c_api.cpp
Added more exported symbols to have access to the low-level LightGBM API.
A new file `LightGBM/export.h` was created to define the  `LIGHTGBM_EXPORT` and `LIGHTGBM_C_EXPORT` macros, according to the compiler.
> Export low level interface API for MSVC

- CMakeLists.txt
- R-package/src/lightgbm_R.cpp
- include/LightGBM/utils/openmp_wrapper.h
- include/LightGBM/utils/threading.h
- src/application/application.cpp
- src/application/predictor.hpp
- src/boosting/gbdt.cpp
- src/c_api.cpp
- src/io/dataset.cpp
- src/io/dataset_loader.cpp
- src/io/sparse_bin.hpp
- src/metric/rank_metric.hpp
- src/treelearner/data_partition.hpp
This PR allows compiling LightGBM with a compiler that doesn't support OpenMP, which is the case of some clang versions shipped with MacOS. It also adds the CMAKE option to create a dylib library instead of a .so one.
The main change in the C Code is the new header file `utils/openmp_wrapper.h`
> Make openmp optional, allow for dylib mac library output

- R-package/R/lgb.Dataset.R
Fix for categorical issue #219 and major performance increase when categorical feature count is huge (we talk about 1mil or more).
Users will get the following error (or a very similar one, depending on the initial type of data: dense/sparse) when trying to use an illegal number/column name:
```
Error in lgb.call("LGBM_DatasetCreateFromCSC_R", ret = handle, private$raw_data@p,  : 
api error: categorical_column is not a number,                         if you want to use a column name,                         please add the prefix "name:" to the column name
```
Test with: `devtools::install_github("Laurae2/LightGBM", ref = "patch-5", subdir = "R-package")`
Dataset example: http://archive.ics.uci.edu/ml/machine-learning-databases/00222/bank.zip
Reproducible example:
```r
library(data.table) …
```
> Attempt to fix categorical issue in R package

- R-package/R/lgb.Dataset.R
When the user input unknown categorical_feature values, error is more verbose for troubleshooting.
Follows #228.
Example frame:
| job | month |
| --- | --- |
| values | values |
Verified not breaking what we have previously:
```r
> model <- lgb.train(params, temp_train, 2, learning_rate=1, min_data = 1, min_hessian = 1, num_leaves = 1024)
[LightGBM] [Info] Number of postive: 521, number of negative: 4000
[LightGBM] [Info] Number of data: 4521, number of features: 2
[LightGBM] [Info] No further splits with positive gain, best gain: 0.000000, leaves: 126
[LightGBM] [Info] No further splits with positive gain, best gain: 0.000000, leaves: 116
> model <- lgb.train(params, temp_train, 2, learning_rate=1, min_data = 1, min_hessian = 1, num_leaves = 1024,
+ categorical_feature = c(1, 2)) …
```
> R-package: Provide more verbose error for categorical_feature

- R-package/R/lgb.Predictor.R
This PR should fix the issue #243 
- the prediction output will be a (nrow, ntree) matrix when predleaf = TRUE
- the prediction output will be a (nrow, nclass) matrix when reshape = TRUE
> fix the reshape and predleaf arguments

- src/metric/map_metric.hpp
To be able to compile without OpenMP, all the includes `<omp.h>` should be replaced by `<LightGBM/utils/openmp_wrapper.h>`. I just fixed this for map_metric.cpp
> Fixed compilation without OpenMP

- include/LightGBM/bin.h
- include/LightGBM/dataset.h
Added virtual destructor to BinIterator class. Let's see if using C++11's `default` works on Travis and MSVC.
> Fixed gcc non virtual destructor warning (bin.h) plus minor const fix

- R-package/demo/00Index
- R-package/demo/README.md
- R-package/demo/multiclass.R
R examples lack how to deal with multiclass problems (training, prediction). This PR adds an example for that, and shows also how to predict output in matrix, get raw scores, and leaf for multiclass.
Verified working, inspected manually the predictions for correctness.
```r
> require(lightgbm)
Loading required package: lightgbm
Loading required package: R6
> 
> # we load the default iris dataset shipped with R
> data(iris)
> 
> # we must convert factors to numeric
> # they must be starting from number 0 to use multiclass
> # for instance: 0, 1, 2, 3, 4, 5...
> iris$Species <- as.numeric(as.factor(iris$Species))-1
> 
> # we cut the data set into 80% train and 20% validation
> # the 10 last samples of each class are for validation
> 
> train <- as.matrix(iris[c(1:40, 51:90, 101:140), ])
> …
```
> Add multiclass example in R (train & prediction)

- docs/Python-API.md
- python-package/lightgbm/sklearn.py
don't need to specify 'binary_' or 'multi_' before 'error' and 'logloss' for LGBMClassifier
> refine LGBMClassifier metric

- docs/Parameters.md
Adds `boost_from_average` to docs to keep consistency with current master branch (issue #352, commit e179c7c).
> Add boost_from_average to docs

- docs/Python-API.md
A space is needed between `#` and the headers content according to Github's Markdown format guideline (https://guides.github.com/features/mastering-markdown/).
After adding the spaces, we can jump to the exact position in page by click the link.
> For a better jump link

- include/LightGBM/utils/common.h
- src/c_api.cpp
- src/treelearner/serial_tree_learner.cpp
Hi.
You didn't use type traits with c++ template in a best practice way, so that there are some warnings in VS2017. And some other warnings are about integral type mismatch.
I fixed them all.
> eliminate all VS2017 warnings

- python-package/lightgbm/callback.py
- python-package/lightgbm/engine.py
- tests/python_package_test/test_engine.py
is there a reason to use attr() to pass best_iteration? I think direct use EarlyStopException object is enough, and it avoids data type casting.
> refine early stopping and add a test case

- python-package/lightgbm/engine.py
- tests/python_package_test/test_engine.py
Refer to issue #376 for the solution.
Explanation: https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.RandomState.html
Demo Python code:
```python
import numpy as np
np.random.RandomState(1).permutation(10)
Out: array([2, 9, 6, 4, 0, 3, 1, 7, 8, 5])
np.RandomState(1).random.permutation(10)
Traceback (most recent call last):
File "<ipython-input-5-d2d1cb7145c9>", line 1, in <module>
np.RandomState(1).random.permutation(10)
AttributeError: module 'numpy' has no attribute 'RandomState'
```
> [Python-package]: Fix RandomState issue #376

- R-package/demo/00Index
- R-package/demo/README.md
- R-package/demo/leaf_stability.R
This PR adds an R example showing visualization of overfitting observations (whether train or validation data) using density plots and without using metrics by:
* Binning by quantiles the mean leaf predicted
* Plotting a density plot
* In 3 different forms
A trained model which should be trained more, check the small peaks:
A good training (not overfitting too much), check the smoothness:
A heavily overfitting trained model, check the heavy peaks:
Idea from issue #384.
> [R-package] Add Leaf (in)Stability Example

- docs/Python-API.md
- python-package/lightgbm/__init__.py
- python-package/lightgbm/plotting.py
This change splits plot_tree to two methods:
1. method of creating digraph of tree
2. method of plotting the digraph with matplotlib
Some users want (1) when a tree has many leaves.
> python-package: refine plot_tree

- src/boosting/gbdt.cpp
In `GBDT::ResetTrainingData()` we have a vector `cnt_per_class` to count the number of examples of each label. This vector is initialized with `num_tree_per_iteration_` elements, which seems to be n-1 when there are n classes? So `cnt_per_class` is missing one element; for example, in binary classification case `num_tree_per_iteration_ = 1` but we need `cnt_per_class` to hold counters for two classes. So I allocate `num_tree_per_iteration_ + 1` elements for `cnt_per_class`. I hope this is the correct fix.
> Fix a memory allocation bug of cnt_per_class in GBDT::ResetTrainingData()

- CMakeLists.txt
- src/boosting/gbdt.cpp
We want to put the submodule Boost.Compute at the beginning of compiler search paths, because the submodule usually contains upstream bug fixes that have not been included into the stable Boost releases installed on the host OS.
> Move Boost.Compute include path to the beginning of compiler search paths

- tests/python_package_test/test_basic.py
We should use `assertAlmostEqual` instead of `assertEqual` for comparing floating point numbers in tests. Otherwise sometimes there will be some tiny differences between the results and the tests fail.
Similarly, we should use `np.testing.assert_almost_equal` to replace `assertListEqual`.
I searched `assertEqual` and `assertListEqual` in all tests and it seems this is the last one we should replace.
> change assertEqual to assertAlmostEqual in tests

- docs/Parameters.md
- src/metric/metric.cpp
- src/metric/regression_metric.hpp
- tests/python_package_test/test_engine.py
To keep consistency with the name "Mean Squared Error" as it is not RMSE.
We may add RMSE back under a better name in another PR, because L2 = MSE being RMSE is causing confusion for users.
> Switch RMSE to MSE (true L2 loss)

- R-package/demo/00Index
- R-package/demo/README.md
- R-package/demo/weight_param.R
Additional example for R package.
Not learning with small weights using bad parameters:
Learning with small weights using adjusted parameters:
Learning with default weights using adjusted parameters:
Comparing learning of working learners (small weights seem to do slightly better):
> [R-package] Add weight-parameter adjustment example

- docs/GPU-Windows.md
Working installation steps, applies to Windows installation for:
* Command Line Interface (CLI)
* Python
* R
Indirectly applies to any Unix-based installation for R (similar steps applies for installation, path, `Makeconf`, and `Makevars` modification).
Step by step installation with pictures.
In addition, allow R installation but requires small changes to R's `Makeconf`. We are using the following variables, as they will not be found easily without:
```
BOOST_INCLUDE_DIR = "C:/boost/boost-build/include"
BOOST_LIBRARY = "C:/boost/boost-build/lib"
OpenCL_INCLUDE_DIR = "C:/Program Files (x86)/AMD APP SDK/3.0/include"
OpenCL_LIBRARY = "C:/Program Files (x86)/AMD APP SDK/3.0/lib/x86_64"
```
These variables are identical to what cmake uses.
User is free to change the paths, as it will be …
> Documentation for GPU installation on Windows

- docs/GPU-Targets.md
- docs/GPU-Tutorial.md
- docs/GPU-Windows.md
This PR is more documentation about:
* Targeting CPU or GPU devices (in any configuration) using `gpu_device_id` and `gpu_platform_id`
* Targeting Intel HD Graphics (by disabling dedicated GPUs)
* OpenCL SDK correspondence with targets (Intel, AMD, NVIDIA) with examples (such as using Intel SDK for OpenCL on AMD GPUs)
* Requesting user to use default device for debugging to avoid useless issues (training on a device that does not exist)
If someone has the ability to test the SDKs on the other configurations, it would be great.
> Add more details about GPU (correspondence, targeting)

- CMakeLists.txt
Removes `-march=core2 -mtune=native`.
Fix to fix cmake inconsistency and allow proper debug: https://github.com/Microsoft/LightGBM/issues/436 (they show up even in Debug but they were supposed to be only for Release in cmake?)
Temporary fix but not permanent fix: https://github.com/Microsoft/LightGBM/issues/431#issuecomment-296198423
Performance impact: approximately between -1% and 1%, depends on the task but it will be unnoticeable by most except by benchmarkers.
To follow later: more details on 6-7 May about when one should add the optimizations for the CPU architecture. I will put it in a separate doc. + a website about Gradient Boosted Trees and optimization flag comparisons.
> Temporarily removing architecture optimizations

- src/treelearner/gpu_tree_learner.cpp
Refer to #447 for removal of `-cl-strict-aliasing` flag.
> Fix for Intel OpenCL installation

- src/treelearner/gpu_tree_learner.cpp
- src/treelearner/gpu_tree_learner.h
On some OpenCL platforms the GPU code may fail to compile. This patch fixes the previously non-working exception handler under this failure case and prints a nice build log. It will be very helpful when reporting issues.
> Better debugging info when OpenCL compilation fails

- src/io/bin.cpp
- src/io/config.cpp
The division expression in line 136 may encounter runtime division-by-zero error if min_data_in_bin is set to 0. Modified the control flow to avoid this problem.
> fixed a bug in BinMapper: division by zero

- python-package/lightgbm/sklearn.py
This PR fixes creating eval_set in LGBMClassifier.
The current master (0eb9921991d21f7a61f5404494bad810811b1209) treats traing set as valid set even when valid set is traing set.  
```python
import numpy
numpy.random.seed(42)
import lightgbm
train_x = numpy.random.rand(100, 10)
train_y = numpy.random.randint(2, size=100)
valid_x = numpy.random.rand(100, 10)
valid_y = numpy.random.randint(2, size=100)
gbm = lightgbm.LGBMClassifier()
gbm.fit(train_x, train_y, eval_set=[(train_x, train_y), (valid_x, valid_y)])
```
```
❯ python test.py
[1]	valid_0's binary_logloss: 0.680061	valid_1's binary_logloss: 0.693353
[2]	valid_0's binary_logloss: 0.6688	valid_1's binary_logloss: 0.698276
[3]	valid_0's binary_logloss: 0.659384	valid_1's binary_logloss: 0.701111
[4]	valid_0's binary_logloss: 0.651245 …
```
> python-package: fix creating eval_set in LGBMClassifier

- python-package/lightgbm/plotting.py
Plotting leaf index is very useful after we use `apply` to get predicted leaf every tree.
Example:
> python-package: plot leaf index

- docs/conf.py
If scikit-learn isn't installed (and Read the Docs doesn't have it),
LGBMDeprecated aren't created and can't be imported.
cf. https://github.com/Microsoft/LightGBM/blob/master/python-package/lightgbm/compat.py#L76
#485
> docs: fix build error by mocking LGBMDeprecated

- CMakeLists.txt
Homebrew updated gcc to 7.1.
https://github.com/Homebrew/homebrew-core/commit/0387fe46e9ce9fe4a14dbce9d31d70f5824ff830
https://github.com/Homebrew/homebrew-core/commit/0ab90d39e3ca786c9f0b2fb44c2fd29880336cd2
> Use gcc-7 on OSX

- .travis.yml
- tests/c_api_test/test.py
- tests/python_package_test/test_basic.py
- tests/python_package_test/test_engine.py
- tests/python_package_test/test_plotting.py
- tests/python_package_test/test_sklearn.py
https://docs.pytest.org/
This is the first commit of #261.
(I'm very sorry for too late starting)
I swithed nose to pytest (cf. #483).
> python: use pytest for tests

- docs/GPU-Windows.md
Just one small bug found from here: https://github.com/Microsoft/LightGBM/issues/503
Does not cause any issue, but just for readability.
> Fix GPU compilation folder structure

- R-package/README.md
- README.md
- docs/gcc-tips.Rmd
Changes:
* R users: recommend switching to `CXX11` flag when R>=3.4 because it cannot be modified easily using package `Makevars`
* R users: recommend switching `gcc` version when appropriate
* R users: recommend choosing `-O3 -mtune=native` for maximum performance
* Some benchmarks in docs
* Links to static and interactive benchmarks
* Some pictures to add in dummy issues in GitHub
To add:
* Detailed parameters in docs
Overrides:
* Pull request #480 (will be outdated after this PR)
* Issue #348 (to close after this)
> [WIP] R 3.4 recommendations + Benchmark/Parameter Notes

- include/LightGBM/utils/random.h
The result of a right-shift of a signed negative number is
implementation-dependent.
cf. https://msdn.microsoft.com/en-us//library/336xbhcz.aspx
Fix #519
Fix #521
> Fix undefined behavior

- src/boosting/score_updater.hpp
warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
> Shut up warning

- docs/GPU-Windows.md
- docs/Parameters.md
Using Intel OpenCL is not recommended and may crash the machine due to being non compliant to OpenCL standards. If the objective is to use LightGBM + OpenCL on CPU, one should use AMD APP SDK instead (it can run also on Intel CPUs without any issues).
@guolinke update wiki to reflect the warning?
Fixes:
* #89: LightGBM installs fine on Sierra, but doesn't seem to be running in parallel
* #446: Installation of CMake&MinGW is slow than Visual Studio
* #447: OpenCL Intel Crash + Windows
* #484: R + Multithreading
* #503: cannot compile Boost properly (Windows 10; R)
About #89, tested with different Macbooks under Mac 10.9, 10.10, 10.11, 10.12, with LightGBM v1, v2, and master: no issue detected for performance compared to Windows / Linux.
> Add Intel OpenCL warning

- include/LightGBM/boosting.h
- include/LightGBM/c_api.h
- include/LightGBM/prediction_early_stop.h
- python-package/lightgbm/__init__.py
- python-package/lightgbm/basic.py
- src/application/predictor.hpp
- src/boosting/gbdt.cpp
- src/boosting/gbdt.h
- src/boosting/gbdt_prediction.cpp
- src/boosting/prediction_early_stop.cpp
- src/c_api.cpp
- tests/c_api_test/test.py
- tests/python_package_test/test_basic.py
- tests/python_package_test/test_engine.py
- windows/LightGBM.vcxproj
- windows/LightGBM.vcxproj.filters
This PR adds prediction early stopping to the GBDT class, through a new prediction function `GBDT::PredictRawEarlyStop()`.
This is only one of multiple ways to implement this. Feedback is welcome. See my comments inline.
> Add prediction early stopping

- CMakeLists.txt
- R-package/R/lgb.Booster.R
- R-package/R/lgb.Predictor.R
- R-package/src/lightgbm-all.cpp
- R-package/src/lightgbm-fullcode.cpp
- R-package/src/lightgbm_R.cpp
- R-package/src/lightgbm_R.h
- docs/Parameters.md
- include/LightGBM/boosting.h
- include/LightGBM/c_api.h
- include/LightGBM/config.h
- include/LightGBM/objective_function.h
- include/LightGBM/prediction_early_stop.h
- include/LightGBM/utils/common.h
- python-package/lightgbm/__init__.py
- python-package/lightgbm/basic.py
- src/application/application.cpp
- src/application/predictor.hpp
- src/boosting/gbdt.cpp
- src/boosting/gbdt.h
- src/boosting/gbdt_prediction.cpp
- src/boosting/prediction_early_stop.cpp
- src/c_api.cpp
- src/io/config.cpp
- src/objective/binary_objective.hpp
- src/objective/multiclass_objective.hpp
- src/objective/rank_objective.hpp
- tests/c_api_test/test.py
- tests/python_package_test/test_basic.py
- tests/python_package_test/test_engine.py
@cbecker 
I push many changes. 
I think the type of early_stoping_instance can be auto inferred by the objective function. 
Another problem is, should users really need to create the early_stop_instance by themselves ?  Passing parameters ```round_period``` and ```threshold_margin```  to the predict function are not enough ?
> Support early stopping of prediction in CLI

- include/LightGBM/boosting.h
- include/LightGBM/prediction_early_stop.h
Hi @guolinke , I noticed there was an issue with MSVC when linking against the .so file. This was because I was declaring PredictionEarlyStopInstance to be a class when it is a struct. It's fixed now.
> Fix compilation warning and linkage error with MSVC due to struct mismatch

- R-package/demo/README.md
This PR fixes package building error for strict environments where a warning becomes an error:
```r
Subdirectory 'demo' contains invalid file names:
'README.md'
```
> Fix Subdirectory demo contains invalid file names

- R-package/DESCRIPTION
- R-package/README.md
- R-package/build_package.R
- R-package/src/install.libs.R
This bumps R-package version to 0.2 and add some elements to README / small code changes.
- ~~Try add more options to compile~~ (maybe try in another PR for proper flag addition)
> R-package version to 0.2

- R-package/README.md
- R-package/src/install.libs.R
Some instructions for R-package installation with precompiled dll/lib.
> Instruction for R-package installation with precompiled dll/lib

- python-package/lightgbm/sklearn.py
This commit will regain backward compatibility that has been broken after e465f92aa389b42da3cd596a2df4a59ae5032de7.
For example, before e465f92aa389b42da3cd596a2df4a59ae5032de7, we could get some attributes:
```python
gbm = LGBMClassifier(use_missing=False)
print(gbm.use_missing)
``` 
but currently we have to change the code like this:
```python
gbm = LGBMClassifier(use_missing=False)
print(gbm.other_params['use_missing'])
```
> python-package: set attributes with kwargs

- docs/FAQ.md
Adds warning for https://github.com/Microsoft/LightGBM/issues/632 issue about bagging and multithreading.
Code for reproducible result:
```r
for (i in 1:4) {
for (j in 1:2) {
lgb.unloader(wipe = TRUE)
test <- agaricus.test
dtest <- lgb.Dataset.create.valid(dtrain, test$data, label = test$label)
valids <- list(test = dtest)
cat("\n\n\n--------------------- THREADS: ", i, " - RUN: ", j, " ---------------------\n\n", sep = "")
model <- lgb.train(c(params, num_threads = i, bagging_seed = 1, bagging_freq = 1, bagging_fraction = 0.1),
dtrain,
5,
valids, …
```
> Add bagging issue to FAQ

- R-package/README.md
- R-package/src/install.libs.R
This PR is to help the release of CRAN package of LightGBM.
It removes Visual Studio requirement on Windows. User may still install LightGBM with Visual Studio from GitHub using [Laurae2/lgbdl](https://github.com/Laurae2/lgbdl/).
MinGW should be the default for the following reasons in Windows:
* R expects MinGW compilation
* Rtools, mandatory to start compiling packages, uses MinGW / gcc
* Rtools is most likely installed than Visual Studio
* CRAN does not use Visual Studio
* Precompiled DLLs for CRAN are last resort only
Updates:
* MinGW instead of Visual Studio by default
* R README.md documentation to reflect changes
See issue #629.
> [R-package] Fallback to MinGW when VS build fails

- R-package/demo/early_stopping.R
When using custom evaluation metric, values are passed as not raw values. (fix example)
See example below:
```r
dtrain <- lgb.Dataset(agaricus.train$data, label = agaricus.train$label)
dtest <- lgb.Dataset(agaricus.test$data, label = agaricus.test$label)
param <- list(num_leaves = 4,
learning_rate = 1)
valids <- list(eval = dtest)
num_round <- 1
evalerror <- function(preds, dtrain) {
labels <- getinfo(dtrain, "label")
print(preds)
err <- as.numeric(sum(labels != (preds >= 0.5))) / length(labels)
return(list(name = "error", value = err, higher_better = FALSE))
}
bst <- lgb.train(param,
dtrain,
num_round,
valids,
objective = "binary",
eval = evalerror)
predict(bst, agaricus.test$data)
``` …
> [R-package] Custom evaluation metric gets values as non-raw

- R-package/DESCRIPTION
Attempts to prevent R6 and jsonlite downloads when installing LightGBM by specifying in description file their versions.
Sometimes R wants to update these packages while installing LightGBM, and in the case of an Intranet with fake Internet it will always fail the installation no matter what (just because it can talk with R servers but not download from, as it is not allowed in some scenarii).
> [R-package] Prevent R6 and jsonlite downloads

- python-package/setup.py
The wheel package is only used in the Python wheel release process, and it is not being actually imported anywhere in the lightgbm code. 
There is no need to require user installing wheel in the pip install process.
> Remove wheel from Python requirement

- .travis/test.sh
- CMakeLists.txt
> Remove CMAKE_CXX_COMPILER and CMAKE_C_COMPILER for OSX

- R-package/README.md
For installation setup in R.
Fixes https://github.com/Microsoft/LightGBM/issues/728
> Rtools requires PATH setup in R

- R-package/R/lgb.cv.R
Fix a bug from a comment on issue 760 (workaround: not linked to avoid auto-closing of the issue).
Install with:
```r
devtools::install_github("Laurae2/LightGBM/R-package@patch-1")
```
Try this:
```r
model <- lgb.cv(params,
dtrain,
20,
nfold = 5,
min_data = 1,
learning_rate = 0.3,
early_stopping_rounds = 10)
```
> Simple CV fix for R-package best score

- R-package/R/lgb.Dataset.R
- R-package/R/lgb.train.R
When the user does not construct the dataset explicitly, the user is free to train as much as it wants as the original dataset is never erased.
Fixes https://github.com/Microsoft/LightGBM/issues/775
Test cases, check test 3 vs test 4 to see it in action:
```r
lgb.unloader(wipe = TRUE)
dtrain <- lgb.Dataset(train$data, label = train$label, weight = inverse.rle(list(lengths = c(rep(500, 12), 513), values = 1:13)), init_score = inverse.rle(list(lengths = c(rep(500, 12), 513), values = (1:13) * 2)))
set.seed(1)
model <- lgb.cv(params,
dtrain,
10,
nfold = 4,
min_data = 1,
learning_rate = 0.01,
early_stopping_rounds = 10)
dtest <- dtrain$clone(deep = …
```
> [R-package] Prevent remembering parameters

- R-package/R/lgb.Dataset.R
- R-package/R/lgb.train.R
- R-package/man/lgb.train.Rd
- R-package/man/predict.lgb.Booster.Rd
Reverts Microsoft/LightGBM#796 and fixes it correctly.
STILL TODO
```r
dtrain <- lgb.Dataset(train$data, label = train$label, weight = inverse.rle(list(lengths = c(rep(500, 12), 513), values = 1:13)), init_score = inverse.rle(list(lengths = c(rep(500, 12), 513), values = (1:13) * 2)))
dtrain$construct()
model <- lgb.train(params,
dtrain,
10,
list(train = dtrain),
min_data = 1,
learning_rate = 1,
early_stopping_rounds = 10,
reset_data = TRUE)
dtrain$setinfo("weight", inverse.rle(list(lengths = c(rep(500, 12), 513), values = 13:1)))
dtrain$getinfo("weight")
model <- lgb.train(params,
dtrain,
10,
list(train = dtrain),
min_data = 1,
learning_rate = 1, …
```
> Fix [R-package] Prevent remembering parameters

- README.md
- docs/README.md
Links to docs/development.md updated to docs/development.rst after https://github.com/Microsoft/LightGBM/pull/776
> Update links to Development Guide in docs

- .travis/amd_sdk.sh
This is to fix issue #814 (the AMD APP SDK download link changed)
> fix AMD APP SDK download link

- include/LightGBM/meta.h
- src/metric/xentropy_metric.hpp
- src/objective/xentropy_objective.hpp
Fixes ability to build with MSVS2013 by defining `__func__` keyword.
Discussed in #817.
> Fix __func__ is not defined in MSVS2013

- docs/Parameters.md
- include/LightGBM/boosting.h
- include/LightGBM/c_api.h
- include/LightGBM/config.h
- include/LightGBM/tree.h
- src/application/application.cpp
- src/application/predictor.hpp
- src/boosting/gbdt.cpp
- src/boosting/gbdt.h
- src/boosting/gbdt_prediction.cpp
- src/c_api.cpp
- src/io/config.cpp
It is nice to get feature importances not only for the whole model but also for a single prediction. This PR adds a polynomial time algorithm for computing [SHAP values](https://arxiv.org/abs/1706.06060). These values allocate the difference between the expected margin output and the current prediction's margin output among the input features. They are based on Shapley values from game theory and so are the only possible consistent allocation (where consistent means increasing a feature's importance in the model never decreases its attributed value).
This PR is mostly complete, but I was not sure where best to put some unit tests. For the interface I just added a fourth predict_type option `C_API_PREDICT_CONTRIB`.
Comments?
> Explain individual predictions using SHAP value feature attributions

- R-package/R/lgb.cv.R
- R-package/R/lgb.train.R
This PR forces the R-package to use the number of iterations and the early stopping from `params` if they are passed. They have priority over the default parameters `nrounds` and `early_stopping_rounds`.
See https://github.com/Microsoft/LightGBM/pull/806
Test cases:
```r
test <- agaricus.test
dtest <- lgb.Dataset.create.valid(dtrain, test$data, label = test$label)
params <- list(objective = "regression", metric = "l2", num_iterations = 5)
valids <- list(test = dtest)
model <- lgb.train(params,
dtrain,
100,
valids,
min_data = 1,
learning_rate = 1,
early_stopping_rounds = 10)
```
```r …
```
> [R-package] Merge iterations and early stopping with params

- include/LightGBM/config.h
- src/io/config.cpp
max_depth can take both positive and negative value
> Remove check of max_depth

- python-package/lightgbm/sklearn.py
- tests/python_package_test/test_sklearn.py
Hi there!
This PR just renames parameters `seed` and `nthread` to `random_state` and `n_jobs` respectively in scikit-learn wrapper with keeping backward compatibility.
The most pieces of code is for keeping backward compatibility. Is it necessary to leave old parameters for a while or should I remove all this stuff and just rename parameters?
> [python] parameters renaming for sklearn naming convention

- R-package/R/lgb.model.dt.tree.R
`leaf_parent` does not seem to exist anymore.
Fixes https://github.com/Microsoft/LightGBM/issues/859
ping @yanyachen
> [R-package] leaf_parent does not seem to exist anymore

- README.md
- docs/Parameters.md
- docs/README.md
- docs/development.rst
This PR is a light refactoring of how documentation is organized. The intention is to **get users more quickly to the documentation they are seeking**.
Notes:
* This now refers to Read the Docs as the "primary" documentation website.
* Links are fixed or improved
* Context is added for links to documentation
Next steps:
After this PR, we can consider to move all documentation from the Wiki to the `docs/` folder. If the LightGBM project owners think this is valuable then I can lead this task and complete it.
> Reorganize documentation references

- examples/python-guide/simple_example.py
- examples/python-guide/sklearn_example.py
- include/LightGBM/boosting.h
- include/LightGBM/c_api.h
- python-package/lightgbm/basic.py
- src/boosting/gbdt.cpp
- src/boosting/gbdt.h
- src/c_api.cpp
- tests/python_package_test/test_engine.py
not let python feature importance rely on dumped json model
@guolinke there are two feature importance types in python now, they are different return types (split - int, gain - float), what do you think it's a better way to deal with it, should I make them all return float?
> [MRG] expose feature importance to c_api

- README.md
This PR reorders badges in more logical way and adds license badge.
> [docs] readme badges

- python-package/lightgbm/sklearn.py
This commit will regain backward compatibility that has been broken
after 015c8fff7203b7266ce187938327bc7b478a7218.
When not using early_stopping, `best_score` has scores calculated with all trees.
I'm sorry that I overlooked https://github.com/Microsoft/LightGBM/pull/870#discussion_r135602296.
> python: always assign best_score after train

- R-package/R/lgb.cv.R
Force requirement of binary objective or multiclass objective for stratified cross-validation in R-package.
Fixes https://github.com/Microsoft/LightGBM/issues/896
Reproducible working code:
```r
lgb.unloader(wipe = TRUE)
data(agaricus.train, package='lightgbm')
dtrain <- lgb.Dataset(train$data, label=runif(6513,0,100))
params <- list(objective="regression", metric="l2")
model <- lgb.cv(params,
dtrain,
10,
nfold = 5,
min_data = 1,
learning_rate = 1,
early_stopping_rounds = 10,
stratified = TRUE)
lgb.unloader(wipe = TRUE)
data(agaricus.train, package='lightgbm')
dtrain <- lgb.Dataset(train$data, label=runif(6513,0,100))
params <- list(objective="regression", metric="l2")
model <- lgb.cv(params,
dtrain,
10, …
```
> [R-package] Classification requirement for CV balanced strata

- CMakeLists.txt
I've discovered that LightGBM suffers from the same [problem](https://github.com/dmlc/xgboost/issues/977) as xgboost does, but the name a little bit differs:
```
_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13find_first_ofEPKcyy
```
The [solution](https://github.com/dmlc/xgboost/issues/977#issuecomment-320521225) which solved the problem for me with xgboost doesn't work here, but `CMAKE_CXX_FLAGS` solves it.
> [installation] MinGW fix

- examples/python-guide/simple_example.py
The example pages have the following description for "simple_example.py"
simple_example.py:
* Construct Dataset
* Basic train and predict
* Eval during training
* Early stopping
* Save model to file
* **Dump model to json format**
* Feature importances
But the dump part was missing from the file
> Added dump_model() to simple_example.py

- src/io/config.cpp
The default log said "[LightGBM] [Warning] Accuarcy may be bad since you didn't set num_leaves." but the case max_depth²>num_leaves could also trigger this log.
Correction of a typo too : Accuarcy > Accuracy
> better log for "Check max_depth and num_leaves"

- include/LightGBM/config.h
- src/io/config.cpp
- src/treelearner/feature_histogram.hpp
- tests/python_package_test/test_engine.py
#853
add `min_data_per_group` to avoid overfitting.
> refine categorical split

- R-package/R/utils.R
Fixes an error when a large number is used in a lightgbm parameter.  R will by default convert to scientific notation, which raises the error below.
Code:
```r
model <- lgb.train(
data = dtrain
,nrounds = 10
,min_data = 1
,num_leaves = 3
,objective = "regression"
,bin_construct_sample_cnt = 2000000
)
```
Result:
```
Error in lgb.call("LGBM_DatasetCreateFromCSC_R", ret = handle, private$raw_data@p,  : 
api error: Parameter bin_construct_sample_cnt should be of type int, got "2e+06"
```
> Fix error in R package where parameter is converted to scientific notation

- README.md
- Add public Slack team
- Use Heroku app to send invitation (like https://github.com/fchollet/keras)
- https://github.com/rauchg/slackin
I don't know why https://github.com/Microsoft/LightGBM/commit/a9258fe2c96994516df92488f5824943b373b386 removed Slack team information, but many open source comunity use Slack for user community to ask questions and join the development discussion, and there is no reason for us not use it.
See also https://github.com/Microsoft/LightGBM/issues/595
> Add LightGBM Slack team to README.md

- tests/python_package_test/test_engine.py
fixed #1015.
@guolinke To be honest, I haven't checked other places where default `stratified=True` could be used for non-classifying tasks. You could merge it as a hotfix and I later open a new PR if found such places.
> [python] fixed stratifiedkfold for non-classifying tasks

- python-package/lightgbm/basic.py
> [python] add network config api 

- docker/README.md
- docker/dockerfile-cli
Hello! Not sure if you'd find it useful, but I wrote a small `Dockerfile` to run LightGBM CLI. I used it because `convert_model` is not available via Python API yet.
> Add a Dockerfile for the command-line interface

- docs/GPU-Tutorial.rst
- docs/Installation-Guide.rst
> [docs] Update GPU-Tutorial.rst

- R-package/R/lgb.cv.R
In the R package lgb.cv function, I think weight and init_score are being assigned to the wrong row indices.  This is because in lines 239-241 the indices in 'folds' are in random order , but getinfo returns the training weight and init_score in the order of the original data. 
In my work, this was causing some strange results when using init_score with lgb.cv.  This change makes results look more reasonable.
> [R] fix weight and init_score assignment in lgb.cv

- docs/Parameters.rst
- python-package/lightgbm/basic.py
- python-package/lightgbm/compat.py
- python-package/lightgbm/engine.py
- python-package/lightgbm/sklearn.py
Refer to [this thread](https://github.com/Microsoft/LightGBM/pull/1007#discussion_r148928795).
> [python] max_bin parameter deprecated

- .appveyor.yml
Updated path to Miniconda with Python 3.4 on Appveyor.
Refer to https://github.com/appveyor/website/commit/ccbf2c87ad7a17f2979e3697cc787073543679ea.
> [ci] updated Appveyor

- R-package/src/install.libs.R
Fixes #1125.
To merge when tested (currently being tested) - will drop a msg in this PR when it's tested.
> [R-package] Singlethread make to lower RAM usage significantly

- docs/Features.rst
- docs/Parameters.rst
- docs/Quick-Start.rst
- include/LightGBM/config.h
- include/LightGBM/network.h
- include/LightGBM/objective_function.h
- include/LightGBM/tree_learner.h
- include/LightGBM/utils/common.h
- python-package/lightgbm/basic.py
- src/boosting/gbdt.cpp
- src/boosting/goss.hpp
- src/boosting/score_updater.hpp
- src/io/config.cpp
- src/metric/metric.cpp
- src/metric/rank_metric.hpp
- src/metric/regression_metric.hpp
- src/objective/objective_function.cpp
- src/objective/regression_objective.hpp
- src/objective/xentropy_objective.hpp
- src/treelearner/feature_histogram.hpp
- src/treelearner/serial_tree_learner.cpp
- src/treelearner/serial_tree_learner.h
Use sklearn's solution for the objective function with zero heassian:
1. only use first-order gradients to construct, 
2. then fix the tree's output according to objective function.
Some benchmarks on L1 objective function:
dataset: https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/regression.html#YearPredictionMSD
Result:
> Fix objective functions with zero hessian

- python-package/lightgbm/basic.py
In `_data_from_pandas`, the categorical columns are replaced with `x.cat.codes`. This step converts NaN values in the columns into -1, and the following warning is printed:
```
[LightGBM] [Warning] Met negative value in categorical features, will convert it to NaN
```
So the NaN values are being converted into -1 by `_data_from_pandas` and then converted back to NaN later.
For example, it can be reproduced with the following lines (with pandas 0.22.0):
```python
category = pd.Series(['first', 'second', 'first', 'first', np.nan])
category_type = pd.api.types.CategoricalDtype(categories=['first', 'second'])
X = pd.DataFrame(category.astype(category_type))
y = np.array([1, 0, 1, 1, 1])
clf = lgb.LGBMClassifier(verbose=-1)
clf.fit(X, y)
```
This PR avoids the warning by mapping `-1` in the …
> Do not map NaN in pandas categorical columns to -1

- R-package/demo/multiclass_custom_objective.R
- src/io/config.cpp
Hi everyone,
This pull request permits the use of a custom objective function for multiclass problems. The only real obstacle that prevented me from doing this before is [this line](https://github.com/Microsoft/LightGBM/blob/master/src/io/config.cpp#L197), because custom objective functions will always have `objective_type_multiclass = false`. I changed that line and added a demo in R for how to implement a simple softmax problem with custom objective function and custom eval metric.
I'm not sure if there are any fundamental problems with my approach or if people just don't use custom objective functions for multiclass problems. If it is the former, feel free to disregard this pull request.
Best,
Jan
> Permit use of custom objective function for multiclass problems

- R-package/R/lgb.Booster.R
Fixers 2 minor errors in lgb.Booster.R
```
self$reset_parameter(objective = "none")
```
amended to 
```
self$reset_parameter(params = list(objective = "none"))
```
and `algb.params2str` amended to `lgb.params2str`
> Fix "argument "params" is missing" when using custom objective in reset_parameter()

- R-package/DESCRIPTION
This PR addresses #1270 . R will throw an error if the DESCRIPTION file has any blank lines. Thanks to @vinhdizzo for reporting this issue.
I was able to reproduce the error cited in that issue with current `master` and can confirm that the error goes away after the changes in this PR. I tested both by running the [installation instructions](https://github.com/Microsoft/LightGBM/tree/master/R-package) in this repo.
> [R-package] Remove blank line in DESCRIPTION

- R-package/README.md
Right now the build instructions for R reference 2.0.4, but currently the R package is at 2.1.0. Updating it so instructions can be copy-paste.
> [R-package] Fix version number in README

- python-package/lightgbm/plotting.py
graphviz with lower version can not handle '\n' use r'\n' instead.
```
dot - graphviz version 2.26.0 (20091210.2329) 
```
```
Warning: <stdin>:2: string ran past end of line
Error: <stdin>:3: syntax error near line 3
context:  >>> threshold: <<< 0.6951541439427532"]
Warning: <stdin>:3: string ran past end of line
Warning: <stdin>:4: string ran past end of line
```
An escape sequence is valid in graphviz: see https://graphviz.gitlab.io/_pages/doc/info/attrs.html#k:escString
> use raw string to show label

- docs/GPU-Targets.rst
Add failures for NVIDIA OpenCL inter-operability with other non-NVIDIA vendor platforms.
> OpenCL GPU fails for NVIDIA

- docs/Python-Intro.rst
- python-package/lightgbm/sklearn.py
A small add-on to the docs to clarify how users of the sklearn API can implement shrinkage of the learning rate via a callback
The PR follows the discussion in #1317
> [python][docs] add info on adaptive learning rate in the sklearn API

- .travis/setup.sh
- .travis/test.sh
This PR introduces new way to overwrite link to gcc (previous one `brew link --overwrite gcc` don't work now, maybe temporary). Also gcc's version has been incremented, now Travis image comes with gcc-8.
Fixed #1356.
@guolinke Could you please turn on Rolling builds option for Appveyor? This will bring significant speedup. This option is located here: Settings -> General -> Rolling builds.
https://www.appveyor.com/docs/build-configuration/#rolling-builds
> [ci] fix macOS builds on Travis

- .travis.yml
- docs/GPU-Targets.rst
- docs/GPU-Windows.rst
- docs/Installation-Guide.rst
Refer to #1342.
This PR should be reverted.
I think it'll take much time to fix links. So it's better to stop run gpu tests until they fix download links.
> [ci] temporarily disable gpu tests

- docs/Parameters.rst
- python-package/lightgbm/basic.py
- python-package/lightgbm/sklearn.py
- tests/python_package_test/test_basic.py
- tests/python_package_test/test_engine.py
- tests/python_package_test/test_sklearn.py
Inspired by [this](https://github.com/Microsoft/LightGBM/issues/1340#issuecomment-385902024).
While writing tests I've found some inconsistency between default value of param in C++ code and sklearn wrapper:
```
bagging_freq, default=0, type=int, alias=subsample_freq
subsample_freq : int, optional (default=1)
```
Also sklearn description says: "Frequence of subsample, <=0 means no enable.", but on C++ side there is a validation `CHECK(bagging_freq >= 0);`
@guolinke Which side should be fixed?
Even after bringing the consistency in `subsample_freq` tests fail. For instance, after first `predict` we have
```
res_engine[0][0]
>>> 0.0013241289219269466
res_sklearn[0][0]
>>> 0.0013241290058445348
```
Also, is there any way to test `pred_parameter` works? As I understand, there is no validation …
> [python][docs] reworked predict method in sklearn wrapper and docs improvements

- src/io/dataset.cpp
- src/treelearner/data_parallel_tree_learner.cpp
- src/treelearner/voting_parallel_tree_learner.cpp
This commit will shut up the below warnings, which are raised with GCC 8.1.0.
- warning: 'void* memset(void*, int, size_t)' clearing an object of non-trivial type 'struct LightGBM::HistogramBinEntry'; use assignment or value-initialization instead [-Wclass-memaccess]
- warning: 'void* memcpy(void*, const void*, size_t)' writing to an object of type 'class std::tuple<int, double, double>' with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
This is all of cmake and make logs.
[hoge.log](https://github.com/Microsoft/LightGBM/files/1987181/hoge.log)
Please review carefully.
> Shut up warnings

- src/objective/binary_objective.hpp
This appears to fix issue #1336, leading to greater default boosting efficiency particularly for small unbalanced binary regression problems.
The change is simple; I copied verbatim the BoostFromScore method in the xentropy objective:
https://github.com/Microsoft/LightGBM/blob/5392c9eaf616b10028170346db898a598739a1a7/src/objective/xentropy_objective.hpp#L107-L128
To the future: There is much in common between `xentropy` and `binary` objectives; it's not clear to me yet whether one should subsume the other.  I.e., if `xentropy` ends up doing essentially the same thing as `binary`, maybe `xentropy` should become simply an alias for `binary`.
> Enable boost_from_average as default for binary objective

- docs/Parameters.rst
- examples/python-guide/README.md
- examples/python-guide/logistic_regression.py
These two objectives are closely related. I included (1) a note in the docs to be explicit that `xentropy` is necessary when labels are not binary and (2) an example that makes the relationship clear for users coming at this with "logistic regression" in mind. 
Non-binary labels are a trivial extension of binary ones under log-loss; any lack of generalization is in the code (i.e. enforcing `int` instead of `float`) rather than mathematical, and so it would be understandable if a user mistakenly tried applying `binary` with non-binary labels. If fact I was doing this in R and have yet to identify why it gave reasonable results and did not crash (while `binary` with non-binary labels does crash in python).
> [docs][examples] Clarify relationship between `xentropy` and `binary`

- R-package/R/lgb.cv.R
- R-package/R/lgb.train.R
- R-package/man/lgb.train.Rd
- docs/Python-Intro.rst
- python-package/lightgbm/callback.py
- python-package/lightgbm/engine.py
- python-package/lightgbm/sklearn.py
The document of `early_stopping_rounds` says it will check all of
eval_set. But, this is not true. It doesn't check the dataset
specified as the training data.
This change appends an extra phrase "except the training data" to all
of the sentences "If there's more than one, will check all of them" in
documents.
> [docs][python][R] early_stopping_rounds doesn't check all of eval_set

- docs/Parameters-Tuning.rst
The document says `num_leaves` should be smaller than `2^(max_depth)`.
But, its example says `70` or `80` may get better in case of `max_depth=6`.
2^6 is 64. 70 and 80 are greater than 64. The example doesn't make sense.
Changed `max_depth` from 6 to 7.
Issue: https://github.com/Microsoft/LightGBM/issues/1394
> [docs] Fix num_leaves example

- python-package/lightgbm/plotting.py
- tests/python_package_test/test_engine.py
- tests/python_package_test/test_plotting.py
- tests/python_package_test/test_sklearn.py
Made tree renders more readable by:
- adding space between name and value of the showing info piece;
- new `precision` parameter for control of digits number in float values.
before:
`precision=6`:
> [python] make tree rendering more clear

- docs/Parameters.rst
- docs/Quick-Start.rst
Refer to https://github.com/Microsoft/LightGBM/pull/1421#issuecomment-394354696.
I think that we can just give a reference to the parameters and highlight where to find the most important ones instead of copy-pasting the part of the params' description in `Quick-Start.rst`.
@guolinke 
Is this list on CLI-only params correct now? Please correct me.
https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L85
https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L97
https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L140
https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config …
> [WIP][docs] clarify CLI-only parameters and rework parameters section in Quick-Start guide

- .appveyor.yml
> [ci] run all python-guide examples at Appveyor side

- .travis/setup.sh
Refer to #1429, #1433.
Fails in GPU tests were caused by the absence of `ocl-icd-libopencl1` package, which is in list of dependences of `libopenmpi-dev` package.
> [ci] simplified Travis setup stage

- python-package/lightgbm/plotting.py
I was running into this:
`ValueError: Unknown format code 'f' for object of type 'str'`
for string values when setting precision in `create_tree_digraph`
> [python] dont format string values with precision

- R-package/R/lgb.Dataset.R
- R-package/tests/testthat/test_parameters.R
1. Add test cases for https://github.com/Microsoft/LightGBM/pull/1449
2. Small change to lgb.Dataset construct that fixes compatabilty issue with R v3.5 when using slice with indices given in 1:n syntax.  This was causing one existing test to fail:  https://github.com/Microsoft/LightGBM/blob/master/R-package/tests/testthat/test_dataset.R#L46.  If there is a better way to fix this issue directly in the C code, this change can be removed.
> Add R package test cases for feature penalties

- include/LightGBM/c_api.h
- python-package/lightgbm/basic.py
- src/c_api.cpp
- tests/python_package_test/test_basic.py
Previous discussion in https://github.com/Microsoft/LightGBM/issues/1264
I was able to achieve significant speedup and memory savings after applying this patch.
In the earlier discussion @guolinke suggested, that I should use LGBM_DatasetCreateFromSampledColumn API and perform sampling in python. I tried that approach https://github.com/slon/LightGBM/tree/create_from_hist , but it resulted in code duplication between python/c++ and suboptimal performance.
> Support creating Dataset from list of matrices

- README.md
Fixed VSTS status badge and added link for the latest build at master branch.
Also reordered badges because of design reasons: VSTS and Appveyor badges have icons and same color pallet and now are shown close to each other.
Result: https://github.com/Microsoft/LightGBM/blob/badges/README.md
Not sure about `definitionId=7` in VSTS URL. I just took this from here:
> [docs] updated status badges

- .travis/test.sh
- helper/parameter_generator.py
Refer to https://github.com/Microsoft/LightGBM/pull/1511#issuecomment-404840307 .
Added test for consistency between parameters' description in `config.h` and `Parameters.rst` files; parameters' checks in `config.h` and `config_auto.cpp` files.
Example of new test:
this https://github.com/Microsoft/LightGBM/compare/doc-test...test?expand=1#diff-911566ea9fc4de585e528a1f5cc37268 results in this https://travis-ci.org/Microsoft/LightGBM/jobs/403637682#L908
Also fixed `sed` with `-i` option at macOS.
> [ci] added test for parameters consistency

- python-package/setup.py
This PR prevents such errors like
https://github.com/RGF-team/rgf/issues/65
https://github.com/henry0312/pytest-codestyle/pull/34
> [python] open files with utf8 encoding during installation

- python-package/lightgbm/sklearn.py
- take into account `'verbosity'` alias
- use neutral `eval_at` for MAP, NDCG metrics
- define `_get_meta_data` outside the loop
- use `in` instead of multiple `==`
- fix `eval_at` description
> [python] minor fixes in sklearn wrapper

- .github/ISSUE_TEMPLATE.md
Show instructions about posting issues only while creating the issue (achieved by html comments tag).
Also, placeholders for logs have been added to prevent the case when part of the log becomes heading (when users paste logs at the same line as heading).
> [docs] reworked GitHub issue template

- include/LightGBM/network.h
This fixes the seg fault error in LightGBM quantile regression when there are more than 2 workers (distributed workflow) found by users here:
https://github.com/Azure/mmlspark/issues/341
I was able to reproduce the "hanging issue" locally in a notebook with 2 partitions, but it was actually a seg fault that occurred when I looked at the debug.  The debug code to track down the issue is located here:
https://github.com/imatiach-msft/LightGBM/commit/9b810a6a08debc4ca20d8a679d2a885223459e3f
When I executed with only 1 worker I did not see any errors.
I'm not very familiar with this code, specifically how Allreduce works in LightGBM, but I was able to confirm that after the fix I was no longer getting any seg faults.
Tagging @guolinke @peay @ezerhoun
> fix error when using distributed quantile regression

- .travis.yml
- python-package/setup.py
GPU task fails with Python 3.7. I suppose it's due to the miss of the `boost` library for py37 at conda.
Drop Python 3.4 task as misleading because there are no packages for it at conda and conda silently replaces `3.4 -> 3.7` ([log](https://travis-ci.org/Microsoft/LightGBM/jobs/415410861)) in this case (Travis scenario). Appveyor has pinned Miniconda versions and in this case conda doesn't replace missed version with the newest one, but simply crashes:
```
UnsatisfiableError: The following specifications were found to be in conflict:
- python 3.4*
- python-graphviz -> python 3.5*
Use "conda info <package>" to see the dependencies for each package.
Command exited with code 1
```
> [python][ci] start to support Python 3.7

- include/LightGBM/utils/pipeline_reader.h
- include/LightGBM/utils/text_reader.h
- src/application/predictor.hpp
- src/c_api.cpp
according to the [discussion](https://stackoverflow.com/questions/4986673/c11-rvalues-and-move-semantics-confusion-return-statement/4986802#4986802) here.
and the C++11 §12.8/32
```
When the criteria for elision of a copy/move operation are met, but not for an exception-declaration, and the
object to be copied is designated by an lvalue, or when the expression in a return statement is a (possibly
parenthesized) id-expression that names an object with automatic storage duration declared in the body or
parameter-declaration-clause of the innermost enclosing function or lambda-expression, overload resolution
to select the constructor for the copy is first performed as if the object were designated by an rvalue. If
the first overload resolution fails or was not performed, or if the type of …
```
> remove unnecessary  std::move & unused capture

- src/application/predictor.hpp
- src/c_api.cpp
Please consider my changes.
1. Exploit the fact that we know `std::vector` size before filling in `RowFunctionFromCSR`
2. I suppose here is typo in `ClearPredictBuffer`. In mine opinion we should use memset in the case when more than a half of elements are non-zeros.
> Small optimizations and fixes

- python-package/setup.py
Do not try to compile MPI version with MSBuild; use CMake + VS instead.
The bug was in that with `--use_mpi` option it actually installed `/p:Configuration=DLL`.
> [python] fixed MPI version installation

- python-package/setup.py
It reduces practically useless log entries from copying files during the installation process.
In the majority of Python versions `verbose=0` is default value.
> [python] copy files silently during the installation

- python-package/README.rst
- python-package/lightgbm/__init__.py
Refer to https://github.com/Microsoft/LightGBM/pull/1606#issuecomment-415932865 .
Is `2.1.4` version OK? 
My thoughts are that at least one version should be uploaded to PyPI with this warning but without switching to Apple Clang.
Connected to #1523.
> add future warning for macOS users about switching to Apple Clang

- CMakeLists.txt
Added LightGBM JAVA SWIG wrapper support for windows OS
TODO: Add to Mac OS (need to find a Mac to validate this on)
To validate on windows (note, you must have SWIG and java sdk installed and JAVA_HOME environment variable must be set):
mkdir build
cd build
cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DUSE_SWIG=ON ..
cmake --build . --target ALL_BUILD --config Release
> Added LightGBM JAVA SWIG wrapper support for windows

- python-package/lightgbm/basic.py
Refer to https://github.com/Microsoft/LightGBM/pull/1603#issuecomment-417114777.
Maybe it's better to predict here with **best** iteration, not **all**?
https://github.com/Microsoft/LightGBM/blob/abd737651f5c8f3c42fde693fb1a18c30bb68be3/python-package/lightgbm/basic.py#L2117
However, `Dataset` creation here is still left nonparameterized. Maybe at least add new `group` param for allowing to refit for ranking task?
https://github.com/Microsoft/LightGBM/blob/abd737651f5c8f3c42fde693fb1a18c30bb68be3/python-package/lightgbm/basic.py#L2120
> [python] added kwargs in refit method

- python-package/lightgbm/plotting.py
Move all **non-LightGBM-specific** arguments in tree plotting functions to `**kwargs`. It will free us from reviewing Digraph constructor arguments.
Users who are using positional arguments will see the warning.
Users who are already using keyword arguments will see no difference.
> [python] use kwargs in tree plotting functions

- build_r.R
Refer to #1501, #1522.
For Apple Clang users this note is unnecessary.
> [docs] updated comment about gcc in build R script

- R-package/README.md
- docs/Installation-Guide.rst
- python-package/README.rst
Refer to https://github.com/Microsoft/LightGBM/pull/1621#issuecomment-417984823.
To be not confused with `MSBuild.exe` https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild?view=vs-2017
> [docs] replaced MSBuild with VS Build Tools

- R-package/R/lgb.Predictor.R
Help fix #1540 reported bug (`seq` -> `sep`)
> Help fixing #1540

- R-package/R/lgb.plot.importance.R
- R-package/man/lgb.plot.importance.Rd
In #1626 , I accidentally left the examples on `lgb.plot.importance` with normal `#` instead of Roxygen `#'` comment indicators. This means that the corresponding documentation file was malformed and `R CMD CHECK` started complaining.
Please consider this PR to fix that example documentation.
> [R-package] fix examples in lgb.plot.importance

- src/objective/binary_objective.hpp
Fixed #1514.
Refer to https://github.com/Microsoft/LightGBM/issues/1514#issuecomment-415773397.
I'm not sure that I've chosen the right place for warning.
> added warning about boost_from_average default value

- docs/Python-Intro.rst
- docs/Quick-Start.rst
- fixed naming and enhanced the list of supported input types in Python wrapper;
- added more cross-references to corresponding params in Quick-Start guide;
- replaced Unix and Windows LightGBM command line call with the unified one: `"./lightgbm"`
> [docs] minor docs enhancements

- python-package/lightgbm/basic.py
~To be honest, I'm **not sure** is this change **needed or not**.
But I **suppose** it **may help** to suppress warnings.~
~Refer to #1628.~
I'm sorry. I confused `Booster`'s and `_InnerPredictor`'s `predict()` method interface in #1629. This PR is hotfix for it.
> [python] pass params to predictor in refit

- tests/c_api_test/test_.py
- added more possible folders where library file might be located (needed for the future CI reworking);
- removed `test_` prefix from names of supporting functions, so no need to mark them as `skip` for pytest anymore.
> slight C_API test refactoring

- .travis.yml
- .travis/test.sh
Speed up MPI version test by splitting it to `source` and `pip` (just like GPU version).
> [ci] split mpi version test into two: source and pip

- docs/Parameters.rst
- include/LightGBM/config.h
- python-package/lightgbm/basic.py
- python-package/lightgbm/engine.py
- python-package/lightgbm/sklearn.py
- src/io/bin.cpp
Hello,
I was trying to use text hash (random value from 0 to `Int32.MaxValue`) as a categorical feature in LightGBM and got into the trouble of memory consumption. Later I realize how lightGBM make decision rule for categorical variables. Using bitset. It seems that for every decision rule we need a bitset with length max(value). That is for `Int32.MaxValue` it leads to ~250 MiB for one decision!
Please, consider my small edits to the documentation and code to help other users to avoid such mistake. 
Thanks!
> Docs & Warning on sparse categorical features

- .appveyor.yml
- .vsts-ci.yml
- .vsts-ci/test_windows.ps1
Now we have the following setting for Windows:
- VSTS: `regular` (with examples), `sdist`, `bdist` under **VS 2017** (~10 min)
- Appveyor: `regular` (with examples) under **VS 2015** and **MinGW** (~10-15 min, was ~40 min)
Also, MinGW version has been updated from 6.3.0 to 7.3.0.
Known bug: conda at Windows cannot handle Python 3.7 properly yet (`Importing the multiarray numpy extension module failed.  Most likely you are trying to import a failed build of numpy. Original error was: DLL load failed: The specified module could not be found.` at VSTS and `Command executed with exception:   from collections import Sequence` at Appveyor).
While working on this PR, I found weird bug. The same symptoms were described in #1475. When I tried to run **all** examples by `pytest …
> [ci] rebalanced Windows tests

- .travis.yml
- .travis/setup.sh
- .travis/test.sh
- .vsts-ci.yml
- .vsts-ci/setup.sh
- .vsts-ci/test.sh
Now we have the following setting for Linux:
- VSTS: `regular` (with examples), `sdist`, `bdist`, `if-else`, `mpi-source`, `gpu-source` with **gcc** (6 jobs, were 8)
- Travis: `regular` (with examples), `sdist`, `bdist`, `pylint`, `check-docs`, `mpi-source`, `mpi-pip`, `gpu-source`, `gpu-pip` with **Clang** (9 jobs, were 11)
Travis can easy run 15 concurrent jobs, so there is no need in reduction of job numbers. In contrast, at Azure Pipelines we should try to stick to 10 tasks.
Use the same name `BUILD_SOURCESDIRECTORY` across build scripts: https://github.com/MicrosoftDocs/vsts-docs/issues/665
> [ci] rebalanced Linux tests

- .vsts-ci.yml
- .vsts-ci/setup.sh
- .vsts-ci/test.sh
Now we have the following setting for macOS:
- VSTS: `regular` (with examples), `sdist`, `bdist`, with **gcc** (3 jobs, nothing changed)
- Travis: `regular` (with examples), `sdist`, `bdist`, `mpi-source`, `mpi-pip` with **Clang** (5 jobs, nothing changed)
The main change is that now compilers can be switched via `COMPILER` variable at both VSTS and Travis.
> [ci] rebalanced macOS tests

- build_r.R
> [R-package] Fix build_r.R failing in Windows

- build_r.R
I found myself forgetting to install a couple of R-package dependencies repeatedly on successive LightGBM installations. This wasted some time because compilation runs for quite a while before getting to the part where these packages are required.
> Enforce R-package dependencies in build_r.R before compilation begins

- .github/ISSUE_TEMPLATE.md
For LightGBM GPU version it's also important to know user's GPU device.
> [docs] updated GitHub issue template

- python-package/lightgbm/basic.py
- python-package/lightgbm/callback.py
- python-package/lightgbm/engine.py
- python-package/lightgbm/sklearn.py
Fixed `_temp_file` -> `_TempFile` according to Python class naming convention.
Extremely large lines caused horizontal scrolling on GitHub, which is inconvenient.
> [python] break extremely large lines and fix classname

- python-package/lightgbm/basic.py
Fixed #1657.
I'm confused about the need to copy
https://github.com/Microsoft/LightGBM/blob/a760eae4ff06fa8d522ed53e7df8c31d9e8298f0/python-package/lightgbm/basic.py#L1438
Also, I'm not sure whether `__attr` should be **copied**.
But I suppose that it's logically correct to reset the info connected to the previous data (e.g. `__train_data_name`, `best_iteration`, `valid_sets`, etc.) after calling the `refit` method.
> [python] copy old Booster's attributes to new one in refit method

- .ci/test.sh
We cannot use the latest Sphinx along with rstcheck, but can use it for docs building itself.
Refer to #1713.
> [ci][docs] build docs with latest sphinx

- R-package/DESCRIPTION
Since 2.2.0 requires higher glibc, and therefore cannot be run in some systems. 
I think we release the new binaries ASAP.
> v2.2.1 release

- .ci/test.sh
[macOS Mojave](https://support.apple.com/macos/mojave) (10.14) has been released recently.
I think that we cannot simply append new versions to the filename indefinitely (max filename length?), so let's keep **several identical wheels** for different macOS versions. This PR breaks one wheel into two: `10.6-10.10` and `10.11-10.14`.
> [ci] support macOS 10.14 Mojave

- src/network/network.cpp
Hello
I think, In the Network::Allgather function, the lines 118 and 121 are duplicated.
In my opinion, line 121 should be deleted.
what do you think?
Thanks.
> Remove Duplicate code in Network::Allgather()

- python-package/lightgbm/basic.py
- python-package/lightgbm/engine.py
- python-package/lightgbm/sklearn.py
Just fixed some typos in Python API docs. 
Contributed as a part of Hacktoberfest 2018
> [docs] Fixed some typos in Python API Docs

- python-package/lightgbm/basic.py
Fixing incorrect order of initialization Booster object in distributed setting - network has to be set before booster object is created.
> Fixed distributed training for python API

- .vsts-ci.yml
If the usage of the latest `nuget.exe` version is crucial, then we can add this task https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/nuget?view=vsts, but it's not recommended:
>If you're using the Microsoft-hosted agents, you should leave this check box cleared. We update the Microsoft-hosted agents on a regular basis, but they're often slightly behind the latest version. So selecting this box will result in your build spending a lot of time updating to a newer minor version.
> [ci] build NuGet via built-in Azure tasks

- .ci/setup.sh
- python-package/README.rst
- python-package/lightgbm/__init__.py
Refer to https://github.com/Microsoft/LightGBM/pull/1740#issuecomment-429195138.
Use the lowest possible version of Xcode on Azure.
To be honest, I'm not sure whether it's good decision or not... macOS users tend to use the latest version of the OS. So maybe it's better to focus on the latest AppleClang version?
> [ci] downgrade Xcode version on Azure

- python-package/lightgbm/basic.py
- tests/python_package_test/test_engine.py
Suppress #1764.
Despite the fact that the issue, described in #1764, was caused by the usage of the undocumented feature, I think that saving `pandas_categorical` field to the model not only in `save_model`, but in `model_to_string` and `dump_model`, is good idea.
> [python] save pandas_categorical to model string and JSON

- docs/FAQ.rst
Add a note about #1789 and similar.
Applies not only to LightGBM but for any OpenMP task.
> FAQ for #1789 about OpenMP

- docs/Parameters.rst
- include/LightGBM/config.h
> [docs] is_provide_training_metric param can be used only in CLI version

- docs/Installation-Guide.rst
MS MPI v10 has been released and download link has been changed.
Also, filename has become lowcase.
> [docs] updated MS MPI download link

- .ci/setup.sh
`brew reinstall` ends up with old CMake on Travis:
```
==> Reinstalling cmake 
==> Downloading https://homebrew.bintray.com/bottles/cmake-3.11.4.high_sierra.bo
Already downloaded: /Users/travis/Library/Caches/Homebrew/cmake-3.11.4.high_sierra.bottle.tar.gz
==> Pouring cmake-3.11.4.high_sierra.bottle.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
/usr/local/share/emacs/site-lisp/cmake
==> Summary
🍺  /usr/local/Cellar/cmake/3.11.4: 2,363 files, 32.7MB
```
> [ci] fixed CMake update on Travis

- docs/Installation-Guide.rst
- docs/_static/js/script.js
- python-package/README.rst
- python-package/setup.py
> [docs] documented version without OpenMP support

- .ci/setup.sh
- .travis.yml
Continuation of #1822.
Previous update for fix works, but it is unstable:
https://github.com/Microsoft/LightGBM/commit/b0a938aee175232bc1f20f0041346d07ff049827#commitcomment-31186324
This PR completely eliminate the need of `softwareupdate` command by the usage of latest `Xcode` version.
BTW, I think it's good point to build artifacts on Azure Pipelines with the lowest possible `Xcode` and sometimes to test building process on Travis with latest `Xcode` (instead of default `9.4`).
> [ci] update Xcode on Travis

- .ci/test.sh
The [fix](https://github.com/myint/rstcheck/pull/51) for the compatibility issue with Sphinx 1.8 has been released in rstcheck 3.3.1 version.
Refer to #1713.
> [ci][docs] use latest Sphinx during the whole docs test

- .appveyor.yml
- .ci/setup.sh
- .vsts-ci.yml
- docs/gcc-Tips.rst
Refer to https://github.com/scikit-learn/scikit-learn/issues/12226.
This temp fix should be removed after scikit-learn `0.20.1` release.
@guolinke Could you please fix dockerfile?
```
NotWritableError: The current user does not have write permissions to a required path.
path: /usr/local/miniconda/pkgs/cache/3e39a7aa.json
uid: 1001
gid: 1001
If you feel that permissions on this path are set incorrectly, you can manually
change them by executing
$ sudo chown 1001:1001 /usr/local/miniconda/pkgs/cache/3e39a7aa.json
In general, it's not advisable to use 'sudo conda'.
```
> [ci][docs] updated temp fix for warning written to stderr, fixed conda permissions and updated bench link

- src/boosting/gbdt_model_text.cpp
Hi!
I would like to complete JSON format with `average_output (bool)` and `objective (string)` fields.
Without these fields it is impossible to restore model behavior from JSON format.
What do you think about this?
> add average_output & objective fields to JSON format

- python-package/lightgbm/sklearn.py
Fixed #1859.
I'm just a little bit confused about the inconsistency in case of one-class classification.
`predict_proba()` returns
```
array([[nan, nan],
[nan, nan],
[nan, nan],
[nan, nan],
...
[nan, nan]])
```
but in `predict()` `np.argmax()` transforms this into
```
array([0, 0, 0, ..., 0])
```
> [python] fixed result shape in case of predict_proba with raw_score arg

- R-package/R/lgb.cv.R
- R-package/R/lgb.train.R
> [R] add reset_data in lgb.cv

- python-package/lightgbm/callback.py
Refer to https://github.com/Microsoft/LightGBM/issues/1893#issuecomment-444803315.
Maybe error is better, because users tend to completely ignore warnings?
> [python] disabled early stopping in dart mode

- src/boosting/rf.hpp
Init has been updated to allow for feature_fraction == 1.0f but the change has not been copyed in the ResetConfig function.
> Enabling feature_fraction == 1.0f in ResetConfig

- .ci/setup.sh
- .travis.yml
- .vsts-ci.yml
There is no `8.3.1` version anymore: https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-Readme.md#xcode
> [ci] bump Xcode version on Azure

- src/io/dataset_loader.cpp
This is https://github.com/Microsoft/LightGBM/pull/1862 , rebased on top of master.
This enables users to override the feature penalty when loading a dataset from a binary file.
For instance, it enables disabling/enabling features via:
```Python
dataset = lgbm.Dataset('data.bin',params={'feature_contri': [0,1,1,0]})
....
```
The above is especially useful when the data set is large, so the cost of recreating the data set from the source data is large.
> When loading a binary file, take feature penalty from config if given there.

- src/io/dataset.cpp
File: [LightGBM//src/io/dataset.cpp]
Function: [138:FastFeatureBundling(...)]
Reserving vectors where we already know the size to save on reallocation costs.
Also removed a variable that was unnecessary.
> [Improve Performance] - Reserve vectors, to save reallocation costs.

- docs/GPU-Windows.rst
- docs/Installation-Guide.rst
- Use the same version (1.63.0) across all docs for examples.
- Encourage users to download the latest version: explicitly point to the latest version for binaries and remove hardcoded version from the link to sources.
From Boost readme:
> Starting with 1.64.0 these binaries have been uploaded to Bintray, previous versions can still be found at Sourceforge.
> [docs] updated Boost docs

- R-package/demo/multiclass_custom_objective.R
This PR solves two issues with the R demo for custom multiclass objectives as mentioned in #1846:
- Currently, the built-in method and the custom method do not return the same predictions in the sample script (the last statement evaluates as `FALSE`)
- The two methods do return the same probabilities but only if the classes are balanced
Both issues are due to the fact that the built-in method boosts from an `init_score` equal to the class mean by default. By contrast, the custom method boosts from zero. In the case of balanced classes, we are off only by a constant (hence we get the same probabilities); the case of imbalanced classes is more problematic.
Setting `boost_from_average=FALSE` fixes this. Alternatively, we could set `init_score` to zero explicitly.
> [R] Fix multiclass demo

- CMakeLists.txt
- docs/Installation-Guide.rst
- python-package/setup.py
Fixed #1898
- https://iscinumpy.gitlab.io/post/omp-on-high-sierra/
- https://cliutils.gitlab.io/modern-cmake/chapters/packages/OpenMP.html
- https://github.com/Homebrew/homebrew-core/pull/20589
> Fix build on macOS Mojave

- R-package/demo/basic_walkthrough.R
As outlined in #1939, we should use `lgb.Dataset.create.valid` for validation data instead of `lgb.Dataset` for histogram correctness.
> [R-package] Use lgb.Dataset.create.valid in demos

- include/LightGBM/R_object_helper.h
- src/lightgbm_R.cpp
fix #1884
ping @Laurae2 , any other places we can use int64_t? 
I remember the length of string, and the number of elements in CSC are still limited by int32.
> fix R's overflow

- .appveyor.yml
- .ci/test.sh
- .vsts-ci.yml
- tests/python_package_test/test_engine.py
> [tests][python] added test for huge string model

- python-package/README.rst
- python-package/setup.py
Refer to #1898, #1919, #1923.
This PR adds two new installation options for Apple Clang users: `--openmp-include-dir` and `--openmp-library`.
#1919 fixed compilation with Apple Clang on Mojave for only one particular case: Homebrew default paths. This PR allows to pass custom paths via these options.
Also, this PR tries to use default MacPorts paths in case of installation failure with Homebrew ones.
Unfortunately, I don't have access to Mojave, so I'm gently asking @henry0312 to check this. And please do not merge until this.
> [python] added OpenMP options for python-package installation

- python-package/lightgbm/basic.py
- src/boosting/gbdt_model_text.cpp
- tests/python_package_test/test_engine.py
- tests/python_package_test/test_sklearn.py
This PR was inspired by the following: https://github.com/Microsoft/LightGBM/pull/1964#pullrequestreview-196488992.
The current solution is quite wasteful, because it loads entire file or duplicates the model in a list entries while we need only one line actually. In consequence, this function becomes a bottleneck during the loading big models.
> [python] refined pandas categorical field loading

- .appveyor.yml
- .ci/test_windows.ps1
It seems that `$?` is more reliable than `$LastExitCode`: https://stackoverflow.com/questions/10666035/difference-between-and-lastexitcode-in-powershell.
After switching to `$?` any python warning causes build failure. So, I've redirected them to stdout. As a bonus there are no annoying red lines at Appveyor like the folowing
```
python : C:\Miniconda36-x64\envs\test-env\lib\site-packages\lightgbm\basic.py:1205: UserWarning: categorical_feature in Dataset is overridden.
At line:2 char:3
+   python $file
+   ~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (C:\Miniconda36-... is overridden.:String) [], RemoteException
+ FullyQualifiedErrorId : NativeCommandError
```
> [ci] refined command status check 

- docs/Installation-Guide.rst
Can't find any `cl-icd-libopencl1` Debian packages, but there are `ocl-icd-libopencl1`, I believe this will be better for users.
> [docs] Fixed OpenCL Debian package name typo

- docs/Python-Intro.rst
- python-package/lightgbm/basic.py
- python-package/lightgbm/compat.py
- python-package/lightgbm/sklearn.py
> [python] convert datatable to numpy directly

- R-package/demo/boost_from_prediction.R
- R-package/demo/categorical_features_rules.R
- R-package/demo/cross_validation.R
- R-package/demo/early_stopping.R
Validation in R-package should use lgb.Dataset.create.valid as pointed out in #1988.
Currently blocking #1987 (2.2.3 release)
As for the "Hand edit broken commit", this is because #1992 (it didn't seem to push the commit anywhere, not even a branch)
> [R-package] Fix demos not using lgb.Dataset.create.valid

- .appveyor.yml
- .ci/setup.sh
- .ci/test.sh
- .ci/test_windows.ps1
- .travis.yml
- .vsts-ci.yml
Fixed #2010. Refer to https://github.com/ContinuumIO/anaconda-issues/issues/10629.
Multiple minor additions of `-q` and `-y` options for `conda` and `wget` commands.
The main idea of this PR is about that `CondaEnvironment` task on Azure Pipelines [has been deprecated recently](https://github.com/Microsoft/azure-pipelines-tasks/pull/9573). Now users should manage `conda` environments by their own scripts. As it was discovered from the conversation in https://github.com/ContinuumIO/anaconda-issues/issues/10629, Azure Pipelines used their own ["activation"](https://github.com/Microsoft/azure-pipelines-tasks/blob/1873ad9bcf74fd7db3dde3f9c8d246610e71101b/Tasks/CondaEnvironmentV1/conda_internal.ts#L133-L147) of `conda` environments which is not correct and doesn't work with the latest …
> [ci] fixed conda

- docs/Python-Intro.rst
* it is confusing to name validation data `test_data` especially as terms like train, validation, test splits are common in ML. Change variable name in python quick start.
> Change variable name test_data > validation_data

- CMakeLists.txt
- docs/Installation-Guide.rst
- Added support for Java SWIG wrapper in macOS
- Updated installation instructions in documentation
- Verified on mac machine I borrowed
This should resolve https://github.com/Microsoft/LightGBM/issues/1326
> added LightGBM SWIG wrappers for macOS and updated docs

- docs/Python-Intro.rst
- python-package/lightgbm/basic.py
- python-package/lightgbm/compat.py
Refer to https://github.com/dmlc/xgboost/pull/4123.
> [python] update DataTable handling

- docs/Parameters.rst
- include/LightGBM/config.h
- src/io/config_auto.cpp
Closed #2023.
Usage example:
```
train = lgb.Dataset(r'../regression/regression.train')
lgb.train({'objective': 'regression', 'weight_column': 5, 'group_column': 7}, train)
```
What note should be written for [`save_binary`](https://lightgbm.readthedocs.io/en/latest/Parameters.html#save_binary) and [`enable_load_from_binary_file`](https://lightgbm.readthedocs.io/en/latest/Parameters.html#enable_load_from_binary_file)?
> [docs] added notes about params usage when data is provided via path and removed unused param

- include/LightGBM/bin.h
- include/LightGBM/c_api.h
- include/LightGBM/dataset.h
- include/LightGBM/feature_group.h
- python-package/lightgbm/basic.py
- src/c_api.cpp
- src/io/dataset.cpp
- src/io/dense_bin.hpp
- src/io/dense_nbits_bin.hpp
- src/io/sparse_bin.hpp
- tests/python_package_test/test_basic.py
This is useful if features have been previously written out to different binary files.
A usage example is:
```
d1 = Dataset('d1.bin')
d2 = Dataset('d2.bin')
d1.add_features_from(d2)
```
The PR includes the functionality itself (add_features_from in the Python package and the underlying C API call LGBM_DatasetAddFeaturesFrom), as well as unit tests for it.
> Add ability to move features from one data set to another in memory

- src/treelearner/feature_histogram.hpp
This typo leads to incorrect gain values, which could lead to a forced split being incorrectly rejected.
> Fix typo in GatherInfoForThresholdCategorical

- python-package/lightgbm/basic.py
- tests/python_package_test/test_engine.py
Closed #2013.
Calculate feature split histogram in XGBoost-style (https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/core.py#L1694-L1737).
**UPD:** … and in standard (numpy) style.
> [python] added get_split_value_histogram method

- python-package/lightgbm/basic.py
- tests/python_package_test/test_engine.py
Replace `TypeError` for categorical features with more understandable `LightGBMError`.
```
from sklearn.datasets import load_boston
data = lgb.Dataset(*load_boston(True), categorical_feature=[2])
booster = lgb.train({'verbose': -1}, data, num_boost_round=20)
booster.get_split_value_histogram(2)
```
```
TypeError                                 Traceback (most recent call last)
<ipython-input-4-46f3fc73cd0a> in <module>
----> 1 booster.get_split_value_histogram(2)
C:\Program Files\Anaconda3\lib\site-packages\lightgbm\basic.py in get_split_value_histogram(self, feature, bins, xgboost_style)
2480             bins = max(min(n_unique, bins) if bins is not None else n_unique, 1)
2481         print(values)
-> 2482         hist, bin_edges = np.histogram(values, bins=bins) …
```
> [python] disabled split value histogram for categorical features

- .appveyor.yml
- .ci/test.sh
- .ci/test_windows.ps1
Pin `tornado` to previous version.
Issue can be observed in #2047 on all CI services.
```
Traceback (most recent call last):
File "/home/travis/miniconda/envs/test-env/bin/jupyter-nbconvert", line 7, in <module>
from nbconvert.nbconvertapp import main
File "/home/travis/miniconda/envs/test-env/lib/python3.6/site-packages/nbconvert/__init__.py", line 7, in <module>
from . import postprocessors
File "/home/travis/miniconda/envs/test-env/lib/python3.6/site-packages/nbconvert/postprocessors/__init__.py", line 5, in <module>
from .serve import ServePostProcessor
File "/home/travis/miniconda/envs/test-env/lib/python3.6/site-packages/nbconvert/postprocessors/serve.py", line 19, in <module>
class ProxyHandler(web.RequestHandler):
File "/home/travis/miniconda/envs/test-env/lib/python3.6/site-packag …
```
> [ci] compatibility hotfix for notebook execution

- .appveyor.yml
- python-package/setup.py
Python 3.4 is reaching its End of Life today and no need to support it anymore.
https://devguide.python.org/#branchstatus
> [python] Drop Python 3.4 support

- docs/Features.rst
- docs/Python-Intro.rst
- python-package/lightgbm/engine.py
`params` is only supported in form of dict.
Also, fixed some typos.
> [docs] Python wrapper doesn't support params in form of list of pairs

- helpers/parameter_generator.py
- include/LightGBM/c_api.h
- include/LightGBM/config.h
- include/LightGBM/utils/common.h
- src/c_api.cpp
- src/io/config_auto.cpp
- src/treelearner/serial_tree_learner.cpp
> fixed cpplint errors about spaces and newlines

- python-package/lightgbm/basic.py
- tests/python_package_test/test_engine.py
> [python] make possibility to create Booster from string official

- src/metric/regression_metric.hpp
"L1 Loss" ==> "Quantile Loss" in the quantile regression loss metric
> Fixed typo in regression_metric.hpp

- docs/Parameters.rst
- include/LightGBM/config.h
- python-package/lightgbm/basic.py
- python-package/lightgbm/sklearn.py
See comments at the end of #1969
> Update doc string for pred_contrib

- python-package/lightgbm/basic.py
- python-package/lightgbm/engine.py
- python-package/lightgbm/sklearn.py
- tests/python_package_test/test_engine.py
- tests/python_package_test/test_sklearn.py
> [python] ignore pandas ordered categorical columns by default 

- docs/Parameters.rst
- include/LightGBM/config.h
- python-package/lightgbm/sklearn.py
Sorry, overlooked yesterday in #2116 that param name in CLI version is slight different.
> [docs] fixed minor typos

- swig/lightgbmlib.i
added typemap for string arrays in SWIG interface
This is needed for PR in mmlspark repository: https://github.com/Azure/mmlspark/pull/526
To resolve issue in mmlspark: https://github.com/Azure/mmlspark/issues/332
Edit:
also added voidp pointer casts needed for PR that adds LGBMRanker to MMLSpark: https://github.com/Azure/mmlspark/pull/554
To resolve issues in mmlspark: https://github.com/Azure/mmlspark/issues/543
and also: https://github.com/Azure/mmlspark/issues/446
> [SWIG] added typemap for string arrays in SWIG interface

- .ci/dockers/ubuntu-14.04/Dockerfile
- .ci/test.sh
- .vsts-ci.yml
Closed #1945, closed #2124.
Compilation of SWIG wrapper with Clang was tested too: 3ee90d2bab2484aa896be67725ddf683f6edb2fa
> [ci] added job for swig compilation on Linux with artifacts

- docs/.linkcheckerrc
OK, seems Yahoo are not in a hurry fixing their servers. But we have to merge too many PRs.
Since I haven't found any mirrors for this dataset, let's stub corresponding URL for a while. Then we'll remove this URL from ignoring list when Yahoo will wake up.
@guolinke Are you OK with this solution?
> [ci] ignore failing Yahoo URL

- swig/lightgbmlib.i
Getting errors on windows build:
"C:\LightGBM\LightGBM\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\LightGBM\LightGBM\build\_lightgbm_swig.vcxproj" (default target) (4) ->
(ClCompile target) ->
c:\lightgbm\lightgbm\build\java\lightgbmlibjava_wrap.cxx(372): error C2440: 'initializing': cannot convert from 'jint *' to 'int *' [C:\LightGBM\LightGBM\build\_lightgbm_swig.vcxproj]
c:\lightgbm\lightgbm\build\java\lightgbmlibjava_wrap.cxx(399): error C2664: 'void JNIEnv_::ReleaseIntArrayElements(jintArray,jint *,jint)': cannot convert argument 2 from 'int *' to 'jint *' [C:\LightGBM\LightGBM\build\_lightgbm_swig.vcxproj]
0 Warning(s)
2 Error(s)
> [SWIG] fix swig build warnings/errors on windows

- .ci/setup.sh
- .ci/test.sh
- .vsts-ci.yml
Current `master` CI checks fail due to that gcc 9 has been released recently.
> [ci] CI fixes

- docs/Python-Intro.rst
- python-package/lightgbm/engine.py
- python-package/lightgbm/sklearn.py
- tests/python_package_test/test_consistency.py
- tests/python_package_test/test_engine.py
Refer to the discussion https://github.com/microsoft/LightGBM/pull/2172#pullrequestreview-237255303.
> [python] added ability to pass first_metric_only in params

- docs/Parameters.rst
- include/LightGBM/config.h
- src/boosting/gbdt.cpp
- src/boosting/gbdt.h
- src/io/config_auto.cpp
refer https://github.com/microsoft/LightGBM/pull/2159#issuecomment-491576482
> first metric only in earlystopping for cli

- docs/Python-Intro.rst
`num_round` is redundant here because it will be overrideen by `num_trees` in the `param` dictionary.
> [docs] remove duplicated param in Python-Intro.rst

- src/io/file_io.cpp
```
/opt/lightgbm/src/io/file_io.cpp:101:49: error: reinterpret_cast from type ‘const void*’ to type ‘char*’ casts away qualifiers
char* buffer = reinterpret_cast<char *>(data);
```
Fixed #2160, fixed #2185.
> fixed cast error

- python-package/lightgbm/basic.py
- python-package/lightgbm/engine.py
- python-package/lightgbm/sklearn.py
- tests/python_package_test/test_sklearn.py
- Fixed #2189.
- Updated docstings to specify signatures of fobj and feval custom functions for every occurence.
@pseudotensor Please confirm the fix.
> [python] fixed picklability of sklearn models with custom obj and updated docstings for custom obj

- include/LightGBM/c_api.h
Final result: https://lightgbm.readthedocs.io/en/c_api/C-API.html.
> [docs] fixed and enhanced format of C API

- python-package/lightgbm/engine.py
Replace "Traninig" with "Training" in two places.
> [Python] Fix typo in engine.py

- docs/.linkcheckerrc
(Temporary ?) hotfix for handshake failure for OpenMPI site.
If I'm not mistaken, `public.tableau.com` is in the list for the same reason.
> [ci][docs] add OpenMPI link to ignore list

- README.md
I noticed that there is a link to "call for contributions" in the main README that points to an empty issue page (https://github.com/microsoft/LightGBM/issues?q=is%3Aissue+is%3Aopen+label%3Acall-for-contribution).
In this PR, I remove the reference and recommend several other small clarifications in the main README.
> updated links in README

- tests/cpp_test/test.py
- tests/python_package_test/test_basic.py
- tests/python_package_test/test_consistency.py
- tests/python_package_test/test_engine.py
- tests/python_package_test/test_sklearn.py
numpy recommends using `assert_allclose`
> Note 
It is recommended to use one of assert_allclose, assert_array_almost_equal_nulp or assert_array_max_ulp instead of this function for more consistent floating point comparisons.
https://docs.scipy.org/doc/numpy/reference/generated/numpy.testing.assert_almost_equal.html#numpy.testing.assert_almost_equal
> [tests] use numpy.testing.assert_allclose

- .appveyor.yml
- .ci/setup.sh
- .vsts-ci.yml
conda 4.7 is broken completely on Windows:
```
Collecting package metadata: ...working... done
Solving environment: ...working... done
environment location: C:\Miniconda
added / updated specs:
- conda
The following packages will be downloaded:
package                    |            build
---------------------------|-----------------
bzip2-1.0.6                |       hfa6e2cd_5         145 KB
ca-certificates-2019.5.15  |                0         166 KB
certifi-2019.6.16          |           py37_0         155 KB
conda-4.7.5                |           py37_0         3.0 MB
conda-package-handling-1.3.10|           py37_0         280 KB
libarchive-3.3.3           |       h0643e63_5         1.4 MB
libiconv-1.15              |       h1df5818_7         664 KB
libxml2-2.9.9              | …
```
> [ci] downgrade conda

- docs/Parameters.rst
- include/LightGBM/config.h
Fix real name and alias of RMSE metric in docs.
https://github.com/microsoft/LightGBM/blob/16751b3803e847592dba3bab876c4f052507e45d/src/metric/regression_metric.hpp#L132-L134
I guess this should fix this https://github.com/microsoft/LightGBM/pull/2209#discussion_r300841937.
> [docs] switch name and alias of rmse metric

- docs/Parameters.rst
- include/LightGBM/config.h
- include/LightGBM/dataset.h
- src/io/config_auto.cpp
- src/io/dataset.cpp
- src/io/dataset_loader.cpp
- tests/python_package_test/test_engine.py
Implement feature requested in issue #1921. Add new parameter max_bin_by_feature.
> Max bin by feature

- src/boosting/dart.hpp
- tests/python_package_test/test_engine.py
> fix bug when using dart with init_model

- .github/CODEOWNERS
See #2194 for details. Please suggest if I've misinterpreted https://github.com/microsoft/LightGBM/blob/76170788c4bd6239334408f88cf51183ec791fa2/docs/FAQ.rst#critical...I did my best to make this file consistent with the conventions I've observed in PRs in this project. It's very likely I have made some mistakes.
My hope is that using `CODEOWNERS` will turn something being done by convention into something being done by automation. It will, I hope, also improve the contributor experience.
> [ci] added CODEOWNERS (fixes #2194)

- include/LightGBM/dataset.h
- include/LightGBM/utils/common.h
- src/io/config.cpp
> throw error when meet non ascii

- examples/python-guide/notebooks/interactive_plot_example.ipynb
- include/LightGBM/tree.h
- python-package/lightgbm/plotting.py
- src/boosting/gbdt_model_text.cpp
- src/io/tree.cpp
- src/treelearner/serial_tree_learner.cpp
- tests/python_package_test/test_plotting.py
> add weight in tree model output

- docs/conf.py
> Changed in version 1.8: Renamed from app.add_javascript(). And it allows keyword arguments as attributes of script tag.
https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_js_file
> [docs] updated js file attaching mechanism

- .gitignore
- docs/.gitignore
- docs/Python-API.rst
- docs/conf.py
This replaces `autoclass/autofunction` with [sphinx autosummary](https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html) to create and paginate the Python API.
- Add `docs/.gitignore` to not track autosummary stubs
- Add `sphinx.ext.autosummary` in `docs/conf.py`
- Add 'members' and 'inherited-members' as default parameters
- Add 'autosummary = True' for setting output with `:toctree:`
- Add `.. autosummary::` tags to replace `.. autoclass::` and `.. autofunction::`
Previously the `Python-API.rst` dumped all of the Python API onto a single page when `sphinx-build` generated html pages.
This replaces the Python-API documentation with an index listing all modules, and paginates all functions and classes onto separate pages.
In summary, this pull request:
- Requires less …
> [docs] 🎨 Sphinx Autosummary for generating Python-API documentation

- include/LightGBM/config.h
- src/io/config.cpp
> allow passing empty value in parameters

- docs/FAQ.rst
- docs/Installation-Guide.rst
- python-package/README.rst
Fixes #2268. Individual questions can be linked to.
- Reformat "Contents" to use the `.. contents::` directive
- Reword "Critical" into "Critical Issues"
- Reformat "Critical" section to define "critical issues" first
- Reformat FAQ sections to follow a new format (below)
- Reformat FAQ sections so individual questions have links
All sections now follow a new format (below).
A "frequently asked question" may also include a possible
cause and a solution (if the two are not obvious from
the context):
```rst
FAQ Section Title
=================
.. contents::
:local:
:backlinks: none
1. Question 1
-------------
**Possible Cause**: This is likely due to...
**Solution**: Fix with...
```
**Some questions were renamed** to try and make their contents more explicit. (e.g.: **Python Package: …
> [docs] 📝 FAQ overhaul for linking to individual questions

- docs/conf.py
Refer to https://github.com/microsoft/LightGBM/pull/2286#issuecomment-516373439.
Before:
```
D:\Users\nekit\Downloads\LightGBM\docs>make html
Running Sphinx v1.8.5
making output directory...
[autosummary] generating autosummary for: Advanced-Topics.rst, C-API.rst, Development-Guide.rst, Experiments.rst, FAQ.rst, Features.rst, GPU-Performance.rst, GPU-Targets.rst, GPU-Tutorial.rst, GPU-Windows.rst, Installation-Guide.rst, Parallel-Learning-Guide.rst, Parameters-Tuning.rst, Parameters.rst, Python-API.rst, Python-Intro.rst, Quick-Start.rst, README.rst, gcc-Tips.rst, index.rst
...
```
Now:
```
D:\Users\nekit\Downloads\LightGBM\docs>make html
Running Sphinx v1.8.5
making output directory...
[autosummary] generating autosummary for: Python-API.rst
...
```
@hayesall Can you please give your …
> [docs] limit number of files to scan for autosummary generation and reorganize conf.py

- docs/Parameters.rst
- include/LightGBM/config.h
Refer to https://github.com/microsoft/LightGBM/issues/2163#issuecomment-517393323.
@guolinke To be honest, I'm not sure that `pos_bagging_fraction` and `neg_bagging_fraction` are used in MultiClassOVA. It seems to me that according to the code below, `num_pos_data = 0` and `balance_bagging_cond = false` because MultiClassOVA objective doesn't override `NumPositiveData()`.
https://github.com/microsoft/LightGBM/blob/55656f27e13e35a634eb01a11493b10ca1c65c1c/src/boosting/gbdt.cpp#L728-L732
Please tell how it is actually working.
> [docs] fixed params description

- docs/FAQ.rst
- docs/Parameters.rst
- include/LightGBM/config.h
- Remove aliases from boosting options in parameters for the consistency with other parameters.
- Remove question separators from FAQ as they consume a lot of space on the page and for brief solutions it may seem that there is no solution at all (your attention is focused on a big dash instead of an answer).
> [docs] remove aliases from options in params and remove separators in FAQ

- python-package/lightgbm/basic.py
Otherwise, it would print `basic.py:762: UserWarning: categorical_feature in param dict is overridden` when you have pandas categorical features in your train dataset. Because when updating the params for a validation data, the updated params for the train data was being used which already contains `'categorical_column'` computed.
> [python] Deep copy params in _update_params of DataSet

- python-package/lightgbm/basic.py
- python-package/lightgbm/compat.py
- tests/python_package_test/test_engine.py
- tests/python_package_test/test_sklearn.py
Fixed #2143.
I guess there are more smart and efficient solutions, like converting to scipy, but according to that https://github.com/pandas-dev/pandas/issues/21978 was closed on Oct 13 2018 and @drkarthi raised the issue only on May 1 2019 (and the lack of comments for more than 2 months), pandas sparse features seems to be not very popular and it's not worth to implement something more smart.
> [python] add sparsity support for new version of pandas and check Series for bad dtypes

- include/LightGBM/tree.h
- include/LightGBM/utils/common.h
- src/io/tree.cpp
to fix #2266
also refer to #2277 
I think a better solution is let json support inf and nan, not to chang model content.
> fix nan in tree model

- src/io/bin.cpp
- tests/python_package_test/test_engine.py
Fixes a minor bug where setting `max_bin < 4` can cause lightgbm to crash. Below is an example to reproduce the bug. I think the problem is that in `bin.cpp`, the method `FindMaxBinWithZeroAsOneBin` sometimes attempts to create more bins than allowed by `max_bin`.
```
import numpy as np
np.random.seed(0)
y = np.random.choice([0, 1], 100)
X = np.zeros((100, 1))
X[:30, 0] = -1
X[30:60, 0] = 1
X[60:, 0] = 2
X[0] = np.nan
params = {'objective': 'binary', 'seed': 0, 'min_data_in_leaf': 1, 'max_bin': 2}  # causes crash in training
#params = {'objective': 'binary', 'seed': 0, 'min_data_in_leaf': 1, 'max_bin': 3}  # works normally
lgb_x = lgb.Dataset(X, label=y)
est = lgb.train(params, lgb_x)
X[0, 0] = np.nan
params = {'objective': 'binary', 'seed': 0, 'min_data_in_leaf': …
```
> Bug fix: small values of max_bin cause program to crash

- src/objective/rank_objective.hpp
- tests/python_package_test/test_sklearn.py
Additionally, the sigmoid function has an arbitrary factor of 2 in the exponent; it is not just non-standard but the gradients are not computed correctly anyway.
> In the rank objective, lambdas and hessians need to factor sigmoid_ into the computation.

- docs/Installation-Guide.rst
- python-package/README.rst
- python-package/setup.py
I think this PR should be merged **after** 2.2.4 release.
Refer to #1129. Closed #1864.
Description of advantages of `bit32` flag comparing to simple removal of exception can be found in https://github.com/microsoft/LightGBM/pull/1864#issuecomment-441091532.
> [docs][python] allow usage and compilation of 32-bit library

- R-package/tests/testthat/test_basic.R
See the linked issue for details. This PR fixes an issue in the R unit tests.
> corrected typo in R unit tests (fixes #2336)

- R-package/src/install.libs.R
As of #2164 , the R package picked up a fix in `install.libs.R` that handles difficulty finding OpenMP stuff when building on Mac OS Mojave.
Per discussion on #2259 , we found that that fix only works if environment variable `CC` is set to something that literally starts with `gcc` (and the same with `CXX` and `g++`). That could cause build failures if you pass a fully-qualified path like `CXX=/usr/local/bin/g++-8`. Thanks to @brandenkmurray for the help identifying that as the problem!
In this PR, I relax that check so that both `g++-8`, `g++`, and `/some/path/to/g++-8` will all work. I did not take an opinion on the versions of `g++` that are known to work with `lightgbm` (as suggested in [this comment](https://github.com/microsoft/LightGBM/issues/2259#issuecomment-522330822))  as I …
> [R-package] fixed overly-strict compiler check in install.libs.R (fixes #2259)

- R-package/src/install.libs.R
As @StrikerRUS noted on #2345 , the regex change I made in #2339 misses cases where `gcc` or `g++` is matched in an intermediate directory name like `C:/Users/gccharlee/pgcc-8`.
This PR fixes that.
> fixed compiler check regex in install.libs.R

- docs/Parameters.rst
- include/LightGBM/config.h
- src/io/config_auto.cpp
- src/objective/rank_objective.hpp
- tests/python_package_test/test_sklearn.py
benchmark run by https://github.com/guolinke/boosting_tree_benchmarks
ndcg at Yahoo LTR:
| Metric      | original | norm |
|----|  ----| ---- | 
| ndcg@1|0.72757|0.732981|
| ndcg@3|0.731267|0.735689|
| ndcg@5|0.750774|0.75352|
| ndcg@10|0.791388|0.793498|
ndcg at Yahoo LTR:
| Metric      | original | norm |
|----|  ----| ---- | 
| ndcg@1|0.512893|0.519751|
| ndcg@3|0.50118|0.499677|
| ndcg@5|0.505995|0.5058|
| ndcg@10|0.524724|0.524123|
> normalize the lambdas in lambdamart objective

- python-package/setup.py
For instance, `CC` can be `/usr/bin/gcc`. Refer to #2339.
@jameslamb Seems that the regex from #2339 for R-package will produce false positive result for something like `C:/Users/gccharlee/pgcc-8` (any **intermediate folder name** which starts with `gcc`).
> [python] correctly handle full path to compiler in CC and CXX env vars

- src/network/linkers_socket.cpp
> change network retry delay strategy

- swig/lightgbmlib.i
part of fix for https://github.com/Azure/mmlspark/issues/483
specifically, we should be using int64_t directly instead of converting from long values as we are currently doing in some parts of the code
> [java][mmlspark] fix lightgbm swig wrapper on windows

- src/c_api.cpp
In mmlspark, the predictied probabilities column was appearing the same as raw predicted values when both columns were computed from the model.  This is due to a caching bug in the native code logic that was recently added.  I added an array of predictors, one for each type, to fix the caching bug - and also added some additional checks in case the cached predictor needs to be reinitialized (not used by mmlspark directly).
> [java][mmlspark] Fix cached predictor causing bad values for predicted probabilities

- R-package/_pkgdown.yml
Fix one issue from https://github.com/microsoft/LightGBM/issues/1143#issuecomment-526936690.
As we generate docs for the each commit to the `master` branch, version cannot be "released".
Before: 
After:
Refer to https://pkgdown.r-lib.org/reference/build_site.html#development-mode.
> [docs] fix version type in the R-package tooltip

- docs/Parameters.rst
- include/LightGBM/config.h
- src/io/bin.cpp
- src/io/config_auto.cpp
- src/treelearner/data_parallel_tree_learner.cpp
- src/treelearner/serial_tree_learner.cpp
- src/treelearner/serial_tree_learner.h
- src/treelearner/voting_parallel_tree_learner.cpp
- tests/python_package_test/test_engine.py
> sub-features for node level

- .appveyor.yml
- .ci/test.sh
- .vsts-ci.yml
- tests/python_package_test/test_sklearn.py
Prepare to `joblib` removal from `scikit-learn`.
```
DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
```
> [ci][tests] install joblib for test directly

- python-package/lightgbm/basic.py
Seems that `isinstance(data.base, np.ndarray)` is enough to check that `data.base` is not `None`.
> [python] removed excess condition

- src/io/metadata.cpp
> avoid nan and inf in weight/label/init_score

- .travis.yml
To be honest, I have no idea when it was lost from there.
> [ci] add if-else job to Travis

- include/LightGBM/c_api.h
Seems that `monotone_constraints` and `feature_penalty` fields cannot be set, just gotten.
> fixed C API SetField description

- .editorconfig
- LICENSE
- R-package/LICENSE
- docs/Parameters.rst
- include/LightGBM/config.h
> added editorconfig

- include/LightGBM/network.h
- src/objective/binary_objective.hpp
- src/objective/multiclass_objective.hpp
> fix the objective init issues in distributed mode

- .ci/test.sh
- .travis.yml
Refer to #1990, https://github.com/microsoft/LightGBM/pull/2407#issuecomment-531627164.
> [ci] added cpplint check

- .github/CODEOWNERS
Allow recursion in CODEOWNERS.
From https://help.github.com/en/articles/about-code-owners:
```
/build/logs/ @doctocat
docs/*  docs@example.com
```
This is proved by #2406 when no codeowners triggered.
> [ci] fix codeowners

- .ci/setup.sh
Depends on https://github.com/guolinke/lightgbm-ci-docker/pull/3.
Some warnings are generated:
```
[ 87%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/gpu_tree_learner.cpp.o
In file included from /__w/1/s/src/treelearner/data_parallel_tree_learner.cpp:9:
In file included from /__w/1/s/src/treelearner/parallel_tree_learner.h:15:
In file included from /__w/1/s/src/treelearner/gpu_tree_learner.h:177:
/__w/1/s/src/treelearner/ocl/histogram256.cl:831:19: warning: adding 'int' to a string does not append to the string [-Wstring-plus-int]
// )"" "\n#endif" + 9
~~~~~~~~~~~~~~~~~~^~~
/__w/1/s/src/treelearner/ocl/histogram256.cl:831:19: note: use array indexing to silence this warning
// )"" "\n#endif" + 9
^
[  ]
In file included from …
```
> [ci] update clang version

- docs/.linkcheckerrc
- docs/R-API.rst
- docs/index.rst
Pros:
- -1 click for users to reach R-API reference;
- -1 broken link in GitHub repo (`./R/reference`).
Cons:
- language and version settings for RTD (`en/latest`, if we will make them in the future) will be reset in case users want to get back to index page.
> [docs] refer to RTD site directly

- src/network/socket_wrapper.hpp
Refer to https://github.com/microsoft/LightGBM/pull/2407#issuecomment-531752226.
- Move block with system C/C++ headers upper;
- apply alphabetical order.
`#include <iphlpapi.h>` cannot be moved according to the alphabetical order:
<details>
<summary>
Error log
</summary>
```
Directory: D:\a\1\s
Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
d-----        9/23/2019   1:37 PM                build                                                                 
-- Building for: Visual Studio 15 2017
-- The C compiler identification is MSVC 19.16.27032.1
-- The CXX compiler identification is MSVC …
```
> refined order of includes

- python-package/lightgbm/basic.py
- tests/python_package_test/test_basic.py
Make debugging function private.
As this format in contrast to `Booster`'s method cannot be used for storing datasets, many users may be confused about it, because of inattentive reading.
I think this method is not needed to ordinary users. However, there is no problems for advanced users to find it.
> [python] make dump_text() private

- python-package/lightgbm/basic.py
- python-package/lightgbm/callback.py
- python-package/lightgbm/engine.py
- python-package/lightgbm/plotting.py
- python-package/lightgbm/sklearn.py
Fix recently added in new version of `pydocstyle` errors `D214` and `D215`:
```
./python-package/lightgbm/basic.py:2321 in public method `predict`:
D214: Section is over-indented ('Note')
./python-package/lightgbm/basic.py:2321 in public method `predict`:
D215: Section underline is over-indented (in section 'Note')
./python-package/lightgbm/basic.py:2516 in public method `get_split_value_histogram`:
D214: Section is over-indented ('Note')
./python-package/lightgbm/basic.py:2516 in public method `get_split_value_histogram`:
D215: Section underline is over-indented (in section 'Note')
./python-package/lightgbm/sklearn.py:178 in public method `__init__`:
D214: Section is over-indented ('Note')
./python-package/lightgbm/sklearn.py:178 in public method `__init__`:
D215: Section underline is …
```
> [docs][python] fixed docstrings

- src/treelearner/cost_effective_gradient_boosting.hpp
- src/treelearner/serial_tree_learner.cpp
- src/treelearner/serial_tree_learner.h
- windows/LightGBM.vcxproj
- windows/LightGBM.vcxproj.filters
> code refactoring: cost effective gradient boosting

- src/treelearner/feature_histogram.hpp
> fix bug in reset config for dataset

- docs/Installation-Guide.rst
> [docs] added installation guide with Homebrew 

- .travis.yml
- .vsts-ci.yml
- docs/.linkcheckerrc
Bump Linux to `Bionic` and Xcode to `11` at Travis. I think it's a good point to test the oldest supported versions at Azure Pipelines for the most compatibility of produced artifacts, while use the newest ones at Travis.
New version of linkchecker has some issues with anchors detection, so just ignore internal Python API refs (with the hope that Sphinx does everything correctly and they are not broken). Refer to https://github.com/microsoft/LightGBM/pull/1497#discussion_r200812795.
All checks are green for the testing commit with swapped compilers 2757b3f8b9dcd3d901485f2f14d99e7bfbbfdb7a:
> [ci] use the latest versions of OSes at Travis

- docs/Features.rst
After upgrading linkchecker in #2467 this link started producing a lot of annoying `Error: 429 Too Many Requests`, which results in the need to manually re-run docs test many times.
```
URL        `https://www.researchgate.net/publication/242580910_On_Grouping_for_Maximum_Homogeneity'
Name       `On Grouping for Maximum Homogeneity'
Parent URL file:///home/travis/build/microsoft/LightGBM/docs/_build/html/Features.html, line 399, col 29
Real URL   https://www.researchgate.net/publication/242580910_On_Grouping_for_Maximum_Homogeneity
Check time 0.936 seconds
Result     Error: 429 Too Many Requests
```
Also, we already use the new link in `Advanced-Topics` document: `Fisher (1958)`  https://github.com/microsoft/LightGBM/blob/master/docs/Advanced-Topics.rst#categorical-feature-support.
> [docs] updated problem link

- .ci/test.sh
Refer to https://github.com/microsoft/LightGBM/issues/1990#issuecomment-533547900, https://chromium-cpp.appspot.com/.
Seem that the whole `build/c++11` group of error is very specific to Chromium development.
Here are errors in the `build/c++11` group:
https://github.com/google/styleguide/blob/5651966e0275572a9956199418d89c9ccc7b2b1a/cpplint/cpplint.py#L5842-L5855
https://github.com/google/styleguide/blob/5651966e0275572a9956199418d89c9ccc7b2b1a/cpplint/cpplint.py#L5861-L5873
@guolinke I'll be happy to replace the filter with multiple `NOLINT`s as we discussed earlier if you think that some errors in this group are useful for LightGBM.
> [ci] added build/c++11 to cpplint filter

- .appveyor.yml
- .ci/test_windows.ps1
- .vsts-ci.yml
They [will not fix package dependencies for Python 3.5](https://github.com/ContinuumIO/anaconda-issues/issues/11315#issuecomment-537964924), so use Python 3.5 for a job where that package is not needed. Python 3.6 is tested at Appveyor, so I replaced 3.6 -> 3.7 for Azure Pipelines as well.
>  [ci] removed temp fix for missing package 

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
Fix deprecation warning from GitHub:
Refer to https://help.github.com/en/articles/about-issue-and-pull-request-templates.
> reworked GitHub issue templates

- python-package/README.rst
As we have quite verbose CI linter which checks all errors except E501 and  W503, info about only subset of errors seems to be misleading.
> [docs] removed misleading section about pep8 in python's readme

- python-package/lightgbm/basic.py
- python-package/lightgbm/callback.py
- python-package/lightgbm/engine.py
- python-package/lightgbm/sklearn.py
Inspired by https://github.com/microsoft/LightGBM/pull/2443#discussion_r329402346.
> [python] handle params aliases centralized

- R-package/R/lgb.Dataset.R
This PR attempts to fix the issue reported by @rgranvil in #2503 . You can confirm by building the R package from this branch and running the sample code provided in that issue.
I effectively just mirrored what was done on the Python side in #2510 .
> [R-package] Sort indices in lgb.cv() (fixes #2503)

- R-package/R/aliases.R
- R-package/R/callback.R
- R-package/R/lgb.cv.R
- R-package/R/lgb.train.R
- R-package/tests/testthat/test_parameters.R
See discussion in #1893 for background. In this PR, I propose disabling early stopping when the user chooses `'dart'` boosting. The same change was made in the Python package in #1895 .
This PR also adds the additional early stopping alias that was added in #2431 .
While working on this piece of code, I refactored it to make it a bit more obvious what is happening. I found that the same code is copied in `lgb.cv()` and `lgb.train()`. I think this duplication could lead to inconsistencies in the future, but I considered reducing that duplication out of scope.
> [R-package] Disabled early stopping when using 'dart' boosting strategy

- examples/python-guide/advanced_example.py
- examples/python-guide/logistic_regression.py
- examples/python-guide/plot_example.py
- examples/python-guide/simple_example.py
- examples/python-guide/sklearn_example.py
- python-package/lightgbm/basic.py
- python-package/lightgbm/callback.py
- python-package/lightgbm/compat.py
- python-package/lightgbm/engine.py
- python-package/lightgbm/plotting.py
- python-package/lightgbm/sklearn.py
- python-package/setup.py
- tests/c_api_test/test_.py
- tests/python_package_test/test_basic.py
- tests/python_package_test/test_consistency.py
- tests/python_package_test/test_engine.py
- tests/python_package_test/test_plotting.py
- tests/python_package_test/test_sklearn.py
We use `pycodestyle`:
https://github.com/microsoft/LightGBM/blob/cc7a1e27398d86e9befdf6eb08141359882f3d49/.ci/test.sh#L56
> [python] removed unused pylint directives

- README.md
We do not maintain **News** section in README quite long time. So let's redirect users to **releases** page where auto-generated changelogs are available.
> [docs] refactored News section in README

- .ci/lint_r_code.R
This PR removes a comment in `.ci/lint_r_code.R` that is inaccurate.
> [ci][R-package] removed outdated comment in lint_r_code.R

- R-package/DESCRIPTION
Noticed while working on #2530 that we have some packages listed as `Suggests` dependencies for the R package which do not show up anywhere in the examples, tests, or package code (as far as I can tell). We can remove:
* `Ckmeans.1d.dp`
* `DiagrammeR`
* `igraph`
* `stringi`
* `vcd`
I think we should remove these suggested dependencies to reduce the cost of building this library. In some cases R will install Suggests of all packages recursively (e.g. with `devtools::install()`). Also when using `R CMD check`, you will get an error if any `Suggests` dependencies are not found, unless you explicitly express it with an environment variable.
> [R-package] removed unnecessary Suggests dependencies

- src/io/json11.cpp
- src/treelearner/gpu_tree_learner.h
This PR addresses the `cpplint` notes around empty statements (from #1990)
```
src/io/json11.cpp:431:  Empty loop bodies should use {} or continue  [whitespace/empty_loop_body] [5]
...
...
...
src/treelearner/gpu_tree_learner.h:178:  Line contains only semicolon. If this should be an empty statement, use {} instead.  [whitespace/semicolon] [5]
src/treelearner/gpu_tree_learner.h:182:  Line contains only semicolon. If this should be an empty statement, use {} instead.  [whitespace/semicolon] [5]
src/treelearner/gpu_tree_learner.h:186:  Line contains only semicolon. If this should be an empty statement, use {} instead.  [whitespace/semicolon] [5]
```
This gets the project from 92 to 88 `cpplint` issues.
<details><summary>full cpplint log</summary>
Done processing …
> addressed linting items about empty statements

- .github/CODEOWNERS
- docker/dockerfile-python
- docker/dockerfile-r
I noticed two things while reviewing #2554 
1. No maintainers were automatically added as reviewers for that PR
2. When I tried to build `dockerfile-python` with `docker build -t lgbpy -f dockerfile-python .`, I got this warning
```
[WARNING]: Empty continuation line found in:
RUN apt-get update &&     apt-get install -y --no-install-recommends         cmake         build-essential         gcc         g++         git         wget &&     wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh &&     /bin/bash Miniconda3-latest-Linux-x86_64.sh -f -b -p $CONDA_DIR &&     export PATH="$CONDA_DIR/bin:$PATH" &&     conda config --set always_yes yes --set changeps1 no &&     conda install -q -y numpy scipy scikit-learn pandas &&     git clone --recursive --branch stable …
```
> [docs][docker] cleaned up CODEOWNERS and fixed build warning in dockerfile-python

- swig/lightgbmlib.i
Changes needed for:
https://github.com/Azure/mmlspark/issues/720
Need the exposure of LGBM_BoosterDumpModel in the same way as LGBM_BoosterSaveModelToString
> [Java] MMLSPARK-ISSUE-720 - Create SWIG version of BoosterDumpModel that returns string to be used in Java

- docs/conf.py
Our docs builds for `master` fails. Pinning `roxygen2` version for the one from the latest successful build solves the problem.
```
* installing *source* package ‘lightgbm’ ...
** libs
installing via 'install.libs.R' to /tmp/RtmprKIQ2D/devtools_install_537456a8988/lightgbm
* DONE (lightgbm)
Loading required package: R6
Updating roxygen version in /home/docs/checkouts/readthedocs.org/user_builds/lightgbm/checkouts/latest/lightgbm_r/DESCRIPTION
Error in env_get(roxy_meta, key, default = default) : 
unused argument (default = default)
Calls: <Anonymous> ... .f -> parse_tags -> markdown_activate -> roxy_meta_get
Execution halted
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File …
```
> [docs] pin roxygen2 version for RTD

- include/LightGBM/utils/common.h
This is to address the following cpplint warning (#1990), taking us from 88 warnings to 87.
```
include/LightGBM/utils/common.h:414:  Closing ) should be moved to the previous line  [whitespace/parens] [2]  
```
This warning is raised because other common headers sometimes include `max`, but it is safer to include it explicitly.
<details><summary>cpplint log</summary>
```
Done processing src/treelearner/data_partition.hpp
Done processing include/LightGBM/network.h
Done processing src/boosting/prediction_early_stop.cpp
Done processing include/LightGBM/utils/file_io.h
Done processing include/LightGBM/application.h
include/LightGBM/json11.hpp:80:  Single-parameter constructors should be marked explicit.  [runtime/explicit] [5]
include/LightGBM/json11.hpp:81:  Single-parameter constructors …
```
> fixed cpplint warning about parenthesis placement

- src/io/parser.cpp
This is to address the following cpplint warning (#1990), taking us from 88 warnings to 87.
```
src/io/parser.cpp:183:  Add #include <algorithm> for max  
```
This warning is raised because other common headers sometimes include `max`, but it is safer to include it explicitly.
<details><summary>cpplint log</summary>
```
Done processing src/treelearner/data_parallel_tree_learner.cpp
Done processing src/main.cpp
src/io/dataset.cpp:30:  Consider using CHECK_GT instead of CHECK(a > b)  [readability/check] [2]
src/io/dataset.cpp:341:  Consider using CHECK_GT instead of CHECK(a > b)  [readability/check] [2]
Done processing src/io/dataset.cpp
src/treelearner/serial_tree_learner.cpp:290:  Consider using CHECK_GE instead of CHECK(a >= b)  [readability/check] [2] …
```
> explicitly import `std::max` from <algorithm>

- src/io/file_io.cpp
Without this revert, error messages come like:
```
/data00/home/shishaochen/github-repos/microsoft/LightGBM/src/io/file_io.cpp: In static member function ‘static hdfs_internal* LightGBM::HDFSFile::GetHDFSFileSystem(const string&)’:
/data00/home/shishaochen/github-repos/microsoft/LightGBM/src/io/file_io.cpp:120:43: error: request for member ‘length’ in ‘LightGBM::kHdfsProto’, which is of non-class type ‘const char*’
size_t end = uri.find("/", kHdfsProto.length());
^
/data00/home/shishaochen/github-repos/microsoft/LightGBM/src/io/file_io.cpp:125:50: error: request for member ‘length’ in ‘LightGBM::kHdfsProto’, which is of non-class type ‘const char*’
std::string hostport = uri.substr(kHdfsProto.length(), end - kHdfsProto.length());
^ …
```
> Fix build error when HDFS is enabled.

- examples/lambdarank/README.md
- Add reference to documentation on the query data format.
- Refer readers to the official install instructions.
- Change command to use relative path to the `lightgbm` binary built at
the project's root when following build instructions.
> Update LambdaRank example documentation

- R-package/R/lgb.cv.R
- R-package/R/lgb.prepare_rules2.R
- R-package/R/lightgbm.R
- R-package/tests/testthat/test_parameters.R
This PR addresses a few issues found during #2530 . Splitting them out into a separate PR because I think they can go through a much quicker review, and we need to fix them regardless of what is decided in #2530 .
1.  extra comma in `lgb.cv.R`. fixes:
```
lgb.cv : <anonymous>: missing arguments not allowed in calls to ‘list’
```
2. missing quote in documentation in `lgb.prepare_rules2.R`. fixes:
```
Error: LaTeX error. Mismatched quote or braces
```
3. two uses of `expect_true()` where `test_that()` should have been used in `test_parameters.R`
4. fix to avoid warning from `R CMD check`
```
multiple.tree.interprete: no visible binding for global variable
‘abs_contribution’
Undefined global functions or variables:
abs_contribution
```
None of these changes impact the `roxygen` …
> [R-package] fixed minor issues with tests and documentation

- R-package/DESCRIPTION
Fixed #2571.
I don't think we need to wait any PRs as this release is mainly a hotfix (refer to https://github.com/microsoft/LightGBM/pull/2565#issuecomment-553289377).
`v2.3.1` is a draft now: https://github.com/microsoft/LightGBM/releases.
@guolinke @chivee @henry0312 @jameslamb @Laurae2
> Release 2.3.1

- docs/Parameters.rst
- include/LightGBM/config.h
Fix current `master` CI failure.
https://en.wikipedia.org/w/index.php?title=Gamma_distribution&curid=207079&diff=928602300&oldid=928602251
> [docs] fixed broken link in docs

- src/main.cpp
- src/network/linkers.h
- src/network/linkers_mpi.cpp
The issue is that the destructor of Application calls MPI_Finalize(), which will cause the program to hand and prevent from exiting. As a solution, we remove MPI_Finalize() from the destructor and let main() decide whether to call MPI_Finalize() or MPI_Abort() based on the reason it is ending.
> LightGBM would hang on MPI run if only some nodes have a fatal error.

- examples/README.md
Have been meaning to do this for a while. I went back through the Kaggle competitions in the last year and did my best to identify top-3 solutions that used `LightGBM`. 
The only exception is the [Elo Merchant Category Recommendation](https://www.kaggle.com/c/elo-merchant-category-recommendation) competition. The 5th-place submission is the highest-ranked one with a public writeup / kernel available.
> [docs] updated records of kaggle competitions

- python-package/lightgbm/basic.py
I believe that this should be a typo, right? It was strange that it could even compile, because it was clearly red in my Pycharm.
By the way, the continuous-integration has 1 test failing because of 'too many requests', so it should be related to some kind of server problem rather than this commit.
> [python] Variable Typo: redictor -> predictor

- include/LightGBM/utils/text_reader.h
- src/io/config.cpp
- src/main.cpp
- src/metric/multiclass_metric.hpp
- src/network/linkers.h
Refer to #1990.
97 -> 88
Address some recently introduced cpplint errors.
> fixed some cpplint issues

- .appveyor.yml
- .ci/test.sh
- .vsts-ci.yml
- docker/dockerfile-python
- docker/gpu/dockerfile.gpu
- docs/GPU-Tutorial.rst
- docs/Python-API.rst
- docs/Python-Intro.rst
- examples/python-guide/README.md
- python-package/lightgbm/compat.py
- python-package/lightgbm/sklearn.py
- python-package/setup.py
> [python] specify the last supported version of scikit-learn

- include/LightGBM/dataset.h
- src/application/predictor.hpp
- src/io/parser.cpp
> fix predict with header

- R-package/R/lgb.train.R
I've been working my way through `lgb.train()`, trying to refresh my understanding of it and learn more about some of the code that I haven't seen before.
I noticed that there is a misspelled variable...`vaild_contain_train` instead of `valid_contain_train`. This isn't causing any issues since it's completely internal, but it does mean that it's hard to use `grep`  or some other tool to search for the corresponding Python code. I do that often to see how the Python package handled a particular problem.
In this PR, I propose fixing those typos.
> [R-package] fixed typo for variable valid_contain_train

- R-package/R/lgb.cv.R
- R-package/R/lgb.train.R
- R-package/R/utils.R
We have function `lgb.check.params()` in the R package. I'm not sure what it's original intent was, but it is [a few years old](https://github.com/microsoft/LightGBM/blame/master/R-package/R/utils.R) and currently just takes in a list called `params` and immediately returns it.
To simplify the R code slightly, in this PR I propose that we remove it. This function is not exported so removing it is not a user-facing breaking change.
> [R-package] removed function lgb.check.params

- R-package/R/utils.R
In this PR, I propose removing an unnecessary check in `lgb.check.eval()` to simplify it.
```r
if (!is.null(eval)) {
if (is.character(eval) || is.list(eval)) {
```
If `eval` is `NULL`, that inner check will be `FALSE`. So the outer check that asks "is `eval` something non-NULL?" isn't needed.
> [R-package] simplified lgb.check.eval()

- python-package/lightgbm/plotting.py
Sometimes it's more comfortable to scroll a tree vertically, but sometimes horizontal representation can be more appropriate.
```
import matplotlib.pyplot as plt
from sklearn.datasets import load_boston
X, y = load_boston(True)
lgb_train = lgb.Dataset(X, y)
params = {'mc': [1 for i in range(X.shape[1])]}
gbm = lgb.train(params, lgb_train)
```
```
lgb.plot_tree(gbm, dpi=600,
show_info=['split_gain', 'internal_value', 'internal_count', 'internal_weight',
'leaf_count', 'leaf_weight', 'data_percentage'],
orientation="vertical")
plt.show()
```
```
lgb.plot_tree(gbm, dpi=600,
show_info=['split_gain', 'internal_value', 'internal_count', 'internal_weight',
'leaf_count', 'leaf_weight', 'data_percentage'],
orientation="horizontal")
plt.show()
```
> [python] allow to specify orientation of a tree

- src/boosting/gbdt_model_text.cpp
Part of #2604.
Implementation is copied from `SaveModelToString` without sorting.
> added feature importance to JSON dump 

- .ci/lint_r_code.R
- R-package/R/callback.R
- R-package/R/lgb.Predictor.R
In this PR, I propose removing two TODOs in the R package's code. I think that issues is a better home for feature requests than TODO comments.
This wasn't caught by our linting because the default for `lintr::todo_comment_linter` is to check only `'todo'` and `fixme`. In this PR, I've also added `'to-do'` to the linting for this project.
I've described these TODOs in #2665 and #2666 , and added those to #2302 .
> [R-package] [ci] removed TODOs in code

- R-package/README.md
This PR adds documentation of the unofficial `lightgbm` R extension described in #2640 . See [this comment](https://github.com/microsoft/LightGBM/issues/2640#issuecomment-568642105) for the reason that this is being added to `R-package/README.md` instead of `README.md`.
> [R-package] [docs] Added reference to unofficial R extensions (fixes #2640)

- docs/Parameters.rst
- include/LightGBM/config.h
- src/application/application.cpp
- src/application/predictor.hpp
- src/c_api.cpp
- src/io/config_auto.cpp
> option to disable the shape checking in prediction.

- python-package/lightgbm/basic.py
- tests/python_package_test/test_basic.py
Added `trees_to_dataframe` method to Booster class in python API. Based on issue [#2578](https://github.com/microsoft/LightGBM/issues/2578).
> [python] Output model to a pandas DataFrame

- R-package/R/lgb.prepare.R
- R-package/R/lgb.prepare2.R
- R-package/R/lgb.prepare_rules.R
- R-package/R/lgb.prepare_rules2.R
- R-package/tests/testthat/test_lgb.prepare.R
- R-package/tests/testthat/test_lgb.prepare2.R
- R-package/tests/testthat/test_lgb.prepare_rules.R
- R-package/tests/testthat/test_lgb.prepare_rules2.R
In this PR, I propose unit tests on the following currently-untested functions in the R package:
* `lgb.prepare()`
* `lgb.prepare2()`
* `lgb.prepare_rules()`
* `lgb.prepare_rules2()`
The tests in this PR cover 100% of the code in those functions and raise the overall test coverage of the package 64.68% to 71.29% (see #2664 for instructions to reproduce that).
This PR also fixes some typos in error messages and removes some unnecessary comments.
While looking at these functions today, I also discovered some areas for improvement. I think it's important to get these tests in place before refactoring the functions. Issues added to #2302 
* `lgb.prepare` functions should convert `"logical"` columns to `"numeric"` or `"integer"` (#2678)
* `lgb.prepare()` and `lgb.prepare_rules()` should …
> [R-package] added tests on lgb.prepare function

- .gitignore
- R-package/README.md
Really excited to say that I've discovered that `covr` (the most popular library for generating test coverage for R projects) now works well with `lightgbm`'s R package! I had created [jameslamb/lightgbm-r-coverage](https://github.com/jameslamb/lightgbm-r-coverage)  to work around the previous issues I had and I am VERY excited to archive that repo.
In this PR, I propose adding instructions to the R package's README explaining how contributors can generate coverage reports. I think this will be a valuable way for us to catch edge cases that are not covered by our current tests, and all the other good things you can do with code coverage.
At the time of creating this PR, the R package is `64.48%` covered.
```
lightgbm Coverage: 64.48%
R/lgb.plot.importance.R: 0.00%
R/lgb.prepare_rules.R: …
```
> [R-package] Added instructions for generating R test coverage

- include/LightGBM/bin.h
- include/LightGBM/meta.h
- src/io/dataset.cpp
- src/io/dense_bin.hpp
- src/io/dense_nbits_bin.hpp
- src/io/ordered_sparse_bin.hpp
- src/io/sparse_bin.hpp
set prefetch hint to increase cache hit chance.
benchmark:
| Data      | Master|  This PR | Improvement |  
|----|  ----| ----- | ----|
| Higgs|252.526271  |192.186991 s | 1.31x |
| Yahoo LTR|158.277699 s |129.526579 s | 1.22x |
| MS LTR|357.12529 s|251.736296 s | 1.42x |
> prefetch hint (1.3x speed-up)

- include/LightGBM/bin.h
- include/LightGBM/dataset.h
- include/LightGBM/feature_group.h
- src/c_api.cpp
- src/io/bin.cpp
- src/io/dataset.cpp
- src/io/dataset_loader.cpp
- src/io/dense_bin.hpp
- src/io/dense_nbits_bin.hpp
- src/io/sparse_bin.hpp
- src/treelearner/data_parallel_tree_learner.cpp
- src/treelearner/feature_histogram.hpp
- src/treelearner/voting_parallel_tree_learner.cpp
Before this PR, LightGBM uses Bin_of_value_0 to determine whether a feature is sparse or not.
This PR will use the most frequent bin instead, which will be more efficient. 
todo:
> support most frequent bin

- python-package/lightgbm/basic.py
- tests/python_package_test/test_basic.py
- tests/python_package_test/test_engine.py
- transfer `test_trees_to_dataframe` test from `test_basic` to `test_engine` with `skipIf` guard as we use `lgb.train()` there;
- add test for the edge case described in https://github.com/microsoft/LightGBM/pull/2592#discussion_r364435337;
- it turned out that dictionary keys are `list` in Python 2, so it's needed to convert them into a `set`
> [python] fix trees_to_dataframe and enhance test

- .ci/test.sh
- python-package/README.rst
According to this article, it seems that Apple officially supports last 3 versions.
https://www.howtogeek.com/350901/which-releases-of-macos-are-supported-with-security-updates/
I think we can do the same and avoid super huge filename which can cause errors in some file systems.
> [ci] indicate support only for the last 3 macOS versions in wheel name

- R-package/R/lgb.cv.R
- R-package/tests/testthat/test_learning_to_rank.R
> [R-package] fixed sorting issues in lgb.cv() when using a model with observation weights (fixes #2572)

- R-package/R/lgb.plot.importance.R
- R-package/man/lgb.plot.importance.Rd
- R-package/tests/testthat/test_lgb.plot.importance.R
`lgb.plot.importance()` in the R package is currently untested. In this PR, I propose a basic test that will cover all of the code in that function and at least help us catch some types of issues in CI.
This PR increases the R package's test coverage from `71.29%` to  `72.29%`.
I also clarified the documentation on the `cex` parameter so that it is easier for users  to identify valid values to pass.
> [R-package] added tests on lgb.plot.importance and clarified documentation

- R-package/tests/testthat/test_dataset.R
Current, `Dataset$setinfo()` has the behavior "if you pass in something for  'group', convert it to integer before storing it". That behavior is not currently tested. This PR adds a test for it.
> [R-package] added test that Dataset$setinfo() converts 'group' input to integer

- R-package/R/lgb.Booster.R
- R-package/man/lgb.get.eval.result.Rd
- R-package/tests/testthat/test_lgb.Booster.R
In this PR, I propose some more user-friendly documentation and error messages for `lgb.get.eval_result()`. I think it would be helpful to be more explicit about how someone can find valid values of `data_name` and `eval_name`.
I've also added tests on the validations in this function, since currently they are not covered by tests.
> [R-package] clarified error messages and documentation for lgb.get.eval.result()

- R-package/R/callback.R
- R-package/R/lgb.Booster.R
- R-package/R/lgb.Dataset.R
- R-package/R/lgb.cv.R
- R-package/R/lgb.importance.R
- R-package/R/lgb.train.R
- R-package/R/lightgbm.R
- R-package/man/lgb.cv.Rd
- R-package/man/lgb.train.Rd
- R-package/man/lgb_shared_params.Rd
- R-package/man/lightgbm.Rd
- R-package/tests/testthat/test_basic.R
- R-package/tests/testthat/test_dataset.R
- R-package/tests/testthat/test_utils.R
While working through the R package, I noticed several places where we have some validation of inputs to function calls below other running code. For example, right now if you pass something like a `data.frame` to `data` in `lgb.cv()` without including `labels`, you won't find out that you have a malformed training dataset  until after a lot of other steps have run, including initializing a `Predictor`.
In this PR,  I propose a few changes throughout  the package which move input validation up toward the beginning of functions, so that users are alerted sooner when something is wrong. I've also added unit tests on these checks  to be sure they're behaving correctly.
> [R-package] moved parameter validations up earlier in function calls

- R-package/tests/testthat/test_basic.R
- R-package/tests/testthat/test_learning_to_rank.R
This PR adds tests on the R package for #2669
> [R-package] Added tests on use of force_col_wise and force_row_wise in lgb.train()

- docs/conf.py
Also, refer to https://github.com/microsoft/LightGBM/pull/2688#issuecomment-574174971.
Versions were taken from an accidental successful build: https://readthedocs.org/api/v2/build/10331271.txt.
> [docs] fix RTD builds due to conda's problems

- windows/LightGBM.vcxproj
For the reason of removing AVX2 refer to https://github.com/microsoft/LightGBM/pull/2699#issuecomment-581091428.
Reset `PlatformToolset` values back to allow compilation with old versions of MSBuild.
Current behavior after #2699 at Appveyor (`image: Visual Studio 2015`):
```
INFO:LightGBM:Starting to compile the library.
INFO:LightGBM:Starting to compile with MSBuild from existing solution file.
WARNING:LightGBM:Compilation with MSBuild from existing solution file failed.
INFO:LightGBM:Starting to compile with Visual Studio 16 2019.
INFO:LightGBM:Starting to compile with Visual Studio 15 2017.
INFO:LightGBM:Starting to compile with Visual Studio 14 2015.
running build
running build_py
creating build
```
Newer versions should automatically update that values, or we have guide how to change …
> removed AVX2 from VS config and reset PlatformToolset values back

- tests/python_package_test/test_engine.py
- tests/python_package_test/test_sklearn.py
I have no idea how `pd.np.random` occurred there 😃 
Fix warning:
```
/Users/travis/build/microsoft/LightGBM/tests/python_package_test/test_engine.py:717: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
"E": pd.Categorical(pd.np.random.permutation(['z', 'y'] * 30),
```
> [python][tests] fixed typo

- python-package/lightgbm/sklearn.py
add property: `feature_name_` in lgb sklearn api, just like Catboost
It allows that the feature name could be retrieved with `self.feature_name_` in sklearn wrapper of lgb, which will be more convenient without duplicated invoking `self._Booster.feature_name()`.
> [python] add property: feature_name_ in lgb sklearn api

- .appveyor.yml
Change Python version for Appveyor to avoid conda packaging errors described in https://github.com/microsoft/LightGBM/pull/2747#issuecomment-583685751 and make `master` branch builds green.
BTW, this is a part of #2713.
> [ci] avoid Appveyor failures

- CMakeLists.txt
- R-package/tests/testthat/test_basic.R
- docs/Parameters.rst
- include/LightGBM/bin.h
- include/LightGBM/config.h
- include/LightGBM/dataset.h
- include/LightGBM/feature_group.h
- include/LightGBM/tree.h
- include/LightGBM/utils/common.h
- src/boosting/gbdt.cpp
- src/boosting/goss.hpp
- src/io/bin.cpp
- src/io/dataset.cpp
- src/io/dense_bin.hpp
- src/io/dense_nbits_bin.hpp
- src/io/metadata.cpp
- src/io/multi_val_dense_bin.hpp
- src/io/multi_val_sparse_bin.hpp
- src/io/sparse_bin.hpp
- src/network/linkers.h
- src/treelearner/data_parallel_tree_learner.cpp
- src/treelearner/data_partition.hpp
- src/treelearner/feature_histogram.hpp
- src/treelearner/gpu_tree_learner.cpp
- src/treelearner/serial_tree_learner.cpp
- src/treelearner/serial_tree_learner.h
- src/treelearner/voting_parallel_tree_learner.cpp
Refer to https://github.com/microsoft/LightGBM/pull/2699#issuecomment-580747526 and #1990.
> various minor style, docs and cpplint improvements

- include/LightGBM/feature_group.h
- src/io/dataset.cpp
> fix subset bug

- R-package/tests/testthat/test_learning_to_rank.R
- docs/Parameters.rst
- include/LightGBM/config.h
For Python we use `verbose_eval` and for R - `eval_freq`.
> [docs] fixed metric_freq param description

- docker/README.md
- docker/dockerfile-r
While working on #2715 , I found myself wanting a way to test multiple R versions locally. This PR changes the R Dockerfile to make it easy to switch R versions. I had to add an `apt-get install cmake` since it seems  `cmake` is not included in older `rocker/verse`  images.
I've tested and confirmed this works as expected. You can test with:
```shell
docker build \
-t lightgbm-r-35 \
-f dockerfile-r \
--build-arg R_VERSION=3.5 \
.
docker run -it lightgbm-r-35 /bin/bash
R --version
```
> [R-package] [docker] Added ability to build LightGBM in an R container with different R versions

- R-package/R/lgb.Booster.R
- R-package/tests/testthat/test_basic.R
- include/LightGBM/lightgbm_R.h
@JoanFM thanks for contributing #2737 ! Unfortunately, there were some issues in the R side. This PR attempts to address them:
* removes trailing  `_` from method names
* fixes bug where `lower_bound()` method was storing its return value in variable `upper_bound`
* adds unit tests to ensure the implementation is working
* added new functions to `lightgbm_R.h` (without that, `LGBM_BoosterGetUpperBoundValue_R` and  `LGBM_BoosterGetLowerBoundValue_R` are not callable from R)
I still need some help though @guolinke @JoanFM @StrikerRUS .... I am not getting the answers  I'd expect. For example, I would expect lower bound to be 0 and upper bound to be 1  for binary classification, but running this:
```r
train …
```
> [R-package] Fixed R implementation of upper_bound() and lower_bound() for lgb.Booster

- src/c_api.cpp
This fixes the issue https://github.com/microsoft/LightGBM/issues/2798.
As stated in that issue, this should fix the bug in case the parameters change, and improve performance when they don't.
Please give me feedback if I'm doing anything in a less than desirable way.
> Fix SingleRowPredictor::IsPredictorEqual comparison (invert)

- tests/python_package_test/test_engine.py
- tests/python_package_test/test_sklearn.py
```
The pandas.SparseArray class is deprecated and will be removed from pandas in a future version. Use pandas.arrays.SparseArray instead.
```
> [tests][python] fixed pandas deprecation warning in tests

- .ci/setup.sh
- .vsts-ci.yml
- python-package/README.rst
Prepare for
```
##[warning]This pipeline uses a Microsoft-hosted agent image that will be removed on March 23, 2020 (MacOS-10.13). You must make changes to your pipeline before that date, or else your pipeline will fail. Learn more (https://aka.ms/removing-older-images-hosted-pools).
```
> [ci] bump Azure image versions

- CMakeLists.txt
- windows/LightGBM.vcxproj
It seems LTCG will slow down the compile speed, while it does not improve the performance.
> No LinkTimeCodeGeneration in VS

- docs/FAQ.rst
- docs/Parameters.rst
- include/LightGBM/config.h
- include/LightGBM/utils/threading.h
- src/boosting/gbdt.cpp
- src/boosting/gbdt.h
- src/boosting/goss.hpp
- src/treelearner/data_partition.hpp
The bagging results should be identical whatever num_threads is.
> decouple bagging with num_threads

- docs/Advanced-Topics.rst
- docs/Parameters.rst
- include/LightGBM/config.h
- src/io/bin.cpp
- src/objective/rank_objective.hpp
> fixed cpplint issues and updated docs

- src/io/bin.cpp
- tests/python_package_test/test_engine.py
> avoid most_freq_bin to be 0 in categorical features

- include/LightGBM/tree_learner.h
- src/boosting/gbdt.h
- src/io/dataset_loader.cpp
- src/treelearner/gpu_tree_learner.h
- src/treelearner/serial_tree_learner.h
Refer to #1990.
Fix error
```
Do not use namespace using-directives.  Use using-declarations instead.  [build/namespaces] [5]
```
I don't know how to fix 2 remaining errors here:
https://github.com/microsoft/LightGBM/blob/e502ed01f67c878f2a24b6fdf6bc3958dd62e939/src/c_api.cpp#L546
https://github.com/microsoft/LightGBM/blob/e502ed01f67c878f2a24b6fdf6bc3958dd62e939/src/lightgbm_R.cpp#L36
> fixed cpplint error about namespace using-directives

- include/LightGBM/dataset.h
- src/io/dataset.cpp
- src/treelearner/data_parallel_tree_learner.cpp
- src/treelearner/serial_tree_learner.cpp
- src/treelearner/voting_parallel_tree_learner.cpp
getting `OMP_NUM_THREADS` in each function seems slightly increase the training cost.
This PR will cache and check it only before the training of one tree.
> reduce the overhead of OMP_NUM_THREADS in training

- R-package/tests/testthat/test_basic.R
#2831 noted a bug that could cause errors training with sparse features (features with some missing values). That issue has been closed and the bug fixed. In this PR, I propose adding a test in the R package to prevent us from re-introducing that bug.
Thanks to @rgranvil for the clean reproducible example. I just turned that example into a test.
> [R-package] added test on training with sparse features

- .ci/setup.sh
- .ci/test_r_package.sh
Fix current `master` fails.
Have no idea why it started to fail:
```
* installing *source* package ‘rlang’ ...
** package ‘rlang’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I./lib/  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c capture.c -o capture.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I./lib/  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c export.c -o export.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I./lib/  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC …
```
> [ci] fix R tests for macOS on Azure Pipelines

- include/LightGBM/R_object_helper.h
- include/LightGBM/lightgbm_R.h
- src/lightgbm_R.cpp
In this PR, I propose removing some unused includes from `R_object_helper.h`, `lightgbm_R.cpp`, and `R_object_helper.h`.
> [R-package] removed unused imports from R-specific lib_lightgbm components

- R-package/tests/testthat/test_basic.R
We currently don't have unit tests on the R package that check that early_stopping is working  correctly. This is an important area to cover, since it involves some non-standard environment editing with `<<-` and since it requires context switching between 0-based indexing (from `lib_lightgbm`) and 1-base indexing (the R code).
I also want to be sure we have these tests before I start on #2368
> [R-package] [ci] added tests on early_stopping

- R-package/README.md
- docs/FAQ.rst
Per conversationi n #2715 , this PR adds documentation on the need to upgrade `data.table`  if you are using `lgb.dl()` to install the R package.
> [R-package] [docs] Added documentation on lgb.dl() and data.table version (fixes #2715)

- include/LightGBM/tree.h
- src/io/file_io.cpp
This PR eliminates 5 of the 49 remaining `cpplint` issues, noted in #1990 --> https://github.com/microsoft/LightGBM/issues/1990#issuecomment-594687740
```
src/io/file_io.cpp:173:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
src/io/file_io.cpp:186:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
src/io/file_io.cpp:197:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
src/io/file_io.cpp:197:  If/else bodies with multiple statements require braces  [readability/braces] [4]
Done processing src/io/file_io.cpp
...
include/LightGBM/tree.h:154:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
```
4 of the 5 relate to handling of …
> [ci] fixed cpplint warnings about braces

- .github/no-response.yml
- .github/release-drafter.yml
- .vsts-ci.yml
Release Drafter: https://probot.github.io/apps/release-drafter/
Work In Progress: https://probot.github.io/apps/wip/
Reminders: https://probot.github.io/apps/reminders/
No Response: https://probot.github.io/apps/no-response/
> add more bots 

- include/LightGBM/R_object_helper.h
- include/LightGBM/lightgbm_R.h
- src/lightgbm_R.cpp
This is a **style-only PR**. As I've been working on  #629 , I see a few opportunities to make the current R-specific parts of `lib_lightgbm` a bit easier to read and edit. The diff looks a bit weird here on GitHub, but to be clear I did not change any of what the code in these files does. In this PR, I'm just proposing some indentation changes, for example taking definitions like this:
```
LIGHTGBM_C_EXPORT LGBM_SE LGBM_DatasetCreateFromFile_R(LGBM_SE filename,
LGBM_SE parameters,
LGBM_SE reference,
LGBM_SE out,
LGBM_SE call_state);
```
and turning them into this
```
LIGHTGBM_C_EXPORT LGBM_SE LGBM_DatasetCreateFromFile_R(
LGBM_SE filename,
LGBM_SE parameters,
LGBM_SE reference,
LGBM_SE out,
LGBM_SE call_state
);
```
I also changed the language in the comment at the top of …
> [R-package] cleaned up formatting in R C/C++ files

- include/LightGBM/bin.h
- include/LightGBM/c_api.h
- include/LightGBM/dataset.h
- include/LightGBM/meta.h
- include/LightGBM/utils/openmp_wrapper.h
- src/c_api.cpp
- src/treelearner/feature_histogram.hpp
- src/treelearner/gpu_tree_learner.h
> fixed cpplint errors and disable warning only for VS

- R-package/tests/testthat/test_basic.R
This PR removes an object, `windows_flag`, that is created but never used in tests on `lgb.train()` and `lightgbm()`.
> [R-package] removed unnecessary flag in tests

- R-package/src/install.libs.R
Another piece of adding Windows CI for the R package (#2335) and, as a result, #629
This PR fixes this Windows-specific NOTE that shows up in `R CMD check --as-cran`:
```
* checking line endings in C/C++/Fortran sources/headers ... NOTE
Found the following sources/headers with CR or CRLF line endings:
src/build/CMakeFiles/3.16.5/CompilerIdC/CMakeCCompilerId.c
src/build/CMakeFiles/3.16.5/CompilerIdCXX/CMakeCXXCompilerId.cpp
src/build/CMakeFiles/FindOpenMP/OpenMPCheckVersion.c
src/build/CMakeFiles/FindOpenMP/OpenMPCheckVersion.cpp
src/build/CMakeFiles/FindOpenMP/OpenMPTryFlag.c
src/build/CMakeFiles/FindOpenMP/OpenMPTryFlag.cpp
Some Unix compilers require LF line endings.
* checking line endings in Makefiles ... OK
```
R does have a method for cleaning up intermediate files, with a `cleanup` …
> [R-package] added command to remove build/ dir in install.libs.R

- README.md
Hi!
Optuna is a new hyperparameter optimization library, and we've written an [tuner module for LightGBM](https://medium.com/optuna/lightgbm-tuner-new-optuna-integration-for-hyperparameter-optimization-8b7095e99258) to make it easy to use Optuna to search for good hyperparameter settings and prune unpromising trials. We're looking for ways to let users of LightGBM know this is available and thought a badge to show Optuna integration is available would be helpful along with a link to Optuna in the further readings section.
If there are other ways you would recommend reaching out to LightGBM users to let them know about Optuna, please let us know.
Thanks!
> [docs] Add LightGBM Tuner by Optuna links to README.md

- .ci/lint_r_code.R
- R-package/R/callback.R
- R-package/R/lgb.Dataset.R
- R-package/R/lgb.cv.R
- R-package/R/lgb.plot.interpretation.R
- R-package/R/lgb.train.R
- R-package/R/utils.R
- R-package/demo/basic_walkthrough.R
- R-package/demo/boost_from_prediction.R
- R-package/demo/cross_validation.R
- R-package/demo/early_stopping.R
- R-package/demo/multiclass.R
- R-package/demo/multiclass_custom_objective.R
- R-package/tests/testthat/test_dataset.R
- R-package/tests/testthat/test_lgb.interprete.R
- R-package/tests/testthat/test_parameters.R
This PR adds a few more R linters:
* `absolute_path_linter`: prevent paths like `~/repos/`
* `nonportable_path_linter`: prevent paths like `C:\Users\` which only work on certain operating systems
* `undesirable_function_linter`: prevent the use of some functions which could cause issues, specifically:
- `dyn.load()` / `dyn.unload()`: direct calls to use symbols in `.dll` / `.so` files. My expectation is that someone using this in a PR either doesn't understand how to write R packages that call C++ code or is introducing something that will be very difficult to maintain.
- `help()`: call up help documentation. This should only be used interactively, not in code checked into this repository.
- `install.packages()`: install new libraries, e.g. from CRAN. This should only be used …
> [R-package] [ci] added more linters

- python-package/lightgbm/sklearn.py
- tests/python_package_test/test_sklearn.py
I am using LightGBM with its scikit-learn API in a wrapper model called [Boruta](https://github.com/scikit-learn-contrib/boruta_py).
Boruta is using multiple cloned LGBM models in sequence.
In every iteration, it is cloning and setting parameters, including the random_state used in random number generation.
LGBM is not able to handle a RandomState object from Numpys random module which is the standard in scikit-learn models.
Because of that, many wrappers just pass down the RandomState in their inner models.
This was already discussed in #730.
LGBM is using an integer to seed its number generators and expects an integer, which makes it unusable in this context.
In this PR I added a random_state property with a setter method to handle RandomState objects.
If an RS object is passed, It …
> [python] handle RandomState object in Scikit-learn Api

- include/LightGBM/c_api.h
- python-package/lightgbm/basic.py
- src/c_api.cpp
- src/lightgbm_R.cpp
- swig/StringArray.hpp
- swig/StringArray.i
- swig/StringArray_API_extensions.i
- swig/lightgbmlib.i
The main reason to add this pull request is outlined in https://github.com/microsoft/LightGBM/issues/2814.
After discussing with @imatiach-msft and the devs at SWIG (https://github.com/swig/swig/issues/1740), 
the devised solution aiming at simplicity and correctness was to add a StringArray to wrap any char** parameters so memory can be managed.
This relies on the already existing `various.i` extensions to return a String[] through a single call.
@imatiach-msft also requested that LGBM_BoosterGetEvalNamesSWIG be refactored to use the same type of API. This meant changing that method signature, and I did so by following the LGBM_* signature of returning the error code as an int 0/-1.
I'm very interested in getting feedback from the team, specially @imatiach-msft with whom I've been …
> Fix SWIG methods that return char**

- R-package/R/lightgbm.R
This PR fixes a new `R CMD CHECK` note introduced in #2803 . See https://github.com/microsoft/LightGBM/pull/2803#issuecomment-601840250 for background.
The note is:
```
* checking R code for possible problems ... NOTE
multiple.tree.plot.interpretation: no visible binding for global
variable ‘bar_color’
Undefined global functions or variables:
bar_color
```
> [R-package] fixed NOTE about unrecognized global variable

- src/c_api.cpp
- src/lightgbm_R.cpp
In this PR, I tried to address the two instances of this `cpplint` error (from #1990):
> Do not use namespace using-directives.  Use using-declarations instead.  [build/namespaces] [5]
I did some research tonight, and found some good resources that explain this. According to [this blog post](https://abseil.io/tips/153):
> The vast majority of C++ users think that the using-directive is injecting names into the scope where it’s declared.... [for example] the scope of [a] function. In reality, the names are injected into the nearest common ancestor of the target namespace ...and the usage namespace ... [which could easily be] the global namespace!
So a directive like `using namespace LightGBM` is risky because it means all the names from the namespace  `LightGBM` will be defined in some …
> [ci] fixed cpplint errors about namespace using-directives

- R-package/tests/testthat/test_lgb.plot.importance.R
This PR adds a unit test to cover a case with `lgb.plot.importance()` that was previously not covered.
This increases the R package's test coverage from 77.78% to 77.83%
> [R-package] added test on uncovered line of lgb.plot.importance()

- R-package/R/utils.R
- R-package/tests/testthat/test_basic.R
- R-package/tests/testthat/test_utils.R
See the linked issue for details. Training with multiple evaluation metrics is currently broken in the R package, for all cases where the metrics have a different number of characters (e.g. `c("auc", "binary_logloss")`.
We may not have caught this until now because the bug doesn't show up if the metrics have the same number of characters, e.g. `c("l1", "l2")` or `c("rmse", "mape")`.
I've added tests in this PR which should prevent us from re-introducing this bug.
I also added explicit uses of `return()` in `lgb.params2str()` just to make that function a bit more explicit.
> [R-package] fixed handling of multiple evaluation metrics (fixes #2913)

- R-package/R/lightgbm.R
- R-package/tests/testthat/test_basic.R
See #2915 for details. Getting evaluation on validation sets with the `lightgbm()` function is currently broken. In this PR, I propose a fix and a test to prevent us from re-introducing the bug.
> [R-package] fixed evaluation on valids in lightgbm() (fixes #2915)

- .gitignore
- R-package/src/install.libs.R
- R-package/tests/testthat/test_lgb.Booster.R
I started working on #2335 tonight, specifically adding CI for Windows.
In this PR, I'd like to propose a few small fixes to start improving support on Windows.
1. Added architecture-specific source directories to `.gitignore`. These come from multi-architecture R package builds on Windows, and shouldn't be checked into source control
2. Minor readability cleanup in Windows section of `install.libs.R`, added some logs and clarified existing logs
3. Fixed one unit test that fails on Windows because of different default quoting between Windows and other operating system
I tested these changes locally on Windows 10, using Visual Studio 16 2019, with `Rscript build_r.R`
> [R-package] fixed some minor issues with testing on Windows

- include/LightGBM/utils/common.h
This PR fixes two `cpplint` warnings (#1990). It replaces uses of `sprintf` with `snprintf`. `sprintf` is dangerous because it doesn't know about the size of the buffer it's writing to.
Since we already had the buffer size easily available in the places that call the relevant functions, and since we were already passing it in, I _think_ that this was an easy change that doesn't break any APIs. However I'm not that good at C++ so very possible I've misunderstood something.
<details><summary>`cpplint` errors after this PR: 42 (click me)</summary>
```
Done processing src/io/dense_bin.hpp
Done processing src/main.cpp
Done processing src/application/application.cpp
Done processing src/metric/map_metric.hpp
Done processing include/LightGBM/feature_group.h
Done processing …
```
> changed sprintf uses to snprintf

- docs/Parameters.rst
- include/LightGBM/config.h
- include/LightGBM/tree.h
- src/io/config.cpp
- src/io/config_auto.cpp
- src/io/tree.cpp
- src/treelearner/leaf_splits.hpp
- src/treelearner/monotone_constraints.hpp
- src/treelearner/serial_tree_learner.cpp
- src/treelearner/serial_tree_learner.h
- tests/python_package_test/test_engine.py
@aldanor @redditur
@guolinke @chivee @jameslamb @huanzhang12 @Laurae2 @StrikerRUS
You were all reviewers of the PRs #2305 and #2717. #2305 was judged to be not merge-able because it is too big. Therefore, in my ultimate comment (https://github.com/microsoft/LightGBM/pull/2305#issuecomment-574560469) I said I would split into smaller PRs easier to merge. This is the second PR in relation with #2305; the first one being #2717 and having been merged.
The goal of this PR is to introduce a new constraining method. This is the "Fast" method from #2305. I introduce a new parameter in the config called "monotone_constraints_method". When this is set to "basic", then the original constraining method is used. When it is set to "intermediate", the new constraining method of this PR is used. (And …
> Improving monotone constraints ("Fast" method; linked to #2305, #2717) 

- .ci/test_r_package.sh
Currently in CI, we run `R CMD check` on the R package and fail builds if ERRORs or WARNINGs  are encountered. As we get closer to CRAN (#629), I'd like to start limiting the NOTEs being generated. Currently Linux and macOS builds have 3 NOTEs. One is being addressed in #2911 , the other two are not problematic.
Following @StrikerRUS 's suggestion in https://github.com/microsoft/LightGBM/pull/2911#issuecomment-602979163, this PR proposing putting an upper limit on the number of NOTEs.
This PR has it set to 3, and mainly introduces _how we'll enforce this_. I think we should merge this, then change it from 3 to 2 on #2911 . I think it's better for this to be a separate PR so that other changes in the repo don't introduce new notes (like I accidentally did in #2803 and then had to fix in …
> [R-package] [ci] added check on number of R CMD CHECK notes

- .ci/test.sh
- .ci/test_r_package.sh
This fixes the issue we are seeing in Mac builds  across all PRs right now.
@StrikerRUS I know you tried a similar change in https://github.com/microsoft/LightGBM/pull/2949#issuecomment-605034139 and said it didn't work. I don't see anything obviously wrong with your approach, but I do know the change I'm suggesting in this PR works on my Mac.
Changes:
1. Change from RStudio CRAN mirror to  https://cloud.r-project.org/
2. Make that explicit, instead of relying on `.Rprofile`
Since  we only have one `install.packages()` call, I don't think we need to deal with the complexity of when and if the `.Rprofile` file gets sourced.
on my Mac: 
My best  guess about what happened is:
1. R binaries for macOS became temporarily unavailable on CRAN
2. this broke whatever process mirrors them from …
> [ci] changed CRAN mirror to fix failing installs

- src/boosting/gbdt_model_text.cpp
Fixed #2933.
The same we have for `split_gain` and `threshold`:
https://github.com/microsoft/LightGBM/blob/a8c1e0a11a5cbfac62fb57d16901fea16de95412/src/io/tree.cpp#L294
https://github.com/microsoft/LightGBM/blob/a8c1e0a11a5cbfac62fb57d16901fea16de95412/src/io/tree.cpp#L310
> fix inf in json model dump

- .ci/test_r_package.sh
- build_r.R
Right now, `Rscript build_r.R` will build a source distribution of the R package and install it. In this PR, I propose an addition to the script to tell `build_r.R` to just build the package tarball but not install it.
This should allow us to cut a few minutes out of the `r-package` tasks in CI!
Right now we are doing this:
```
Rscript build_r.R
R CMD check lightgbm_*.tar.gz
```
That means we're building `lib_lightgbm` twice, without getting any extra testing benefit. In fact, I think that the scenario of checking a source tarball on a system where `lightgbm` hasn't been installed already is an even better test of the experience for our users!
Note that this PR won't change the existing behavior for anyone using  `build_r.R`. The default will still be to both build and install.
> [R-package] [ci] Add option to skip installation in build_r.R

- swig/StringArray_API_extensions.i
fix seg fault in LGBM_BoosterGetEvalNamesSWIG
> [SWIG][mmlspark] fix seg fault in LGBM_BoosterGetEvalNamesSWIG

- .appveyor.yml
- .ci/test_windows.ps1
- .vsts-ci.yml
Per discussion from https://github.com/microsoft/LightGBM/pull/2936#issuecomment-606720235. Right now some CI logic is duplicated in `.vsts-ci.yml` and `.appveyor.yml`. Similar to how we've centralized that logic for mac and linux builds in `.ci/` scripts, in this PR I propose cutting out that duplication and centralizing the logic in `.ci/tetst_windows.ps1`.
This should make it a little easier to make changes (such as changing our pegged version of scikit-learn whenever #2949 is merged) and should make #2936 easier to review.
> [ci] reduce duplication in Python Windows CI

- include/LightGBM/tree.h
- src/io/tree.cpp
* Clean up comparisons of missing_type using the enum name instead of hard-coded constants 
This does not incur in any overhead and eases code comprehension.
> Cleanup MissingType enum constants

- src/io/json11.cpp
It removes the difference between R-specific library and ordinary one.
Refer to #2837.
> replace built-in assert with own CHECK macro

- .travis.yml
- .vsts-ci.yml
We currently test the R package against R 3.6.1,  a version from July 2019. In this PR, I'd like to propose we upgrade to R 3.6.3, the most recent version of the 3.x series.
I had this in #2936 but I think that PR will still take a few more rounds of reviews.
([list of R versions and release dates](https://cran.r-project.org/bin/windows/base/old/))
> [ci] upgrade to R 3.6.3 in CI

- include/LightGBM/utils/openmp_wrapper.h
- src/io/tree.cpp
- src/lightgbm_R.cpp
> fixed cpplint errors

- .ci/test_r_package.sh
- docs/requirements_base.txt
Fixed #2974.
While we are waiting new breathe release which will be compatible with sphinx 3, let's downgrade sphinx version to fix our CI.
Refer to https://github.com/michaeljones/breathe/pull/491.
> [ci][docs] downdrage sphinx and fix LaTeX error in R-package tests

- docs/GPU-Targets.rst
I started to see errors 
```
URL        `https://rocm.github.io/'
Name       `ROCm'
Parent URL file:///home/travis/build/microsoft/LightGBM/docs/_build/html/GPU-Targets.html, line 217, col 146
Real URL   https://rocm.github.io/
Check time 0.094 seconds
Size       71B
Result     Error: 503 Backend is unhealthy
```
I hope without redirect it will be "healthier" 🙂 .
> [docs] update URL in docs

- docs/requirements.txt
Temporary fix error in `master`:
```
ERROR: breathe 4.15.0 has requirement Sphinx>=3.0, but you'll have sphinx 2.4.4 which is incompatible.
```
Continuation of #2974.
New `breathe` version is still incompatible with Sphinx 3.
Refer to https://github.com/michaeljones/breathe/pull/491#issuecomment-610581862 and https://github.com/sphinx-doc/sphinx/issues/7423#issuecomment-610668512.
> [ci][docs] downgrade breathe

- R-package/R/lgb.Booster.R
- R-package/README.md
- R-package/tests/testthat/test_lgb.Booster.R
This PR adds unit tests on the code in the R package that handles saving a Booster to file or string and creating a new Booster from a file or string. This brings the unit test coverage on the package from 78.20% to 79.71%.
Importantly, it covers calls from R to C++ functions `LGBM_BoosterSaveModelToString_R`, `LGBM_BoosterCreateFromModelfile_R`, and `LGBM_BoosterLoadModelFromString_R`  which were previously not covered (see #2944 for why this is valuable).
This PR does not change the behavior of `lgb.load()` at all, but it does reorganize the internals to cut out some redundant checks and make the logic a little easier to follow.
This PR also removes an unnecessary step from the docs on generating test coverage in `R-package/README.md`. Removing the `build/` directory is no longer …
> [R-package] Added unit tests on creating Booster from file or string

- .appveyor.yml
- .ci/test.sh
- .vsts-ci.yml
- docker/dockerfile-python
- docker/gpu/dockerfile.gpu
- docs/GPU-Tutorial.rst
- docs/Python-API.rst
- docs/Python-Intro.rst
- examples/python-guide/README.md
- python-package/lightgbm/compat.py
- python-package/lightgbm/sklearn.py
- python-package/setup.py
- tests/python_package_test/test_sklearn.py
Skip failing `check_no_attributes_set_in_init` test, refer to  https://github.com/microsoft/LightGBM/issues/2628#issuecomment-604519043.
Minor refactoring to pass new `check_sample_weights_not_an_array` test.
Reverted #2637. Fixed #2628. Closed #2946.
> [python] Re-enable scikit-learn 0.22+ support

- .ci/test.sh
- .ci/test_r_package.sh
> [ci] fixed r-lintr version constraint

- include/LightGBM/R_object_helper.h
I noticed this constant `TYPE_BITS` defined in `R_object_helper.h`. It isn't used anywhere (`git grep TYPE_BITS`) so I think we can remove it.
> [R-package] Removed unused constant in R_object_helper.h

- R-package/DESCRIPTION
I've been reading the `DESCRIPTION` section of [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-DESCRIPTION-file), and found a few other fields we should be setting in our package metadata. I think this will help with #629 as well.
* changed tabs to spaces in author section of the DESCRIPTION
* fixed a minor typo in description of the package
* added `NeedsCompilation: yes`
> The ‘NeedsCompilation’ field should be set to "yes" if the package contains code which to be compiled, otherwise "no" (when the package could be installed from source on any platform without additional tools). This is used by install.packages(type = "both") in R >= 2.15.2 on platforms where binary packages are the norm: it is normally set by R CMD build or the repository …
> [R-package] Updated package metadata in DESCRIPTION

- swig/lightgbmlib.i
resolves issue https://github.com/microsoft/LightGBM/issues/2615 by introducing long versions of SWIG-generated array
ping @chris-smith-zocdoc @guolinke 
validated jar in mmlspark
> [mmlspark] allow allocating more than int max array

- .gitignore
- R-package/DESCRIPTION
- R-package/R/lgb.Booster.R
- R-package/R/lgb.Dataset.R
- R-package/R/lgb.plot.interpretation.R
- R-package/R/lgb.prepare_rules.R
- R-package/R/saveRDS.lgb.Booster.R
- R-package/man/agaricus.test.Rd
- R-package/man/agaricus.train.Rd
- R-package/man/bank.Rd
- R-package/man/lgb.Dataset.set.categorical.Rd
- R-package/man/lgb.plot.interpretation.Rd
- R-package/man/lgb.prepare_rules.Rd
- R-package/man/lgb.save.Rd
- R-package/man/saveRDS.lgb.Booster.Rd
- docs/FAQ.rst
- docs/conf.py
**NOTE:* Moving #2999 over here (based on a LightGBM branch) so we can test readthedocs builds. See https://github.com/microsoft/LightGBM/pull/2999#issuecomment-614648492
--------
See comments from @StrikerRUS 
* https://github.com/microsoft/LightGBM/pull/2989#issuecomment-614374151
* https://github.com/microsoft/LightGBM/pull/2989#issuecomment-614375963
A few of the R examples are broken right now. These weren't caught by tests because one is only a warning, one is a plot that is generated successfully but is incorrect, and one is an issue specific to our readthedocs builds.
I think the issue for `lgb.cv()` is #2715. In that issue we found that `data.table 1.11.4` and R 3.6.0 lead to a data.table error ending in `column or argument 2 is NULL`. I think this can be fixed by upgrading to …
> [R-package] fix R examples and lgb.plot.interpretation()

- .readthedocs.yml
- docs/conf.py
- docs/requirements_rtd.txt
Upstream bugs... again.
Continuation of #3013.
Default installed Sphinx version at RTD is `1.8.5`.
Refer to https://github.com/michaeljones/breathe/issues/495#issuecomment-610710637 and https://github.com/pypa/pip/issues/8001#issuecomment-611785558.
In this workaround separate config for RTD duplicates code but allows to not touch LightGBM's users - they are free to continue using old Sphinx in their environments.
I hope https://github.com/pypa/pip/issues/8001 will be resolved soon (https://github.com/pypa/pip/issues/988#issuecomment-617142142) and we'll be able to revert this PR.
> [ci][docs] Fix RTD builds

- .ci/test_r_package.sh
No that we use `Rscript build_r.R --skip--install`, the only build of the R package is from `R CMD check`. `R CMD check` suppresses output from the build and writes it to a file. Those logs are useful for us to check for compiler warnings and debug issues.
See https://github.com/microsoft/LightGBM/pull/2936/files#r411607175
> [R-package] [ci] added echoing of R CMD check logs to CI

- R-package/R/utils.R
- R-package/tests/testthat/test_utils.R
Continuing work on #2944, trying to cover all calls from the R package to the C++ side in R unit tests. These tests cover  `LGBM_GetLastError_R`.
Confirmed by running https://github.com/microsoft/LightGBM/blob/master/R-package/README.md#testing.
These changes increase the test coverage of the R package from 79.71% to 80.27%.
> [R-package] Added tests on LGBM_GetLastError_R

- R-package/README.md
As of #2957 , you can use `Rscript build_r.R --skip-install` to build the R package without installing it. Right now the instructions for generating R test coverage doesn't take advantage of that, so you end up compiling `LightGBM` twice. This PR fixes that.
> [R-package] [docs] remove unnecessary build in test coverage

- R-package/tests/testthat/test_lgb.Booster.R
This PR is a part of #2944. Currently, we do not test the call from LightGBM's R package to the C++ function  `LGBM_BoosterRollbackOneIter_R`. This PR proposes such a test.
> [R-package] added tests on LGBM_BoosterRollbackOneIter_R

- R-package/R/callback.R
- R-package/R/lgb.Booster.R
- R-package/R/lgb.cv.R
- R-package/R/lgb.train.R
- R-package/tests/testthat/test_basic.R
I started to pick up #2471 but found that I needed to make enough changes that I thought it made sense to just put them in a new PR and close that one. I also think this makes the review process cleaner, so I'm not technically updating a PR that belongs to @Laurae2 while also acting as a reviewer on my own code.
I tried to address #2295 in this PR. Basically, when early stopping is not used, the best score and best iteration should be determined using the first metric and first validation set given, **excluding the training data**. #2295 suggested that right now, if you pass the training data to `valids` it's possible that `best_iter` and  `best_score` will be based on the training data.
This PR proposes the following improvements:
* exclude training data from consideration for …
> [R-package] fixed best_iter and best_score when training data is passed (fixes #2295, #2525)

- tests/c_api_test/test_.py
- tests/python_package_test/test_engine.py
- tests/python_package_test/test_sklearn.py
Just out of curiosity, I ran this on the codebase tonight:
```shell
flake8 --exclude=E501,W503
```
This PR fixes these warnings from it
```text
./tests/python_package_test/test_engine.py:1860:9: F841 local variable 'iter_min' is assigned to but never used
./tests/python_package_test/test_sklearn.py:304:21: F821 undefined name 'warnings'
./tests/c_api_test/test_.py:4:1: F401 'sys' imported but unused
```
A couple other warnings are generated but I think they should be ignored. Some thing in outt tests look like "local variable never used" but they're things like this where even if we don't test the value, generating acts as a smoke test:
```python
model = lgb.train(default_params, lgb_train, valid_sets=[lgb_val])
```
Here is the full log if you're curious:
<details><summary>flake8 …
> [python][tests] unused and missing imports

- R-package/README.md
Since the method of installing LightGBM for R changed significantly, using [Laurae2/lgbdl](https://github.com/Laurae2/lgbdl) package is now broken.
This PR removes lgbdl temporarily from the documentation until a new working replacement package is made (to avoid confusion for end users who attempt using it and see it does not work).
The replacement package is likely to be named differently as there are currently scripts relying on the package pointing to old commits for compatibility.
@StrikerRUS `doc` is this the right label for this PR?
> [R-package] Remove lgbdl from docs until fix

- src/objective/rank_objective.hpp
- tests/python_package_test/test_sklearn.py
An earlier refactoring led to an error in the loss computation. This change is intended to fix that so the loss is correctly computed following the paper (https://arxiv.org/abs/1911.09798)
> Fix loss computation in rank cross-entropy objective

- R-package/src/cmake/modules/FindLibR.cmake
I think that `conda` installations of R put the core library at `${R_HOME}/lib`. See https://github.com/microsoft/LightGBM/issues/3045#issuecomment-623208825 and the rest of #3045 for details.
@StrikerRUS I created this as a `LightGBM` branch so it can be tested on readthedocs. Could you enable this branch there?
> [R-package] add conda dir for LIBR_CORE_LIBRARY (fixes #3045)

- docs/GPU-Targets.rst
Less redirects - less possibility to disappoint `linkchecker` 🙂 .
> [docs] update ROCm link in docs

- .vsts-ci.yml
I noticed that Linux MPI builds at Azure Pipelines have started to fail (refer for example to #3055). Seems that dropping outdated Python 2.7 version from that build fixes the issue.
On Linux we have tests with Python 2.7 here, so this version is still covered by our CIs.
https://github.com/microsoft/LightGBM/blob/18c706dc840c72341a2a85e05dfb5fad6366902a/.travis.yml#L18
Refer to https://github.com/microsoft/LightGBM/pull/1964#issuecomment-458674944.
> [ci] fix flaky test

- python-package/setup.py
I found that there is one place in the Python package where we're using a tuple instead of a `set`  for an `in` condition.
I'd like to propose we change to a set, like we use everywhere else in the package, since `in` operations are O(1) with sets, faster than the O(n) with tuples.
> [python-package] Use set for OS check

- R-package/tests/testthat/test_lgb.Booster.R
This is the last PR needed for #2944. It adds a test to cover how the R package calls the C++ function `LGBM_BoosterResetTrainingData_R`.
> [R-package] added tests on LGBM_BoosterResetTrainingData_R

- python-package/lightgbm/plotting.py
- src/objective/binary_objective.hpp
> removed deprecated code

- docs/FAQ.rst
This PR documents the solution to the issue found on #3060 (workaround of PR #664).
Users should run `cmake` twice when the compiler is MinGW, because `cmake` has a one time stopper when it detects MinGW.
This one time stopper was removed from `cmake` on the following commit: https://github.com/microsoft/LightGBM/commit/3421bc6ce6f7294e22db7abad48a42e94fcc92cc#diff-473c89bfc9641f554ac12d37ebc3d377R61 (version = ???)
This issue also applies to most of R users who use MinGW as the compiler of choice (default of Rtools, and for those modifying the LightGBM installation script to explicitly compile using MinGW).
> Document cmake+MinGW (fixes #3060)

- R-package/tests/testthat/test_lgb.Booster.R
- docs/FAQ.rst
> The MinGW Makefiles generator no longer issues an error if sh.exe is present in the environment’s PATH.
https://cmake.org/cmake/help/v3.17/release/3.17.html#other-changes
Refer to #3078.
> [docs] document one more workaround for CMake and MinGW build and fix typos

- .github/CODEOWNERS
Noticed in #3076 that not all C++ maintainers were added as reviewers for a change to `CMakeLists.txt`. I think this change will fix that :grinning:
> Update CODEOWNERS rule about CMakeLists.txt

- .appveyor.yml
- .ci/test_r_package_windows.ps1
- .vsts-ci.yml
- R-package/DESCRIPTION
- R-package/src/install.libs.R
- build_r.R
This is another PR that contributes to #2936 , but which I think has standalone value.
Right now on Windows, to figure out which version of Visual Studio is available we try to build `lib_lightgbm` by generating and executing the corresponding `CMake` Makefile for the 3 most recent versions of VS. This is pretty expensive, and means that you have to build `lib_lightgbm` .
I went into this thinking that this is why r-package CI builds on Azure Devops with Visual Studio [take 20 minutes](https://dev.azure.com/JayLamb20/jameslamb-lightgbm/_build/results?buildId=248&view=logs&j=87d556e4-1858-51ea-bb1c-8e61473c09c8)...and it seems like it! I tested merging these changes into #2936 [on my fork](https://github.com/jameslamb/LightGBM/pull/13), and it takes the build time down from 20 minutes to …
> [R-package] speed up installation with Visual Studio

- src/boosting/gbdt.cpp
- src/boosting/gbdt.h
- src/boosting/goss.hpp
> fix goss with constant hessian

- docs/GPU-Windows.rst
The `GPU-Windows` docs currently state that you can install the R package with `devtools::install_github()`. That will not work and hasn't for a long time, so I suggest that we remove that language.
The whitespace changes in this PR were made automatically by my editor. I can revert them if you'd like.
> [R-package] [docs] Removed outdated language about the R package

- R-package/tests/testthat/test_basic.R
This PR fixes two warnings I noticed in the logs for the R unit tests (https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=6053&view=logs&j=9f61088a-36ee-57e4-0947-03329fd6ee90&t=2528b315-ee14-54c7-8330-fcfcaf0cbb8e)
```text
[LightGBM] [Warning] Unknown parameter: labels
[LightGBM] [Warning] Unknown parameter: labels
[LightGBM] [Warning] Unknown parameter: min_hess
[LightGBM] [Warning] Unknown parameter: min_hess
```
> [R-package] fix warnings in tests

- .ci/test_r_package.sh
- .gitignore
- R-package/R/lightgbm.R
- R-package/man/lgb_shared_params.Rd
- R-package/pkgdown/_pkgdown.yml
This PR fixes the warnings from the last outstanding item in this comment: https://github.com/microsoft/LightGBM/issues/1143#issuecomment-526936690
```text
Warning message:
Topics missing from index:
* lgb_shared_params
* lightgbm
```
To confirm, I ran:
```shell
Rscript build_r.R
cd lightgbm_r
Rscript -e "pkgdown::build_site(install = FALSE)"
```
re-using this branch from #3072 since it's already enabled on readthedocs.
> [R-package] [docs] fix warnings in pkgdown site  building

- .appveyor.yml
Currently, we run the same build logic twice on AppVeyor for every commit to `master` or a branch with a PR into `master`.
This slows development because on the free tier of AppVeyor we are limited to one build at a time.
In this PR, I propose that we only build once on PRs and on every commit to `master`. I think this should work per: https://help.appveyor.com/discussions/problems/14586-build-any-pull-requests-against-any-branches.
> [ci] avoid duplicate AppVeyor builds

- R-package/src/cmake/modules/FindLibR.cmake
I've noticed in the logs from running `Rscript build_r.R` that one log message seems misaligned
```text
-- Check for working CXX compiler: /usr/local/clang-7.0.0/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
R version passed into FindLibR.cmake: 3.6.3
-- Found LibR: /usr/lib/R  
-- LIBR_EXECUTABLE: /usr/bin/R
-- LIBR_INCLUDE_DIRS: /usr/share/R/include
-- LIBR_CORE_LIBRARY: /usr/lib/R/lib/libR.so
```
I looked into it tonight, and this is because the `"R version passed into...`"` message produced in `FindLibR.cmake` is not characterized. In other words, it is using `message("R version...")` instead of `message(STATUS "R version...")`.
This PR proposes characterizing …
> [R-package] characterize all cmake messages

- .ci/test_r_package.sh
This PR fixes this error in `r-package` linux CI builds (see [the most recent master build](https://travis-ci.org/github/microsoft/LightGBM/jobs/688107049) for an example)
> W: GPG error: https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/ InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 51716619E084DAB9
E: The repository 'https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/ InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
This isn't breaking our builds right now, but it's a distracting error taking up space in the logs.
Confirmed on [my …
> [ci] fix add-apt-repository warning

- src/objective/rank_objective.hpp
- tests/python_package_test/test_sklearn.py
A summary of the changes in this PR:
1. Return immediately if there are not enough documents in the set
2. Reduce memory footprint by removing one of the vectors ("l2s") created in the loss computation code; instead, reuse the same vector.
> Optimize the computation of the cross-entropy ranking loss

- src/boosting/prediction_early_stop.cpp
See #3067 for details. When building for the R package, `Log::Fatal` calls `Rf_error`:
https://github.com/microsoft/LightGBM/blob/master/include/LightGBM/utils/log.h#L123
That function will result in a fatal error, but not on the C++ side...it tells the calling R process to throw n R error. I think that is why MSVC thinks it's possible for control to reach the end of `PredictionEarlyStopInstance`.
In this PR, I'd like to propose refactoring `PredictionEarlyStopInstance` to make it clearer to compilers that this function's control flow does always end.
We don't have CI for MSVC + R builds yet (it's in progress in #2965 ), but I tested this on my laptop tonight (Windows 10, Visual Studio 16 2019, R 3.6.1, Rtools 3.5). You can see in this log from running `Rscript build_r.R` that the warning …
> fix MSVC warning about control paths (fixes #3067)

- src/boosting/score_updater.hpp
Using '0' results in a very small number in double, so in practice it seems okay, but in theory, the initial scores are wrong if we're not using the external initial scores.
This patch fixes this issue.
> fix a bug when we set the default score

- R-package/R/callback.R
- R-package/R/lgb.Booster.R
- R-package/R/metrics.R
- R-package/tests/testthat/test_basic.R
- R-package/tests/testthat/test_metrics.R
This PR fixes #3099. Several metrics are currently being misclassified for early stopping purposes.
Today, the R package uses a regular expression on metric name to decide if a metric should be maximized or minimized.
That logic says:
> if a metric name starts with `"ndcg"`, `"map"`, or `"auc"`, assume it should be maximized. Otherwise, assume it should be minimized
~The author of #3099 ran into this issue with `mape`, but I believe that several of the [support edmetrics](https://lightgbm.readthedocs.io/en/latest/Parameters.html#metric-parameters) are currently misclassified:~
* ~`lambdarank`~
* ~all `xendcg` aliases and flavors`~
* ~`mean_average_precision` (alias for `map`)~
* `auc_mu`
UPDATE: ^ this comment about all those metrics being misclassified is incorrect, see …
> [R-package] fix issue where early stopping thinks higher MAPE is desirable (fixes #3099)

- src/treelearner/data_parallel_tree_learner.cpp
- src/treelearner/feature_parallel_tree_learner.cpp
- src/treelearner/split_info.hpp
- src/treelearner/voting_parallel_tree_learner.cpp
memory corruption was found using valgrind
see relevant issue for debugging info:
https://github.com/microsoft/LightGBM/issues/2981
> memory corruption fix for distributed data parallel version before SyncUpGlobalBestSplit

- .travis.yml
- .vsts-ci.yml
While using `.vsts-ci.yml` and `.travis.yml` as references in #2353 , I noticed that we currently set environment variable `HOME_DIRECTORY`. It doesn't seem to be used anywhere, so I think we can remove it.
> [ci] remove unused environment variable in CI setups

- python-package/lightgbm/sklearn.py
Fixes issue related to [#17353](https://github.com/scikit-learn/scikit-learn/issues/17353) in scikit-learn (see [SLEP010](https://scikit-learn-enhancement-proposals.readthedocs.io/en/latest/slep010/proposal.html) for further details).
> [python][scikit-learn] add new attribute for used number of features

- R-package/R/lgb.Predictor.R
- R-package/tests/testthat/test_Predictor.R
Fixes https://github.com/microsoft/LightGBM/issues/3139
Just copy-pasted code snippet from lgb.Dataset initalizer.
As I am still not very familiar with the LightGBM data logic, @Laurae2 and @jameslamb would need to confirm that this makes any sense.
> [R-package] Turn matrix to storage mode "double"

- R-package/R/lgb.train.R
- R-package/tests/testthat/test_custom_objective.R
Right now, if you use a custom evaluation function and no other metrics, the code to find `best_iter` and `best_score` breaks. This PR fixes that and adds a test that that pattern is supported.
> [R-package] fix best_score using custom evaluation (fixes #3112)

- include/LightGBM/utils/common.h
Fix compilation error for VS 2017 at Azure NC12 VM.
I have no idea why we haven't seen this error at our CIs...
Refer to https://docs.microsoft.com/ru-ru/cpp/intrinsics/bitscanreverse-bitscanreverse64?view=vs-2019#example.
```
C:\Users\ntitov\Downloads\LightGBM\build>cmake -A x64 ..
-- Building for: Visual Studio 15 2017
-- Selecting Windows SDK version 10.0.16299.0 to target Windows 10.0.14393.
-- The C compiler identification is MSVC 19.12.25835.0
-- The CXX compiler identification is MSVC 19.12.25835.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/Hostx86/x64/cl.exe …
```
> fix error C3861: '_BitScanReverse': identifier not found

- docs/requirements_base.txt
- docs/requirements_rtd.txt
Refer to https://github.com/sphinx-doc/sphinx/issues/7817.
Avoid
```
Warning, treated as error:
/home/travis/build/microsoft/LightGBM/docs/../python-package/lightgbm/sklearn.py:docstring of lightgbm.LGBMClassifier.best_iteration_:1:duplicate object description of lightgbm.LGBMClassifier.best_iteration_, other instance in pythonapi/lightgbm.LGBMClassifier, use :noindex: for one of them
Makefile:20: recipe for target 'html' failed
make: *** [html] Error 2
```
in `master`.
> [ci][docs] temporarily pin Sphinx version

- .ci/test_r_package_windows.ps1
Fixed #3088.
Refer to
> Some parts of the operation of INSTALL depend on the R temporary directory (see tempdir, usually under /tmp) having both write and execution access to the account running R. This is usually the case, but if /tmp has been mounted as noexec, environment variable TMPDIR may need to be set to a directory from which execution is allowed.
https://www.rdocumentation.org/packages/utils/versions/3.6.2/topics/INSTALL
> [ci] avoid VS warning for R builds

- .appveyor.yml
- .ci/test_r_package.sh
- .ci/test_r_package_windows.ps1
- .github/workflows/main.yml
- .gitignore
- .vsts-ci.yml
- R-package/README.md
- R-package/inst/make-r-def.R
- R-package/src/cmake/modules/FindLibR.cmake
- R-package/src/install.libs.R
- R-package/src/make-r-def.R
- build_r.R
- docs/GPU-Windows.rst
Experimental fix for https://github.com/microsoft/LightGBM/issues/3064. Opening this PR to show the way I'm thinking about adding support for R 4.0. I will remove the `[WIP]` and request reviewers when it's ready for review, but any comments before then are welcomed if you have time!
* `gendef.exe` removed from Rtools 😭 
* `mingw32-make.exe` is no longer bundled with `Rtools` 😭 
* `Rtools` paths removed underscores, so `mingw_64/` becomes `mingw64/` 😂 
**gendef.exe fix**
Building the `LightGBM` R package on Windows with Visual Studio compilers requires `gendef.exe`. That was bundled in previous versions of `RTools` but isn't part of `Rtools` 4.0.
This PR replaces it with an R script that uses `objdump.exe`, software bundled in old and new distributions of `Rtools`.
**mingw32-make.exe …
> [R-package] Add support for R 4.0 (fixes #3064, fixes #3024)

- .appveyor.yml
- .ci/test_r_package_windows.ps1
- .github/workflows/main.yml
- .vsts-ci.yml
This PR addresses https://github.com/microsoft/LightGBM/pull/3065#pullrequestreview-429217760, moving all Windows R CI jobs to GitHub Actions.
This should reduce the total runtime of CI for this project. GitHub Actions allows 20 concurrent builds...AppVeyor (which we currently use) allows 1 😬 
While testing [on my fork](https://github.com/jameslamb/LightGBM/actions/runs/136691678), I found that thanks to this concurrency, all 12 jobs for R run in 12-13 minutes!!!
As of this PR, we will have four R Windows jobs all in GitHub Actions:
* R 4.0 + `MSYS2` toolchain
* R 4.0 + Visual Studio 2019
* R 3.6 + `MINGW` toolchain
* R 3.6 + Visual Studio 2017
You can see the full details of software versions for the GitHub Actions environments [here](https://github.com/actions/virtual-environments).
We …
> [ci] Move R Windows CI to GitHub Actions

- docs/requirements_base.txt
- docs/requirements_rtd.txt
- python-package/lightgbm/sklearn.py
Refer to https://github.com/sphinx-doc/sphinx/issues/7817#issuecomment-643295015.
Completely remove attribute names from `__init__` docstring because new Sphinx version doesn't fully comply with `numpy` docstring guide in terms of
> Attributes that are properties and have their own docstrings can be simply listed by name:
https://numpydoc.readthedocs.io/en/latest/format.html#class-docstring
Ugly constructions like ```:obj:``` are needed to workaround pydocstyle test:
```
./python-package/lightgbm/sklearn.py:680 in public method `best_score_`:
D401: First line should be in imperative mood; try rephrasing (found 'dict')
./python-package/lightgbm/sklearn.py:680 in public method `best_score_`:
D403: First word of the first line should be properly capitalized ('Dict', not 'dict') …
```
> [docs][scikit-learn] removed duplicated docstrings

- R-package/tests/testthat/test_Predictor.R
- R-package/tests/testthat/test_lgb.interprete.R
- R-package/tests/testthat/test_lgb.plot.importance.R
- R-package/tests/testthat/test_lgb.plot.interpretation.R
- R-package/tests/testthat/test_parameters.R
I've been looking at our test logs a lot the few days, and saw some opportunities to cut test time a little. This PR proposes cutting `nrounds` for a few tests to reduce CI time.
> [R-package] [ci] cut nrounds in unit tests

- R-package/R/lgb.train.R
- docs/Parameters.rst
- include/LightGBM/config.h
- include/LightGBM/tree.h
- include/LightGBM/tree_learner.h
- include/LightGBM/utils/common.h
- python-package/lightgbm/basic.py
- src/boosting/gbdt.cpp
- src/boosting/rf.hpp
- src/io/config.cpp
- src/io/config_auto.cpp
- src/io/tree.cpp
- src/treelearner/col_sampler.hpp
- src/treelearner/data_parallel_tree_learner.cpp
- src/treelearner/feature_parallel_tree_learner.cpp
- src/treelearner/gpu_tree_learner.cpp
- src/treelearner/gpu_tree_learner.h
- src/treelearner/parallel_tree_learner.h
- src/treelearner/serial_tree_learner.cpp
- src/treelearner/serial_tree_learner.h
- src/treelearner/voting_parallel_tree_learner.cpp
- tests/python_package_test/test_engine.py
Implement interaction constraints feature requested in #2884.
> Interaction constraints

- .ci/test_r_package_windows.ps1
- R-package/R/lgb.Booster.R
- R-package/R/lgb.Dataset.R
- R-package/R/readRDS.lgb.Booster.R
- R-package/R/saveRDS.lgb.Booster.R
- R-package/man/lgb.Dataset.Rd
- R-package/man/lgb.Dataset.save.Rd
- R-package/man/lgb.Dataset.set.categorical.Rd
- R-package/man/lgb.load.Rd
- R-package/man/lgb.save.Rd
- R-package/man/readRDS.lgb.Booster.Rd
- R-package/man/saveRDS.lgb.Booster.Rd
- R-package/tests/testthat/test_basic.R
- R-package/tests/testthat/test_lgb.Booster.R
- R-package/tests/testthat/test_parameters.R
This fixes the following NOTE from `R CMD check` on Windows:
> checking for non-standard things in the check directory ... NOTE
Found the following files/directories:
'data.bin' 'lgb-Dataset.data' 'lgb-model.rds' 'lgb-model.txt'
'lgb.Dataset.data' 'model.rds' 'model.txt'
It fixes this by only using `tempfile()` files everywhere that examples and tests write to the file system.
It also cleans up the logs in Windows R jobs. As of #3168 , I used `{processx}` to run some commands and redirect `stderr`, to avoid transient failures.
That produces hard-to-read logs like this:
This PR resolves that by assigning the result of `processx::run()` and setting `echo = TRUE` in those calls too stream out the logs.
> [R-package] fix R CMD check NOTE about leftover files

- CMakeLists.txt
- docs/Installation-Guide.rst
> [docs] document option to build a static library

- include/LightGBM/boosting.h
- include/LightGBM/c_api.h
- include/LightGBM/meta.h
- include/LightGBM/tree.h
- python-package/lightgbm/basic.py
- python-package/lightgbm/sklearn.py
- src/application/predictor.hpp
- src/boosting/gbdt.cpp
- src/boosting/gbdt.h
- src/c_api.cpp
- src/io/tree.cpp
- tests/python_package_test/test_engine.py
Adding sparse support to TreeSHAP algorithm in lightgbm.  The feature importances for a sparse matrix should be returned as a sparse matrix as well.  This should improve both performance and memory usage for very sparse datasets.
Unlike other predict APIs, it's not as easy to figure out prior to prediction what the size will be of the sparse matrix result, so we allocate the data on the native-side and expose an additional API to deallocate the sparse matrix arrays.
> adding sparse support to TreeSHAP in lightgbm

- .ci/test_r_package_windows.ps1
- .gitignore
See #3198 for details. Basically, R Windows jobs in CI today have to scrape a TeX archive page to find the name of a `miktexsetup` distribution to download. The scraping logic assumes that only one `miktexsetup` will be found there. That has been true for a while, but `miktexsetup` just had a major version bump (from 2.10.x to 4.0.0).
This PR fixes our CI by looking for a specific version of `miktexsetup`.
> [R-package] [ci] Fix MiKTeX downloads (fixes #3198)

- src/treelearner/serial_tree_learner.cpp
This PR is to fix #3054 .
The split_gain_ in Tree is only used by feature importance, apart from being saved into models.  
> https://github.com/microsoft/LightGBM/blob/9f367d11ad52ae8f2f1cf7b3447735723281d820/src/boosting/gbdt_model_text.cpp#L587-L621
Storing the true split gain in trees will also change the feature importance value. Feature importance values without subtracting the min_split_gain should be more meaningful, which reflects the true loss reduction by splitting with the feature.
BTW, is the comparing of split gains with 0 necessary in the code above? I thought split gains in tree models should always be >= 0, even after subtracting min_split_gain.
> Store the true split gain (without subtracting min_split_gain) in tree models (fix Issue #3054)

- .ci/setup.sh
- .ci/test.sh
Refer to https://github.com/Homebrew/homebrew-core/pull/54364#issuecomment-653448513.
Fix current MPI jobs failures.
> [ci] bump gcc version for macOS

- .ci/test.sh
- .ci/test_r_package.sh
- .github/workflows/main.yml
- R-package/R/lgb.importance.R
From @StrikerRUS 's suggestion in https://github.com/microsoft/LightGBM/pull/3188#discussion_r449203929, this pull request proposes adding a new R CI jobs called `check-r-docs`. This job regenerates the documentation for the R package and checks if there are any changes that have not been committed to the repo.
In R, the process for builds the docs in the `R-package/man/` folder is like this:
1. change files in `R-package/R/`
2. install the liibrary
3. run `roxygen2::roxygenize(load = 'installed')`
Because this process relies on installing the library, I think it makes sense to add into `./.ci/test_r_package.sh`. It requires installing one additional somewhat-expensive dependency (`roxygen2`) and the documentation is not dependent on operating system so I think it makes sense to do this …
> [ci] [R-package] catch builds that have not updated docs

- src/metric/multiclass_metric.hpp
Fixes #3201. Auc-mu was giving wrong values for large training sets, due to an integer overflow error when multiplying class sizes. This PR rewrites the calculation to avoid this multiplication.
> Fix integer overflow in auc_mu (fixes #3201)

- R-package/DESCRIPTION
Today we list `{knitr}` and `{rmarkdown}` as `Suggests` dependencies in the R package. This pull request proposes removing them.
`{knitr}` and `{rmarkdown}` are not used by anything in the R package today. I think removing them will provide a better user experience for anyone who is installing the R package in a way that also installs its `Suggests` dependencies.
> [R-package] remove unused Suggests dependencies

- R-package/src/R_object_helper.h
This PR is a step towards #3016 . Now that we are comfortable using R's provided headers in the R package, we can start to factor out custom things to reduce the maintenance burden for the R package.
This replaces `xlen_t` with `R_xlen_t` from `Rinternals.h`.
You can see the implementation at https://github.com/wch/r-source/blob/trunk/src/include/Rinternals.h#L71-L82
> [R-package] remove xlen_t in custom R-to-C++ interface

- .ci/test_r_package.sh
Should fix current `master` failures for R-package tests (https://github.com/microsoft/LightGBM/pull/2760#issuecomment-657538134).
```
Found the following significant warnings:
Warning: package ‘R6’ was built under R version 4.0.1
```
Extracted from #3188 because we need this change right now.
> [ci] bump R 4 version

- .github/CODEOWNERS
I've noticed recently that I'm getting automatically added as a reviewer for Python-only PRs like #3222. I think this is because `.github/CODEOWNERS` does not cover the `tests/` directory and my name is in the catch-all rule.
This PR proposes more specific rules for PRs that touch `tests/`, and some language-specific catch-all rules.
When reviewing this, remember that GitHub will use the matching rule that is furthest down in the file. So, for example, if someone touches the code in `helpers/`, the `helpers/` rule will be used, not the `*.py` one.
> add rules for tests/ in CODEOWNERS

- python-package/lightgbm/sklearn.py
- tests/python_package_test/test_sklearn.py
This PR fixes a bug in the LGBMClassifier class. The code as-is breaks when eval_metric is a list of strings. This is meant to work (as referenced in the documentation) and does work on all derived classes of LGBMModel except LGBMClassifier. The issue is in the following code in the master branch:
https://github.com/microsoft/LightGBM/blob/1e2013a306c0ca719fa076a733796a6372e5b77e/python-package/lightgbm/sklearn.py#L785-L798
with the fix the following line works as expected (see tests in PR):
`gbm = lgb.LGBMClassifier(**params).fit(eval_metric=['fair', 'error'], **params_fit)`
> [python][scikit-learn] Fixes a bug that prevented using multiple eval_metrics in LGBMClassifier

- src/c_api.cpp
Closes #3227
Upcast index of `leaf_preds` to size_t. In the current implementation, the index is an int32, which will segfault with large data sets and a large number of estimators.
> Upcast index to size_t in Refit

- .ci/test_r_package.sh
- .ci/test_r_package_windows.ps1
- R-package/DESCRIPTION
- R-package/demo/leaf_stability.R
Today the R package has a `Suggests` dependency on `{ggplot2}`.  This is only for one demo, `demo/leaf_stability.R`. This pull request proposes factoring it out and replacing it with `base` R code.
This will allow us to cut out this `R CMD check` NOTE:
> * checking package dependencies ... NOTE
Package suggested but not available for checking: ‘ggplot2’
More importantly, it's an expensive dependency that anyone installing the `Suggests` dependencies of `{lightgbm}`has to pay for.
Some of these plots look different from the comments around them, but this PR does not address that...it can be addressed in #1944 . This PR is limited to just factoring out `{ggplot2}`, to make the package as lightweight as possible when it goes to CRAN (work-in-progress, #629 ).
I've included before and after …
> [R-package] factor out {ggplot2}

- R-package/tests/testthat/test_lgb.Booster.R
This PR proposes a test for the R package on the configuration of feature types introduced in #3220 .
> [R-package] add test on importance types

- .ci/test_r_package.sh
- .ci/test_r_package_windows.ps1
- R-package/tests/testthat/test_lgb.Booster.R
See https://github.com/microsoft/LightGBM/pull/3224#issuecomment-661125688
#3224 removed the last `Suggests:` dependency for the R package that isn't installed in CI, so we can remove the environment variables set to change the `WARNING` about suggests dependencies into a `NOTE`.
> [ci] remove unnecessary R_CHECK_FORCE_SUGGESTS in CI scripts

- R-package/DESCRIPTION
- R-package/R/lgb.unloader.R
- R-package/R/utils.R
- R-package/man/lgb.unloader.Rd
- R-package/tests/testthat/test_lgb.unloader.R
- R-package/tests/testthat/test_utils.R
This PR proposes adding a few more tests on R code that isn't currently covered by tests.
It also proposes fixing an inconsistency I found while writing the tests. Today `lgb.check.eval()` sometimes sets `metric` as a character vector, and sometimes sets it as a list. This PR fixes that and guarantees that it always uses a list. A `list` is preferred because it allows for mixing string metric  names and custom eval function objects.
> [R-package] Add tests on lgb.check.eval, lgb.unloader, and lgb.encode.char

- include/LightGBM/utils/openmp_wrapper.h
Looking at the logs from https://github.com/microsoft/LightGBM/issues/629#issuecomment-664714892, I noticed many instances of this:
```
In file included from ./include/LightGBM/utils/common.h:9:0,
from ./include/LightGBM/config.h:16,
from io/config_auto.cpp:8:
./include/LightGBM/utils/openmp_wrapper.h:84:2: warning: extra ‘;’ [-Wpedantic]
};  // extern "C"
```
Uses of `extern "C" {}` don't need a closing `;`.
This PR proposes removing the trailing `;` in `openmp_wrapper.h` to suppress this compiler warning when using `-pedantic`.
You can see the R Hub logs here: https://builder.r-hub.io/status/original/lightgbm_2.3.2.tar.gz-6d1aa84ffbbd409293c9dcd94714bb47
> remove unnecessary semicolon

- R-package/src/Makevars.in
- R-package/src/Makevars.win.in
I think we can remove setting `CPICFLAGS`  in `Makevars.in` and `Makevars.win.in` in the R package. I noticed in the logs from R Hub (https://github.com/microsoft/LightGBM/issues/629#issuecomment-664714892) that my choioce was being ignored anyway...`-fpic` is used in many of the jobs.
Re-reading ["Writing R Extensions"](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Configure-and-cleanup), I see that I probably should have been using `CXX11PICFLAGS`.
In this PR, I propose just removing `CPICFLAGS` from these Makefiles and using whatever values R chooses based on the environment it is installed in. That should slightly simplify our configuration and reduce the risk of the CRAN package failing checks on the many obscure environments CRAN uses for testing.
> [R-package] allow R to pick between -fPIC and -fpic for CRAN package

- .travis.yml
- .vsts-ci.yml
This removes remained duplicated runs of CI for PRs from the original repo and now is in consistency with Appveyor and GitHub Actions configs.
Refer to #3096.
> [ci] run Travis and Azure Pipelines only for master branch

- .gitignore
This PR adds a few files to `.gitignore` that I've seen generated while working on the R package.
* `.tgz` --> the default when using `R CMD INSTALL --build` to create precompiled binaries
* `config.status` --> running `cd R-package && Rscript -e "pkgdown::build_site()"` now creates this, I don't know why
* `R-package/src/Makevars` --> this is generated at build time of the CRAN package but should never be checked in since its values will changed based on the system you install the package on
> [R-package] add some R build files to gitignore

- src/boosting/goss.hpp
This is to fix Issue #3243.
The gradients_ and hessians_ of GBDT object is of size 0 if customized objective function is used.
> https://github.com/microsoft/LightGBM/blob/1cf13dbaa433c414b2ec871ac4090bb853eceb1f/src/boosting/gbdt.cpp#L95-L99
However, they are used by the bagging function of GOSS, for example
> https://github.com/microsoft/LightGBM/blob/1cf13dbaa433c414b2ec871ac4090bb853eceb1f/src/boosting/goss.hpp#L103-L106
which causes the segment fault.
> create buffer for gradients and hessians with goss and customized objective (fixes #3243)

- python-package/lightgbm/engine.py
> [doc] better doc for `keep_training_booster`

- docs/Parallel-Learning-Guide.rst
- include/LightGBM/c_api.h
Fix two errors:
- 404 for `https://www.kubeflow.org/docs/fairing/fairing-overview`;
- `End of list marker found without any preceding list items` error in new Doxygen version.
> [ci][docs] fix current master failures for docs test

- docs/Experiments.rst
Fixes #3290, by removing the duplicated `tree_method = approx` from hyper-parameter setting of `xgboost_hist`.
> [docs] Fix repetition of `tree_method` hyper-parameter in xgboost_hist

- tests/python_package_test/test_basic.py
- tests/python_package_test/test_engine.py
- tests/python_package_test/test_plotting.py
Fix warning
```
FutureWarning: Pass return_X_y=True as keyword args. From version 0.25 passing these as positional arguments will result in an error FutureWarning)
```
> [ci][python] fix sklearn FutureWarning about positional args

- python-package/setup.py
Eliminate warning:
```
C:\Miniconda37-x64\envs\test-env\lib\site-packages\setuptools\distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
"Distutils was imported before Setuptools. This usage is discouraged "
```
Refer to https://github.com/pypa/setuptools/pull/2143, https://github.com/pypa/setuptools/issues/2259.
> [python] try to use bundled distutils to setuptools during setup

- R-package/.Rbuildignore
- R-package/DESCRIPTION
- R-package/cran-comments.md
- build-cran-package.sh
- python-package/setup.py
This addresses feedback from our first ever submission to CRAN!
https://github.com/microsoft/LightGBM/issues/629#issuecomment-671648923
* The note about "possible misspellings" can be fixed by putting `LightGBM` in quotes. I remember we had to do this when we first submitted [`uptasticsearch`](https://github.com/uptake/uptasticsearch/blob/master/r-pkg/DESCRIPTION#L17)
* the error from "not installed on i386" is from setting `Biarch: false` in `DESCRIPTION`. I thought that flag could be a way to publish a package that doesn't support 32-bit, but I don't think that works. Let's remove that field and we'll get a better error on CRAN 32-bit checks.
This also proposes adding a `cran-comments.md` to track feedback from CRAN. Since the CRAN upload process involves back-and-forth with humans (not …
> [R-package] DESCRIPTION changes to address CRAN feedback

- .ci/test_r_package.sh
We now have two PRs hitting CI failures on R builds for this issue:
```text
* checking installed package size ... NOTE
installed size is  5.2Mb
sub-directories of 1Mb or more:
libs   4.5Mb
```
https://github.com/microsoft/LightGBM/pull/3305#issuecomment-674348634, https://github.com/microsoft/LightGBM/pull/3264#issuecomment-671509757
That note is very unpredictable and likely to be allowed by CRAN. This PR proposes allowing it in CI jobs.
> [ci] fix flaky R CMD check test about library size

- include/LightGBM/bin.h
- src/io/bin.cpp
- src/io/dense_bin.hpp
- src/io/sparse_bin.hpp
- src/treelearner/feature_histogram.hpp
> fix zero bin in categorical split

- R-package/R/lgb.Booster.R
- R-package/R/lgb.Dataset.R
- R-package/R/utils.R
- R-package/tests/testthat/test_dataset.R
fix #3187 
The handle type should be int, otherwise, its size will be always 8 bytes on both 32bit and 64bit build, and cause the problems.
> [R] Fix 32-bit build

- .ci/test_r_package_windows.ps1
- R-package/README.md
Now that #3307 has ben merged and the R package is passing `R CMD check` for both `x64` and `i386` architectures, this PR proposes testing that in our CI. Since the 32-bit build isn't enable when  building with CMake (and I think we should not enable it), as of this PR `R CMD check` would be run without `--no-multiarch` only for CRAN builds.
This PR also proposes removing the `--no-multiarch` option from the documentation for installing with `{remotes}`. If we do that, I'd want to update the artifact `lightgbm-3.0.0-1-r-cran.tar.gz` on release `3.0.0rc`. @guolinke is that ok? Generally I think it's bad to update artifacts once they're published, but in this case since it's something very new and experimental, since its only a pre-release, and since the new artifact would't have any …
> [ci] Test 32-bit builds for R package

- docs/requirements_rtd.txt
Temp fixes for current `master` docs builds... again.
For some reason RTD by default installs old versions of `sphinx_rtd_theme` and `readthedocs-sphinx-ext` which results in
```
...
WARNING: the readthedocs_ext.readthedocs extension does not declare if it is safe for parallel reading, assuming it isn't - please ask the extension author to check and make it explicit
WARNING: doing serial read
...
build finished with problems, 2 warnings.
```
> [ci][docs] explicitly recuire fresh versions of RTD stuff

- R-package/.Rbuildignore
I saw this really interesting discussion on the `r-pkg-devel` mailing list: https://stat.ethz.ch/pipermail/r-package-devel/2020q3/005894.html
Basically, the `.Rbuildignore` file does not support comments. Lines that start with `#` will be evaluated as patterns that could match a file.
It also does not skip blank lines, so having blank lines just increases the time it takes to build a package.
This PR should slightly reduce the build time for the R package, and should avoid the unlikely but not impossible case where one of the "commented" lines matches and ignores a file that should not be ignored.
Since I'm touching this file, I also took the opportunity to rearrange it so that it is in alphabetical order (ignoring non-alphanumeric characters).
> [R-package] remove blank lines and not-really-comments from .Rbuildignore

- python-package/lightgbm/sklearn.py
There are no `group` and `eval_group` arguments in `fit` methods of `LGBMRegressor` and `LGBMClassifier`.
> [docs][python][sklearn] remove excess fit arguments from docstrings

- .ci/test_r_package.sh
- .ci/test_r_package_windows.ps1
This PR skips this `R CMD check` check that is breaking builds
```text
* checking for future file timestamps ... NOTE
unable to verify current time
```
You can see https://stat.ethz.ch/pipermail/r-package-devel/2020q3/005930.html for details. Essentially `R CMD check` relies on two small web services that provide a global clock, and this NOTE can show up when those services are unavailable. They are experiencing some issues this week 🙃 
I think this hack is better than just bumping `ALLOWED_CHECK_NOTES`, as described here: https://github.com/microsoft/LightGBM/pull/3338#discussion_r479346363
I've added this fix in #3336 and #3298 , but since it's blocking any other PRs, I thought it made sense to pull it out into its own PR we can merge quickly.
> [ci] fix R CMD check issue 'unable to verify current time'

- python-package/lightgbm/sklearn.py
- tests/python_package_test/test_sklearn.py
Fixed #3014 .
Probably we should replace properties with attributes under the work on #2966 to be better compatible and meet expected behavior from scikit-learn.
> [python][sklearn] be compatible with check_is_fitted sklearn function

- R-package/README.md
Fixes typo to allow for copy-paste installation of R package.
> [R-package] fix typo in R installation instructions

- .github/workflows/main.yml
see https://github.community/t/is-it-possible-to-require-all-github-actions-tasks-to-pass-without-enumerating-them/117957/4?u=graingert
> [ci] add an allgood job for easy [required] builds

- .ci/test_r_package.sh
Now that the R CI seems to be working ok on GitHub Actions (#3119 ) and the R components have been removed from the image used for Azure (https://github.com/guolinke/lightgbm-ci-docker/pull/11), I think we can simplify the CI code for R by removing `if $AZURE == "true"`branches from the code.
I also think it's possible to remove the dependency `texlive-fonts-extra` on Linux. Using this PR to test if that's true.
> [ci] remove Azure checks from R CI

- python-package/lightgbm/basic.py
- python-package/lightgbm/engine.py
- python-package/lightgbm/sklearn.py
- tests/python_package_test/test_engine.py
- tests/python_package_test/test_sklearn.py
This PR refactors the code in LGBM's scikit-learn API to allow the user to pass a list of evaluation metrics to the parameter `eval_metric` in the `fit` method of `LGBMModel` and its subclasses.
The snippet bellow shows an example of the possible uses of this functionality:
```python
import ...
def custom_recall_sklearn(y_true, y_pred):
return 'recall', recall_score(y_true, y_pred > 0.5), True
def custom_precision_sklearn(y_true, y_pred):
return 'precision', precision_score(y_true, y_pred > 0.5), True
parameters = {
"objective": "binary",
"metric": "binary_logloss",
}
model = lightgbm.LGBMClassifier(**parameters)
model.fit(
X=train,
y=train_label,
eval_set=(validation, validation_label),
eval_metric=[custom_recall_sklearn, custom_precision_sklearn, "auc"])
```
Where `eval_metric` receives …
> [Python] Refactors scikit-learn API to allow a list of evaluation metrics

- examples/README.md
Added winning solutions for LightGBM from completed Kaggle Competitions.
> [docs] update list of winning solutions in data science competitions

- examples/README.md
Correct link for the 2nd place solution is https://www.kaggle.com/c/abstraction-and-reasoning-challenge/discussion/154391 and I don't see any mentions of LightGBM there. Also, I checked 1st and 3rd solutions - no usage of LightGBM as well.
> [docs] remove unrelated entry from winning solutions list

- .ci/test_r_package_windows.ps1
- .ci/test_windows.ps1
Today, the Windows CI jobs sometimes fail downloading artifacts like Rtools and mixtexsetup.exe.
For example, see https://github.com/microsoft/LightGBM/pull/2912#issuecomment-686534527
Following the suggestion in https://github.com/microsoft/LightGBM/pull/2912#issuecomment-686556271, I've hosted the artifacts where we see these failures most often on a very old release (https://github.com/microsoft/LightGBM/releases/tag/v2.0.12). I also updated that release to explain that those artifacts are not a part of LightGBM. I think the "right" way to do this is to create a bucket in an object store like Azure Blob Store, but this is free and easier to maintain.
This PR proposes the necessary changes to download these files from GitHub instead of their current sources. I think that this PR will …
> [ci] host some artifacts needed by R Windows CI jobs

- src/boosting/gbdt.cpp
This PR is to fix #3317. When a booster is created from model file, its config_ member will be undefined. However, the ResetConfig method of GBDT is not aware of this. As @glarb pointed out.
> Avoid segment fault in ResetConfig for GBDT in prediction (fix #3317)

- R-package/R/callback.R
- R-package/R/lgb.Booster.R
- R-package/R/lgb.Dataset.R
- R-package/R/lgb.Predictor.R
- R-package/R/lgb.cv.R
- R-package/R/lgb.importance.R
- R-package/R/lgb.interprete.R
- R-package/R/lgb.model.dt.tree.R
- R-package/R/lgb.plot.importance.R
- R-package/R/lgb.plot.interpretation.R
- R-package/R/lgb.train.R
- R-package/R/lightgbm.R
- R-package/R/readRDS.lgb.Booster.R
- R-package/R/removed.R
- R-package/R/saveRDS.lgb.Booster.R
- R-package/R/utils.R
- R-package/man/lgb.prepare.Rd
- R-package/man/lgb.prepare2.Rd
- R-package/man/lgb.prepare_rules.Rd
- R-package/man/lgb.prepare_rules2.Rd
- R-package/man/lgb_shared_params.Rd
- R-package/man/lightgbm.Rd
- R-package/tests/testthat/test_basic.R
- R-package/tests/testthat/test_metrics.R
This PR proposes removing some comments in the R package that I think are unnecessary.
There are a lot of things like this in the R code:
```r
return(ret)
```
Comments like this don't add any understanding of the code, but they do make it slightly harder to read and possibly lead to false positives when using `git grep` or similar tools to search through the codebase for things.
> [R-package] remove unnecessary comments

- python-package/lightgbm/basic.py
I ran `pylint` over the Python package tonight and found a few small things.
This PR sets one unused variable to `_` to make the code a little easier to read and a little more memory-efficient.
> [python] remove unused variable

- .ci/test.sh
- .travis.yml
- docs/.linkcheckerrc
Refer to https://blog.travis-ci.com/2020-08-10-focal-build-environment.
Our policy is to test LightGBM against the most recent versions of OSes at Travis CI (in the opposite to Azure where we try to use the oldest images for producing public artifacts).
> [ci] Use Ubuntu Focal image at Travis

- .appveyor.yml
- .github/workflows/main.yml
- .travis.yml
- .vsts-ci.yml
- python-package/setup.py
Python 3.5 is reaching its End of Life today and no need to support it anymore.
https://devguide.python.org/#branchstatus
> [python] Drop Python 3.5 support

- src/treelearner/serial_tree_learner.cpp
this is useful to filter the histogram that cannot split.
> improve subfeature_bynode

- src/metric/multiclass_metric.hpp
- tests/python_package_test/test_engine.py
Fix auc_mu metric so that it uses the data weights if provided by the user.
> Auc mu weights

- src/c_api.cpp
- tests/python_package_test/test_engine.py
PR to fix sparse multiclass local feature contributions and add test.
This is a follow-up to this previous PR from me that was merged but had a bug in the multiclass case:
https://github.com/microsoft/LightGBM/pull/3000
This PR addresses bugs for multiclass case for both CSR and CSC matrixes:
1.) For CSR case, the indices array was getting overwritten for each matrix, so I added a 'matrix_offsets' array
2.) For CSC case, we were not incrementing col_ptr_index and matrix_start_indices was filled in invalid way
3.) Also, I added optimization to CSC case by parallelizing the code by matrix
The PR also adds a python test for multiclass sparse feature contributions case, which is similar to the test in the previous PR.
This bug was discovered in the …
> fix sparse multiclass local feature contributions and add test

- docs/Parameters.rst
- include/LightGBM/config.h
- src/io/config.cpp
- src/treelearner/feature_histogram.hpp
- src/treelearner/monotone_constraints.hpp
- src/treelearner/serial_tree_learner.cpp
- tests/python_package_test/test_engine.py
@aldanor @redditur
@guolinke @jameslamb @StrikerRUS 
Following PRs #2305, #2717, #2770, and #2939 here is the last PR of the series. #2305 was judged to be not merge-able because it was too big. Therefore, in my ultimate comment I said I would split it into smaller PRs easier to merge. #2717 was some refactoring, #2770 was the intermediate method, #2939 was the monotone penalization, and this PR is about the advanced method.
As a reminder, the basic method over-constrains leaves, and creates "unused space" between them. The intermediate method is smarter in updating the constraints and creates less "space" between the leaves, but it doesn't take into account that depending on thresholds, a leaf on the right and on the left of a monotone splits may not have to constrain each other. This …
> Pr4 advanced method monotone constraints

- src/treelearner/data_parallel_tree_learner.cpp
- src/treelearner/serial_tree_learner.cpp
- src/treelearner/serial_tree_learner.h
- src/treelearner/voting_parallel_tree_learner.cpp
When applying path smoothing, we need to calculate the output of the parent node. Previously this was calculated repeatedly for each potential split feature, but it's more efficient to just do it once per node. See comment here: https://github.com/microsoft/LightGBM/pull/3384/files/6d03633cdf41f7fd68118cdee7f169cac8b88eb0#r487355787
I also fixed a small bug: I was using `leaf_split->leaf_index() == 0` to test whether we are splitting the root node, but this is incorrect, now using `tree->num_leaves() == 1`.
> Improve performance of path smoothing

- R-package/R/metrics.R
- docs/Parameters.rst
- include/LightGBM/config.h
- src/metric/binary_metric.hpp
- src/metric/metric.cpp
- tests/python_package_test/test_engine.py
Implement average precision score for binary classification. This is very similar to the precision-recall AUC requested in #3026, but it does not interpolate the points of the curve, since this is not recommended for PR curves (see https://scikit-learn.org/stable/modules/generated/sklearn.metrics.average_precision_score.html).
> Average precision score

- R-package/R/lightgbm.R
I've just opened #3390. I think it's a great thing for Hacktoberfest contributors to work on.
Today the R package has a lot of internal function calls that use positional arguments instead of keyword arguments. This can be dangerous and lead to silent mistakes if you mix up values parameters that can take similar input ranges, for example `nrounds` and `early_stopping_rounds`.
I'm opening this PR to fix the cases in `lightgbm.R` and to serve as an example for #3390 .
> [R-package] use keyword arguments in internal function calls

- R-package/DESCRIPTION
In #3338 ,  we learned from CRAN that all copyright holders of any part of the source code need to be listed in the R package's `DESCRIPTION` file.
Since #3160 added some code with an IBM copyright on it, IBM needs to be added to `DESCRIPTION`. https://github.com/microsoft/LightGBM/pull/3338#discussion_r493584038
> [R-package] add new copyright holder in DESCRIPTION

- .github/workflows/main.yml
I realized today that the environment variable `CONDA_ENV` is not used by any of the R CI jobs. So it can safely be removed from the GitHub Actions config for this jobs.
> [ci] removed unused environment variable CONDA_ENV

- docs/Parameters.rst
- include/LightGBM/config.h
Following the discussion in the last few comments of #3264, I updated the monotone constraints reference report here.
> [docs] Change doc link to monotone constraints report to HAL document

- include/LightGBM/feature_group.h
- src/io/dataset.cpp
- src/metric/multiclass_metric.hpp
- src/treelearner/serial_tree_learner.cpp
- src/treelearner/serial_tree_learner.h
> fix warnings

- src/boosting/gbdt.cpp
> disable monotone constraint in objective functions with renew_tree_output

- python-package/lightgbm/basic.py
I was able to reproduce the bug from #3398 consistently on my machine with the script below (Windows, Visual Studio, Python 2.7). It always crashes on `seed=105`.
I think the cause is that `LGBM_DatasetGetFeatureNames` is expecting a `size_t` input for `buffer_len` but we pass a Python integer. Apparently this can cause unpredictable behavior depending on the compiler, see https://stackoverflow.com/questions/51903911/calling-c-functions-via-python-ctypes-why-does-passing-uints-to-a-function-expe
```
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(*load_breast_cancer(return_X_y=True),
test_size=0.1, random_state=1)
train_data = lgb.Dataset(X_train, y_train)
for …
```
> Use ctypes to pass parameters (fixes #3398)

- python-package/lightgbm/basic.py
> [python] Use ctypes for parameters of DLL functions for Dataset

- .ci/test_r_package.sh
- R-package/cleanup
While working on https://github.com/microsoft/LightGBM/pull/3405#issuecomment-703203133, I ran into this NOTE from `R CMD check`:
```text
* checking compilation flags in Makevars ... NOTE
Package has both ‘src/Makevars.in’ and ‘src/Makevars’.
Installation with --no-configure' is unlikely to work.  If you intended
‘src/Makevars’ to be used on Windows, rename it to ‘src/Makevars.win’
otherwise remove it.  If ‘configure’ created ‘src/Makevars’, you need a
‘cleanup’ script.
```
I don't completely understand the conditions when this might happen, but I know how to prevent it! 
From ["Writing R Extensions"](https://cran.r-project.org/doc/manuals/R-exts.html#Configure-and-cleanup):
> Under a Unix-alike only, an executable (Bourne shell) script cleanup is executed as the last thing by `R CMD …
> [R-package] add 'cleanup' script to handle left-behind Makevars

- docker/gpu/README.md
- docker/gpu/dockerfile-cli-only-distroless.gpu
- docker/gpu/dockerfile-cli-only.gpu
Closed #3286.
Replaces #3287 due to CLA problems.
@rsdmse Thank you very much for your contribution! Please help to review this PR.
> added new GPU docker files

- R-package/R/lgb.train.R
Fixes lgb.train.R from a list of functions listed on #3390
> [R-package] Updated lgb.train.R with keyword arguments

- .ci/test_r_package.sh
- build-cran-package.sh
This PR addresses pragma warnings that gcc was outputting since CRAN builds cannot suppress them. See issue #3433 for more information and recreation steps.
Major changes:
1. `build-cran-package.sh` was modified to remove `#pragma warning`s from all `h`, `hpp`, and `cpp` files in the temporary build folder (`lightgbm_r`).
2. An additional check was added to the end of the CI script `test_r_package.sh` that ensures no unknown pragma warnings were omitted during the build or else it will exit.
Closes #3433
> [R-package] Suppresses unknown pragma warnings during CRAN build

- include/LightGBM/c_api.h
- src/network/linkers_socket.cpp
This allows for network retries, to scale well with the
number of machines, and still retains the existing functionality
for cases with smaller num_machines ( 500 )
Fixes #3301
> Updated network retry delay strategy to scale

- .ci/test_r_package.sh
- .ci/test_r_package_windows.ps1
- .github/workflows/r_package.yml
In CI for the R package,  we check for `R CMD CHECK` warnings by looking for the string "warning" in its logs. That test is currently breaking builds (https://github.com/microsoft/LightGBM/runs/1268855023)  for a  warning that  can safely be ignored:
> Warning: package 'R6' was built under R version 4.0.3
This PR proposes ignoring those warnings. It also slightly simplifies the config for the UBSAN tests added in #3439  (based on https://github.com/microsoft/LightGBM/pull/3443#discussion_r506961056)
> [ci] ignore R CMD CHECK warnings on new R version

- .ci/setup.sh
- .vsts-ci.yml
Howbrew has recently removed the possibility to install old versions of packages from GitHub commits.
```
Error: Calling Installation of swig from a GitHub commit URL is disabled! Use 'brew extract swig' to stable tap on GitHub instead.
```
Now one should maintain their own GitHub repo for that.
More reading:
https://github.com/Homebrew/brew/issues/8791
https://discourse.brew.sh/t/has-brew-install-force-formula-raw-path-been-taken-out/8793
But fortunately I've found `SWIG@3` official formulae. I remember I hadn't got a luck to find it when setup SWIG building pipeline.
@imatiach-msft Just wonder, can we eventually migrate to SWIG 4? How about backward compatibility in this case?
> [ci] update SWIG installation on macOS

- src/boosting/gbdt_model_text.cpp
Fix warnings from Clang compilation: https://github.com/microsoft/LightGBM/pull/3443#discussion_r507728708.
> remove std::move

- .ci/setup.sh
- .github/workflows/cuda.yml
> setup CUDA CI job

- include/LightGBM/cuda/vector_cudahost.h
For `cudaPointerAttributes`, the attribute name has been updated from `memoryType` to `type` since 10.0, add support for compiling version less then 10.0 .
https://docs.nvidia.com/cuda/archive/9.2/cuda-runtime-api/structcudaPointerAttributes.html#structcudaPointerAttributes
https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/structcudaPointerAttributes.html#structcudaPointerAttributes
> Add support for cuda version less then 10.0

- include/LightGBM/utils/threading.h
- src/treelearner/leaf_splits.hpp
the stable multi-threading sum solution is much slower than omp sum. 
So we rollback for now.
> rollback omp sum

- src/io/config.cpp
> avoid min_data and min_hessian are zeros at the same time

- .gitignore
- tests/python_package_test/test_basic.py
- tests/python_package_test/test_engine.py
- tests/python_package_test/test_plotting.py
- tests/python_package_test/test_sklearn.py
- tests/python_package_test/utils.py
I spent some time this weekend learning [`snakeviz`](https://jiffyclub.github.io/snakeviz/), a Python profiler. I tried running it over the Python package tests here, and I think I found an opportunity to cut the test run time.
I realized we're spending time loading and reloading the same datasets.  This PR proposes reducing those calls by caching the results of `sklearn.datasets.load_*` calls. The datasets are really small so I don't think holding them all in memory will cause an issue.
**UPDATE:** Ok from some experiments, the speedup from this seems really small on my laptop. But might be larger in CI environments, where we know that disk I/O is a lot slower (https://github.com/microsoft/LightGBM/pull/2965#issuecomment-624421092).
These results were obtained on my laptop.  The …
> [ci] [python] reduce unnecessary data loading in tests

- .travis.yml
There is a new version of The macOS Build Environment. So I propose changes for you to use a modern one. https://docs.travis-ci.com/user/reference/osx/
> [ci] Update MacOS version at Travis

- CMakeLists.txt
According to the following discussion: https://github.com/microsoft/LightGBM/pull/3405#discussion_r502223468.
CMake < 3 is very-very old (in terms of their frequent releases). With 3.0 it will be possible to check API docs easier at least (docs for < 3 are hiddedn deep at their site and not structured).
> bump minimal CMake version

- R-package/R/lgb.Booster.R
-I am facing problems while generating the docs
Little help please
#3390
> [R-package] Updated lgb.Booster.R with keyword arguments

- R-package/configure
- R-package/configure.ac
This removes some unused variables in `R-package/configure.ac`.
The CRAN build of the R package contains a file `configure`, which is a shell script that run whenever the package is installed. It looks around on the system to figure out things like "is OpenMP installed", then fills out variables in a templated Makefile (`R-package/src/Makevars.[w]in`), which is then used to compile the library.
`configure` is created from a file `R-package/configure.ac` using `autoconf`.
When `configure.ac` was originally added, I copied and pasted some code from other examples and ["Writing R Extensions"](https://cran.r-project.org/doc/manuals/r-release/R-exts.html). That included this snippet:
```shell
CC=`"${R_HOME}/bin/R" CMD config CC`
CXX=`"${R_HOME}/bin/R" CMD config CXX11` …
```
> [R-package] remove unused variables in configure.ac

- .gitignore
- R-package/configure
- R-package/configure.ac
This PR fixes two bugs in the CRAN package
* uses a C++ compiler, not a C compiler, for `MM_PREFETCH` and `MM_MALLOC` checks
* removes extra `int main(...)` scaffolding in `MM_PREFETCH` and `MM_MALLOC` checks, which was causing them to fail
Look at the diff for `R-package/configure` and [the autoconf documentation on AC_LANG_CONFTEST](https://www.gnu.org/software/autoconf/manual/autoconf-2.61/html_node/Generating-Sources.html)...autoconf adds that scaffolding for you! So this check was ~always failing for the CRAN package on Mac and Linux~ failing for the CRAN on Mac, because the conftest code has an extra `int main(...)`!!
~NOTE: Once CI runs, I'm going to update this and a table here comparing the `MM_MALLOC` and `MM_PREFETCH` check results for CRAN vs. CMake builds...I think they'll …
> [R-package] fix MM_PREFETCH and MM_MALLOC checks in configure.ac

- docs/conf.py
#3276 documents some issues rendering plots in examples for the R package's documentation site, at https://lightgbm.readthedocs.io/en/latest/R/reference/.
I think that this is caused by the use of an older R version. This PR proposes fixing that by upgrading to R 4.0.3. It seems that R 4.0.3 packages are now available from conda-forge (thanks to the hard work of @xhochy and other https://github.com/conda-forge/r-base-feedstock maintainers).
This PR also simplifies our setup on RTD in a few ways:
* removes unnecessary dependency `testthat`
* removes unnecessary setting of `repos` option
* builds the entire env in one step (instead of installing anaconda and conda-forge packages separately) 
I tested locally with the following code, on an Ubuntu 18.04 laptop using `conda` 4.8.4:
```shell …
```
> [R-package] [docs] fix broken plots in pkgdown site (fixes #3276)

- .ci/test_r_package_windows.ps1
In #3469, I've been trying to figure out why this CI job on GitHub Actions often fails:
```text
- os: windows-latest
task: r-package
compiler: MINGW
toolchain: MINGW
r_version: 3.6
build_type: cmake
```
I don't think I've solved it yet, but I did find one problem we definitely need to fix. `Rtools35` stores `mingw32-make.exe` at `C:\Rtools\mingw_64\bin\mingw32-make.exe`, but that path isn't currently on `PATH` in our CI. I think it was just lost accidentally in some refactoring.
This PR doesn't fix #3469 but based on my testing, it does seem to make that issue happen less often. So maybe it will  at least make the contributor experience better.
> [R-package] [ci] add correct path for mingw32-make in CI

- R-package/src/install.libs.R
Way back in #2530 , we added some code to `R-package/src/install.libs.R` which removes `.NOTPARALLEL` directives from the makefiles generated by `CMake`. This was done to appease `R CMD CHECK` to get us closer to a CRAN-ready package.
Now that a CRAN-ready version of the R package exists and doesn't rely on CMake or `install.libs.R` at all, I think that that hack can be removed. We don't need to care that `R CMD CHECK` is complaining about this, and it might make installation with CMake faster: https://github.com/microsoft/LightGBM/pull/2530/files#r353195984.
We've already established that the CRAN package's main goal is portability / ease-of-installation and the CMake-created package's main goal is performance. I think this change is in line with that. I also think this is a good change …
> [R-package] remove Makefile hack in install.libs.R

- .github/workflows/cuda.yml
- .github/workflows/r_artifacts.yml
- .github/workflows/r_package.yml
- .github/workflows/r_valgrind.yml
I've been noticing a bunch of these warnings in GitHub Actions jobs:
> The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
For example, you can see these annotations on https://github.com/microsoft/LightGBM/actions/runs/343069981.
To be sure that these changes from GitHub don't disrupt our CI, this PR updates the GitHub Actions workflows in this project to use the newest versions of …
> [ci] upgrade GitHub Actions third-party actions to newest versions

- .gitignore
When you work locally with `dask`, by default it will create a directory for itself called `dask-worker-space/`. You can see this by running a small example like this
```python
from dask.distributed import Client
client = Client()
```
We'll start doing more local development with Dask in this project soon, based on #3515, so I think this directory `dask-worker-space/` should be added to `.gitignore`.
> ignore files from local Dask work

- src/treelearner/leaf_splits.hpp
> fix invalid read detected by valgrind

- .ci/test_r_package_valgrind.sh
An issue caught by `valgrind` was recently introduced onto `master` because the `valgrind` CI job didn't catch it: #3525 .
This PR fixes that so similar problems are caught in the future. Specifically, it will now fail builds where valgrind produces "invalid read" (like https://github.com/microsoft/LightGBM/issues/3525) or "invalid write" (like https://www.stats.ox.ac.uk/pub/bdr/memtests/valgrind/lightgbm/tests/testthat.Rout) errors.
> [ci] Make valgrind check stricter

- R-package/tests/testthat/test_learning_to_rank.R
This is a (hopefully temporary) workaround for #3513, as suggested in https://github.com/microsoft/LightGBM/issues/3513#issuecomment-720132153. See that issue for details.
I think this is necessary for the `3.1.0` release (#3484 ), because without it the R package might fail CRAN's checks on Solaris.
I have tested on R Hub and confirmed this allows the R package to pass `R CMD check` on Solaris:
```shell
sh build-cran-package.sh
```
```r
result <- rhub::check(
path = "lightgbm_3.0.0.99.tar.gz"
, email = "jaylamb20@gmail.com"
, check_args = c(
"--as-cran"
)
, platform = c(
"solaris-x86-patched"
, "solaris-x86-patched-ods"
)
, env_vars = c(
"R_COMPILE_AND_INSTALL_PACKAGES" = "always"
, "_R_CHECK_FORCE_SUGGESTS_" = "true"
, "_R_CHECK_CRAN_INCOMING_USE_ASPELL_" = "true"
)
)
```
> [R-package] fix learning-to-rank tests on Solaris

- src/io/config.cpp
Fix https://github.com/microsoft/LightGBM/issues/2898
Clearer warning message for user when `2^max_depth > num_leaves` happens.
> Fix #2898: Clearer warning message for user (2^max_depth > num_leaves).

- .ci/test_r_package.sh
- .ci/test_r_package_windows.ps1
- .github/workflows/r_package.yml
I've been learning about [`shellcheck`](https://github.com/koalaman/shellcheck), a linter for shell scripts.
This PR has a small simplification to `test_r_package.sh` that it suggested: replacing `grep "something | wc -l` with `grep --count "something"`. This might make that script a tiny tiny bit faster, but more importantly makes it a little easier to understand.
This PR also simplifies away a duplicated line in `test_r_package_windows.ps1` that I noticed while working on #3523
> [ci] simplify R CI scripts

- python-package/lightgbm/sklearn.py
- tests/python_package_test/test_sklearn.py
Modify the integration test for scikit-learn. Some deprecations have been raised in 0.23 and the upcoming release of 0.24 will break this test.
> TST make sklearn integration test compatible with 0.24

- src/objective/regression_objective.hpp
huber loss should use the same `IsConstantHessian` as its parent class, not need to override.
> fix constant hessian for huber objective 

- .github/workflows/cuda.yml
I was wrong in https://github.com/microsoft/LightGBM/pull/3524#pullrequestreview-522772442. I guess to use v2 we need update Actions runner first: https://github.com/actions/checkout/issues/348. @guolinke Could you help please? For now rollback to v1.
```
Run actions/checkout@v2.3.4
with:
fetch-depth: 5
submodules: true
repository: microsoft/LightGBM
token: ***
ssh-strict: true
persist-credentials: true
clean: true
lfs: false
Error: No such file or directory
```
> [ci] fix CUDA CI builds

- docs/FAQ.rst
Saw this problem on AWS Batch...
- LightGBM ran fine in standalone Batch jobs (one container per instance)
- LightGBM ran really slowly/hanged in Batch array jobs (multiple containers per instance)
> Add note on LightGBM/OpenMP hanging on AWS Batch

- docs/requirements_base.txt
- docs/requirements_rtd.txt
Build successful: https://readthedocs.org/projects/lightgbm/builds/12308946/.
I hope in the future we will be able to drop `requirements_rtd.txt` completely, but now `pip` still fails to resolve conflicts with preinstalled old (`1.8.5`) Sphinx and latest Breathe.
> [docs] simplify RTD config and use latest Sphinx

- include/LightGBM/train_share_states.h
One more warning from #3561 about unused field.
```
2020-11-13T15:29:38.5052580Z /Users/runner/work/1/s/include/LightGBM/train_share_states.h:134:16: warning: private field 'cur_multi_val_bin_' is not used [-Wunused-private-field]
2020-11-13T15:29:38.5053820Z   MultiValBin* cur_multi_val_bin_;
2020-11-13T15:29:38.5054740Z                ^
```
> fix compilation warning

- python-package/lightgbm/__init__.py
Refer to https://github.com/microsoft/LightGBM/pull/3484#issuecomment-723484953.
> [python] mark 3.1 version is the last one with Python 2 support

- .ci/setup.sh
- .ci/test.sh
- .ci/test_r_package.sh
- .ci/test_r_package_windows.ps1
- .github/workflows/r_package.yml
On https://github.com/microsoft/LightGBM/pull/3405#issuecomment-728353296, I see the Windows CI jobs on GitHub Actions failing with this output
```text
==> WARNING: A newer version of conda exists. <==
current version: 4.8.3
latest version: 4.9.2
Please update conda by running
$ conda update -n base -c defaults conda
#
#
#
#
```
I'm worried that this is another case where programs writing to stderr in GitHub Actions Windows jobs causes those jobs to fail. I don't know if this recently started failing because of software updates in GitHub Actions images (https://github.com/actions/virtual-environments/commits/main) or something else.
This PR proposes just updating `conda` to the latest version every time, to hopefully avoid this warning.
> [ci] remove conda from R CI jobs

- python-package/MANIFEST.in
This PR removes unnecessary files from the tarball created by `python setup.py sdist`,  to make that source distribution smaller.
This week I've been revisiting a conference talk I gave in April, where I showed how to deploy a LightGBM model on [AWS Lambda](https://aws.amazon.com/lambda/), using a Python Lambda.
To make external dependencies like `lightgbm`  available to a Python Lambda, you have to create something called a ["Lambda Layer"](https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html), which is basically like a volume with files on it that get mounted into the filesystem used by your code. The sum of all "layers" that you add cannot exceed 250 MB uncompressed. This made it hard to set up, for example, a Lambda that used `lightgbm`, `pandas`,  and …
> [python] remove unnecessary files to reduce sdist size

- docker/dockerfile-r
As requested in https://github.com/microsoft/LightGBM/pull/3581#discussion_r527795182, moving R Docker changes in a separate PR.
> small R Docker cleanup

- .github/workflows/r_artifacts.yml
This PR fixes #3567 . When third-party actions were updated in #3524 I think it broke the job that is used to create a source distribution of the CRAN package.
> [ci] Fix missing git install in R artifact job (fixes #3567)

- .ci/test_r_package_windows.ps1
- .github/workflows/r_package.yml
- R-package/tests/testthat/test_learning_to_rank.R
Based on https://github.com/microsoft/LightGBM/issues/3585#issuecomment-731663718. We were recently surprised by some test failures on 32-bit Windows checks for CRAN.
I think this is because I thought we were running tests with a 32-bit version of R on Windows (#3311 ) but maybe we never actually were.
I think that the root cause is that the test setup for our R environment doesn't install i386 components for R-win.exe, as documented in https://cran.r-project.org/bin/windows/base/rw-FAQ.html#Can-I-customize-the-installation_003f.
As of this PR, 32-bit R will be installed in GitHub Actions jobs and the R package will be tested against both architectures (x86 and i386).
In #3585 , we ran into issues only on CRAN's R 3.6 + Windows (32-bit) job. Today, the only tests of the CRAN package are …
> [ci] test 32-bit R in CI

- include/LightGBM/feature_group.h
- src/io/dataset.cpp
- src/io/dataset_loader.cpp
This PR is to fix:
1. Issue #3557 . The issue is due to that `used_feature_map_` is not correctly extended before being used in `Dataset::AddFeaturesFrom`. And the `real_feature_idx_` of the new dataset after adding features is not set correctly. The `bin_offsets_` is not extended in `FeatureGroup::AddFeaturesFrom`.
2. Potential problem with dense multi-val feature groups, when all the following conditions are satisfied:
- The first feature group is a dense multi-val feature group.
- The first feature of the dense multi-val feature group has non-zero `most_freq_bin_`
- In col-wise histogram construction case.
In this case, the `bin_offsets_` and `num_total_bin_` are not set correctly in `FeatureGroup` constructors (including `AddFeaturesFrom` method). And there will be a `CHECK` failure …
> Fix #3557 and potential issue with dense multi-val feature groups.

- src/c_api.cpp
Remove code duplication in c_api.cpp through use of templates.
> [refactor] Reduce code duplication in c_api.cpp

- python-package/MANIFEST.in
Fix warning on Windows:
```
warning: manifest_maker: MANIFEST.in, line 7: path 'compile/compute/' cannot end with '/'
```
https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=8065&view=logs&j=e0c3ed1e-0c79-508f-2647-33e12d6ed3d4&t=d764710f-c78e-54fd-dda4-11d6a80fefc7&l=439
> [python] fix regex in MANIFEST file

- README.md
LightGBM4j is a high-level Java wrapper for the LightGBM library. It can be nice to have it referenced from the main docs.
> [docs] add link to lightgbm4j to readme

- .ci/test.sh
- .travis.yml
- python-package/README.rst
- python-package/setup.py
Other ML libraries like XGBoost allows user to build wheel package to deliver it then to a cluster nodes.
LightGBM can be also build into wheel package, but with default options only (like no --gpu and no --cuda). If one wants to build custom wheel, he/she will face with ``option --gpu not recognized`` error and so on.
In this PR I've added custom `bdist_wheel` script which accepts just the same arguments as `install`.
> [python] Allow to build Python wheel package

- .ci/test_r_package_valgrind.sh
Refer to https://github.com/microsoft/LightGBM/pull/3484#discussion_r523766573.
> [R-package][tests] update values in valgrind test

- .github/workflows/r_package.yml
I realized tonight that we're setting environment variables `R_*_VERSION` unnecessarily in the GitHub Actions config for the R-package tests. It's set directly in https://github.com/microsoft/LightGBM/blob/6be3e57d21446022d33266605375660a9b35d9af/.ci/test_r_package.sh#L16-L24,  and I think that's a better place because we should try to keep the CI config files as simple as possible, in case they ever need to move to different CI providers.
This PR removes those unnecessary statements.
> [ci] remove unnecessary environment variables in R-package CI

- R-package/R/utils.R
This PR contributes to issue #3390 for the utils.R file. I added keyword arguments for the following functions `lgb.check.r6.class`, `lgb.encode.char`, and `lgb.c_str` and did not add keyword arguments for functions in R's standard library. I also checked that building the package and `R CMD INSTALL` works successfully.
Let me know if I did anything wrong with the PR. Thanks!
> [R-package] use keyword arguments for internal functions in utils.R

- .github/workflows/r_package.yml
- R-package/R/lgb.Dataset.R
Addresses part of #3390. Two notes:
1. There are a few functions that have only one argument(e.g., `lgb.is.Dataset(x)`). I don't know if it is necessary to modify these function calls to use keyword arguments; if it is, please let me know and I'll make a new commit to modify all these function calls.
2. I am not so sure about line 280. Is it correct that the first argument of the call `private$predictor$predict()` is `data`?
Thank you @jameslamb for providing this learning opportunity! I am already learning something new about git and github!
> [R package] update lgb.Dataset.R to use keyword arguments

- R-package/README.md
I agree with https://github.com/microsoft/LightGBM/pull/3586#issuecomment-735417087 ... `{lightgbm}` has been [on CRAN](https://cran.r-project.org/web/packages/lightgbm/index.html) for 11 days now with no significant errors and CRAN maintainers have not asked for a new submission, so we can safely publicize the fact that CRAN installation is now an option 🎉 
This PR updates the text in the R documentation to reflect that.
* I chose to make this a `feature` so that the changelog entry "{lightgbm} is now available on CRAN" shows up in the Release Notes 😀 
* I'm proposing that we remove the docs on pre-compiled binaries. CRAN will create those for Mac and Windows now, and the previous way we created them for Linux (#3285) didn't really work …
> [R-package] {lightgbm} is now available on CRAN (fixes #629)

- R-package/R/callback.R
- R-package/R/lgb.Booster.R
- R-package/R/lgb.Dataset.R
- R-package/R/lgb.Predictor.R
- R-package/R/lgb.convert_with_rules.R
- R-package/R/lgb.cv.R
- R-package/R/lgb.importance.R
- R-package/R/lgb.interprete.R
- R-package/R/lgb.plot.interpretation.R
- R-package/R/lgb.train.R
- R-package/R/lightgbm.R
- R-package/R/utils.R
Closes #3390 .
I didn't edit the following `.R` files because all internal function calls in these files are already using keyword arguments:
- lgb.plot.importance.R
- lgb.unloader.R
- metrics.R
- readRDS.lgb.Booster.R
- saveRDS.lgb.Booster.R
> [R-package] Update remaining internal function calls to use keyword arguments

- .gitignore
While testing #3515 using some AWS services, I realized that some common types of files used to store credentials and sensitive key material are not currently ignored by this project's `.gitignore`.
This PR proposes adding them, to avoid accidentally checking in sensitive information.
> [ci] add credentials to gitignore

- docs/Features.rst
I was reading https://lightgbm.readthedocs.io/en/latest/Features.html today and realized that a list of metrics is maintained there. That list is missing some of the newer things that @btrotta has added (average precision, AUC-mu). This PR proposes adding them.
I'm also proposing something I think we should do more of...adding a label like `new in v3.0.0`. Since we only host one version of the documentation, based on `master`, I think these types of annotations are useful. This is a practice I really appreciate in the `scikit-learn` docs, for example.
For example, https://scikit-learn.org/stable/modules/generated/sklearn.compose.ColumnTransformer.html#sklearn-compose-columntransformer
> [docs] update documentation with AUC-mu, average precision

- include/LightGBM/dataset_loader.h
- src/io/dataset_loader.cpp
To avoid binary file with non-matching parameters from being used.
> Check max_bin, etc. match config when using binary

- src/io/dataset_loader.cpp
> fix typo in dataset checks

- .ci/test_r_package.sh
- .ci/test_r_package_windows.ps1
- R-package/R/lgb.cv.R
This PR fixes #3629 , and fixes the R package CI to be sure that similar issues don't arise in the future.
Also fixes #3616
For CI, I'm proposing that instead of having a limit on the NUMBER of R CMD CHECK NOTES, we just ignore very specific NOTEs that we know are not problematic for CRAN. I think that will be less susceptible to issues like #3629 and give us more confidence that CI is catching problems that would be caught by CRAN.
This is blocking release 3.1.1 (#3611)
> [R-package] fix partial matching of keyword arguments in lgb.cv() (fixes #3629)

- README.md
Found it from here: https://medium.com/intel-analytics-software/improving-the-performance-of-xgboost-and-lightgbm-inference-3b542c03447e.
> [docs] added daal4py to related projects

- python-package/MANIFEST.in
Similar to #3579, this PR proposes making `python-package/MANIFEST.in` stricter to prevent unnecessary files from being bundled in the source distribution of the Python package.
#3405 introduced two new submodules (`fmt` and `fast_double_parser`), and right now all of their contents are being bundled in the source distribution of `lightgbm`. That includes a lot of files that are unnecessary for LightGBM, like tests and documentation.
This PR removes them. See #3579 for why this is worth caring about.
|                                       | 3.1.0       | 3.1.1     | `master` | this PR   |
|:-------------------------------:|:------------:|:----------:|:----------:|:------------:|
| sdist (compressed)       | 728K        | 572K    | 1.9M     | 712K       |
| sdist (uncompressed)   | 13M …
> [python-package] remove unnecessary files to reduce sdist size

- docs/conf.py
```
Collecting package metadata: ...working... done
Solving environment: ...working... failed
PackagesNotFoundError: The following packages are not available from current channels:
- r-base==4.0.3=hc603457_2
Current channels:
- https://conda.anaconda.org/conda-forge/linux-64
- https://conda.anaconda.org/conda-forge/noarch
- https://repo.anaconda.com/pkgs/main/linux-64
- https://repo.anaconda.com/pkgs/main/noarch
- https://repo.anaconda.com/pkgs/free/linux-64
- https://repo.anaconda.com/pkgs/free/noarch
- https://repo.anaconda.com/pkgs/r/linux-64
- https://repo.anaconda.com/pkgs/r/noarch
To search for alternate channels that may provide the conda package you're
looking for, navigate to
https://anaconda.org
and use the search bar at the top of the page.
Could not find conda environment: …
```
> [docs] fix RTD builds

- python-package/lightgbm/basic.py
as mentioned in https://github.com/microsoft/LightGBM/issues/3648
the average precision metric is a higher and better metric as auc
and we need to add back the rule in __higher_better_inner_eval
> [python] add average precision into higher_better eval

- README.md
This PR adds a link to the LightGBM integration with [ML Flow](https://mlflow.org/docs/latest/index.html). If you're curious, you can see more details on the individual methods at https://mlflow.org/docs/latest/python_api/mlflow.lightgbm.html#module-mlflow.lightgbm.
> [docs] add link to ML Flow and treesnip in LightGBM docs

- .appveyor.yml
- .ci/install_opencl.ps1
- .ci/test_windows.ps1
- .vsts-ci.yml
- docs/GPU-Targets.rst
- docs/GPU-Windows.rst
- python-package/README.rst
- tests/python_package_test/test_dual.py
Continuation of #3403.
@tpboudreau  Please help with review.
> [docs][ci] added docs about GPU support out of the box for Windows wheels and small refactoring for dual test

- README.md
In the official docs name of this package is written as `MLflow` (without a whitespace). I think it is like someone call `LightGBM` as `Light GBM`. And it improves searchability.
> [docs] fix MLflow spelling

- .ci/setup.sh
- .ci/test.sh
- .vsts-ci.yml
This PR proposes a few of the small changes from #3672, which I think should be non-controversial. Hopefully this will make that PR's diff smaller and make it easier to review.
* removes `[[ $TRAVIS == "true" ]]` checks on `check-docs` and `lint` tasks
- the fact that we happen to currently run those tasks on Travis doesn't need to be guarded in the code
* sets `AZURE=true` as a global variable in Azure DevOps config, reducing duplication
* changes the condition `if [[ $TRAVIS == "true" ]] || [[ $GITHUB_ACTIONS == "true" ]]` to simply `if [[ $SETUP_CONDA != "false" ]];`
- this condition was capturing "Linux jobs on Azure run in a container that already has conda, and all other jobs need to set it up". I think it's more explicit and less error-prone to just have `setup.sh` install conda by …
> [ci] remove unused CI checks, other small simplifications

- docs/Parameters.rst
- include/LightGBM/config.h
This proposes a change to the `min_data_in_leaf` docs, explaining that splits can produced leaf nodes with smaller counts, per the discussion in #3634.
> [docs] add doc on min_data_in_leaf approximation (fixes #3634)

- .ci/test_r_package.sh
Noticed this warning in R CI jobs on Mac (for example https://github.com/microsoft/LightGBM/runs/1620012053).
> Warning: Calling brew cask install is deprecated! Use brew install [--cask] instead.
This PR changes the one use of `brew cask install` to `brew install --cask` so that warning does not become an error whenever `brew cask install` is formally removed. It also removes some leftover horizontal whitespace in CI scripts.
> [ci] fix deprecated 'brew cask install' call

- include/LightGBM/dataset.h
Closes #3677 
Compile warnings have been fixed, `double` and `float` types where having issues when `double` values were assigned to a `float` type vector. In this case, the solution was just using a `static_cast<float>(doubleVal)` construction, which would lower the `double` value precission in order to fill the target `float` space.
There is to say that there could be a data loss during this process (not anything different than before), so it should be studied if `double` is the desired type for the `features_values` vector or it should be `float` type.
It would be desirable to use `.at()` instead of `[]` in order to throw exceptions when incorrect array positions are consulted.
> Added static cast from double to float

- README.md
This PR closes #3689. It removes references to Gitter and Slack.
I hope this will strengthen the LightGBM community by consolidating the conversation. As of this PR, the official advice in the README will be that general questions about LightGBM should go to the `lightgbm` tag on Stack Overflow, and bugs + feature requests should go on the GitHub Issues page here.
> [docs] Remove Gitter and Slack (fixes #3689)

- .gitignore
- tests/python_package_test/test_basic.py
- tests/python_package_test/test_engine.py
- Rename temp model file to not overcomplicate `.gitignore`.
- Reduce code duplication in params definition.
- Use asserts from `unittest` module for consistency with the rest codebase.
> [python][tests] small Python tests cleanup

- .vsts-ci.yml
Trying to take the non-controversial changes off of #3672 to make that PR smaller, and to get some changes onto `master` without needing to wait on that PR.
This PR is based on https://github.com/microsoft/LightGBM/pull/3672#issuecomment-751888860
> Could you please remove all occurrences of the maxParallel param to give Azure full control under the jobs' queue?
Per https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#job, `maxParallel` in an Azure DevOps pipeline config controls the maximum number of jobs to try to run simultaneously. This limit might be useful if you have some autoscaling set up or if you had some reason to want to slow down, but for our purposes it would be better to just let the default limits work and …
> [ci] remove maxParallel limits on Azure DevOps

- R-package/README.md
This PR proposes some small improvements to the R package README.
* note that R package tests are run on GitHub Actions (not Travis)
* change instructions for getting package coverage to use source builds of the CRAN package
- for someone checking test coverage, I think using the more-likely-to-work installation method is a lot more important than using the cmake-based method that produces a more efficient lib_lightgbm
* change test coverage script to only care about tests (not examples or vignettes)
> [docs] [R-package] improve R-package docs on testing

- R-package/README.md
Sorry, noticed this inconsistency only after merging #3724.
Previous link led to the customization of installation with CMake.
> [docs][R-package] change obsolete wordings in R README

- src/treelearner/feature_histogram.hpp
This is a PR to fix issue #3621. The thing was I didn't take into account the case where different constraints on different thresholds would prevent a split from happening. So, very rarely, a bad split happened which made the test fail. In theory this could have broken the monotone constraints required by the end user, but it happens so rarely that I don't think the end users have really been impacted (if it happens on a single tree in a forest of 100 trees, it most likely won't show). In this PR I make sure that constraints are admissible for any split, and I think that should remove the bug @StrikerRUS reported. Let me know what you think.
As an example, the following piece of code was producing the error mentioned in #3621, but runs smoothly now.
```
import numpy …
```
> fix test_monotone_constraints often fails on MPI builds

- include/LightGBM/dataset.h
- src/io/dataset_loader.cpp
- src/io/tree.cpp
- src/treelearner/linear_tree_learner.cpp
- src/treelearner/linear_tree_learner.h
Fix compiler warnings C4244 and C4267
> Fix compiler warnings caused by implicit type conversion (fixes #3677)

- src/io/dataset_loader.cpp
This is to fix #3657. In line 1208 of `dataset_loader.cpp`, it should use `ref_text_data` instead of `text_data`.
> Fix bug in ExtractFeaturesFromMemory when predidct_fun_ is used

- src/boosting/gbdt_model_text.cpp
It can only save the model in the local file before this pr. Although we can resave it into other filesystem e.g. hdfs by some other library, it's more convenient to provide such feature in LightGBM especially we train the model by the command directly  instead of python package.
> support more filesystem as the storage for model file 

- .ci/setup.sh
- .ci/test.sh
- .ci/test_r_package.sh
- .github/workflows/r_package.yml
- .github/workflows/static_analysis.yml
- .travis.yml
- .vsts-ci.yml
- README.md
Because of #3519 , we're in the process of removing all CI jobs that run on Travis and moving them to GitHub Actions.
This PR moves `check-docs` and `lint` to GitHub Actions. I wanted to do this one by itself to make #3672 smaller. These two jobs are also the easiest to move.
This PR proposes putting `check-docs` and `lint` into a separate GitHub Actions workflow called "Static Analysis". Today, GitHub Actions does not allow you to re-run individual failed jobs. So if one job fails for random or temporary reasons, you have to re-run all jobs in the workflow. Since the `check-docs` tasks fails somewhat regularly due to temporary network problems, I think it is a good idea to keep it + `lint` separate, so that the cost of re-running it is low.
Thanks for reviewing all of these @StrikerRUS . …
> [ci] Move check-docs and lint jobs off Travis

- .ci/test.sh
- .travis.yml
- docs/_static/js/script.js
- docs/conf.py
@jameslamb I remember you proposed this change some time ago. But I was against because was not bought of idea to rewrite all docs source files during the build process. Now I know that we can do it via internal Sphinx process which doesn't require rewriting files on a disk. Also, this approach safer than rewriting files because we are sure our regex is applied **only** to links in docs (`self.document.traverse(reference)`) not to the whole document.
Live demo: https://lightgbm.readthedocs.io/en/sphinx/
> [ci][docs] replace file extensions in docs during Sphinx build

- .vsts-ci.yml
To help with #3519, @guolinke has created a pool of self-owned runners for CI jobs on Azure DevOps. https://github.com/microsoft/LightGBM/issues/3519#issuecomment-748589207
This PR proposes moving the linux jobs we currently run on Azure DevOps to that pool. This should have no effect on those jobs, since they are containerized and run in containers based on the image from https://github.com/guolinke/lightgbm-ci-docker.
Running on this pool should decrease our overall CI time. See some of the comments from https://github.com/microsoft/LightGBM/pull/3672#issuecomment-753727415. Azure allows us 10 concurrent builds across all operating systems for all jobs using microsoft-hosted runners. After this change, those 10 concurrent builds would only be used by Mac and Windows jobs.
I think this …
> [ci] run Azure linux tasks on self-hosted runner pool

- .github/workflows/python_package.yml
- .travis.yml
- README.md
This is another step towards removing Travis from this project, in response to recent policy changes there (#3519).
This was originally proposed in #3672. On that PR, there is still a bit of work to be done for Linux jobs (https://github.com/microsoft/LightGBM/pull/3672#issuecomment-757387694), so this pulls out just the Mac changes so that we can reduce our reliance on Travis and start using GitHub Actions. The sooner this is done, the sooner we'll start learning about things that can be changed / fixed on GitHub Actions.
> [ci] move Python Mac jobs from Travis to GitHub Actions

- src/io/dataset.cpp
- src/io/train_share_states.cpp
This is to fix corner case bug due to histogram bin mismatch, which is introduced by a previous PR #3522. An error can occur when all the following conditions are satisfied
1. Row-wise histogram construction is used or feature subsampling is used.
2. The first feature group is a multi-value feature group.
3. The first group needs an extra padding bin.
> Fix bug in corner case with histogram bin mismatch

- src/treelearner/linear_tree_learner.cpp
I think this will fix one of the valgrind issues found in #3699
> Initialize any_nan_ property of LinearTreeLearner

- docs/Python-Intro.rst
- python-package/README.rst
closes https://github.com/microsoft/LightGBM/issues/3542
> [docs][python] add conda-forge install instructions

- .github/workflows/cuda.yml
- src/treelearner/cuda_tree_learner.cpp
- src/treelearner/cuda_tree_learner.h
Refer to 
- https://github.com/microsoft/LightGBM/issues/3450#issuecomment-756188587
- #3299 
- https://github.com/microsoft/LightGBM/pull/3748#pullrequestreview-565432556
> Update CUDA treelearner according to changes introduced for linear trees

- .ci/get_workflow_status.py
- .github/workflows/optional_checks.yml
By passing code phase instead of workflow name to `get_workflow_status.py` we can filter triggering comments by this phrase. It allows to workaround time delta described in first bad scenario in https://github.com/microsoft/LightGBM/pull/3740#issue-551423557. In other words, even for big queue for optional workflows in case commit was made nearly in the same time as triggering comment, required `Optional checks` workflow will wait for the latest reported status of just triggered optional workflow.
> [ci] Slightly optimize optional workflows checks

- tests/python_package_test/test_basic.py
Related to https://github.com/microsoft/LightGBM/issues/3732
This PR migrates the unitest-based test to use pytest. Additionally, this PR uses the `tmp_path` fixture when the test needs to create a temporary file.
> [python][tests] Migrates test_basic.py to use pytest

- tests/python_package_test/test_basic.py
This is the last tempfile left after the main work on replacing it with pytest fixture in #3764.
> [tests][python] completely remove tempfile from test_basic

- R-package/tests/testthat/test_basic.R
- R-package/tests/testthat/test_lgb.Booster.R
Validation results are not asserts to anything in these tests. So I believe we can remove `valids` param for clearness and to not waste time computing validation scores.
Sorry, I should have mentioned this during review of #3699.
> [R-package][tests] remove unused lines in tests for the speedup

- CMakeLists.txt
Partly reverts #3541.
That PR was an attempt to fix CMake + R 3.6 frequent random failures happen due to CMake cannot see standard libraries, tools, etc.
Unfortunately, that attempt didn't solve the issue.
I believe we should revert it to not hide real problems behind not executing linking step.
> [ci] revert forcing CMake to try compile static library for R-package

- src/application/predictor.hpp
- src/c_api.cpp
- Switch to for-based range loops in predictor.hpp (same performance, slightly more readable)
- Eliminate repeated and redundant variable update in SingleRowPredictor
> Minor C API cleanup in predictor & SingleRowPredictor 

- R-package/R/lgb.Dataset.R
- R-package/man/getinfo.Rd
- R-package/man/setinfo.Rd
- docs/Parameters.rst
- include/LightGBM/config.h
- python-package/lightgbm/basic.py
- python-package/lightgbm/sklearn.py
Based on the discussion in https://github.com/microsoft/LightGBM/pull/3708#discussion_r558570787, this PR proposes adding more details to the explanation of `group` in the Python and R packages.
I think that the current description doesn't give enough details for someone unfamiliar with LightGBM to get started. I know that I personally really struggled to understand what "group" should look like the first time I did learning-to-rank with LightGBM.
> [docs] expand documentation on 'group' for ranking task

- docs/.linkcheckerrc
Try to workaround `Valid: 429 too many requests` to GitHub.
This is the most frequent error I see.
https://github.com/linkchecker/linkchecker/issues/193
https://github.com/linkchecker/linkchecker/blob/7db035d1bc124d531370ac25179af3e7a08a40ff/config/linkcheckerrc#L170-L171
> [ci][docs] set limit for max requests per second to one host in linkchecker

- tests/python_package_test/test_dask.py
This PR proposes a refactoring of `tests/python_package_test/test_dask.py`, to reduce the runtime of the Dask tests.
* makes models smaller by setting `n_estimators=10` and `num_leaves=10` (the defaults are `n_estimators=100` and `num_leaves=31`)
* adds the `predict_proba()` tests for `DaskLGBMClassifier` into the existing `test_classifier` test. I don't think effectively testing `predict()` and `predict_proba()` requires separate training runs
I tried running `pytest tests/python_package_test/test_dask.py` 5 times on `master` and 5 times on this branch (on my laptop). I found that the changes in this PR reduce the runtime of the Dask tests by around  35 seconds.
I think this speedup will have a meaningful impact on development speed for the Dask module.
```text
before (avg = 137s): …
```
> [dask] reduce test times

- docs/Parameters.rst
- python-package/lightgbm/basic.py
- python-package/lightgbm/engine.py
- python-package/lightgbm/sklearn.py
After merging #3772 RTD builds started to fail with very strange error during creating PDF.
```
[143
! pdfTeX error (ext4): \pdfendlink ended up in different nesting level than \pd
fstartlink.
\AtBegShi@Output ...ipout \box \AtBeginShipoutBox 
\fi \fi 
l.13061 \item[{Return type}]
\leavevmode
!  ==> Fatal error occurred, no output PDF file produced!
```
I guess we hit the following issue: https://tex.stackexchange.com/a/424262.
I guess that the change of docstrings caused that some reference has been broken up by new page break position.
By trial and errors I found that either significant reduction of new `group` param description can change page breaks and solve th issue or some small addition to the current description. So I added `..., records 31-70 are in the third group ...`.
Also, I …
> [docs] fix current RTD failures

- python-package/lightgbm/dask.py
- tests/python_package_test/test_dask.py
This PR has two small cleanup actions for the Dask module.
1. moves `scipy` import above relative imports like `from .basic`, matching the ordering we use in other modules
2. replaces unused variables in tests with `_`
I found both of these small things with `pylint`.
> [dask] fix Dask import order

- docs/Installation-Guide.rst
No exceptions for threadless version.
https://github.com/microsoft/LightGBM/blob/d107872a5342442420edaa1d1849901f865f2331/CMakeLists.txt#L47-L51
> [docs] fix min CMake version in docs for macOS

- docs/requirements_base.txt
Needed to fix (probably [this one](https://github.com/readthedocs/sphinx_rtd_theme/pull/941)?) the following problem with lists inside other elements where colon is missed in version < 0.5 and words are joined.
Unfortunately, output from `breathe` still is not fixed. But there tooltip appeared on hover can help to split words.
> [docs] bump min sphinx_rtd_theme version

- src/c_api.cpp
The single row predictor methods in the C APi are not thread safe as reported in https://github.com/microsoft/LightGBM/issues/3751 and https://github.com/microsoft/LightGBM/issues/3675. This fixes both reports. Thank you https://github.com/tarunreddy1018 for the detailed reports!
By using a unique lock instead of the shared lock the timings are very similar, but predictions are correct.
Remarks for future work:
- Even so, by designing a small C++ benchmark with a very simple LGBM model, more threads on a simple model are slower than the single-thread case. This is probably due to very small work units, the lock contention overhead increases.
- We should in the future benchmark with more complex models to see if supporting
threading on these calls is worth it in performance gains.
- If …
> Fix thread-safety in C API's PredictSingleRow

- include/LightGBM/config.h
`ParseMetricAlias` and `ParseObjectiveAlias` functions should focus on enumerating aliases.
No need to overcomplicate the code. Cases for values that have no aliases are handled by the last unconditional `return` statement.
https://github.com/microsoft/LightGBM/blob/4885f063302ec5773376c90e56cb97f7a6d4b9a7/include/LightGBM/config.h#L1181
> remove unused code

- tests/python_package_test/test_engine.py
Towards https://github.com/microsoft/LightGBM/issues/3732
> [python][tests] migrate test_engine.py to pytest

- tests/python_package_test/test_dask.py
Addresses issue #3817. Correlation between dask's ranker scores and locally-trained ranker scores is stochastic, despite our best efforts to make deterministic `_make_ranking` data and using `seed=42` throughout DaskLGBM* tests.
I ran the test 100 times and this is the observed distribution:
@StrikerRUS observed a run achieving only 0.86 correlation.
So lowering the threshold to a more conservative 0.75.
This is a stopgap - ideally there is a way to distribute data deterministically to dask workers in tests.
> [dask] Address flaky test_ranker tests

- tests/python_package_test/test_plotting.py
Towards https://github.com/microsoft/LightGBM/issues/3732
> [python-package] migrate test_plotting.py to pytest

- tests/python_package_test/test_basic.py
- tests/python_package_test/test_engine.py
`test_basic.py` contains tests only for `Dataset` and `Booster` classes. There is `train()` function which we test in `test_engine.py` file in `test_save_and_load_linear` test.
<No changes, simple copy-paste.>
> [python][tests] transfer test_save_and_load_linear to test_engine

- src/treelearner/cuda_tree_learner.cpp
@StrikerRUS Don't copy more than has been allocated to device_features.
Fix CUDA failures [#3450](https://github.com/microsoft/LightGBM/issues/3450)
Possible compilation issues related to [#3750](https://github.com/microsoft/LightGBM/pull/3750)
> Don't copy more than has been allocated to device_features.

- tests/python_package_test/test_dask.py
- tests/python_package_test/utils.py
This ~can speed up tests by caching and also~ makes `make_ranking` function available for non-Dask tests.
**UPD:** OK, we cannot cache it due to unhashable `group` argument.
Diff for `make_ranking` (docstring fixed):
https://www.textcompare.org/index.html?id=600cacc151271d00170ec70c
> [dask][tests] move make_ranking into utils

- .github/workflows/triggering_comments.yml
Do not waste time (~20s) to clone the repo.
Skip everything for comments not starting with `/gha run`
> [ci] improve optional checks

- tests/python_package_test/test_dask.py
Ensure that local and Dask estimators share the same parameters.
Argument should be preferred to param alias (`seed` -> `random_state`) because internally both values are stored and then cpp code produces warning for ambiguous values.
> [dask][tests] reduce code duplication in Dask tests

- README.md
- docs/FAQ.rst
- docs/Parallel-Learning-Guide.rst
- docs/Python-API.rst
- docs/conf.py
- python-package/README.rst
- python-package/lightgbm/__init__.py
- python-package/lightgbm/compat.py
- python-package/lightgbm/dask.py
- python-package/lightgbm/engine.py
- python-package/lightgbm/sklearn.py
- python-package/setup.py
Towards #3814.
Maybe we can ask to [archive](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-repositories) old [dask-lightgbm](https://github.com/dask/dask-lightgbm) repo?
Live demo: https://lightgbm.readthedocs.io/en/dask_docs/Python-API.html#dask-api.
Why don't we have the most general class `DaskLGBMModel`?
> [dask][docs] initial setup for Dask docs

- python-package/lightgbm/dask.py
Based on https://github.com/microsoft/LightGBM/issues/3834#issuecomment-766351436.
Today, LightGBM's distributed learning supports three methods (feature parallel, data parallel, and voting parallel) --> https://lightgbm.readthedocs.io/en/latest/Features.html#optimization-in-parallel-learning
The Dask interface in `lightgbm.dask` is currently only tested with data parallel, where each chunk of the dataset is a row-wise chunk (all features, subset of rows).
The other methods MIGHT work with `lightgbm.dask`, but significant testing and documentation is needed. Supporting those methods might include adding extra validation to the Dask package as well.
The other parallel learning methods are optimizations, and I don't think the work to support them (#3834) needs to make it into the next …
> [dask] warn if attempting to use tree_learner other than data parallel

- tests/python_package_test/test_dask.py
Use benefits of #3822 and import `DaskLGBM*` classes from the root.
Import only things that are really used.
Skip `test_dask.py` when Dask is not installed. This is necessary to not force non-Dask contributors install all Dask stuff to run tests locally.
> [dask][tests] skip Dask tests when Dask is not installed and improve imports in Dask tests

- .ci/test.sh
- tests/python_package_test/test_dask.py
This PR fixes #3796.
We currently install `dask-ml` in CI, but only for the use of two small metrics functions in tests. To reduce CI times and other issues that dependencies can introduce (e.g. incompatibilities that lead to failed or slower conda environment solves, breaking API changes), this proposes removing `dask-ml` and just using our own small implementations of the two metrics needed by tests.
This PR uses @ffineis 's simple R^2 originally proposed in https://github.com/microsoft/LightGBM/pull/3708/commits/b39a1617af2eff0b618f4aa93a2d45ac7f2db963#diff-25c5c42e96fce8e0eb89cc7c991691d224c8b238cd91d2f795efe9fe7151750c.
> [dask] factor dask-ml out of tests (fixes #3796)

- include/LightGBM/feature_group.h
- src/io/dataset.cpp
This is to fix the efficiency problem reported by #3637. When bagging is used, `Dataset::CopySubrow` multi-threads by feature groups, which is not quite reasonable when a large multi-value feature group exists.
This PR changes the group-wise multi-threading into column-wise multi-threading.
> Change Dataset::CopySubrow from group-wise to column-wise

- R-package/pkgdown/_pkgdown.yml
I think `predict()` should be grouped together with `train()`, as the most primitive ML (name of the section in docs) can be described as fit+predict 😄 .
> [R-package][docs] improve grouping in R API reference

- tests/python_package_test/test_dask.py
> [dask] merge local_predict tests into other tests (fixes #3833)

- python-package/lightgbm/dask.py
Addresses #3795. The `_train` function in `dask.py` places delayed "parts," i.e. `data`, `label`, `sample_weight`, and `group` data into lists (which get distributed to workers) to enforce co-locality of data.  Each worker is distributed a `list_of_parts`, a list of lists. Once the worker receives its lists of parts, it infers the `data`, `label`, and then optionally `sample_weight` and `group` from each `list_of_parts` by assuming that `data` is in position 0, `label` is in position 1, and if the model is *not* a DaskLGBMRanker, the second position is reserved for `sample_weight`.
This is an issue of readability + scalability - implying the presence of `sample_weight` and `group` based on the length of each sublist of `list_of_parts` in conjunction with the estimator type is... hard to …
> [dask] [python] Store co-local data parts as dicts instead of lists

- tests/python_package_test/test_sklearn.py
Closes https://github.com/microsoft/LightGBM/issues/3732
> [python-package] migrate test_sklearn.py to pytest

- .vsts-ci.yml
I noticed that the availability of Ubuntu machines is greater than Windows ones in general (jobs start faster). Also, Windows machines cost more (see screenshot below, it is for GitHub Actions but they utilize Azure). I think it makes sense to run packaging job on the most cheap and available VM type.
> [ci] run artifacts packaging job on Ubuntu

- python-package/lightgbm/dask.py
I started working on type hints for the Dask module (#3756 ), and to do that effectively I needed to import `lightgbm.sklearn.LGBMModel`.
This PR proposes changing `_LGBMModel` to `_DaskLGBMModel`, so that when that type hints PR happens, we don't have two classes being referenced in the dask module whose names are only different by one character. I felt this change was valuable anyway for consistency, and would be quick and non-controversial to review, so broke it into a separate PR.
> [dask] rename _LGBMModel to _DaskLGBMModel

- .vsts-ci.yml
- python-package/lightgbm/basic.py
- python-package/lightgbm/compat.py
- python-package/lightgbm/dask.py
Will be reworked after discussion in #3808.
But for now this PR makes docstrings consistent with actual method signatures and reliable for early-adopters of lightgbm.dask.
Live demo: https://lightgbm.readthedocs.io/en/dask_docs/Python-API.html#dask-api.
With fixed importing way via `compat.py` module users are able to actually import classes, read their docstrings but in case of missing Dask dependencies informative error will be raised:
> [dask] fix Dask docstrings and mimic sklearn wrapper importing way

- .vsts-ci.yml
- tests/python_package_test/test_dual.py
- tests/python_package_test/test_engine.py
- tests/python_package_test/test_sklearn.py
- Use `pytest.approx` for scalars instead of `numpy.testing.assert_allclose`.
- Use default tolerance in asserts where possible.
- Bring back one assertion lost during #3844.
- Remove misleading comment.
> [python][tests] minor Python tests cleanup

- python-package/lightgbm/basic.py
- python-package/lightgbm/compat.py
- python-package/lightgbm/dask.py
- python-package/lightgbm/sklearn.py
Use common library import aliases as a prefixes in class names for better readability and to avoid possible name collisions.
Refer to https://github.com/microsoft/LightGBM/pull/3855#discussion_r564556639.
> [python] use better names for imported classes from extra libraries

- python-package/lightgbm/dask.py
- tests/python_package_test/test_dask.py
While working on #3756 , I've been running `mypy python-package/`. This caught a bug in my refactoring from recent PRs (not sure which one).
> python-package/lightgbm/dask.py:251: error: Name 'tree_learner' is not defined
This PR fixes that, and adds unit tests to cover the behavior under the two warnings in `lightgbm.dask._train()`.
> [dask] add tests on warnings, fix incorrect variable in log

- .ci/test.sh
Based on https://github.com/microsoft/LightGBM/pull/3865#issuecomment-767897424, this PR proposes adding `mypy` to the `lint` task in CI.
Similar to the approach we took with `cpplint` (#1990), this PR will print logs from `mypy` but not actually enforce anything yet. I've opened https://github.com/microsoft/LightGBM/issues/3867 to document why `mypy` is valuable and explain how contributors can help with it.
> [ci] add mypy to linting task

- .ci/setup.sh
- .github/workflows/cuda.yml
- README.md
Due to 
> It seems currently both azure pipeline and github actions cannot support the power-off/turn-on machines.
Even with the VM scale set in azure pipeline, it needs at least one machine stand by.
I know there are some external solutions, but they seems to require my Azure (Microsoft) account permission, which seems to violate our policy.
https://github.com/microsoft/LightGBM/pull/3424#issuecomment-701723558
machine with NVIDIA GPU is always turned on and I don't see any reasons to not run CUDA jobs on it for every PR in this case. Running CUDA jobs on a regular basis will make us sure that no one new PR breaks CUDA source code.
CUDA jobs cannot be run in parallel but the duration of all 3 jobs I set in this PR are about 20 min. Is it OK?
> [ci] improve and run CUDA jobs for every commit and PR

- .github/workflows/cuda.yml
- src/treelearner/cuda_tree_learner.cpp
- tests/python_package_test/test_utilities.py
Fix current CUDA workflow failures in `master` due to merge conflict.
> [ci] ignore CUDA-related strings in Python logger test

- .ci/test_r_package.sh
- .github/workflows/r_package.yml
Partly reverts #3876.
https://github.com/microsoft/LightGBM/pull/3876#issuecomment-769202545
macOS binaries for `withr` have been uploaded to CRAN.
https://cran.r-project.org/web/packages/withr/index.html
> [ci][R-package] remove CI workaround with manual withr installation

- .readthedocs.yml
- docs/requirements_rtd.txt
Refer to https://github.com/microsoft/LightGBM/pull/3554#issue-518762299.
Finally pip is smart enough to resolve dependency conflicts without our help. Now it forces updating `Sphinx` due to new `breathe` version.
https://github.com/michaeljones/breathe/blob/a8be7365bc3e6f4380053291b1e66e3a788e342a/setup.py#L17
Live demo: https://lightgbm.readthedocs.io/en/test_docs/
> [docs][ci] drop special dependency requirements for RTD site

- tests/python_package_test/test_dask.py
Further addresses #3817 by making `test_dask.py` a little bit more predictable. Previously the `test_ranker` test while using `output='array'` provided very uneven `group` allocations among its two test workers, unlike in the case of dask.dataframe input. Because `#data` is so small (e.g. 100 rows), when one worker gets a small amount of data relative to the other(s), this can cause rather significant discrepancies between the Dask ranker and the standard `LGBMRanker`. [See comment](https://github.com/microsoft/LightGBM/issues/3817#issuecomment-770426671) for more background.
Applying [`client.rebalance`](https://distributed.dask.org/en/latest/api.html#distributed.Client.rebalance) in this case (small data and uneven worker data distributions) helps make the tests a bit more predictable, …
> [dask] [python] client.rebalance on dask ranker test

- docs/Parameters.rst
- include/LightGBM/config.h
- src/application/application.cpp
- src/io/config.cpp
- src/io/dataset_loader.cpp
The main motivation of adding `save_binary` task type is to save memroy.
The python function `Dataset.save_binary()` has two drawbacks:
1. Uses much more memory compared to data itself
- triple memory usage to be more exact, but I didn't investigate this too deep
2. Can not use the `two_round` parameter compared to command line verison to reduce memory usage
If you have interest to merge this PR, I'd also update the corresponding docs.
> Add new task type: "save_binary".

- README.md
For use-case: I open LightGBM repo -> I see last CRON link checks workflow is failing -> I want to rerun that workflow to see whether error was temporary or we need update broken link.
> [docs] make link checks badge clickable

- .github/workflows/linkchecker.yml
Just noticed this. I think our ordinary name for a such jobs better reflects what's happening inside.
Wording `Note(Check) that all tests succeeded` we are using for special `all-successful` jobs:
https://github.com/microsoft/LightGBM/blob/c324e891be58789f0423cd5c986e7396a524b3ce/.github/workflows/python_package.yml#L73-L79
> [ci] Rename linkchecker job

- .vsts-ci.yml
- python-package/lightgbm/dask.py
- tests/python_package_test/test_dask.py
Refer to https://github.com/microsoft/LightGBM/pull/3883#discussion_r569033103.
> [dask] remove unused private _client attribute

- python-package/lightgbm/dask.py
Looks like I missed removing the `client` argument in `DaskLGBMRegressor` in #3883 , sorry!
I think in the future, we might be able to use `mypy` to catch API differences between the Dask package and its scikit-learn equivalents. For now, this PR removes that argument.
> [dask] remove extra 'client' kwarg in DaskLGBMRegressor

- swig/pointer_manipulation.i
I'm a maintainer of the [lightgbm4j](https://github.com/metarank/lightgbm4j) library, and would like to expose the `LGBM_DatasetGetFeatureNames` function in a more java-friendly way. 
The problem with the `LGBM_DatasetGetFeatureNames` function is that it requires a `size_t` [type param](https://lightgbm.readthedocs.io/en/latest/C-API.html#c.LGBM_DatasetGetFeatureNames), which is not possible to instantiate at all, as SWIG definition file only exposes int/long/double/float/int64_t/int32_t types.
This one-liner PR also exposes a `size_t` function family in SWIG wrapper, so `lightgbmlibJNI.java` will also include these new ones:
```
>   public final static native long new_size_tp();
>   public final static native long copy_size_tp(long jarg1);
>   public final static native void …
```
> [SWIG] add size_t manipulation functions

- src/io/dataset.cpp
- src/network/network.cpp
- src/treelearner/cuda_tree_learner.cpp
- src/treelearner/gpu_tree_learner.cpp
I was reading through the code in `src/network` while reviewing #3823 , and found a typo in a log message. So I looked for others like this:
```shell
grep -E "Log\:\:" -r src/* | aspell list | sort -u
```
This PR fixes a few typos in log messages.
> fix typos in log messages

- python-package/lightgbm/dask.py
- tests/python_package_test/test_dask.py
This PR fixes https://github.com/microsoft/LightGBM/issues/3861.
Thanks to @jmoralez for figuring out that the root issue was `pandas` "category" columns for data frames! `lightgbm.dask._predict_part()` did some conversions thatt did not handle these columns correctly.
1. Removes code in `_predict_part()` that converts a chunk of data to array before passing it through to `.predict()` on the underlying scikit-learn model.
- LightGBM's scikit-learn estimators already support scoring directly on pandas data frames, so this was useless. And it was the root of the problem! Because when you use `.values` on a pandas "category" column, the results are strings. Passing a numpy array with string data into `.predict()` methods in LightGBM leads to errors.
2. Adds data frames with a "category" …
> [dask] Support Dask dataframes with 'category' columns (fixes #3861)

- .ci/run_rhub_solaris_checks.R
- .github/workflows/optional_checks.yml
- .github/workflows/r_solaris.yml
- .github/workflows/triggering_comments.yml
- R-package/README.md
Refer to #3740.
How it looks like: https://github.com/StrikerRUS/LightGBM/pull/5#issuecomment-773700926.
> [ci][R-package] run R CRAN checks on Solaris by optional workflow

- LESSONS
- tests/python_package_test/test_dask.py
I tried to check for a sublist in sklearn's args which matches dask's (this ensures that order is checked), the same goes for the
default values. 
fixes #3907
> [dask] Add unit tests that signatures are the same between Dask and scikit-learn estimators 

- python-package/lightgbm/dask.py
- tests/python_package_test/test_dask.py
This PR adds support in the Dask module for getting indices of the leaf nodes in each tree that each observation in a dataset falls into, via `.predict(X, pred_leaf=True)`. It fixes #3792.
This brings the Dask module a step closer to feature parity with the estimators available from `lightgbm.sklearn`.
These tests also led to the discovery of this bug: https://github.com/microsoft/LightGBM/issues/3918
> [dask] Add support for 'pred_leaf' in Dask estimators (fixes #3792)

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
I've observed that people reporting bugs in this project very very rarely use the issue template. I think that we're asking for too much information, and that people just get overwhelmed and ignore it entirely.
I've noticed that other projects like https://github.com/PrefectHQ/prefect/issues and https://github.com/dask/distributed/issues get a much higher % of issues following their template, and I think this is because their templates are so much simpler.
This PR proposes simplifying the issue template for bug reports greatly, to hopefully get higher-quality reports.
> [docs] simplify bug report template

- tests/python_package_test/test_dask.py
This includes a test to check that the training process succeeds even when a worker has no data, e.g. verify that #3882 is solved. 
I wanted to persist the collections to a specific worker with something like:
```python
for worker in workers:
dX, dy, dw = client.persist([dX, dy, dw], workers=worker)
```
However I got: `TypeError: unhashable type: 'Array'`.
So in the test I just create a collection with one chunk, persist it and check that it is only in one worker. Any feedback to make this test more robust is welcome.
> [dask] test training when a worker has no data

- python-package/lightgbm/dask.py
- python-package/lightgbm/sklearn.py
- tests/python_package_test/test_dask.py
This PR proposes a fix to https://github.com/microsoft/LightGBM/issues/3871.
* corrects type information (e.g. to say "dask Array" instead of "array-like")
* removes docs for keyword args that aren't currently supported (like `init_score` and various `eval_*` arguments)
* removes docs for custom objective, since that isn't supported yet (TODO: I'll write up a feature request tomorrow)
To minimize duplication, this PR moves the `sklearn` docstrings into template strings that are then formatted with `.format()`. This indirection is a little confusing, but we can at least rely on getting CI failures in the `check-docs` task, since `.format()` has to fill all template values.
```python
"{a} - {b}".format(a="hello")
```
* I opened this PR on the `docs/jlamb` branch so we can check on …
> [dask] [docs] Fix inaccuracies in API docs for Dask module (fixes #3871)

- tests/python_package_test/test_dask.py
Based on thread starting at https://github.com/microsoft/LightGBM/pull/3930#discussion_r573107195.
#3908 added some tests that the `lightgbm.dask` estimators correctly handled Dask DataFrames where some columns are `pandas` "category" columns. That PR used the parameter `categorical_feature` to explicitly provide a list of which features should be treated as categorical.
This is unnecessary, since `auto` is the default behavior and `auto` tells LightGBM "treat 'category' columns as categorical features" (https://github.com/microsoft/LightGBM/blob/846b512d892426d34fac0749ccfd2d7a31eef877/python-package/lightgbm/basic.py#L513-L514).
This PR removes the unnecessary `categorical_features` parameter in tests. As of this PR, we'll now be testing not only that `lightgbm.dask` estimators …
> [dask] test that Dask automatically treats 'category' columns as categorical features

- python-package/lightgbm/dask.py
- python-package/lightgbm/sklearn.py
I was wrong in my suggestion previously https://github.com/microsoft/LightGBM/pull/3930#discussion_r573036384.
Shape can be `[n_samples]` in case of binary problem and `raw_score=True` or custom objective function.
> [docs][python] fix shape description of returned result for predict_proba

- docs/Python-API.rst
This proposes adding a `versionadded` note on the Dask API docs. Sorry I didn't think about it on #3822 .
> [docs][dask] add versionadded note to Dask docs

- include/LightGBM/utils/openmp_wrapper.h
Fix #3915. OpenMP stubs do not use the noexcept attibute which is present in the gcc version of openmp, and which trigger compilation errors as seen below. dmlc-core uses the same technique and macro.
/usr/lib/gcc/x86_64-linux-gnu/9/include/omp.h:114:12: error: declaration of ‘int omp_get_thread_num() noexcept’ has a different exception specifier
114 | extern int omp_get_thread_num (void) __GOMP_NOTHROW;
|            ^~~~~~~~~~~~~~~~~~
...
xxx/include/LightGBM/utils/openmp_wrapper.h:81:14: note: from previous declaration ‘int omp_get_thread_num()’
81 |   inline int omp_get_thread_num() {return 0;}
|              ^~~~~~~~~~~~~~~~~~
> openmp_wrapper.h stubs signature use __GOMP_NOTHROW

- docs/Parameters.rst
- include/LightGBM/config.h
As suggested by @flippercy https://github.com/microsoft/LightGBM/issues/3910#issuecomment-775502268
> [DOCS] Update docs about linear tree and monotone constraints

- src/network/linkers.h
Reading through the `network/` code today while working on reviewing #3823 , I noticed a few small mistakes. This PR fixes them.
> [docs] fix typos in network docs

- python-package/lightgbm/dask.py
Address [comment](https://github.com/microsoft/LightGBM/pull/3952#discussion_r575713223) in #3952 to reuse `len(parts)` as `n_parts`. cc @jameslamb
> [dask] reuse len(parts) as n_parts

- python-package/setup.py
> [ci][python] apply isort to python-package/setup.py #3958

- .ci/get_workflow_status.py
- .ci/test.sh
- .editorconfig
- .nuget/create_nuget.py
- python-package/lightgbm/__init__.py
- python-package/lightgbm/basic.py
- python-package/lightgbm/compat.py
- python-package/lightgbm/dask.py
- python-package/lightgbm/engine.py
- python-package/lightgbm/sklearn.py
- tests/python_package_test/test_engine.py
- tests/python_package_test/test_sklearn.py
Fixed #3958.
Closed #3983.
Some files have `isort`-related diff although `isort` has been already applied due to new `120` length limit in config file.
Also prefer installation from conda to pip for `rstcheck`. `mypy`, `isort` and `pycodestyle` have conflicts when installing from `conda` altogether.
> [ci][python] run isort in CI linting job

- .ci/setup.sh
- .ci/test.sh
- .vsts-ci.yml
- tests/python_package_test/test_dask.py
- tests/python_package_test/test_engine.py
Contributes to #1129.
Fixed #3456.
Fixed #3517.
(Superceded) closed #3421.
I run 10x10 consecutive runs and all of them were successful, so I'm quite sure in stability of new QEMU job.
It can be seen from the picture above that sometimes QEMU job takes ~30min and sometimes ~1h. I thought that maybe there is any bottlenecking test that freezes whole job. But unfortunately, long runs are related to QEMU itself (it is common practice to set `timeout=360` for QEMU builds) because in those jobs all tests contribute to slowness. Here are timings from `pytest`.
```
2021-02-12T14:26:32.5928137Z ============================== slowest durations ===============================
2021-02-12T14:26:32.5928779Z 555.37s call     tests/python_package_test/test_engine.py::test_int32_max_sparse_contribs …
```
> Run tests and build Python wheels for aarch64 architecture

- python-package/lightgbm/basic.py
Approximately %80 of runtime when loading "low column count, high row
count" DataFrames into Datasets is consumed in `np.fromiter`, called
as part of the `Dataset.get_field` method.
This is particularly pernicious hotspot, as unlike other ctypes-based
methods this is a hot loop over a python iterator loop and causes
significant GIL-contention in multi-threaded applications.
Replace `np.fromiter` with a direct call to `np.ctypeslib.as_array`,
which allows a single-shot `copy` of the underlying array.
This reduces the load time of a ~35 million row categorical dataframe
with 1 column from ~5 seconds to ~1 second, and allows multi-threaded
execution.
> Optimize array-from-ctypes in basic.py

- tests/python_package_test/test_dask.py
Working on a proposal to address https://github.com/microsoft/LightGBM/pull/3823#pullrequestreview-582002723, I found that sometimes the "find an open port" test in `test_dask.py` failed with an error.
> assert new_port == 12401
> E assert 12404 == 12401
I think that test is too strict. Right now it checks "if port 12400 is unavailable, `_find_open_port()` returns 12401". If 12401 is busy for some unrelated reason, this test fails.
This PR proposes loosening the condition a bit, to reduce the risk of test failures like that. It isn't important that that method finds 12401 specifically. Just some port that is `>` the port number you passed in.
> [tests][dask] make find-open-port test more reliable

- src/metric/xentropy_metric.hpp
This PR proposes removing removing some commented-out OpenMP pragmas in the cross-entropy source code.
From the blame, it appears this commented-out code was introduced 4 years ago :grinning: 
https://github.com/microsoft/LightGBM/blame/master/src/metric/xentropy_metric.hpp#L284
> remove commented-out code in cross-entropy metric source

- CMakeLists.txt
- README.md
- docs/Advanced-Topics.rst
- docs/Experiments.rst
- docs/Features.rst
- docs/Installation-Guide.rst
- docs/Parallel-Learning-Guide.rst
- docs/Parameters.rst
- docs/Quick-Start.rst
- docs/index.rst
- examples/binary_classification/train.conf
- examples/binary_classification/train_linear.conf
- examples/lambdarank/train.conf
- examples/parallel_learning/README.md
- examples/regression/train.conf
- examples/xendcg/train.conf
- include/LightGBM/config.h
- include/LightGBM/dataset.h
- python-package/lightgbm/basic.py
- src/application/application.cpp
- src/io/config.cpp
- src/io/dataset_loader.cpp
- src/io/metadata.cpp
In https://github.com/microsoft/LightGBM/issues/3596, we agreed to replace the terminology "parallel learning" with "distributed learning" in this project's documentation, everywhere that that phrase was used to refer to **multi-machine training**. It was also agreed in that issue that this change should not break any current documentation links.
I've started doing that in https://github.com/microsoft/LightGBM/pull/3951, in preparation for adding new Dask docs (#3814).
While working on #3951, I realized that many of the places where this language needs to be changed won't break any links. These are in things like code comments and log messages.
This pull request proposes just those changes that don't break links, to hopefully reduce the size of #3951 and make it easier to review.
> [docs] Change some 'parallel learning' references to 'distributed learning'

- python-package/lightgbm/dask.py
The Dask sklearn estimators in `lightgbm.dask` inherit from both their `lightgbm.sklearn` equivalent and a mixin called `_DaskLGBMModel`.
https://github.com/microsoft/LightGBM/blob/7880b79fde36873b95839c0029ea9d649397da51/python-package/lightgbm/dask.py#L525
Those equivalents from `lightgbm.sklearn` inherit from a mix of LightGBM internal classes and some mixins brought in from `sklearn`.
```python
from lightgbm.sklearn import DaskLGBMClassifier
for c in DaskLGBMClassifier.__mro__:
print(c)
```
Since `LGBMClassifier` is the first parent class in the method resolution order ("MRO") for `DaskLGBMClassifier`, if it or any of the parent classes from `sklearn` introduce a method that conflicts with one of the method names in `_DaskLGBMModel`, the `_DaskLGBMModel` method won't be used, which …
> [dask] use more specific method names on _DaskLGBMModel

- .ci/test_r_package.sh
This PR proposes a fix to #4008. The root cause for that issues is that `{data.table}` recently did a release, but binaries are not available from CRAN yet for it. As a result, the newest version is being compiled from source in CI, and that compilation is failing.
This PR proposes changing the strategy for installing dependencies to "install the newest binary" instead, so that such temporary situations won't disrupt CI and slow development on the entire project in the future.
This reverts the change made in https://github.com/microsoft/LightGBM/pull/3876. Since R package builds have to pass for any LightGBM PRs to be merged, I think we should prefer minimizing disruptions even if it means that it takes an extra day or two for our CI to start using the newest version of a dependency.
I …
> [ci] prefer older binary to new source for R packages on Mac builds (fixes #4008)

- docs/Parameters.rst
- include/LightGBM/config.h
- src/application/predictor.hpp
As noted in #4002, `pred_contrib` does not work for linear trees.
> [DOCS] Update docs to note that pred_contrib is not available for linear trees

- .github/workflows/python_package.yml
- tests/python_package_test/test_engine.py
Refer to https://github.com/microsoft/LightGBM/pull/3987#issuecomment-782489734.
I think it is important to have this test to not introduce a regression in the future.
> [tests][python] Add test for single leaf in linear tree

- python-package/lightgbm/basic.py
- tests/python_package_test/test_basic.py
- tests/python_package_test/test_dask.py
- tests/python_package_test/test_sklearn.py
This solves #3909 by allowing to have an `(n_samples, 1)` array as label when `data` is a `pandas.DataFrame`.
> [dask] [python-package] include support for column array as label

- .ci/test_r_package_windows.ps1
- tests/python_package_test/test_dask.py
Fixes #4031. In `scikit-learn` 0.24.x, support for passing a class (instead of an instance) to `sklearn.utils.estimator_checks.check_parameters_default_constructible()` was removed (https://github.com/scikit-learn/scikit-learn/pull/17134).
We must have recently started getting `scikit-learn` >=0.24.0 in tests, because CI has been failing on this test with this error
> E           TypeError: type() takes 1 or 3 arguments
This error only shows up for the Dask estimators, because we call `check_parameters_default_constructible()` directly there. The equivalent test in `tests/python_package_test/test_sklearn.py` isn't failing because it's skipped on `sklearn>=0.24.0` (https://github.com/microsoft/LightGBM/blob/6356e659af74909aa77eb87d54b79f0373772509/tests/python_package_test/test_sklearn.py#L …
> [dask] [ci] add support for scikit-learn 0.24+ in tests (fixes #4031)

- .ci/test_r_package.sh
- .ci/test_r_package_windows.ps1
R Windows CI jobs are currently failing on `master` ([logs](https://github.com/microsoft/LightGBM/runs/2018204127)) and #4027 ([logs](https://github.com/microsoft/LightGBM/pull/4027/checks?check_run_id=2018832067)) with the following:
```text
* checking whether package 'lightgbm' can be installed ... WARNING
Found the following significant warnings:
Warning: package 'R6' was built under R version 4.0.4
See 'C:/tmp-r-cmd-check/lightgbm.Rcheck/00install.out' for details.
Status: 1 WARNING
```
There has not been a release of `{R6}` since October 2020 (https://cran.r-project.org/web/packages/R6/index.html), but CRAN does create new package binaries when a new version of R is released. R version 4.0.4 was released about two weeks ago: https://twitter.com/pdalgd/status/1361246911378960391, but …
> [ci] [R-package] upgrade to R 4.0.4 in CI

- python-package/lightgbm/dask.py
- python-package/lightgbm/sklearn.py
- tests/python_package_test/test_dask.py
This solves #3807 by including the option to specify `init_score` as a dask collection to the `fit` methods of the dask estimators. A test is included to check that using `init_score` with dask and scikit-learn estimators results in the same result and that not using it results in a different one.
> [dask] Include support for init_score

- .gitignore
While developing on the python package, I regularly run `jupyter lab` and create a new notebook for testing. This results in leaving behind files with names like `Untitled.ipynb`, `Untitled2.ipynb`, etc. Those names are the default notebook names created by Jupyter ( https://github.com/jupyter/notebook/blob/bc28d6123117c3c733697e27e9d4bd71d7f0c46b/notebook/services/contents/manager.py#L74), so anyone doing something similar might create such files.
This PR proposes adding a rule to `.gitignore` to prevent such notebooks from being checked into source control here.
> [ci] ignore untitle Jupyter notebooks in .gitignore

- .ci/test.sh
Python CI jobs in several pull requests are failing right now. For example, see https://github.com/microsoft/LightGBM/pull/4048#issuecomment-79328858 and https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=9396&view=logs&j=c28dceab-947a-5848-c21f-eef3695e5f11&t=fa158246-17e2-53d4-5936-86070edbaacf .
All of the Dask tests are failing with an error like this
> E AttributeError: 'HighLevelGraph' object has no attribute 'dask_distributed_pack'
This error occurs when you try to use `dask` 2021.2.0 with `distributed` 2021.3.0. For more documentation on that, see https://github.com/dask/dask/issues/7331.
Specifically, LightGBM's CI is hitting this error because it installs `dask` and `distributed` from the default anaconda channel, which is updated more slowly than …
> [ci] prevent getting incompatible dask and distributed versions

- .ci/test_r_package.sh
- .ci/test_r_package_windows.ps1
This PR attempts to fix #4049. See https://github.com/microsoft/LightGBM/issues/4049#issuecomment-793412254 for a more detailed explanation of this proposal.
> [ci] fix R CMD CHECK note about example timings (fixes #4049)

- .ci/test_r_package_windows.ps1
- .github/workflows/r_package.yml
I *think* this PR fixes https://github.com/microsoft/LightGBM/issues/3469 😬 
Using https://github.com/nelsonjchen/reverse-rdp-windows-github-actions, (mentioned in https://github.com/microsoft/LightGBM/issues/3469#issuecomment-785538447), I RDP'd into a GitHub Actions runner running the `windows-latest` image and try some experiments. I discovered something confusing and scary that I think could be the root cause of CI instability mentioned in #3469.
I manually copied the content of [test_r_package_windows.ps1](https://github.com/microsoft/LightGBM/blob/3a5e3c001f7a571eec375d021d12ccd37353a60c/.ci/test_r_package_windows.ps1) into a Powershell shell running in that runner, a few lines at a time.
Immediately after installing Rtools, the directory `C:\Rtools` was visible in Windows Explorer …
> [ci] add CMake + R 3.6 test back (fixes #3469)

- tests/python_package_test/test_dask.py
This includes an additional task of multiclass-classification for `test_dask.py` and renames classification to binary-classification. I removed the `centers` argument from the `_create_data` function and now define them inside the function accordingly to the classifying task. I also created `task_to_dask_factory` and `task_to_local_factory` dictionaries to simplify the task of getting a model factory from a task, this was specially useful now that we have two classification tasks. 
I noticed that `test_init_score` fails for the multiclass-classification task but I removed it from the tasks in that test and can make a different PR adding it back once #4046 is solved. I also noticed that `test_classifier` sometimes fails when comparing the local vs dask probabilities, so I'm happy to …
> [dask] include multiclass-classification task in tests

- python-package/lightgbm/dask.py
- tests/python_package_test/test_dask.py
As of #3994 , it's possible to give the estimators in `lightgbm.dask` an exact set of worker IPs + ports to use for distributed training. This is done by providing a parameter `machines`, a string with a comma-delimited list like `ip1:port1,ip2:port2`.
If you accidentally include duplicates in this list, the error you get today is not very informative:
>  KeyError: 'pop from an empty set'
This PR proposes catching this case and throwing a more informative error.
In this case, "duplicates" refers to duplicate `ip-port` pairs. It is possible and very common to run multiple Dask workers on one physical machine. In those cases, it's `machines` might look like this
```text
ip1:12400
ip1:12405
ip1:12475
```
In #4057, I mentioned that it was probably possible to even further reduce the risk of …
> [dask] raise more informative error for duplicates in 'machines' (fixes #4057)

- .github/workflows/r_solaris.yml
I forgot to add one line that sets yellow 'pending' status for running R Solaris workflow in #3913.
Similar to R valgrind workflow:
https://github.com/microsoft/LightGBM/blob/15853a7a02621347aa74bdacb97bbbdc80b25cab/.github/workflows/r_valgrind.yml#L31-L37
Noticed that in https://github.com/microsoft/LightGBM/pull/3872#issuecomment-795972470.
> [ci] set 'pending' commit status for running R Solaris optional workflow

- src/io/tree.cpp
This is to fix #3778. When loading booster from a model file produced by old version of LightGBM without linear tree option, we should set `is_linear_` of a tree to `false`, to avoid uninitialized `is_linear_` value, which can cause undefined behavior.
> Set `is_linear_` to false when it is absent from the model file

- python-package/lightgbm/libpath.py
- Added type hints for libpath.py as per https://github.com/microsoft/LightGBM/issues/3756.
- Verified that there were no additional errors when running mypy.
> [python-package] Add type hint to the libpath file

- .ci/test.sh
- docs/Parallel-Learning-Guide.rst
- examples/python-guide/dask/binary-classification.py
- examples/python-guide/dask/multiclass-classification.py
- examples/python-guide/dask/prediction.py
- examples/python-guide/dask/ranking.py
- examples/python-guide/dask/regression.py
- python-package/README.rst
Dask examples are placed in the [`python-guide/dask`](https://github.com/microsoft/LightGBM/tree/master/examples/python-guide/dask) subdirectory.
Also this PR adds some punctuation to Dask guide.
> [ci] run Dask examples on CI

- python-package/lightgbm/basic.py
While working on `lightgbm.dask`, I noticed that the docstring for `machines` in `Booster.set_network()` seems to be incorrect.
It says the following:
> machines : list, set or string
Names of machines.
However, `machines` is passed to `lightgbm.basic.c_str()`, which only accepts strings: https://github.com/microsoft/LightGBM/blob/bcf443b568052eac05cb8b11b17be9926b862f8f/python-package/lightgbm/basic.py#L2359.
If you pass a set or list, you'll get an error like.
> AttributeError: 'set' object has no attribute 'encode'
```python
machines = set(["10.1.1.1:12400", "10.1.1.2:12400"])
lgb.basic.c_str(machines)
```
This PR proposes updating that docstring to make it clear that only strings are supported. It also adds type hints on the other arguments in …
> [python-package] add type hints on Booster.set_network()

- tests/python_package_test/test_dask.py
This PR attempts to fix the occasional failure in the Dask tests mentioned in https://github.com/microsoft/LightGBM/pull/4068#issuecomment-798972634. One of the test cases in `test_dask.py` explicitly requires that at least two workers join the cluster and have pieces of the training data.
This PR tries to prevent that error by using [`Client.wait_for_workers(2)`](https://distributed.dask.org/en/latest/api.html#distributed.Client.wait_for_workers). That call will block until at least 2 workers are up and have joined the cluster, which should prevent errors caused by one worker process being a little slow to start sometimes.
It's difficult to reliably test that this PR would fix the problem mentioned in https://github.com/microsoft/LightGBM/pull/4068#issuecomment-798972634, since it …
> [dask] [ci] fix flaky network-setup test

- .ci/test.sh
This reverts commit 4e9c976867e1493b881b32d0e94ccf5c915fa31f.
Refer to https://github.com/microsoft/LightGBM/pull/4054#issuecomment-793743273.
> [ci] install Dask from main conda channel

- python-package/lightgbm/dask.py
This PR removes two unused imports from `typing`  in the Dask module. I think the need for them was removed in recent refactorings.
Caught these by looking at `pylint python-package/`.
> [dask] remove unused imports from typing

- .ci/setup.sh
- .ci/test.sh
- .vsts-ci.yml
Today I had to re-run Azure builds more than 5 times to make it create new release. Also, many current PRs are failing with 
```
Executing transaction: ...working... g_module_open() failed for /home/AzDevOps_azpcontainer/miniconda/envs/test-env/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: libXrender.so.1: cannot open shared object file: No such file or directory
g_module_open() failed for /home/AzDevOps_azpcontainer/miniconda/envs/test-env/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: libXrender.so.1: cannot open shared object file: No such file or directory
```
For example, #4093, #4092.
I hope system-wide installation of `libxau` along with `libxrender1` will solve the issue.
Refer to https://github.com/conda-forge/graphviz-feedstock/issues/35#issuecomment-786368 …
> [ci] fix flaky Azure Pipelines jobs

- .ci/setup.sh
Continuation of #4095.
Now we get 
```
Executing transaction: ...working... g_module_open() failed for /home/AzDevOps_azpcontainer/miniconda/envs/test-env/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: libXext.so.6: cannot open shared object file: No such file or directory
g_module_open() failed for /home/AzDevOps_azpcontainer/miniconda/envs/test-env/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: libXext.so.6: cannot open shared object file: No such file or directory
```
randomly.
Also, I think our Azure agents are unhealthy because I see some weird errors: failures to clone the repo, Dask test hangs for 1h and aborted, failures during `apt-get install ...`, etc.
> [ci] fix flaky Azure Pipelines jobs (2)

- .ci/setup.sh
Our CUDA+Clang builds are incopatible with yesterday-released CMake 3.20.0 version:
Found Clang, but using gcc.
```
-- The C compiler identification is Clang 6.0.0
-- The CXX compiler identification is Clang 6.0.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++ - skipped
...
gcc: error: unrecognized command line option ‘-fopenmp=libomp’; did you mean ‘-fopenmp-simd’?
```
```
-- The C compiler identification is Clang 6.0.0
-- The CXX compiler identification is Clang 6.0.0
-- Detecting C compiler ABI info
-- …
```
> [ci] restrict CMake version for CUDA+Clang jobs

- src/network/socket_wrapper.hpp
Issue: set TCP_NODELAY failed in distributed training and it could be found from the warning log. 
The reason is that the type of kNoDelay should be int from https://man7.org/linux/man-pages/man2/getsockopt.2.html and https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-setsockopt
```
int setsockopt(int sockfd, int level, int optname,
const void *optval, socklen_t optlen);
```
> Most socket-level options utilize an int argument for optval. 
> To enable a Boolean option, the optval parameter points to a nonzero integer. To disable the option optval points to an integer equal to zero.
> Fix tcp_no_deplay setting by using int type

- R-package/tests/testthat/test_basic.R
This fixes a typo in params on one of the R unit tests, which led to the warning noted in https://github.com/microsoft/LightGBM/issues/4105#issuecomment-806259143
> [LightGBM] [Warning] Unknown parameter: categorical_featurs
That test specifically checks that training a model in R using linear models at the leaves works if you also have categorical features. So this typo might have actually prevented that test from running correctly and covering what it was expected to.
I also looked through the logs from a recent build of the `r-package (windows-2019, MSVC, R 4, cmake)` CI job. Those jobs use `Rscript testthat.R` instead of `R CMD CHECK`, so you can see all of the logs from the tests. For the other warnings that look problematic, I've opened #4108 with the tag `good first issue` so that …
> [R-package] fix typo in linear learner test

- .vsts-ci.yml
Refer to https://github.com/microsoft/LightGBM/pull/3872#issuecomment-804087682.
I believe that adding archives with repo source code to artifacts that we produce for each commit in `master` is pointless, so I'm not adding `PublishBuildArtifacts@1` step for archives.
> [ci] attach archives with complete source code of the repo to releases

- .github/workflows/cuda.yml
Why switch to NVIDIA NGC? Due to #3518.
> [ci] bump CUDA version and pull dockers from NVIDIA NGC

- tests/python_package_test/test_dask.py
This modifies the `dataframe-with-categorical` output type to create only two categorical features and makes one of them informative for the task. 
In order to have more consistent results I've modified the `_create_data` function to generate 1,000 samples instead of 100, which caused problems with categoricals and reduced the accuracy of the distributed training. Also, for regression 100 features were being generated, I changed this to generate only 4, with 2 informative.
Adding more samples allows the tolerances in the array checks to be lower, but I had to increase a bit the complexity of the models for `test_regressor` and `test_classifier`.
I didn't change anything in `_create_ranking_data` because I haven't seen problems with those tests, but could take a look as well.
> [tests][dask] Create an informative categorical feature

- tests/cpp_test/test_chunked_array.cpp
This should fix the remaining cpplint issues in test_chunked_array.
This also cleans up a bit the last test.
Requested by @StrikerRUS in https://github.com/microsoft/LightGBM/pull/4092.
> Update test_chunked_array to please cpplint

- docs/Installation-Guide.rst
This reverts commit f2632a6e1eb1088ea3f462724e61d70f7131c784.
Refer to https://github.com/microsoft/LightGBM/pull/3872#issuecomment-806252148.
Hope this is temporarily.
But right now our installation guide suggests to install outdated version of LightGBM via Homebrew.
> [docs] remove macOS installation method with Homebrew formula 

- tests/python_package_test/test_dask.py
Save CI time.
I think these tests are for specific network params and we don't test something principally new by feeding different data types.
> [ci] remove output parametrization from two Dask tests

- docker/dockerfile-python
While trying to run LightGBM via the Dockerfile (dockerfile-python) there was a below issue saying 'curl not found' while trying to run the curl command, as curl lib was not added as part of the installation package lists. So I have added the curl lib as part of the docker installation.
```/bin/sh: 1: curl: not found```
```The command '/bin/sh -c apt-get update &&     apt-get install -y --no-install-recommends         ca-certificates         cmake         build-essential         gcc         g++         git &&     curl -sL https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o conda.sh &&     /bin/bash conda.sh -f -b -p $CONDA_DIR &&     export PATH="$CONDA_DIR/bin:$PATH" &&     conda config --set always_yes yes --set changeps1 no &&     conda install -q -y numpy scipy …
```
> [ci] Added curl library to the installed packages list inside dockerfile-python installation

- docs/Installation-Guide.rst
- docs/Parameters.rst
- include/LightGBM/config.h
> [docs] add missed CUDA device type in docs

- python-package/lightgbm/dask.py
This PR resolves a critical source of instability in `lightgbm.dask`, which I think might be the cause of some of the issues we have observed sporadically in tests (#4057, #4074, #4099).
* specifies arguments in `lightgbm.dask`'s use of [`distributed.Client.submit()`](https://distributed.dask.org/en/latest/api.html#distributed.Client.submit) to more tightly control how Dask schedules LightGBM training tasks
I believe this PR will fix a critical source of instability that can cause training to fail (either throwing an error or hanging indefinitely) if multiple training tasks are accidentally scheduled onto the same worker. I think that the risk of this issue increases as you have more workers in the Dask cluster and as there is more other work going on in the cluster alongside LightGBM …
> [dask] run one training task on each worker

- tests/python_package_test/test_dask.py
This includes all boosting types (gbdt, rf, goss, dart) in `test_classifier`, `test_regressor` and `test_ranker`
> [tests][dask] test all boosting types (fixes #3896)

- python-package/lightgbm/dask.py
There is no `is_deterministic` param, only `deterministic`: https://lightgbm.readthedocs.io/en/latest/Parameters.html#deterministic.
> [docs] fix param name typo in comments
