microsoft/LightGBM

.github/workflows/r_configure.yml, .github/workflows/triggering_comments.yml, R-package/README.md
Closed #3283.
Refer to https://github.com/microsoft/LightGBM/pull/4117#pullrequestreview-622620015 for the initial discussion.
Refer to https://github.com/StrikerRUS/LightGBM/pull/1 for the usage example.
~Push from a workflow won't trigger our regular workflows:~
> ~For example, if a workflow run pushes code using the repository's `GITHUB_TOKEN`, a new workflow will not run even when the repository contains a workflow configured to run when `push` events occur.~
~https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token~
~I don't think that this a problem for us, because anyway we need a follow-up commit with reverting back to `~~VERSION~~` in `configure.ac`, right?~
=> [ci] use GitHub Actions to re-generate R configure

python-package/lightgbm/dask.py, tests/python_package_test/test_dask.py
* if using training with "search for random ports" strategy (documented in https://lightgbm.readthedocs.io/en/latest/Parallel-Learning-Guide.html#using-specific-ports), `lightgbm.dask.` will now check for the situation where it found duplicate `IP-port` pairs. If such duplicates are found, `lightgbm.dask` will re-run the random search up to 10 times.
https://github.com/microsoft/LightGBM/issues/4057 documents a class of error that can fail with distributed training using `lightgbm.dask`. If you do not provide `machines` or `local_listen_port` at training time, LightGBM will randomly search for ports to use on each worker.
To limit the overhead introduced by this random search, a function `_find_random_open_port()` is run once at the same time on every worker, using …
=> [dask] make random port search more resilient to random collisions (fixes #4057)

tests/python_package_test/test_dask.py
Reference: https://github.com/scikit-learn/scikit-learn/blob/95119c13af77c76e150b753485c662b7c52a41a2/sklearn/metrics/_regression.py#L693-L694
=> [tests][dask] use dy_true mean in denominator for _r2_score

docs/GPU-Targets.rst, src/treelearner/linear_tree_learner.cpp, src/treelearner/serial_tree_learner.cpp
`*TreeLearner::Train()` methods have a DEBUG-level log like this:
```text
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 6
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 7
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 8
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 8
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 7
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 8
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 7
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 9
```
This message is saying "ok, …
=> clarify DEBUG-level log about tree depth

.ci/setup.sh, .ci/test_r_package.sh
As documented in #4160, LightGBM's macOS jobs for the R package started failing two days ago, roughly around the same time as the version of `basictex` was updated at https://github.com/Homebrew/homebrew-cask/pull/103001.
I was going to file a bug report with Homebrew, and in that process I was directed to that project's "how to report bugs" guidelines: https://github.com/Homebrew/homebrew-cask#reporting-bugs. That includes the suggestion that you should run `brew update-reset && brew update`. After trying that on my Mac, I was then able to `brew install --cask basictex`.
This PR proposes adding a similar to step to LightGBM's CI. This is similar to how this project uses `sudo apt-get update` to update repository information for the `apt` package manager on Linux jobs.
* `brew …
=> [ci] run 'brew update' in macOS jobs (fixes #4160)

tests/python_package_test/test_dask.py
This replaces the client fixture (which creates and tears down a `LocalCluster` for every test) with a cluster fixture that creates a cluster once for all the tests and then every test creates a client based on it. This reduces the time it takes for `test_dask` to run significantly.
I replaced all the `client.close(timeout=CLIENT_CLOSE_TIMEOUT)` with a context manager for the `client`, so the diff seems awful but there's an option to hide whitespace changes in github which can be toggled in the little gears when reviewing the files. If this is too much I can just add a `client = Client(cluster)` at the top of every test instead, but I thought it'd be nice to unify all the tests to use this context manager.
I modified `test_errors` to use a regular cluster (instead of the async one) as …
=> [tests][dask] replace client fixture with cluster fixture

docs/Installation-Guide.rst
Refer to https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/.
> May 1st, 2021 | Bintray services will no longer be available.
=> [docs] update link to Boost binaries

.ci/test.sh, docs/requirements.txt
Recently updated ~Doxygen at `conda-forge`~ results in the following error
```
Warning, treated as error:
/home/runner/work/LightGBM/LightGBM/docs/C-API.rst:2:Unparseable C cross-reference: '[out]'
Invalid C declaration: Expected identifier in nested name. [error at 0]
[out]
^
make: *** [Makefile:20: html] Error 2
```
I guess that this is actually `breathe` issue.
**UPD:** Well, the root cause was updated breathe, not Doxygen.
=> [ci] Restrict breathe version at CI

.nuget/create_nuget.py, docs/conf.py
=> Migrated to f-strings for .\.nuget\create_nuget.py  #4136

src/io/dataset.cpp
These fields are saved to binary file. Currently they are uninitialized and (maybe) not used.
Undefined Behavior Sanitizer will complain about assigning to bool variables (`use_missing_`, `zero_as_missing_`) whose value is not 0 or 1 in `DatasetLoader::LoadFromBinFile`.
=> fix: Dataset::CreateValid init fields which saves to binary.

swig/StringArray_API_extensions.i
A SWIG wrapper for a `LGBM_DatasetGetFeatureNames` C API call. There is a similar `LGBM_BoosterGetFeatureNames` already implemented, and this PR just makes it available for another type of handle.
When implementing `LGBM_DatasetGetFeatureNames` call in [lightgbm4j](https://github.com/metarank/lightgbm4j) we found an interesting corner case in the C API, which happens between C <-> JDK:
* we need to preallocate an array of strings for feature names (with a properly-sized per name buffer) to call `LGBM_DatasetGetFeatureNames` method
* it's doable from JVM side, so you can technically call `LGBM_DatasetGetFeatureNames` and call it a day (see the example below).
* but `LGBM_DatasetGetFeatureNames` call writes directly to the char[] buffer of the string, which makes JVM a bit surprised, as
* …
=> [swig] add wrapper for LGBM_DatasetGetFeatureNames

.ci/setup.sh
This reverts commit ab474dc4035416ef512961ea14595a729b55e1ef.
Refer to #4104.
Closed #4106.
=> [ci] unpin CMake version for CUDA + Clang toolchain

R-package/README.md
There are a few examples in the R-package documentation which rely on the use of Docker containers. These involve mounting in the current working directory, and then running `cd` to change directories to that location.
This PR proposes a minor change to remove that manual use of `cd`, just to make those examples slightly easier to use.
```shell
docker run \
-v $(pwd):/opt/LightGBM \
-it ubuntu:latest \
cd /opt/LightGBM && do-something
docker run \
-v $(pwd):/opt/LightGBM \
-w /opt/LightGBM \
-it ubuntu:latest \
do-something
```
=> [docs] add working dir to R package docker run examples

R-package/R/lgb.importance.R
Feature importances are returned as invisible. I don't get why would anyone want them invisible. This PR fixes it.
=> [R-package] Make returned feature importances from lgb.importance() visible by default

R-package/R/lgb.cv.R, R-package/R/lgb.train.R, R-package/R/lightgbm.R, R-package/man/lgb.cv.Rd, R-package/man/lgb.train.Rd, R-package/man/lightgbm.Rd
Hi @jameslamb 
Here is the PR related to the issue #4192. Please check out the update!
Best,
Issac
=> [docs][R-package] Update the explanation of num_threads (fixes #4192)

python-package/lightgbm/sklearn.py
Switches some string formatting in `sklearn.py` to use f-strings, as part of #4136.
=> [python] Migrate to f-strings in python-package/lightgbm/sklearn.py

R-package/R/lgb.Dataset.R, R-package/R/lgb.train.R, R-package/R/lightgbm.R, R-package/R/saveRDS.lgb.Booster.R, R-package/man/lgb.Dataset.Rd, R-package/man/lgb.cv.Rd, R-package/man/lgb.train.Rd, R-package/man/lgb_shared_params.Rd, R-package/man/lightgbm.Rd, R-package/man/saveRDS.lgb.Booster.Rd
This PR proposes some clarifications in the R documentation, based on the feedback in #4193.
Pushing to the branch  `docs/jlamb` so we can check the rendered docs on readthedocs.
=> [R-package] clarify parameter documentation (fixes #4193)

python-package/lightgbm/dask.py
Fixes typo in dask _train as mentioned in [this comment](https://github.com/microsoft/LightGBM/pull/4101#discussion_r616275252).
=> [dask] Fix typo mentioned in 4101

src/treelearner/data_parallel_tree_learner.cpp, src/treelearner/voting_parallel_tree_learner.cpp
In data distributed learning (including both `data` and `voting` modes), when the value distribution of a feature differs too much across machines (for example, two machines have totally nonoverlapped ranges of the same feature), there can be a leaf which contains 0 local data on a machine during training.
(Note that this happens more easily when `pre_partition=true`. With `pre_partition=false`, the data partition will be random and feature value distributions across machines are likely to be similar.)
In that case, the histogram buffers of that leaf won't be cleared because the `ConstructHistograms` method in `Dataset` will simply exit.
https://github.com/microsoft/LightGBM/blob/6ad3e6e9e306d3657a0a3d0201862d1f471b2a5e/include/LightGBM/dataset.h#L470-L478
Thus the histogram clear code in …
=> [fix] Fix bug in data distributed learning with local empty leaf

docs/Installation-Guide.rst
The "Link Checks" job is currently failing with the following error.
```text
URL        `https://www.microsoft.com/en-us/download/details.aspx?id=100593'
Name       `MS MPI'
Parent URL file:///home/runner/work/LightGBM/LightGBM/docs/_build/html/Installation-Guide.html, line 596, col 28
Real URL   https://www.microsoft.com/en-us/download/404Error.aspx
Check time 1.069 seconds
Size       92.45KB
Info       Redirected to
`https://www.microsoft.com/en-us/download/404Error.aspx'.
```
Most recent build was 10 hours ago: https://github.com/microsoft/LightGBM/actions/runs/782291613
I see that broken download links have also been reported in the MS MPI repo: https://github.com/microsoft/Microsoft-MPI/issues/54
This PR proposes linking to [the official release notes …
=> [docs] fix broken MS MPI link in Installation Guide

R-package/tests/testthat/test_basic.R
This PR addresses several (but not all) of the R unit test warnings documented in #4108.
**`Unknown parameter: valids / {memory_address}`**
```text
[LightGBM] [Warning] Unknown parameter: 0x7fb4ee5c84d8>
[LightGBM] [Warning] Unknown parameter: valids
```
These warnings were caused by calls that were passing `valids` to `lgb.cv()`.
`lgb.cv()` does not accept validation data...it creates holdout sets using k-fold cross-validation.
This is an example of something that is currently a warning which would be an error if `...`
was not allowed (https://github.com/microsoft/LightGBM/pull/4202#discussion_r616075433, ~will write up a feature request soon~ https://github.com/microsoft/LightGBM/issues/4226).
**`Unknown parameter: categorical_features`**
```text
[LightGBM] [Warning] Unknown parameter: …
```
=> [R-package] fix warnings in unit tests

tests/python_package_test/test_dual.py
This PR removes an unused import in tests, found with `flake8 --ignore=E501,W503 tests/`:
```text
tests/python_package_test/test_dual.py:6:1: F401 'numpy as np' imported but unused
```
=> [ci] [python-package] remove unused import in tests

R-package/R/lgb.cv.R, R-package/R/lgb.train.R, R-package/R/utils.R
This PR fixes a bug where the R package can produce misleading warnings when using `interaction_constraints`.
> [LightGBM] [Warning] Unknown parameter: 2,3
Fixes #4108
Today, using interaction constraints in the R package can lead to an unavoidable and misleading warning.
```r
library(nycflights13)
data(flights)
dtrain <- lgb.Dataset(
data = as.matrix(flights[, c("month", "day", "dep_time")])
, label = flights[["dep_delay"]]
)
bst <- lgb.train(
data = dtrain
, params = list(
objective = "regression"
, interaction_constraints = list(c(1L, 2L), 3L)
, learning_rate = 0.01
)
, nrounds = 10L
, verbose = 1L
, valids = list(
"train" = dtrain
)
)
```
> [LightGBM] [Warning] Unknown parameter: 2,3
> [LightGBM] [Warning] Unknown parameter: 2,3
This comes from here …
=> [R-package] avoid misleading warnings when using interaction constraints (fixes #4108)

src/network/socket_wrapper.hpp
Today in LightGBM, when `send`, `receive`, or `accept` operations fail in socket-based distributed training, a FATAL-level log message is printed with the integer code for that error.
* Windows codes: https://docs.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2
* non-Windows: https://www-numi.fnal.gov/offline_software/srt_public_context/WebDocs/Errors/unix_system_errors.html
For example, you might get a message like those that have been showing up in the Dask tests (#4074, #4116)
> lightgbm.basic.LightGBMError: Socket recv error, code: 104
This PR proposes changing those log messages to include the corresponding error text. Using the reproducible example from https://github.com/microsoft/LightGBM/issues/4074#issuecomment-808578600, for example, you can see that …
=> show specific error message in TCP accept/send/receive logs

.ci/setup.sh, .ci/test.sh
Fixed #4204.
`graphviz` cannot be installed from the default conda channel with Python 3.9:
```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:
Specifications:
- python-graphviz -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0']
Your python: python=3.9
If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
The following specifications were found to be incompatible …
```
=> [ci] Install graphviz system-widely

R-package/R/lgb.Booster.R, R-package/R/lgb.Dataset.R, R-package/R/lgb.Predictor.R, R-package/src/lightgbm_R.cpp, R-package/src/lightgbm_R.h, R-package/tests/testthat/test_dataset.R, build_r.R
This is another step towards #3016.
As of #4155 and #4163, the R package use `.Call()` to call routines from the C++ library. Currently, an integer called `call_state` is initialized on the R side before each such call, its value is manipulated during the call, and its value is returned by each call. Initializing this integer and passing it around is unnecessary, because nothing is done with it on the R side after the call completes. All uses of `.Call()` in the R package (except in calls to `LGBM_GetLastError_R`) modify their inputs by reference and do not return anything.
This PR proposes simplifying the R package and removing unnecessary memory usage and computation by removing the `call_state` concept. Instead, the functions defined in …
=> [R-package] remove pre-allocated call_state in C++ calls

R-package/R/utils.R, R-package/src/lightgbm_R.cpp, R-package/src/lightgbm_R.h, build_r.R
This is a small step towards #3016. This PR proposes converting `LGBM_GetLastError_R` (and the R function that calls it, `lgb.last_error()`) to use R's built-in types instead of the custom type defined in https://github.com/microsoft/LightGBM/blob/91f72e2a8c8b1e5433d30d3891923b3a067402a6/R-package/src/R_object_helper.h.
~This PR is not dependent on #4155.~ #4155 has been merged to `master` and this PR has been updated with it.
You can see the following to learn about the `SEXP`type.
* usage:
- https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Handling-R-objects-in-C
- https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Garbage-Collection
- https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Allocating-storage
- …
=> [R-package] Convert LGBM_GetLastError_R to use R built-in types

R-package/src/R_object_helper.h, R-package/src/lightgbm_R.h
Another small steps towards #3016 (removing `R-package/src/R_object_helper.h`).
Today, to use things from `Rinternals.h`, the code in `lightgbm_R.h` includes `R_object_helper.h` which includes `Rinternals.h`.
This proposes moving that `#include` of `Rinternals.h` into `lightgbm_R.h`, the first place it is needed.
=> [R-package] move Rinternals.h closer to where it is used

R-package/src/R_object_helper.h, R-package/src/lightgbm_R.cpp, R-package/src/lightgbm_R.h
This is another step towards #3016. It proposed using R's standard interface to handle integers passed into the C++ side (for things like array size, buffer size, number of iterations, etc.).
Changes in this PR:
* use R builtin `SEXP` type for any arguments passed from R to C++ that should be read-only integers
* use R builtin `Rf_asInteger()` to convert those SEXP objects to ints (replacing LightGBM's `R_AS_INT`)
* fix minor inconsistencies between `lightgbm_R.h` and `lightgbm_R.cpp` (e.g. parameter named `nrow` in the header file and `num_row` in the implementation)
There is not a scalar integer type in R. When you run some code like `x <- 1L`, R creates a length-one **array** (referred to in R as a "vector").
To treat such data as an integer, instead of an integer array, in C/C++, it's …
=> [R-package] use R standard routine to access read-only ints passed to C++

R-package/src/R_object_helper.h, R-package/src/lightgbm_R.cpp, R-package/src/lightgbm_R.h, R-package/tests/testthat/test_basic.R
Another step towards #3016.
Fixes #4216.
Changes in this PR:
* removes LightGBM-custom pointers to R data (`R_REAL_PTR()`, `R_INT_PTR()`) with the standard equivalents from `Rinternals.h` (`REAL()`, `INTEGER()`)
* converts arguments on the C++ side that are accessed that way from `LGBM_SE` to `SEXP`
R is a dynamically-typed language. You can run code like `x <- c(1, 2, 3)` without declaring that `x` is a numeric array, and R will just figure it out.
R makes this possible by storing data for an object in a structure called a `SEXPREC`. That structure will contain different data based on the R class (integer, character, function, etc.). Libraries can reference that data in C code using a type, `SEXP`, provided by `Rinternals.h`. Libraries can also get a pointer to a particular type of data …
=> [R-package] Use R standard routines to access numeric and integer array data in C++

R-package/R/lgb.Booster.R, R-package/R/lgb.Dataset.R, R-package/R/lgb.Predictor.R, R-package/R/utils.R, R-package/src/lightgbm_R.cpp, R-package/src/lightgbm_R.h, R-package/tests/testthat/test_utils.R
=> [R-package] Use R standard routines to access character data in C++

src/boosting/gbdt.h, src/treelearner/gpu_tree_learner.h
Correction of #4250.
`hessians` here is a param name (`const score_t* hessians`) and should be written from a small letter.
=> fix param name

python-package/lightgbm/engine.py
=> [python] added f-strings to python-package/lightgbm/engine.py

R-package/src/lightgbm_R.h
There have been several changes to the R package's C++ interface recently, in works towards #3016.
As a result of those changes (and other changes before), the documentation comments in `R-package/src/lightgbm_R.h` contain some inconsistencies, typos, and other small issues. For example, as of #4244 most of the functions there return an R NULL value, but their docs still say they return an integer indicating whether they succeeded or failed.
This PR proposes fixing them.
I intentionally skipped the four functions modified in #4256, since that PR changes those functions' signatures and docs.
=> [docs][R-package] update docs on C++ interface

R-package/R/lgb.Booster.R, R-package/R/lgb.Dataset.R, R-package/R/utils.R, R-package/src/R_object_helper.h, R-package/src/lightgbm_R.cpp, R-package/src/lightgbm_R.h, R-package/tests/testthat/test_dataset.R, R-package/tests/testthat/test_lgb.Booster.R, R-package/tests/testthat/test_utils.R
Another step towards #3016.
Resolves https://github.com/microsoft/LightGBM/pull/4155#discussion_r623899919.
This PR affects the following functions that return an R character vector:
* `LGBM_DatasetGetFeatureNames_R()`
* `LGBM_BoosterGetEvalNames_R()`
* `LGBM_BoosterSaveModelToString_R()`
* `LGBM_BoosterDumpModel_R()`
Currently, a buffer and an R character vector are allocated on the R side, then the corresponding C++ functions are called to write model data to that buffer and, eventually, copy it into that character vector.
This PR proposes simplifying that interaction by just creating that character vector from the C++ side and returning it to R. This has the following benefits:
* eliminates some unnecessary computation, like joining all eval names into one tab-separated string and then …
=> [R-package] move creation of character vectors in some methods to C++ side

R-package/R/lgb.Booster.R, R-package/R/lgb.cv.R, R-package/README.md, R-package/man/lgb.load.Rd, R-package/src/lightgbm_R.cpp, include/LightGBM/network.h, src/boosting/gbdt.h, src/io/dataset_loader.cpp, src/treelearner/monotone_constraints.hpp
This PR fixes a few places with unnecessary extra spaces in comments, docs, or log messages. Just some minor cleanup that might slightly help with actions like searching for things using `git grep` or `grep -R`.
=> [docs] remove extra spaces in comments and docs

include/LightGBM/c_api.h, python-package/lightgbm/basic.py
Fixes #4264 .
This PR updates the docs on `LGBM_BoosterGetEvalNames` and `LGBM_BoosterGetEvalCounts` to clarify that those functions refer to evaluation *metrics*, not validation datasets.
=> [docs] clarify docs for LGBM_BoosterGetEvalNames and LGBM_BoosterGetEvalCounts (fixes #4264)

python-package/lightgbm/plotting.py
=> Migrate to f-strings in python-package\lightgbm\plotting.py (#4136)

.ci/test.sh
This PR is a temporary fix to unblock continuous integration jobs in this project, which are currently blocked by https://github.com/microsoft/LightGBM/issues/4285.
=> [ci] pin dask and distributed in CI jobs

R-package/src/lightgbm_R.cpp
Fix compilation warnings like the following one
```
C:\Users\runneradmin\RtmpMzXGiG\R.INSTALL11384d93526b\lightgbm\src\src\lightgbm_R.cpp(670,3): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [C:\Users\runneradmin\RtmpMzXGiG\R.INSTALL11384d93526b\lightgbm\src\build\_lightgbm.vcxproj]
```
Checked all `Rf_asInteger` and `INTEGER` calls and tried to bring data types in the consistency with original ones from 
https://github.com/microsoft/LightGBM/blob/master/include/LightGBM/c_api.h.
=> [R-package] Handle integer types more accurate in R-to-C interface

CMakeLists.txt
Set property `CUDA_ARCHITECTURES` would fix the warnings reported by CMake 3.20.x
=> [CUDA] Add CUDA_ARCHITECTURES to fix CMake warnings (#3754)

tests/c_api_test/test_.py
I am improving the python code to the fstring format for the file tests/c_apo_test/test.py 
I am trying to contribute to the issue #4136
@jameslamb
=> [python] Improving the syntax of the f-strings in the file: tests/c_api_test/test.py

python-package/lightgbm/basic.py
The same as for R-package in #4291.
Match function signatures from https://github.com/microsoft/LightGBM/blob/master/include/LightGBM/c_api.h.
=> [python] Handle integer types more accurate in Python-to-C interface

src/objective/regression_objective.hpp
This PR replaces `/ exp(x)` by `* exp(-x)` in the Gamma deviance objective.
It was a finding in #4283.
=> Replace division of exponential in Gamma loss

docs/Parallel-Learning-Guide.rst
The most recent `link checks` job failed.
```text
URL        `https://github.com/Azure/mmlspark/blob/master/notebooks/samples/LightGBM%20-%20Quantile%20Regression%20for%20Drug%20Discovery.ipynb'
Name       `this MMLSpark example'
Parent URL file:///home/runner/work/LightGBM/LightGBM/docs/_build/html/Parallel-Learning-Guide.html, line 273, col 8
Real URL   https://github.com/Azure/mmlspark/blob/master/notebooks/samples/LightGBM%20-%20Quantile%20Regression%20for%20Drug%20Discovery.ipynb
Check time 0.464 seconds
```
reference: https://github.com/microsoft/LightGBM/runs/2618067011?check_suite_focus=true
Seems that `mmlspark` removed their LightGBM Quantile Regression example yesterday. See https://github.com/Azure/mmlspark/pull/1043.
This PR proposes updating …
=> [docs] replace broken mmlspark notebook link in docs

tests/c_api_test/test_.py
Linking #4292.
Match function signatures from https://github.com/microsoft/LightGBM/blob/master/include/LightGBM/c_api.h.
=> [tests][python] Handle data types more accurate in C API test

examples/python-guide/plot_example.py, python-package/lightgbm/basic.py, python-package/lightgbm/plotting.py, python-package/lightgbm/sklearn.py
Based on #4302.
It turned out that some users don't know that python cannot find packages installed during the current session by default. So it will be good to tell them about this fact in error messages.
=> [python] improve error message for required packages

python-package/lightgbm/sklearn.py
=> [docs][python] fix LGBMRanker docstring

python-package/lightgbm/basic.py, tests/python_package_test/test_basic.py
Refer to https://github.com/microsoft/LightGBM/pull/4256#discussion_r628743652.
=> [python] handle arbitrary length feature names in Python-package

src/treelearner/feature_histogram.hpp
This is to fix #4286. In `GatherInfoForThresholdNumerical `, since it is calculating the right sum statistics, it should break when `static_cast<uint32_t>(t + offset) <= threshold` instead of `static_cast<uint32_t>(t + offset) < threshold`. Because data with bin value `<= threshold` are split into the left child node.
=> [fix] fix GatherInfoForThresholdNumerical boundary (fix #4286)

.vsts-ci.yml
`120` is too close to values reported in https://github.com/microsoft/LightGBM/pull/3996#issuecomment-845068961 and can sometimes be not enough to finish all tests (for example, here https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=10157&view=logs&j=c2f9361f-3c13-57db-3206-cee89820d5e3). Sorry, I had to think about this in #3996.
=> [ci] Increase timeout value for QEMU builds

cmake/Sanitizer.cmake, cmake/modules/FindASan.cmake, cmake/modules/FindLSan.cmake, cmake/modules/FindTSan.cmake, cmake/modules/FindUBSan.cmake
Adding compiler flag will automatically link to the required libraries.
Besides, clang static links to sanitizer libraries by default. Thus linking to dynamic library must be removed in order to use clang.
For reference:
- [Difference of AddressSanitizer in Clang and GCC](https://github.com/google/sanitizers/wiki/AddressSanitizerClangVsGCC-(5.0-vs-7.1))
- [StackOverflow answer](https://stackoverflow.com/a/40215639/306935) about `-lasan` option has been discouraged. It directs to mailing list answer by ASan developer
- [LeakSanitizer doc](https://github.com/google/sanitizers/wiki/AddressSanitizerLeakSanitizer#stand-alone-mode) mentions that standalone mode can work without the slowdown of ASan. This mode will link to "a runtime library containing just the bare necessities required for …
=> [ci] cmake: remove linking to sanitizer library

src/io/bin.cpp
As described in https://github.com/microsoft/LightGBM/issues/4301#issuecomment-848622040, this is to fix #4301 by skipping the empty bins when calculating cnt_in_bin in `BinMapper::FindBin`. So that we can correctly decides the `most_freq_bin_`.
=> [fix] skip empty bins when calculating cnt_in_bin in BinMapper::FindBin (fix #4301)

include/LightGBM/tree.h, src/io/tree.cpp, tests/python_package_test/test_basic.py, tests/python_package_test/test_engine.py
As requested here: https://github.com/microsoft/LightGBM/pull/3299#issuecomment-821039568
=> Add linear leaf models to json output (fixes #4186)

R-package/R/utils.R
While starting to work on adding a deprecation warning for uses of `...` in the R package (as part of #4310), I found some unused code that I think can be removed.
`lgb.params2str()`, an internal-only utility function, is only ever called with the single keyword argument `params`.
This PR proposes removing `...` from that function's signature.
Contributes to #4226
=> [R-package] remove unused code in lgb.params2str()

R-package/R/lgb.Booster.R, R-package/R/lgb.Predictor.R, R-package/R/lgb.train.R
Contributes to #4226
This PR proposes removing the use of `...` from the constructor for the `Predictor` class in the R package. That class is not exported in the package's namespace, so this is not a user-facing breaking change.
Removing this use of `...` makes the package's code slightly stricter, which reduces the risk of bugs.
=> [R-package] remove uses of ... in Predictor constructor

R-package/R/callback.R
Noticed tonight that the function returned by `cb.early.stop()` has an argument `finalize = FALSE`.
That argument's value is never referenced, and no existing code expects to pass it. This PR proposes removing it.
The places where callbacks are executed only pass a single argument, `env`:
https://github.com/microsoft/LightGBM/blob/28c3c45d3be82f115630c4a887a0cf5e611ef5e0/R-package/R/lgb.train.R#L288-L290
https://github.com/microsoft/LightGBM/blob/28c3c45d3be82f115630c4a887a0cf5e611ef5e0/R-package/R/lgb.train.R#L329-L331
https://github.com/microsoft/LightGBM/blob/28c3c45d3be82f115630c4a887a0cf5e611ef5e0/R-package/R/lgb.cv.R#L367-L369
https://github.com/microsoft/LightGBM/blob/28c3c45d3be82f115630c4a887a0cf5e611ef5e0/R-package/R/lgb.cv.R#L393-L395
I'm also confident in this change because …
=> [R-package] remove unused argument in early stopping callback

R-package/R/utils.R, R-package/src/lightgbm_R.cpp, R-package/src/lightgbm_R.h, R-package/tests/testthat/test_utils.R, build_r.R
It seems that #4163 removed the last uses of the internal helper function `lgb.last_error()` in the R package. This PR proposes removing that function and its C++ counterpart, `LGBM_GetLastError_R()`. It's no longer necessary for the R package to reach into the C++ side and get the last error, since as of #4163 and other refactoring, C++ calls will raise R errors whenever one is thrown.
https://github.com/microsoft/LightGBM/blob/28c3c45d3be82f115630c4a887a0cf5e611ef5e0/R-package/src/lightgbm_R.cpp#L36-L38
Removing this code should have all the usual benefits of removing unused code...faster compilation, smaller library size, reduced maintenance burden, etc.
=> [R-package] remove lgb.last_error() and LGBM_GetLastError_R()

R-package/R/lgb.Booster.R, R-package/R/lgb.Dataset.R, R-package/R/utils.R, R-package/tests/testthat/test_utils.R
The R package has many places where it needs to check that an object is a special LightGBM R6 class (`lgb.Booster`, `lgb.Dataset`, or `lgb.Predictor`). Today, it is inconsistent in the way that it does this. Some code uses special functions like `lgb.is.Booster()` which call a one-line utility function `lgb.check.r6.class()`. Other code calls `lgb.check.r6.class()`.
This code proposes factoring out `lgb.check.r6.class()` completely. I think this has the following benefits:
* removes a layer of indirection / opportunity for inconsistency
* makes the code easier to read and understand
```r
if (!lgb.check.r6.class(object = train_set, name = "lgb.Dataset"))
if (!lgb.is.Dataset(train_set))
```
Since what `lgb.check.r6.class()` does is so simple, I think that the added indirection it introduces …
=> [R-package] factor out lgb.check.r6.class()

R-package/tests/testthat/test_dataset.R
This PR resolves the following warning in the R package's tests, which was probably introduced in #4265
> Warning message:
In is.na(handle) :
is.na() applied to non-(list or vector) of type 'externalptr'
=> [R-package] resolve test warning about is.na() and handles

examples/python-guide/logistic_regression.py
This PR contributes to issue #4136 .
I've updated the file as I stated in https://github.com/microsoft/LightGBM/issues/4136#issuecomment-856897054.
In this PR I have updated the file `.\examples\python-guide\logistic_regression.py` where I have updated 4 lines of code with the f-string format.
I have previously updated 2 lines and updated two lines after your feedback @jameslamb.
Do let me know if there's an issue. Thank You.
=> [python-package] use f-strings for concatenation in examples/python-guide/logistic_regression.py

R-package/tests/testthat/test_dataset.R
This PR proposes removing two unnecessary `library()` calls in the R package's tests. Using `{testthat}`, it's rarely necessary to call `library()` for dependencies from inside test scripts.
I thought it was fun and interesting to note that the two calls removed in this PR have been there since the very first PR that introduced the R package!
#168 (January 2017)
=> [R-package] remove unnecessary library() calls in tests

R-package/R/callback.R, R-package/R/lgb.cv.R
The bug discovered in #4360 was missed for a long time because `lgb.cv()` relied on an internal function which set a default for a keyword argument. That default meant that it was possible for a bug of the form "an argument from `lgb.cv()` is not being passed through to this internal function" was possible.
This PR proposes removing other defaults in internal functions, to prevent similar issues in the future. I did not find any cases where the functions changed in this PR were being called without an explicit value for every keyword argument, so this is just defensive and should not change any current behavior for users.
=> [R-package] remove defaults in internal functions

docs/Installation-Guide.rst
This anchor will allow to provide more "direct" link for artifacts downloading.
https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#nightly-builds
Users will be able to faster find badge they need to click on.
=> [docs] add anchor for nightly builds in docs

R-package/R/lgb.cv.R, R-package/man/lgb.cv.Rd, R-package/tests/testthat/test_basic.R
`lgb.cv()` in the R package performs k-fold cross-validation, and can optionally compute the standard deviation of evaluation metrics across all folds. This option is controlled by the argument `showsd` (default TRUE).
Today, even when `showsd = FALSE`, an internal function called by `lgb.cv()` still calculates error standard deviations and then `lgb.cv()` just ignores them.
https://github.com/microsoft/LightGBM/blob/9143003df6eb1a17b6e697159c3c870d5a5e7219/R-package/R/lgb.cv.R#L388-L390
This PR proposes a fix that avoids this unnecessary work, which should slightly speed up `lgb.cv()` for users who are not interested in the standard deviation of error estimates. It also introduces a test confirming that the output format of `lgb.cv()` changes based on the value of the `showsd` argument.
=> [R-package] avoid unnecessary computation of std deviations in lgb.cv()

R-package/R/lgb.Booster.R, R-package/R/lgb.Dataset.R, R-package/R/lgb.Predictor.R, R-package/src/lightgbm_R.cpp, R-package/tests/testthat/test_Predictor.R, R-package/tests/testthat/test_basic.R, R-package/tests/testthat/test_dataset.R, R-package/tests/testthat/test_lgb.Booster.R
Contributes to #4282 (fixing memory leaks in the R package). Specifically, this addresses the following comment from that issue:
> Functions that return an R external pointer are wrapped into R6 classes, with the finalizer for the external pointer being under the R6 finalizer. If an error occurs during initialization (when calling `Class$new(...)`, like it is done when creating a dataset), the finalizer will not be called, thus leaking the C++ object (e.g. a dataset or a model). This could be solved by setting the finalizer in the R external pointer object itself.
From https://cran.r-project.org/doc/manuals/r-release/R-exts.html#External-pointers-and-weak-references:
> An external pointer object can have a *finalizer*, a piece of code to be run when the object is garbage collected. This …
=> [R-package] move more finalizer logic into C++ side to address memory leaks

docs/Development-Guide.rst, docs/Installation-Guide.rst
Refer to https://xgboost.readthedocs.io/en/latest/contrib/unit_tests.html#sanitizers-detect-memory-errors-and-data-races, #3555, #4330.
=> [docs] document sanitizers

python-package/lightgbm/dask.py
Addresses #4375 - removes `Dask DataFrame` type option for DaskLGBM estimators' `group`, `init_score`, and `sample_weights` parameters. These must be 1-d distributed vectors, cannot be 2-d.
To be honest I was kind of torn grammatically between "`Dask Array or Dask Series or None, optional (default=None)`" and "`Dask Array, Dask Series, or None, optional (default=None)`". Welcome an opinion on this!
=> [dask] Dask Vector types for group, init_score, sample_weights (fixes #4375)

tests/python_package_test/test_engine.py
Avoid unnecessary trainset generation.
=> [tests] replace pytest.parametrize

R-package/R/lgb.Dataset.R
As part of adding a deprecation warning about the removal of `...` support in the R package (per https://github.com/microsoft/LightGBM/issues/4226#issuecomment-829473584), I wanted to be able to give different warnings in items passed through `...` in `lgb.Dataset()` based on whether they are params (e.g. `max_bin`) or "info" elements (e.g. `init_score`).
I realized that there are three duplicate places where the R package stores the list of valid keys for "info".
This PR proposes consolidating them into a single place, to reduce the risk of inconsistencies and simplify the code a bit.
=> [R-package] consolidate duplicate lists of Dataset info keys

include/LightGBM/utils/random.h
This is to fix #4134. Currently, when `K=1`, it is impossible for the `Sample` function to sample the last element. Add a separate case for `K=1`.
=> [fix] fix Sample when sampling only one element (fix #4134)

python-package/lightgbm/basic.py
=> fix: typo in python class _InnerPredictor docstring

include/LightGBM/utils/common.h, tests/cpp_tests/test_common.cpp
For texts that resolve to infinity, under or overflow should be accepted.
This should resolve unit test failure mention in #4330.
=> Log warning instead of fatal when parsing float get under/overflow.

include/LightGBM/utils/array_args.h, tests/cpp_tests/test_array_args.cpp
Fixes issue https://github.com/microsoft/LightGBM/issues/4272
Added some tests for ArrayArgs::Partition
=> Fix undefined behavior in ArrayArgs::Partition() when interval size is 1 (fixes #4272)

examples/python-guide/simple_example.py, examples/python-guide/sklearn_example.py
Based on comments https://github.com/microsoft/LightGBM/pull/4386#pullrequestreview-686376988 and https://github.com/microsoft/LightGBM/pull/4386#discussion_r655295441.
These files are already marked as done in #4136 because there were no old string formatting methods there, only `print`s.
=> [python] Improving the syntax of `print`s in `simple_example.py` and `sklearn_example.py`

src/objective/binary_objective.hpp
when training a binary classifier in distribution mode, the init score should depend on all training dataset, not local training dataset
=> sync for init score of binary objective function

R-package/R/aliases.R, docs/Parameters.rst, include/LightGBM/config.h, python-package/lightgbm/basic.py, src/c_api.cpp, src/io/config_auto.cpp, tests/python_package_test/test_engine.py
- add `precise_float_parser` to Dataset params at language wrappers level and raise error in case of new value in config for constructed Dataset
- move `linear_tree` param to Dataset section (**open to discussion** about another way how indicate the fact that `linear_tree` config value is used at Dataset creation step)
=> fix param aliases

.github/workflows/r_valgrind.yml
Replacing #4397 because it cannot be merged with a failing test, and the changes here are needed for the test to pass.
<hr>
(description copied from #4397)
See #4391 (comment) and this failed job with a timeout of 180 minutes (https://github.com/microsoft/LightGBM/actions/runs/959047226).
It seems recently-added R package tests (or maybe some combination of that and changes in the C++ side) has led to the valgrind jobs exceeding 120 minutes. As a reminder, R runs substantially slower under valgrind (https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Using-valgrind).
=> [ci] [R-package] increase timeout on valgrind job

python-package/lightgbm/dask.py, tests/python_package_test/test_dask.py
`.predict()` in the Dask estimators allows users to pass additional prediction parameters (https://lightgbm.readthedocs.io/en/latest/Parameters.html#predict-parameters) through `**kwargs`. To be applied correctly, those `**kwargs` have to be passed through several layers of function calls inside the package.
One of those pass-throughs is currently missing, and as a result additional prediction parameters will be silently ignored when data passed to `.predict()` is a Dask Array.
This PR proposes fixing that and adding tests confirming that additional parameters are being passed through correctly.
I looked at `lightgbm.basic._InnerPredictor.predict()` for the names of specific parameters to be passed through.
https://github.com/microsoft/LightGBM/blob/bd21efed4f9dfffa5119775c835e1097d078085b …
=> [dask] pass additional predict() parameters through when input is a Dask Array

.github/workflows/r_valgrind.yml, R-package/src/lightgbm_R.cpp
=> [R-package] fix protection stack imbalance and unprotected objects (fixes #4390)

tests/python_package_test/test_dask.py
Adds a missing `.compute()` call in the Dask tests, see https://github.com/microsoft/LightGBM/pull/4399/files#r659165339.
=> [tests][dask] add missing compute() in Dask test

python-package/lightgbm/basic.py, python-package/lightgbm/engine.py, tests/c_api_test/test_.py, tests/python_package_test/test_engine.py
> `empty`, unlike `zeros`, does not set the array values to zero, and may therefore be marginally faster. On the other hand, it requires the user to manually set all the values in the array, and should be used with caution.
https://numpy.org/doc/stable/reference/generated/numpy.empty.html
=> [python] replace numpy.zeros with numpy.empty for the speedup

src/treelearner/cuda_kernel_launcher.cu
By using the log from https://github.com/microsoft/LightGBM/blob/master/src/treelearner/cuda_tree_learner.cpp#L334, we could see the CUDA memory allocated is 18000000 bytes,  when running the example code of https://github.com/microsoft/LightGBM/issues/4315. But by adding a log on https://github.com/microsoft/LightGBM/blob/master/src/treelearner/kernels/histogram_16_64_256.cu#L148, I found that the access offset defined by `feature_id * feature_size` is much larger than 18000000 bytes. This is the cause of the memory accessing error.
Actually, the `feature_id` is already the identity number of these dense features, so we don't need, and can't multiply the `num_workgroups` for CUDA kernel in https://github.com/microsoft/LightGBM/blob/master/src/treelearner/cuda_kernel_launcher.cu
I have …
=> [CUDA] fix CUDA memory error by reducing block number (#4315)

python-package/lightgbm/dask.py
Following up on https://github.com/microsoft/LightGBM/pull/4101#pullrequestreview-693527253 (cc @ffineis just so you know this is what I was talking about in that comment).
The function `lightgbm.dask._pad_eval_names()` currently has a type hint suggesting that argument `required_names` could be `None`, but its code doesn't handle that case. The `for` loop below would fail with an error complaining about `NoneType` not being iterable.
https://github.com/microsoft/LightGBM/blob/b5502d19b2b462f665e3d1edbaa70c0d6472bca4/python-package/lightgbm/dask.py#L98
I don't think it is actually possible for that argument to ever be `None`, because of
https://github.com/microsoft/LightGBM/blob/b5502d19b2b462f665e3d1edbaa70c0d6472bca4/python-package/lightgbm/dask.py#L186-L189 …
=> [dask] fix typehint on _pad_eval_names()

tests/cpp_tests/test_array_args.cpp
https://github.com/microsoft/LightGBM/blob/b918b5b2ff2dd776527e134f26eb8c0f0f096cfa/include/LightGBM/utils/array_args.h#L101
```
D:\a\1\s\tests\cpp_tests\test_array_args.cpp(21): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [D:\a\1\s\build\testlightgbm.vcxproj]
D:\a\1\s\tests\cpp_tests\test_array_args.cpp(31): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [D:\a\1\s\build\testlightgbm.vcxproj]
D:\a\1\s\tests\cpp_tests\test_array_args.cpp(38): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [D:\a\1\s\build\testlightgbm.vcxproj]
D:\a\1\s\tests\cpp_tests\test_array_args.cpp(47): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data …
```
=> [tests] fix compiler warning about types conversion in cpp tests

swig/StringArray.i, swig/StringArray_API_extensions.i
```
D:\a\1\s\build\java\lightgbmlibJAVA_wrap.cxx(792): warning C4101: 'e': unreferenced local variable [D:\a\1\s\build\_lightgbm_swig.vcxproj]
D:\a\1\s\build\java\lightgbmlibJAVA_wrap.cxx(887): warning C4101: 'e': unreferenced local variable [D:\a\1\s\build\_lightgbm_swig.vcxproj]
D:\a\1\s\build\java\lightgbmlibJAVA_wrap.cxx(925): warning C4101: 'e': unreferenced local variable [D:\a\1\s\build\_lightgbm_swig.vcxproj]
D:\a\1\s\build\java\lightgbmlibJAVA_wrap.cxx(964): warning C4101: 'e': unreferenced local variable [D:\a\1\s\build\_lightgbm_swig.vcxproj]
```
=> [SWIG] fix compiler warning about unused variable in SWIG

python-package/lightgbm/sklearn.py
Adds
- Type hints for [init of LGBMModel](https://github.com/microsoft/LightGBM/blob/189a80181eb9e3e739a5f508a953ec6351be9dad/python-package/lightgbm/sklearn.py#L351) per #3756
=> [python-package] Add type hints to init for LGBMModel

examples/python-guide/plot_example.py
=> [python-package] f-string format updated in plot_example.py

.gitignore
Due to
https://github.com/microsoft/LightGBM/blob/c359896e9bdbbbf89af5e186dd07080a40545452/examples/python-guide/dataset_from_multi_hdf5.py#L89-L90
=> [ci] add h5 files into `.gitignore`

tests/c_api_test/test_.py, tests/cpp_tests/test.py, tests/python_package_test/test_basic.py, tests/python_package_test/test_consistency.py, tests/python_package_test/test_dask.py, tests/python_package_test/test_engine.py, tests/python_package_test/test_sklearn.py, tests/python_package_test/test_utilities.py
=> [python] migrate to pathlib in python tests

tests/python_package_test/test_basic.py
```
/__w/1/s/tests/python_package_test/test_basic.py:173: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```
=> [tests] fix deprecation numpy warning

examples/python-guide/dask/ranking.py, tests/python_package_test/test_engine.py
Based on the advice in https://github.com/microsoft/LightGBM/pull/4378#issuecomment-873805964, this PR proposes changing a few uses of `.todense()` called on sparse arrays to `.toarray()`.
This method converts a sparse array to a `np.array`, a better-supported object type than `np.matrix` (the type returned by `.todense()`).
See https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.spmatrix.toarray.html.
There are a few other uses of `.todense()` in the Dask tests, but those will be changed as part of #4378.
=> [python-package] use toarray() instead of todense() in tests and examples

include/LightGBM/utils/random.h
Thanks @DexGroves for pointing out the bug in the Reservoir Sampling. It turns out the fix for #4134 in #4324 did not remove the root cause. The real problem is the `+1` being missing in `int v = NextInt(0, r);`. This should solves both #4134 and #4371.
=> [fix] fix Reservoir Sampling in Sample of random.h (fix #4371 and #4134)

python-package/lightgbm/__init__.py, python-package/lightgbm/basic.py, python-package/lightgbm/engine.py, python-package/lightgbm/libpath.py, python-package/lightgbm/sklearn.py, tests/python_package_test/test_basic.py, tests/python_package_test/test_consistency.py, tests/python_package_test/test_engine.py
Allow to pass filenames as `libpath.Path` objects. Now path-like objects can be used in both named arguments and `params` dictionary (`kwargs`).
Contributes to #4416.
=> [python] allow to pass some params as pathlib.Path objects

tests/distributed/_test_distributed.py
Refer to https://github.com/microsoft/LightGBM/pull/4254#discussion_r659450888.
https://github.com/microsoft/LightGBM/blob/a06899ab72e59aeb635c794962cb19a5880724df/tests/distributed/_test_distributed.py#L135
=> [tests] clarify RuntimeError in distributed tests

tests/python_package_test/test_dask.py, tests/python_package_test/test_engine.py
Refer to https://github.com/microsoft/LightGBM/pull/4411#issuecomment-869208342.
Currently, prediction early stopping is never tested with ranking task.
=> [tests][python] added tests for early stop in prediction in ranking task

.nuget/create_nuget.py, .vsts-ci.yml, docs/conf.py, helpers/parameter_generator.py, python-package/setup.py, tests/c_api_test/test_.py, tests/cpp_tests/test.py
=> [python] migrate to pathlib in setup.py and use `absolute()` on paths first

include/LightGBM/tree.h
Currently, the `CategoricalDecision()` function casts the input `fval` into `int`, when `fval` is possibly a NaN (Not-a-Number):
https://github.com/microsoft/LightGBM/blob/5b7a6f3e7150aeb704d1dd2b852d246af3e913a3/include/LightGBM/tree.h#L368-L379
This cast causes undefined behavior when `fval` is NaN. According to https://stackoverflow.com/a/10366541:
> When a finite value of real floating type is converted to an integer type other than _Bool, the fractional part is discarded (i.e., the value is truncated toward zero). **If the value of the integral part cannot be represented by the integer type, the behavior is undefined.**
Casting NaN into `int` may or may not produce a negative value.
Minimal reproducible example, where this is a problem:
```python
import numpy …
```
=> Fix undefined behavior with NaN input in CategoricalDecision()

src/c_api.cpp
This removes code duplication for creating sample indices.
Previously discussed in https://github.com/microsoft/LightGBM/pull/4089#issuecomment-871958002.
=> [refactor] Use CreateSampleIndices in c_api.cc

helpers/parameter_generator.py
contributes to #3756
Added type hints on helpers/parameter_generator.py
=> [python] Add type hints to helpers/parameter_generator.py

docs/Parameters.rst, examples/binary_classification/train.conf, examples/lambdarank/train.conf, examples/multiclass_classification/train.conf, examples/parallel_learning/train.conf, examples/regression/train.conf, examples/xendcg/train.conf, include/LightGBM/config.h
Answering [this stack overflow question](https://stackoverflow.com/questions/68482580/in-the-example-regression-which-is-the-target-column/68506958#68506958) tonight, I wasn't able to figure out from LightGBM's documentation that, when using the CLI, if `label_column` is omitted from `train.conf`, LightGBM defaults to using the first column in the training data as the target.
I had to figure this out from source code
* `Dataset.label_idx_`  is initialized to 0: https://github.com/microsoft/LightGBM/blob/a8ee487aca35363fafa027e6b7695976045096b3/src/io/dataset_loader.cpp#L22
* `Dataset.label_idx_` is only overridden if label_column is provided in the config: https://github.com/microsoft/LightGBM/blob/a8ee487aca35363fafa027e6b7695976045096b3/src/io/dataset_loader.cpp#L48-L57
This PR proposes …
=> [docs] document CLI behavior when label_column is omitted

docs/conf.py
=> [docs][ci] bump versions of R-package dependencies at RTD

python-package/lightgbm/basic.py, tests/python_package_test/test_basic.py
=> [python] support Dataset.get_data for Sequence input.

R-package/src/lightgbm-win.def
Through investigation of #4464, I've learned a lot about how R loads DLLs for packages. Particularly, I've learned that there are some settings where two DLLs having the same symbols can lead to conflicts that cause crashes or incorrect behavior.
This PR proposes a change to limit the visibility of symbols in the `lightgbm.dll` created for this project's R package.
From https://cran.r-project.org/doc/manuals/R-exts.html#Writing-portable-packages
> It is good practice for DLLs to register their symbols (see Registering native routines), restrict visibility (see Controlling visibility) and not allow symbol search (see Registering native routines). It should be possible for a DLL to have only one visible symbol, R_init_pkgname, on suitable platforms, which would completely avoid symbol …
=> [R-package] limit exported symbols in DLL

build-cran-package.sh
LightGBM provides a script, `build-cran-package.sh`, which can be used to produce a CRAN-style source distribution of the R package.
This is effectively user-facing code, since we encourage users to run it while developing or building from `master` to get unreleased features (e.g. https://github.com/microsoft/LightGBM/issues/4259#issuecomment-832900302, https://github.com/microsoft/LightGBM/issues/4464#issuecomment-890454199).
I realized yesterday, working on #3946 , that that script can break if called from a path that has spaces in it.
Consider the following:
```shell
mkdir -p './some files'
cd 'some files'
git clone --recursive https://github.com/microsoft/LightGBM.git
cd LightGBM
sh build-cran-package.sh
```
This errors out like so:
> build-cran-package.sh: line 15: test: …
=> [R-package] quote path variables in build-cran-package.sh

include/LightGBM/c_api.h, python-package/lightgbm/basic.py
As pointed in PR https://github.com/microsoft/LightGBM/pull/4478#issuecomment-885578558.
=> Update c_api LGBM_SampleIndices() comment.

python-package/lightgbm/dask.py, tests/python_package_test/test_dask.py
This replaces my initial proposal (#3823) of using `client.run` to find an open port in each worker, since that could produce collisions (#4057, #4458) when one host had more than one worker process running in it (as is the case with `LocalCluster`). The collisions problem was solved in #4133, however it would be desirable to not have any collisions at all, which is what this (hopefully) achieves.
=> [dask] find all needed ports in each host at once (fixes #4458)

R-package/configure.win
Another small thing I noticed in the R package's `configure` scripts while looking into #4131 .
The variable `R_SCRIPT` is unused in `configure.win`. It isn't something special (for example, you won't see it mentioned in https://cran.r-project.org/doc/manuals/R-exts.html). So I'm very confident it can be removed.
This PR proposes removing it.
=> [R-package] remove unused variable R_SCRIPT in configure.win

.ci/test.sh, tests/python_package_test/test_dask.py
The recent change of the search for open ports for the dask interface (#4498) removed the collisions and to make sure we never got any the test ran 1,000 times, which is too much for the QEMU CI job (https://github.com/microsoft/LightGBM/pull/4498#discussion_r682665570).
This reduces the number of times the collisions are tested to 25 (as suggested in https://github.com/microsoft/LightGBM/pull/4498#discussion_r682809148).
=> [tests][dask] reduce number of collisions tests

README.md
Previous repo is achieved now.
https://github.com/mlr3learners/mlr3learners.lightgbm/commit/903ecc123a0199fb8a89f0cdeb1db514f1b8827b
=> [docs] Update link to mlr3-compliant interface in README

.ci/test.sh
I've been experimenting with [`shellcheck`](https://github.com/koalaman/shellcheck) recently in some projects.
I ran it over all of this project's shell scripts tonight, like this:
```shell
brew install shellcheck
shell_scripts=$(
git ls-files \
| grep -E "\.sh$"
)
shellcheck \
--color=never \
--format=gcc \
$shell_scripts
```
This PR proposes fixing one type of warning raised by `shellcheck`. 
```text
.ci/test.sh:43:31: note: Use $(...) notation instead of legacy backticked `...`. [SC2006]
.ci/test.sh:45:86: note: Use $(...) notation instead of legacy backticked `...`. [SC2006]
```
See https://github.com/koalaman/shellcheck/wiki/SC2006 for some background on why `$()` should be preferred to backticks for inline expressions.
=> [ci] replace uses of backticks in test.sh with $()

docs/conf.py
This PR proposes using CRAN-style builds of the R package on readthedocs (RTD).
Advantages of this approach over CMake builds:
* (maybe) faster RTD builds, since `cmake` does not need to be installed
* easier updates of the `conda` R dependencies for RTD builds
* reduced risk of failures when the RTD images change (since the CRAN package is optimized for portability)
* another step towards publishing vignettes on the `{pkgdown}` site (contributes to #1944)
- I say this because I'm going to propose on #3946 that we only build vignettes for CRAN-style builds of the R package
=> [docs] [R-package] use CRAN-style builds when building pkgdown site

.ci/test_r_package_valgrind.sh, .github/workflows/r_package.yml, .github/workflows/static_analysis.yml, R-package/README.md, R-package/configure.win
Looking into #4131 as part of #4310, I've noticed some other areas for possible improvement in the `configure` and `configure.win` scripts.
This PR fixes one in `configure.win`. I noticed that the mm_prefetch and mm_malloc tests are being run with a C compiler on Windows. They should be done with a C++ compiler, as they are on Linux/Mac
https://github.com/microsoft/LightGBM/blob/5fe27d594285eeaf31d2f1ebfe29453f8c6c6ad3/R-package/configure.ac#L41
and for all CMake-based builds
https://github.com/microsoft/LightGBM/blob/5fe27d594285eeaf31d2f1ebfe29453f8c6c6ad3/CMakeLists.txt#L253
I'm not aware of any problems caused by the fact that these checks were being done by a C compiler, but a C++ compiler is going to be used for compiling `lib_lightgbm`.
To understand the difference between …
=> [R-package] use C++ compiler for pre-compile checks on Windows

.github/workflows/r_package.yml
On PRs I opened within the last hour (#4522, #4523), the `r-package (ubuntu-latest, R-devel, GCC ASAN/UBSAN) (pull_request)` job is failing.
> E: Repository 'http://deb.debian.org/debian testing InRelease' changed its 'Codename' value from 'bullseye' to 'bookworm'
Error: Process completed with exit code 100.
https://github.com/microsoft/LightGBM/pull/4523/checks?check_run_id=3332073359
After some research, I think this could be fixed by preferring `apt update` to `apt-get update`. A similar error was reported a few hours ago in https://www.mail-archive.com/debian-user@lists.debian.org/msg772749.html, and responses in that thread suggest that running `apt update` in place of `apt-get update` can fix it (e.g. https://www.mail-archive.com/debian-user@lists.debian.org/msg772763.html).
As far …
=> [ci] use flag '--allow-releaseinfo-change' in some 'apt-get update' calls

R-package/R/lgb.Dataset.R, R-package/R/lgb.cv.R, R-package/R/lgb.train.R, R-package/man/dim.Rd, R-package/man/getinfo.Rd, R-package/man/lgb.cv.Rd, R-package/man/lgb.train.Rd, R-package/man/setinfo.Rd
Contributes to #4310 (based on https://github.com/microsoft/LightGBM/issues/4226#issuecomment-829473584).
This PR proposes adding some deprecation warnings on uses of `...` for parameters in the following functions:
* `dim.lgb.Dataset()`
* `getinfo.lgb.Dataset()`
* `lgb.cv()`
* `lgb.train()`
* `setinfo.lgb.Dataset()`
Given this R code
```r
model <- lgb.train(
params = list(
objective = "regression"
)
, data = dtrain
, nrounds = 5L
, bagging_fraction = 0.5
, bagging_freq = 2L
)
```
This is the warning shown:
> Warning message:
In lgb.train(params = list(objective = "regression"), data = dtrain,  :
lgb.train: Found the following passed through '...': …
=> [R-package] add deprecation warnings about some uses of '...'

.ci/test_r_package_valgrind.sh, R-package/configure, R-package/configure.ac
Investigating #4131 , I've been re-reading [the section of "Writing R Extensions" that discusses `configure` scripts](https://cran.r-project.org/doc/manuals/R-exts.html#Configure-and-cleanup).
I believe the R package's current `configure` script is not currently following some of that manual's advice. When it does configure tests (e.g. to check for an included `mm_malloc`), it isn't passing through the compiler flags that R will use when compiling `lib_lightgbm`.
> You will very likely need to ensure that the same C compiler and compiler flags are used in the configure tests as when compiling R or your package
> You can use `R CMD config` to get the value of the basic configuration variables... If you do, it is essential that you use both the command and the appropriate flags, so that for …
=> [R-package] pass R-configured compiler flags to checks in configure

R-package/R/lgb.Booster.R
Contributes to #4310 (based on https://github.com/microsoft/LightGBM/issues/4226#issuecomment-829473584).
This proposes removing the `...` from the constructor of the `Booster` class in the R package. That class is not exported from the R package, so its constructor can be considered a private API and this change should be considered non-breaking (similar to #4338).
Removing this use of `...` makes the package's code slightly stricter, which reduces the risk of bugs.
Internal calls of the `Booster` class always use that class's existing keyword arguments.
https://github.com/microsoft/LightGBM/blob/86ead2050c006b984e88396e0e380304bac114d1/R-package/R/lgb.Booster.R#L812
https://github.com/microsoft/LightGBM/blob/86ead2050c006b984e88396e0e380304bac114d1/R-package/R/lgb.Booster.R#L819 …
=> [R-package] remove unused '...' in Booster constructor

R-package/configure, R-package/configure.ac
Fixes #4131.
It makes a few improvements to the way that CRAN-style builds of the R package's `configure` script checks for the presence of OpenMP on macOS.
As a result, **OpenMP detection in the R package should be more reliable, meaning more users can benefit from multi-threading speedups**.
changes:
* passes the result of `R CMD config LDFLAGS` when running the OpenMP check, to ensure that that check uses the same linker flags that R itself will use when compiling `lib_lightgbm`
- notably, this puts `-L/usr/local/lib` into the statement used to compile a test program, so brew-installed `libomp` will be found
- this also allows users to install `{lightgbm}` with non-standard install locations for `libomp` by modifying `LDFLAGS` in `~/.R/Makevars`
* adds an additional check using only …
=> [R-package] fix OpenMP checking on macOS (fixes #4131)

docs/conf.py
Adds type hints to code in `docs/conf.py`, as part of #3756.
#3756 has been open for about 8 months now, so I think it's ok for maintainers to start picking up the work to finish it and not wait any longer for outside contributors to find it from searches for `good first issue`.
Better type hints will improve the ability of `mypy` to catch issues (#3868 ).
=> [python] add type hints in docs/conf.py

README.md
It's now a subfolder in `scikit-learn-intelex` repository.
=> [docs] Update link to `daal4py` in README

python-package/lightgbm/basic.py
Adds type hints to logging code in `python-package/lightgbm/basic.py`, as part of #3756.
See https://github.com/microsoft/LightGBM/issues/3756#issuecomment-899115595.
I ran `mypy --ignore-missing-imports python-package/lightgbm` and don't see any new warnings about `basic.py` or code imported from there
=> [python] add type hints to logging functions in basic.py

.ci/test_r_package.sh, .ci/test_r_package_windows.ps1
Make sure we provide efficient version of LightGBM via CRAN distribution.
=> [ci] Add checks that MM_PREFETCH and MM_MALLOC are used in CRAN builds

include/LightGBM/utils/text_reader.h
I started exploring [`cppcheck`](http://cppcheck.sourceforge.net/), a static analyzer for C++ projects, tonight.
This PR proposes fixing one of the warnings raised by that tool. It caught some cases where two consecutive code blocks were guarded by identical `if()` conditions. Consolidating those blocks removes two unnecessary checks.
```text
include/LightGBM/utils/text_reader.h:202:11: style: The if condition is the same as the previous if condition [duplicateCondition]
if (is_used) { lines_.emplace_back(buffer, size); }
^
include/LightGBM/utils/text_reader.h:201:11: note: First condition
if (is_used) { out_used_data_indices->push_back(line_idx); }
^
include/LightGBM/utils/text_reader.h:202:11: note: Second condition
if (is_used) { lines_.emplace_back(buffer, size); }
^ …
```
=> consolidate duplicate conditions in TextReader

README.md
Hi,
I'm Prince Canuma a Data Scientist and DevRel at [Neptune.ai](https://neptune.ai),
We have created a [Neptune + LightGBM integration](https://docs.neptune.ai/integrations-and-supported-tools/model-training/lightgbm) that allows LightGBM users to **automatically log** the following metadata to Neptune:
* training and validation metrics
* parameters
* feature names, num_features and num_rows for the train_set
* hardware consumption (CPU, GPU, Memory)
* stdout and stderr logs
* training code and git commit information
We are looking for ways to let users of LightGBM know this integration exists, is available and is up to date. To ensure the latter, we want to collaborate with you in future versions of LightGBM.
Finally, besides the README are there other ways you would recommend …
=> [doc] Add link to Neptune hyperparam tuning guide

src/io/parser.cpp
`GetDataType()` is used by code that reads from text files, to determine whether file is a CSV, TSV, or LibSVM format.
`cppcheck` raises the following warning about that function's implementation (#4359):
```text
src/io/parser.cpp:195:27: style: Condition 'lines.size()>1' is always true [knownConditionTrueFalse]
} else if (lines.size() > 1) {
^
src/io/parser.cpp:187:20: note: Assuming that condition 'lines.size()==1' is not redundant
if (lines.size() == 1) {
^
src/io/parser.cpp:195:27: note: Condition 'lines.size()>1' is always true
} else if (lines.size() > 1) {
^
```
This is pointing out, correctly, that the code in that function has a structure like this pseudo code
```text
if lines.size() == 0:
do_something()
elif lines.size() == 1:
do_something_else()
elif lines.size() > 1: …
```
=> factor out .size() checks in GetDataType()

R-package/R/lgb.Booster.R, R-package/R/lgb.Dataset.R, R-package/man/lgb.Dataset.Rd, R-package/man/lgb.Dataset.create.valid.Rd, R-package/man/predict.lgb.Booster.Rd, R-package/tests/testthat/test_lgb.Booster.R, docs/Python-Intro.rst, python-package/lightgbm/basic.py, src/io/parser.cpp
Fixes #4034.
Contributes to #4310.
`predict()` methods in LightGBM can be used with data stored in a text file (CSV, TSV, or LibSVM). Those methods do not support creating predictions on other formats like LightGBM `Dataset` objects saved in a binary file.
This PR proposes the following changes to fix #4034:
* clarifies the supported file formats for predict methods in the R and Python package documentation
* adds a unit test in the R package on the behavior of calling `Booster$eval()` on a constructed `Dataset` stored in a file (https://github.com/microsoft/LightGBM/issues/4034#issuecomment-843003438)
* updates the relevant error message in the C++ code used to determine file type when predicting on a file, to make it clearer that only certain formats of text file are supported
=> [docs] Clarify the fact that predict() on a file does not support saved Datasets (fixes #4034)

README.md, docs/Parallel-Learning-Guide.rst
MMLSpark was renamed into SynapseML and moved from Azure to Microsoft GitHub account.
=> [docs] update links to SynapseML (former MMLSpark)

R-package/tests/testthat.R
With all the added deprecation warnings from #4226, I found that I wanted to be able to see the warnings generated in the R package's unit tests.
Today, when you run the unit tests outside of `R CMD check`, like this:
```shell
sh build-cran-package.sh
R CMD INSTALL lightgbm_3.2.1.99.tar.gz
cd R-package/tests
Rscript testthat.R
```
You'll just see LightGBM's logs from the C++ side, `{testthat}` context describing the different test sections, and then a line like this at the end.
```text
[ FAIL 0 | WARN 54 | SKIP 2 | PASS 680 ]
```
With the change in this PR, we'll be able to see the actual content of those warnings in CI logs, which I think will help contributors and maintainers assess changes and find opportunities for improvements.
See the logs from MSVC R jobs (like …
=> [R-package] use {testthat} SummaryReporter in tests

python-package/lightgbm/dask.py
I'm sorry, I missed this one in #4557.
=> [python][docs] Refer to string type as `str` in docstrings

R-package/R/lgb.Booster.R, R-package/R/lgb.Dataset.R, R-package/R/lgb.cv.R, R-package/R/lgb.train.R, R-package/R/lgb.unloader.R, R-package/R/readRDS.lgb.Booster.R, R-package/R/saveRDS.lgb.Booster.R, R-package/man/lgb.Dataset.set.reference.Rd, R-package/man/lgb.cv.Rd, R-package/man/lgb.dump.Rd, R-package/man/lgb.get.eval.result.Rd, R-package/man/lgb.load.Rd, R-package/man/lgb.save.Rd, R-package/man/lgb.train.Rd, R-package/man/lgb.unloader.Rd, R-package/man/predict.lgb.Booster.Rd, R-package/man/readRDS.lgb.Booster.Rd, R-package/man/saveRDS.lgb.Booster.Rd
The deprecation warnings added as part of #4226 introduced some warnings in the examples in `{lightgbm}`'s documentation.
For example, see https://lightgbm.readthedocs.io/en/latest/R/reference/lgb.train.html
This PR fixes them and converts examples to the new pattern we want to encourage as of v3.3.0 (#4310), passing all parameters through `params`.
=> [R-package] fix warnings in examples

.gitignore, R-package/demo/basic_walkthrough.R, R-package/demo/categorical_features_rules.R, R-package/demo/early_stopping.R, R-package/demo/leaf_stability.R, R-package/demo/multiclass.R, R-package/demo/multiclass_custom_objective.R, R-package/demo/weight_param.R
Similar to the changes made to examples in the R package's API docs in #4568, this PR fixes warnings in demos related to the deprecation warnings added as part of #4226.
For example, if you run `Rscript R-package/demo/basic_walkthrough.R` on current `master`, you'll see the following on stdout.
> Warning message:
In lgb.train(data = dtrain2, num_leaves = 4L, learning_rate = 1,  :
lgb.train: Found the following passed through '...': num_leaves, learning_rate, nthread, objective. These will be used, but in future releases of lightgbm, this warning will become an error. Add these to 'params' instead. See ?lgb.train for documentation on how to call this function.
This PR fixes them and converts examples to the new pattern we want to encourage as of v3.3.0 (#4310), passing all parameters …
=> [R-package] fix warnings in demos

python-package/lightgbm/dask.py
Fixed #4375.
Same as #4380 but for `eval_***` equivalents of `weight`, `init_score` and `group` arguments.
=> [dask] Fixed Dask type annotation

R-package/R/lgb.Dataset.R
Another step towards #4226 as part of #4310. 
This PR proposes adding a deprecation warning on uses of additional parameters passed through `...` in `Dataset$slice()` in the R package.
=> [R-package] deprecate uses of '...' in Dataset slice() method

python-package/lightgbm/basic.py, python-package/lightgbm/callback.py, python-package/lightgbm/dask.py, python-package/lightgbm/engine.py, python-package/lightgbm/sklearn.py
Also, use singular form of a word in a `list of ...` type descriptions to match ones with simple types (`list of int` or `list of str`).
=> [docs][python] Refer to functions as `callable` in docstrings

python-package/lightgbm/plotting.py, tests/python_package_test/test_plotting.py
Respect `importance_type` attribute of LGBMModel in `plot_importance()`.
Marking this as `breaking`, but I don't think this change will actually affect many users. Only those will be affected who for some reason specify `LGBMModel(importance_type="gain")` and leave default value (`importance_type="split"`) in `plot_importance()`.
=> [python] add 'auto' value for `importance_type` param in plotting

R-package/R/callback.R, R-package/R/lgb.Dataset.R, R-package/R/lgb.convert_with_rules.R, R-package/R/lgb.importance.R, R-package/R/lgb.interprete.R
This PR proposes a few changes to comments in the source code of the R package. Some things I've noticed while looking closely at that code a lot recently, working on #4310.
* removes reference to `lgb.convert()` (was removed about a year ago, in #3269)
- I also checked for other uses with `git grep -E "lgb\.convert"`...did not find any
* removes comments that do not add any additional information about what the code is doing or why it's doing it (similar to changes in #4383)
for example:
```r
if (!lgb.is.Dataset(x = dataset)) {
```
=> [R-package] fix inaccurate comments, remove unnecessary comments

R-package/R/lgb.Dataset.R
Noticed while working on #4586.
An error message in `Dataset$get_colnames()` currently references `Dataset$dim()`, which is inaccurate and might lead to confusion.
This PR fixes that error message.
=> [R-package] fix inaccurate error message in Dataset get_colnames() method

.vsts-ci.yml
Use `--format` option insted of parsing the whole output with `jq` tool.
https://docs.docker.com/engine/reference/commandline/inspect/#options
=> [ci] simplify docker info parsing in QEMU builds

python-package/lightgbm/basic.py, python-package/lightgbm/dask.py, python-package/lightgbm/engine.py, python-package/lightgbm/sklearn.py
Proposing this PR to include in #4310
> I also think this release could be a good opportunity for maintainers to think carefully about what breaking changes might be made (in addition to #3234) in a 4.0.0 release, and to add deprecation warnings for them in the 3.3.0 release.
Having multiple params and arguments that control verbosity is quite confusing, see https://github.com/microsoft/LightGBM/issues/1157#issuecomment-395257431. I believe leaving only `verbose` keyword argument, that is described in our [general parameters guide](https://lightgbm.readthedocs.io/en/latest/Parameters.html#verbosity) and which one that a lot of users is used to simply set to `-1`, will simplify user experience and decrease the maintainance burden for us.
=> [RFC][python] deprecate `silent` and standalone `verbose` args. Prefer global `verbose` param

tests/python_package_test/test_dask.py
See https://github.com/microsoft/LightGBM/pull/4552#issuecomment-914536864 and https://github.com/microsoft/LightGBM/pull/4552#issuecomment-914633031 for background.
This PR proposes skipping Dask tests on QEMU builds, essentially reverting #3996.
I hope this will be a temporary change, but for now I think it's necessary. Timeouts in QEMU builds are blocking development in this repo and have led to a backlog of pull requests starting to pile up.
#4595 is still a valuable fix and should be merged.
I'd like to continue to use #4552 as place to test configurations that preserve some or all of the Dask tests in QEMU builds.
=> [ci] skip Dask tests on QEMU builds

CMakeLists.txt
I learned today that @tkruse, the maintainer of `cpplint`, also maintains a static analyzer for `CMakeLists.txt` files, called `cmakelint`!
You can learn about this tool at https://github.com/cmake-lint/cmake-lint.
I ran it over `LightGBM` today, and found that it had mainly cosmetic recommendations:
* "Do not mix upper and lower case commands"
* "Lines should be <= 120 characters long"
* "Expression repeated inside endif; better to use only endif()"
* "Extra spaces between 'if' and its ()"
* "Weird indentation; use 2 spaces"
* "Tab found; please use spaces"
<details><summary>full log and commands I ran (click me)</summary>
Installed on my mac
```shell
pip install --upgrade cmakelint
```
then ran from root of the repo
```shell
cmakelint --linelength=120
```
full logs
```text …
```
=> prefer spaces to tabs in CMakeLists.txt

tests/python_package_test/test_dask.py
Fixes #4594.
Since the dask tests run on a `LocalCluster` we used `127.0.0.1` as the host for the workers, however something seems to have changed and on my machine (ubuntu) now the scheduler gets `127.0.0.1` and the workers get `192.168.100.4` and in the QEMU build they're getting `172.17.0.2`. This PR extracts the hostname from the worker addresses to run the tests that require using the workers' addresses.
=> [tests][dask] Use workers hostname in tests (fixes #4594)

python-package/lightgbm/sklearn.py, tests/python_package_test/test_sklearn.py
=> [python][sklearn] respect `eval_at` aliases in keyword arguments

R-package/R/lgb.Dataset.R, R-package/tests/testthat/test_dataset.R
Noticed while working on #4586.
`Dataset$set_reference()` allows changing the reference Dataset that a given `Dataset` is based on, which affects (for example) how features are binned.
Using `Dataset$set_reference()` to set `reference` to the existing object doesn't have any effect on the `Dataset` object. This PR proposes moving the existing check for that all the way up to the beginning of that method, to avoid any other unnecessary computation and slightly speed up this method for that case.
=> [R-package] avoid unnecessary computation and add tests for Dataset set_reference() method

docs/Python-API.rst, python-package/lightgbm/__init__.py, python-package/lightgbm/callback.py, python-package/lightgbm/engine.py, python-package/lightgbm/sklearn.py, tests/python_package_test/test_utilities.py
In response to https://github.com/microsoft/LightGBM/pull/4574#discussion_r699411060.
=> [python] rename `print_evaluation()` into `log_evaluation()`

R-package/src/lightgbm_R.cpp, R-package/tests/testthat/test_basic.R, R-package/tests/testthat/test_lgb.Booster.R, include/LightGBM/utils/log.h
Fixes #4282
This PR addresses a couple sources of potential memory leaks in the R interface:
* Changes the logger to print R error messages instead of throwing errors directly, thus avoiding long jumps in the middle of C++ functions (which would be triggered by R errors).
* Adds unwind protection around R allocations that happen after C++ allocations that need to call a destructor.
* Expands the try-catch blocks to catch also C++ exceptions, which if thrown from an R-called C function can produce leaks in the best case and segfaults in the worst case.
~* Moves the order of header includes so as to have the R ones at the end as suggested in the R extensions manual, in order to avoid any possible misinitialization of non-R code.~
=> [R-package] Fix R memory leaks (fixes #4282, fixes #3462)

python-package/lightgbm/dask.py
Fixed
```
python-package\lightgbm\dask.py:33: error: First argument to namedtuple() should be "_HostWorkers", not "HostWorkers"
```
=> [python] fix mypy error in `dask.py`

python-package/setup.py
Fix the following errors:
```
python-package/setup.py:247: error: Argument "integrated_opencl" to "copy_files" has incompatible type "int"; expected "bool"
python-package/setup.py:247: error: Argument "use_gpu" to "copy_files" has incompatible type "int"; expected "bool"
python-package/setup.py:248: error: Argument "use_mingw" to "compile_cpp" has incompatible type "int"; expected "bool"
python-package/setup.py:248: error: Argument "use_gpu" to "compile_cpp" has incompatible type "int"; expected "bool"
python-package/setup.py:248: error: Argument "use_cuda" to "compile_cpp" has incompatible type "int"; expected "bool"
python-package/setup.py:248: error: Argument "use_mpi" to "compile_cpp" has incompatible type "int"; expected "bool"
python-package/setup.py:249: …
```
=> [python] initialize installation options with boolean values in `setup.py`

R-package/src/lightgbm_R.cpp
As a follow up from https://github.com/microsoft/LightGBM/pull/4597, this PR adds preventions in case an R external object pointer object fails to allocate. This should be an incredibly uncommon situation (failing to allocate 8 bytes), but it is in any case preventable.
=> [R-package] prevent memory leak if pointer fails to allocate 

.github/workflows/cuda.yml
The NVIDIA driver on the ci CUDA machine has been reloaded, and now we can recover the CUDA tests.
=> [ci] Recover running CUDA tests at CI (fixed #4611)

python-package/lightgbm/plotting.py, tests/python_package_test/test_plotting.py
Similarly to `title` argument in `plot_split_value_histogram()` function:
https://github.com/microsoft/LightGBM/blob/d10f9d43c490d3e49afc4fdcb72a129cfaf70777/python-package/lightgbm/plotting.py#L199-L205
=> [python] add placeholders to titles in plotting functions

python-package/lightgbm/plotting.py
Continuation of #4614.
With `@metric@` placeholder we don't need to maintain `'auto'`.
=> [python] deprecate "auto" value of `ylabel` argument of `plot_metric()` function

.github/workflows/cuda.yml
Starting from `11.4.1` version you have to specify OS as a part of image.
https://ngc.nvidia.com/catalog/containers/nvidia:cuda/tags
=> [ci] bump CUDA version from 11.4.0 to 11.4.2 at CI

.ci/setup.sh, .gitmodules
Attempts to fix the blocking CI issue on CUDA jobs (#4646). See that issue for more investigation.
Basically, I believe that the `nvidia/cuda` images (last updated 9/20/2021) are using a client somewhere that is using one or more certificates relying on the Let's Encrypt root certificate that expired 9/30/2021.
This PR patches `.ci/setup.sh` to say "just trust the kitware apt repository and don't check it's certificate" for CUDA jobs.
I'm going to open an issue later today on the issues page for the `nvidia/cuda` images, asking them to update their images. But at least for now, I hope this PR will unblock LightGBM's CI.
=> [ci] ignore certificates for kitware apt channel in CUDA jobs (fixes #4646)

python-package/lightgbm/sklearn.py
Refer to scikit-learn 1.0 release notes and corresponding PR:
> `Enhancement` `utils.validation.check_is_fitted` now uses `__sklearn_is_fitted__` if available, instead of checking for attributes ending with an underscore.
https://scikit-learn.org/stable/whats_new/v1.0.html#sklearn-utils
https://github.com/scikit-learn/scikit-learn/pull/20657
After doing some search over GitHub repos, it looks like that only XGBoost has already adopted that new API:
https://github.com/dmlc/xgboost/pull/7230
=> [python][sklearn] add `__sklearn_is_fitted__()` method to be better compatible with scikit-learn API

python-package/lightgbm/compat.py
Refer to the following thread https://github.com/microsoft/LightGBM/pull/4639#discussion_r720068911. Making dummy classes constructible with any arguments may help to write tests.
I'm not overriding default `__init__()` method for three internal classes (prefixed with `_`) because doing that for two of them (`_LGBMRegressorBase` and `_LGBMClassifierBase`) makes `autosummary` Sphinx extension to fail because of inheritance issues.
=> [python] Make dummy classes constructible with any arguments

.ci/test.sh
According to the policy, we indicate support only for the last 3 macOS versions in wheel name: https://github.com/microsoft/LightGBM/pull/2691#issue-549125519.
I believe that "the last 3 macOS  versions" means 3 last major releases like it was before 11.x 
Successfully built bottles for `arm64_monterey`, `arm64_big_sur`, `monterey`, `big_sur`, `catalina`, `mojave` by Homebrew team give some confidence in that LightGBM is indeed compatible with the wide range of macOS versions.
https://github.com/Homebrew/homebrew-core/blob/4060c0ab42d8b9b7168b34f55f12e16a91b27150/Formula/lightgbm.rb#L10-L15
Just FYI, it is now possible to provide one `universal2` wheel for both `x86_64` and `arm64`.
- https://discuss.python.org/t/apple-silicon-and-packaging/4516
- …
=> [ci] indicate support of Monterey

R-package/configure.win
On Windows builds in #3946, I see the following NOTE from `R CMD check`
```text
* checking top-level files ... NOTE
Non-standard file/directory found at top level:
'conftest.cpp'
```
Example build: https://github.com/microsoft/LightGBM/runs/3367486204?check_suite_focus=true.
After pushing the same change from this PR to #3946, I can confirm that this `R CMD check` NOTE no longer shows up in `cran` Windows builds. e.g. https://github.com/microsoft/LightGBM/runs/4053638197?check_suite_focus=true.
The file `conftest.cpp` is created by tests run in `configure.win` which compile test programs to figure out compiler flags to use when compiling LightGBM.
https://github.com/microsoft/LightGBM/blob/dcae8dd5696cb35f105680ecc1de15feede250a1/R-package/configure.win#L30 …
=> [R-package] remove temporary files created in configure.win

.ci/test_r_package_valgrind.sh, .github/workflows/r_package.yml, R-package/README.md, build-cran-package.sh
There are several CI jobs in this project which rely on non-standard builds of `R`:
* valgrind: https://github.com/microsoft/LightGBM/blob/d574fcbd0095f772ab4cfc5c14d4894dd8dc6c0f/.ci/test_r_package_valgrind.sh#L5
* sanitizers: https://github.com/microsoft/LightGBM/blob/d574fcbd0095f772ab4cfc5c14d4894dd8dc6c0f/.github/workflows/r_package.yml#L197
Those custom builds of R also have their own libraries of installed R packages. Consider the following:
```shell
docker run \
--rm \
-it \
wch1/r-debug:latest \
/bin/bash
Rscript -e "library(data.table)"
RDscript -e "library(data.table)"
Rscript -e "install.packages('data.table', repos = 'https://cran.r-project.org')"
Rscript -e "library(data.table)"
RDscript -e "library(data.table)"
```
This project's CI jobs using custom R builds all rely on …
=> [R-package] allow use of custom R executable when building CRAN package

docs/conf.py
I think it's better to add `datatable` because we try to import it here
https://github.com/microsoft/LightGBM/blob/d62378b45314c2688deef7333ae16fcc9863d881/python-package/lightgbm/compat.py#L43
=> [docs][python] add `datatable` to the mocked modules during docs building process and sort them alphabetically

.github/workflows/cuda.yml, .github/workflows/linkchecker.yml, .github/workflows/optional_checks.yml, .github/workflows/python_package.yml, .github/workflows/r_configure.yml, .github/workflows/r_package.yml, .github/workflows/r_solaris.yml, .github/workflows/r_valgrind.yml, .github/workflows/static_analysis.yml, .github/workflows/triggering_comments.yml
This project's CI jobs running on GitHub Actions use the `actions/checkout` action to clone the repo at the beginning of builds. Most jobs in the repo are currently using v2.3.4 of this action (CUDA jobs are using v1).
This PR proposes upgrading all jobs to v2.4.0, the newest release of that action. Just to keep up with changes there and take advantage of small bugfixes.
See https://github.com/actions/checkout/releases for details on the newest releases of this action.
=> [ci] upgrade actions/checkout to v2.4.0

.ci/test_r_package_solaris.sh, .github/workflows/r_solaris.yml, .github/workflows/r_valgrind.yml
As a result of the changes #3946 , which introduce `vignettes/` to the R package (part of #1944), building the R package with `R CMD build` will include installing the package, since it must be installed to create vignette outputs.
To make this work in the existing Solaris CI job, two changes are required:
* `pandoc` must be available in the container used to build the package before submitting it to R Hub
* `{lightgbm}`'s dependencies must be installed *before* running `sh build-cran-package.sh`.
This PR proposes both of those changes. It proposes the re-organization of `test_r_package_solaris.sh` just to make the diff of #3946 slightly smaller and easier to review.
Changing the image used in the Solaris job (to one that already has `pandoc` installed) needs to be done in a separate PR, …
=> [ci] use wch1/r-debug image in Solaris tests

.ci/test.sh, .vsts-ci.yml
Previous Dask version works fine on our CI.
Closed #4769.
`2021.9.1` Dask version isn't available for Python <3.7, so don't pin version to use the latest available (`2021.3.0`).
=> [ci] Temporary pin dask version at CI

python-package/lightgbm/engine.py
Refer to this thread: https://github.com/microsoft/LightGBM/pull/4758#discussion_r741644285.
=> [python] improve warning message about aliases in `cv()` function

docs/conf.py
For #3946, I'm experimenting with adding `{rmarkdown}` and `{knitr}` explicitly to the conda environment used in readthedocs builds (currently they are included implicitly by installing `{pkgdown}`).
While doing this, I've been testing locally by running the following.
```shell
docker run -it continuumio/miniconda3 /bin/bash
conda create \
-q \
-y \
-c conda-forge \
-n r_env \
r-base=4.1.0=hb67fd72_2 \
r-data.table=1.14.0=r41hcfec24a_0 \
r-jsonlite=1.7.2=r41hcfec24a_0 \
r-matrix=1.3_4=r41he454529_0 \
r-pkgdown=1.6.1=r41hc72bb7e_0 \
r-roxygen2=7.1.1=r41h03ef668_0
```
From https://github.com/microsoft/LightGBM/blob/1d0d746e7f95ca654ed410f9da1f9161ce0fc7c1/docs/conf.py#L267-L277
I found that environment solves were taking a long time, and remembered that mixing the default channels and …
=> [ci] only use conda-forge when installing R packages in docs builds

python-package/lightgbm/sklearn.py, tests/python_package_test/test_sklearn.py
Ease access to the **real** number of boosted iterations performed during the training.
`n_estimators_` is added to highlight the possible difference between initially passed `n_estimators` and the actual number of iterations.
`n_iter_` is added to mimic `HistGradientBoosting[Regressor/Classifier]` interface.
https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.HistGradientBoostingRegressor.html#sklearn.ensemble.HistGradientBoostingRegressor.n_iter_
=> [python][sklearn] add `n_estimators_` and `n_iter_` post-fit attributes

.github/workflows/r_valgrind.yml
The changes coming in #3946 push the timing for the `valgrind` job very close to its current 3-hour limit.
Based on https://github.com/microsoft/LightGBM/pull/3946#issuecomment-960368528, this PR proposes increasing that timeout to 240 minutes.
=> [ci] increase timeout for valgrind job to 240 minutes

.ci/test_windows.ps1
This reverts commit d62378b45314c2688deef7333ae16fcc9863d881.
Something was changed in Windows environments and we don't need that workaround anymore.
=> [ci] Revert temp workaround for `freetype` version

R-package/cran-comments.md
Updating `R-package/cran-comments.md` with a record of the v3.3.1 submission of the R package to CRAN (#4715).
Will keep this as a draft until we see if the submission is successful.
=> [docs] [R-package] update cran-comments for v3.3.1 release

tests/python_package_test/test_plotting.py
New `0.18` version of graphviz was released about 7 hours ago: https://pypi.org/project/graphviz/#history.
In new version something was broken (I guess due to [refactoring the internal class hierarchy](https://github.com/xflr6/graphviz/blob/master/CHANGES.rst#version-018)) and default value for the `filename` argument was changed.
> **filename** – Filename for saving the source (defaults to `name` + `'.gv'`).
https://graphviz.readthedocs.io/en/stable/api.html#graphviz.Digraph
So our test started to fail with the following assertion error:
```
graph.render(view=False)
assert isinstance(graph, graphviz.Digraph)
assert graph.name == 'Tree4'
>       assert graph.filename == 'Tree4.gv'
E       AssertionError: assert 'Digraph.gv' == 'Tree4.gv'
E         - Tree4.gv
E         + Digraph.gv
``` …
=> [ci][tests][python] remove assertion for `filename` that is no longer true with new version of graphviz

python-package/lightgbm/sklearn.py
This PR proposes adding links to the specific estimator class in the Return doc for `.fit()` methods in LightGBM's scikit-learn interface.
Based on @jmoralez 's suggestion: https://github.com/microsoft/LightGBM/pull/4716#issuecomment-952033373
```shell
cd docs
make clean html
open _build/html/index.html
```
Looks like the docs are rendering correctly.
I also clicked through the links next to `Return type` and confirmed that they link back to the constructor docs for the relevant class.
=> [docs] add specific estimator names to sklearn fit() docs

python-package/lightgbm/basic.py, tests/python_package_test/test_utilities.py
=> Suppress categorical warning (fixes #3379)

src/treelearner/serial_tree_learner.cpp, src/treelearner/serial_tree_learner.h, tests/python_package_test/test_engine.py
Fixes #4601.
Root cause for this issue: The histogram for the force split feature might not construct if feature_fraction < 1.0. And it would failed at SplitInner.
- Only col-wise histogram construction impacted.  row-wise histogram construction would go through all features.
- Only force split settings gain > 0 impacted. If no gain for force_split leaf, the force_split settings would be auto ignored.
=> Always respect forced splits, even when feature_fraction < 1.0 (fixes #4601)

python-package/lightgbm/sklearn.py, tests/python_package_test/test_sklearn.py
I believe this is quite odd to add objective alias used in sklearn (`loss` #4637) and simply ignore any objective aliases at the same time.
=> [python][sklearn] respect objective aliases

R-package/R/aliases.R, R-package/tests/testthat/test_basic.R, docs/Parameters.rst, include/LightGBM/config.h, python-package/lightgbm/basic.py, src/io/config_auto.cpp
This PR addresses #4743, adding `nrounds` as an alias for `num_iterations` so that (within the R package) the top-level `nrounds` parameter may also be passed to the `params` argument of `lightgbm` and `lgb.train`. 
I followed the template of #4637 and the new tests work on my machine (:tm:). Please let me know if I missed anything!
=> Add 'nrounds' as an alias for 'num_iterations' (fixes #4743)

python-package/lightgbm/basic.py, python-package/lightgbm/compat.py
* Faster categorical column names selection
Change slow and redundant dataframe query by select_dtypes into a dataframe.dtypes list comprehension
=> [python] Faster categorical column names selection

CMakeLists.txt, cmake/modules/FindLibR.cmake
Contributes to #4602.
Fix all
- `Expression repeated inside endif; better to use only endif() [readability/logic]`
- `Expression repeated inside endfunction; better to use only endfunction() [readability/logic]`
errors.
=> [ci] use pure `endif()` and `endfunction()` without expression inside in `CMakeLists.txt`

.ci/test.sh, include/LightGBM/c_api.h, python-package/lightgbm/basic.py, src/c_api.cpp
Mentioned in https://github.com/microsoft/LightGBM/issues/4609, these edits improve ANSI C compatibility by removing reliance on stdbool.h. These edits may cause a compiler warning for existing code which passes a `_Bool` pointer as `out`. However, given the brief tenure of ANSI C compatibility, it seems unlikely there will be much breakage.
=> [c_api] Improve ANSI compatibility by avoiding <stdbool.h>

README.md, docs/Parameters.rst, include/LightGBM/boosting.h, include/LightGBM/config.h, include/LightGBM/dataset.h, include/LightGBM/utils/common.h, include/LightGBM/utils/text_reader.h, src/application/predictor.hpp, src/boosting/gbdt.cpp, src/boosting/gbdt.h, src/boosting/gbdt_model_text.cpp, src/io/config_auto.cpp, src/io/dataset_loader.cpp, src/io/parser.cpp, tests/python_package_test/test_basic.py
Currently, lightGBM can only support three text data formats (tsv, csv, libsvm), and data type check process is kind of coarse. For example, a tsv may be judged as libsvm if there is string feature containing colon. Besides, lightGBM does not support feature transformation, users need to do separate transformation themselves, which may be a bit inconvenient.
In this PR, we'd like to add customized parser to unlock free data preprocessing scenario. Users could use lightgbm as dependency, and follow `parser` interface to design their own parsers or could simply try [freeform parser](https://github.com/microsoft/lightgbm-transform/blob/main/examples/freeform2_parser.cpp). 
Compared to separate transformation. this way has several pros:
- More efficient. Data preprocessing can go with parsing …
=> Add customized parser support

.ci/get_workflow_status.py
Refer to https://docs.github.com/en/rest/reference/issues#list-issue-comments.
In https://github.com/microsoft/LightGBM/pull/3234#issuecomment-970129705 script cannot update status for Solaris CI build because it doesn't receive the latest comments in that PR.
=> [ci] fix getting status of optional workflows in PRs with a lot of comments

.vsts-ci.yml
Fixed #4810.
**DO NOT MERGE** before uncommenting `# condition: not(startsWith(variables['Build.SourceBranch'], 'refs/pull/'))`.
=> [ci] Fix CI job for R artifact

R-package/DESCRIPTION
The R package has R6 as a 'Depends', which causes it to load it fully into the namespace when loading lightgbm. This is not actually required since only one function from this package is used in the R code, and this function is prefixed with `R6::`. This PR moves to 'Imports' instead so that it doesn't load its full namespace in user sessions.
Also it updates the dependency on R to 3.6, since after the latest PRs it won't compile with R 3.5 anymore due to headers not having all the function prototypes.
=> [R-package] Move R6 to Imports

python-package/lightgbm/basic.py
Pass keys that should be ignored during comparing to make `_compare_params_for_warning()` function reusable.
Function was introduced in #4768.
=> [python] add type hints to `_compare_params_for_warning()` and make it reusable

python-package/lightgbm/basic.py, python-package/lightgbm/engine.py, python-package/lightgbm/sklearn.py
According to https://github.com/microsoft/LightGBM/issues/3756#issuecomment-907622141.
Follow-up PR after #4547.
Based on the investigation from the following thread: https://github.com/microsoft/LightGBM/pull/4547#discussion_r695989171.
=> [python][docs] fix type hints for custom functions and remove vague `array-like` wording

python-package/lightgbm/__init__.py, python-package/lightgbm/callback.py
=> [python] Remove `print_evaluation()` function

python-package/lightgbm/plotting.py
=> [python] remove "auto" value of `ylabel` argument of `plot_metric()` function

examples/python-guide/advanced_example.py, python-package/lightgbm/engine.py
=> [python] remove `learning_rates` argument of `train()` function

python-package/lightgbm/compat.py, python-package/setup.py
This PR adds `# type: ignore` comments to suppress two `mypy` warnings.
> python-package/lightgbm/compat.py:30: error: Name "pd_CategoricalDtype" already defined (possibly by an import)
python-package/setup.py:43: error: "Path" not callable
Confirmed that this suppresses these warnings by running the following.
```shell
mypy \
```
I think it's appropriate to use `# type: ignore` in these two cases since they are somewhat non-standard and the types of cases that type-checkers can struggle with. One is a use of `exec` and one is an import preceded by two other try-catched imports.
=> [python-package] fix mypy errors in compat.py and setup.py

python-package/lightgbm/dask.py
This PR fixes one `mypy` error in `dask.py`.
> python-package/lightgbm/dask.py:933: error: Need type annotation for "out"
Confirmed that this suppresses these warnings by running the following.
```shell
mypy \
```
=> [python-package] fix mypy error about missing type hint in dask.py

python-package/lightgbm/plotting.py
This PR fixes `mypy` errors in `plotting.py`.
> python-package/lightgbm/plotting.py:243: error: Value of type "Union[int, str, None]" is not indexable
python-package/lightgbm/plotting.py:243: error: Unsupported left operand type for - ("str")
python-package/lightgbm/plotting.py:243: note: Both left and right operands are unions
python-package/lightgbm/plotting.py:244: error: Unsupported operand types for / ("str" and "int")
python-package/lightgbm/plotting.py:244: note: Left operand is of type "Union[Any, str]"
python-package/lightgbm/plotting.py:244: error: Value of type "Union[int, str, None]" is not indexable
python-package/lightgbm/plotting.py:256: error: Value of type "Union[int, str, None]" is not indexable
python-package/lightgbm/plotting.py:256: error: …
=> [python-package] fix mypy errors in plotting.py

python-package/lightgbm/sklearn.py
This PR fixes `mypy` errors in `sklearn.py`.
> python-package/lightgbm/sklearn.py:532: error: Need type annotation for "_other_params" (hint: "_other_params: Dict[<type>, <type>] = ...")
python-package/lightgbm/sklearn.py:879: error: "None" has no attribute "current_iteration"
python-package/lightgbm/sklearn.py:890: error: "None" has no attribute "current_iteration"
python-package/lightgbm/sklearn.py:944: error: Item "None" of "Optional[str]" has no attribute "replace"
python-package/lightgbm/sklearn.py:1011: error: Item "None" of "Optional[str]" has no attribute "replace"
python-package/lightgbm/sklearn.py:1110: error: Item "None" of "Optional[str]" has no attribute "replace"
Confirmed that this suppresses these warnings by running the following.
```shell
mypy \ …
```
=> [python-package] fix mypy errors in sklearn.py

python-package/lightgbm/dask.py
This PR fixes a few `mypy` errors in `dask.py`
> python-package/lightgbm/dask.py:1144: error: Item "None" of "Optional[str]" has no attribute "partition"
python-package/lightgbm/dask.py:1327: error: Item "None" of "Optional[str]" has no attribute "partition"
python-package/lightgbm/dask.py:1490: error: Item "None" of "Optional[str]" has no attribute "partition"
Confirmed that this suppresses these warnings by running the following.
```shell
mypy \
```
=> [python-package] [dask] fix mypy errors from dask.py docstrings

python-package/lightgbm/callback.py, python-package/lightgbm/engine.py
This PR fixes `mypy` errors in `engine.py`
> python-package/lightgbm/engine.py:226: error: Incompatible types in assignment (expression has type "Set[<nothing>]", variable has type "Optional[List[Callable[..., Any]]]")
python-package/lightgbm/engine.py:230: error: Incompatible types in assignment (expression has type "Set[Callable[..., Any]]", variable has type "Optional[List[Callable[..., Any]]]")
python-package/lightgbm/engine.py:242: error: Item "List[Callable[..., Any]]" of "Optional[List[Callable[..., Any]]]" has no attribute "add"
python-package/lightgbm/engine.py:242: error: Item "None" of "Optional[List[Callable[..., Any]]]" has no attribute "add"
python-package/lightgbm/engine.py:244: error: Item "List[Callable[..., Any]]" of "Optional[List[Callable[..., …
=> [python-package] fix mypy errors in engine.py

build-cran-package.sh
Discovered tonight while testing things for #4813 that there was a small issue introduced in #4775.
```shell
```
> invalid argument '--no-build-vignettes'
This PR fixes it. This project doesn't have any CI jobs that use that option, but I tested it locally.
=> [R-package] fix `--no-build-vignettes` option for `build-cran-package.sh`

helpers/parameter_generator.py, python-package/lightgbm/sklearn.py
I checked the Python code in this project tonight with `flake8`, and found a few unused imports. This PR proposes removing them.
```shell
flake8 --ignore=E501,E2,E302,E713 ./helpers/
```
> ./helpers/parameter_generator.py:11:1: F401 'typing.Any' imported but unused
./helpers/parameter_generator.py:11:1: F401 'typing.Optional' imported but unused
```shell
flake8 --ignore=E501,E2,E302,E713 ./python-package/
```
> ./python-package/lightgbm/sklearn.py:10:1: F401 '.callback.log_evaluation' imported but unused
=> [python-package] remove unused imports

python-package/lightgbm/sklearn.py, tests/python_package_test/test_dask.py
Do not replace default `0` with `None` in sklearn wrapper.
https://github.com/microsoft/LightGBM/blob/e048a6b409ff72cd2f563b05689ec082bd2e4635/python-package/lightgbm/engine.py#L270
Refer to https://github.com/microsoft/LightGBM/pull/4574#issuecomment-908810538.
=> [python][sklearn] unify values of `best_iteration` for sklearn and standard APIs

python-package/lightgbm/callback.py
Python 2 support was dropped for this project in #3581.
With Python 3 we can use [`nonlocal` statement](https://docs.python.org/3/reference/simple_stmts.html#the-nonlocal-statement) instead of wrapping variables into lists as a [workaround](https://stackoverflow.com/a/52667047) for `UnboundLocalError` in nested function scopes.
This workaround was introduced in https://github.com/microsoft/LightGBM/pull/1895#discussion_r240008496 when we had to support Python 2.
Found this during investigating the failures in #4846.
=> [python] remove workaround for `UnboundLocalError` in early stopping callback for Python 2

R-package/R/lgb.Booster.R
Contributes to #4226.
This PR removes support for passing anything through `...` in `Booster$reset_parameter()`.
=> [R-package] remove support for '...' in Booster reset_parameter()

R-package/R/lgb.Booster.R, R-package/man/predict.lgb.Booster.Rd
Contributes to #4226.
This PR removes support for passing anything through `...` in `predict.lgb.Booster()` and `Booster$predict()`.
=> [R-package] remove support for '...' in predict()

python-package/lightgbm/dask.py
This PR fixes a `mypy` error in `dask.py`
> python-package/lightgbm/dask.py:726: error: Argument "worker_addresses" to "_machines_to_worker_map" has incompatible type "KeysView[Any]"; expected "List[str]"
Confirmed that this suppresses the error by running the following.
```shell
mypy \
```
=> [python-package] [dask] fix mypy error about worker_addresses

python-package/lightgbm/dask.py, tests/python_package_test/test_dask.py
This PR fixes `mypy` errors in `dask.py`
> python-package/lightgbm/dask.py:99: error: Invalid index type "Optional[str]" for "Dict[str, _HostWorkers]"; expected type "str"
python-package/lightgbm/dask.py:383: error: Invalid index type "Optional[str]" for "defaultdict[str, Set[int]]"; expected type "str"
This is `mypy` correctly pointing out the `urlparse(something).hostname` can be `None`, but `lightgbm.dask` treats as if it is guaranteed to be non-None.
```python
from urllib.parse import urlparse
print(urlparse("https://127.0.0.1:123").hostname)
print(urlparse("127.0.0.1:123").hostname)
```
The changes in this PR add explicit handling for that case, so that if it happens `lightgbm` will raise a more specific and helpful error.
Confirmed that this suppresses the …
=> [python-package][dask] handle failures parsing worker host names

R-package/R/lgb.cv.R, R-package/man/lgb.cv.Rd, R-package/tests/testthat/test_basic.R, R-package/tests/testthat/test_learning_to_rank.R
Contributes to #4226.
This PR removes support for passing anything through `...` in `lgb.cv().
=> [R-package] remove support for '...' in lgb.cv()

R-package/DESCRIPTION
This PR proposes adding @mayer79 to the list of contributors in `R-package/DESCRIPTION`, acknowledging his great contributions to the project and especially to the R package.
* introducing the first vignette (#3946)
* fixing a critical bug where training could fail silently on integer data (#3140)
* fixing a bug in weighted gamma loss (#4283)
* contributing to important conversations about the R package, like #4226, #4319 and others
=> [R-package] [docs] add Michael Mayer to DESCRIPTION

R-package/R/lgb.Dataset.R, R-package/man/lgb.Dataset.Rd, R-package/man/lgb.Dataset.create.valid.Rd, R-package/man/lgb_shared_dataset_params.Rd
Contributes to #4543.
This PR proposes removing the keyword argument `info` from functions used for creating and manipulating `Dataset`s. After this PR, users of the R package will have to provide `init_score`, `label`, `weight`, and `group` via the keyword arguments added in #4573.
This PR is focused only on the *public* parts of the package's API. A future PR might propose replacing `Dataset$private$info` with e.g. `Dataset$private$init_score`, `Dataset$private$label`.
=> [R-package] remove support for 'info' in Dataset

R-package/R/lgb.train.R, R-package/R/lightgbm.R, R-package/man/lgb.train.Rd, R-package/man/lightgbm.Rd, R-package/tests/testthat/test_Predictor.R, R-package/tests/testthat/test_basic.R, R-package/tests/testthat/test_lgb.Booster.R, R-package/tests/testthat/test_lgb.interprete.R, R-package/tests/testthat/test_lgb.plot.interpretation.R, R-package/tests/testthat/test_lgb.unloader.R, R-package/tests/testthat/test_parameters.R, R-package/vignettes/basic_walkthrough.Rmd
Contributes to #4226.
This PR removes support for passing anything through `...` in  `lgb.train()`.
=> [R-package] remove support for '...' in lgb.train()

python-package/lightgbm/callback.py, tests/python_package_test/test_sklearn.py
Right now `early_stopping()` callback cannot be used with scikit-learn's `GridSearchCV` tool due to that storages for metric results are not cleaned after early stopping occurs. This results in **comparing current results with the best iteration for the first grid iteration for the first fold**.
This was spotted by our `test_grid_search` test
https://github.com/microsoft/LightGBM/blob/fe535a0e9dfb251fcc85dd33fb0bf193d022fe90/tests/python_package_test/test_sklearn.py#L276
which fails with early stopping setup passed via callback with the following error
```
>       assert grid.best_estimator_.best_score_['valid_0']['multi_logloss'] < 0.25
E       assert 0.5915701709051111 < 0.25
../tests/python_package_test/test_sklearn.py:318: AssertionError
```
This PR proposes resetting all global …
=> [python] reset storages in early stopping callback after finishing training

R-package/R/lgb.Dataset.R, R-package/man/dim.Rd
Contributes to #4226 and #4543.
This PR removes support for passing anything through ... in `dim.lgb.Booster()`.
=> [R-package] remove support for '...' in `dim.lgb.Dataset()`

R-package/R/lgb.Dataset.R, R-package/man/lgb.Dataset.Rd, R-package/tests/testthat/test_basic.R
Contributes to #4226 and #4543.
This PR removes support for passing anything through ... in `lgb.Dataset()`.
=> [R-package] remove support for '...' in `lgb.Dataset()`

R-package/R/lgb.Dataset.R, R-package/man/slice.Rd, R-package/tests/testthat/test_dataset.R
Contributes to #4226 and #4543.
This PR removes support for passing anything through `...` in `lgb.Dataset.slice()` and `Dataset$slice()`.
=> [R-package] remove support for '...' in `slice()`

examples/python-guide/notebooks/interactive_plot_example.ipynb, examples/python-guide/plot_example.py, python-package/lightgbm/engine.py, tests/python_package_test/test_engine.py, tests/python_package_test/test_plotting.py
=> [python] remove `verbose_eval` argument of `train()` and `cv()` functions

.appveyor.yml, .ci/test.sh, .github/workflows/python_package.yml, .vsts-ci.yml, python-package/setup.py
Python 3.6 is reaching its End of Life next week and no need to support it anymore.
https://devguide.python.org/#branchstatus
=> [python] Drop Python 3.6 support

python-package/lightgbm/sklearn.py, tests/python_package_test/test_sklearn.py
Simplify codebase and unify standard and sklearn interfaces.
Similarly to #4845.
=> [python][sklearn] do not replace empty dict with `None` for `evals_result_`

.github/workflows/python_package.yml, python-package/lightgbm/callback.py, tests/python_package_test/test_sklearn.py
Similarly to #4868.
Also, simplify early stopping callback by unconditionally reset all storages at the first iteration. This is much easier than tracking `inited` nonlocal flag (refer to https://github.com/microsoft/LightGBM/pull/4868#issuecomment-989456487).
=> [python] reset storage in record evaluation callback each time before starting training

tests/python_package_test/test_engine.py, tests/python_package_test/test_sklearn.py, tests/python_package_test/utils.py
Contributes to #4793.
Replaces the `load_boston` function with `make_synthetic_regression` (which calls `sklearn.datasets.make_regression`) in the tests that don't make assertions about the score of the model.
=> [tests][python-package] change boston dataset to synthetic dataset in tests that don't check score

R-package/tests/testthat/test_basic.R, R-package/tests/testthat/test_custom_objective.R, R-package/tests/testthat/test_dataset.R, R-package/tests/testthat/test_learning_to_rank.R, R-package/tests/testthat/test_lgb.Booster.R
Contributes to #4862.
This PR proposes the next batch of changes to reduce the verbosity of the R package tests.
See testing instructions in description of #4879.
This PR reduces the R package test logs from 2984 lines to 2871.
=> [R-package] reduce verbosity in tests using lgb.train()

R-package/R/lgb.Dataset.R, R-package/R/lgb.cv.R, R-package/R/utils.R
I've been looking more closely at the R package recently, and noticed a few comments that are either uninformative or provide typos. This PR proposes cleaning them up.
=> [R-package] remove unnecessary comments and fix typos in comments

R-package/R/lgb.cv.R, R-package/tests/testthat/test_basic.R
=> [R-package] fix CVBooster reset_parameter() method (fixes #4900)

examples/python-guide/notebooks/interactive_plot_example.ipynb, examples/python-guide/plot_example.py, python-package/lightgbm/engine.py, tests/python_package_test/test_engine.py, tests/python_package_test/test_plotting.py
=> [python] remove `evals_result` argument of `train()` function

src/io/dataset_loader.cpp
Sample data is useless after BinMapper is constructed, but the corresponding memory is still there before feature extraction is finished.
=> clear memory allocated for sampled data when constructing Dataset from text file

R-package/R/lgb.cv.R, R-package/R/lgb.train.R, R-package/tests/testthat/test_basic.R
Related to #4667.
Related to #4862.
While investigating #4667, I noticed a small inconsistency in `lgb.train()` and `lgb.cv()`. Those functions have a keyword argument `verbose` and update the parameter `verbose` in parameters passed down to `LGBM_BoosterCreate`.
https://github.com/microsoft/LightGBM/blob/7b10baffb6e600862b087a4207343b0b58eed2b5/R-package/R/lgb.cv.R#L105
https://github.com/microsoft/LightGBM/blob/7b10baffb6e600862b087a4207343b0b58eed2b5/R-package/R/lgb.train.R#L77
As a result, if you pass different values for `verbosity` (in `params`) and `verbose` (via keyword arguments), then the Booster's parameters will contain both `verbosity` and `verbose`.
Consider this example:
```r
data("agaricus.train")
dtrain <- lightgbm::lgb.Dataset(
data = …
```
=> [R-package] update parameter 'verbosity' based on keyword arg 'verbose'

docs/Parameters-Tuning.rst, docs/Python-Intro.rst, examples/python-guide/simple_example.py, python-package/lightgbm/callback.py, python-package/lightgbm/engine.py, tests/python_package_test/test_engine.py
=> [python] remove `early_stopping_rounds` argument of `train()` and `cv()` functions

R-package/R/lgb.cv.R, R-package/man/lgb.cv.Rd, R-package/tests/testthat/test_basic.R
Attempt to solve https://github.com/microsoft/LightGBM/issues/4911 
If we set `eval_train_metric = TRUE` in `lgb.cv()`, then we get output like 
[1] "[50]:  train's binary_logloss:0.248276+0.00109575  valid's binary_logloss:0.248655+0.00448549"
The resulting object "cvm" contains the information in the `record_evals` slot and the average training performance of the best round could be found by something like `cvm$record_evals$train$binary_logloss$eval[[cvm$best_iter]]`.
There is no unit test yet, but that does not mean we shouldn't write one.
=> [R-package] added argument eval_train_metric to lgb.cv() (fixes #4911)

R-package/tests/testthat/test_basic.R, R-package/tests/testthat/test_dataset.R, R-package/tests/testthat/test_learning_to_rank.R, R-package/tests/testthat/test_lgb.convert_with_rules.R
Similar to #4915, this PR proposes removing `{lightgbm}`'s use of a `{testthat}` function that is currently deprecated.
From the vignette describing `{testthat}` 3.x ([link](https://github.com/r-lib/testthat/blob/f8ccf033a74d89e2d1d3cb2ec3c6c4f63ca69055/vignettes/third-edition.Rmd#L78-L79)), which was first released in October 2020 ([link](https://cran.r-project.org/src/contrib/Archive/testthat/))
> `expect_is()` is deprecated in favour of the more specific `expect_type()`, `expect_s3_class()`, and `expect_s4_class()`.
This ensures that you check the expected class along with the expected OO system.
This PR proposes removing uses of `expect_is()` in the R package's tests. It proposes replacing them with `expect_true(methods::is())` instead of the newest `{testthat}` because those 3 …
=> [R-package][tests] remove uses of `testthat::expect_is()`

R-package/R/utils.R, R-package/tests/testthat/test_utils.R
Fixes #4521.
When LightGBM's core library finds duplicates provided in params, it emits a warning-level log message and uses the value from the first instance of that parameter encountered while parsing parameters.
The R package doesn't enforce uniqueness of parameter names either, but due to a bug in how it converts an R list of parameters to a string, the warning message generated when duplicate parameters are passed is currently incorrect.
This PR proposes fixing that.
=> [R-package] fix handling of duplicate parameters (fixes #4521)

R-package/tests/testthat/test_Predictor.R, R-package/tests/testthat/test_basic.R, R-package/tests/testthat/test_custom_objective.R, R-package/tests/testthat/test_dataset.R, R-package/tests/testthat/test_learning_to_rank.R, R-package/tests/testthat/test_lgb.Booster.R, R-package/tests/testthat/test_lgb.convert_with_rules.R, R-package/tests/testthat/test_lgb.importance.R, R-package/tests/testthat/test_lgb.interprete.R, R-package/tests/testthat/test_lgb.plot.importance.R, R-package/tests/testthat/test_lgb.plot.interpretation.R, R-package/tests/testthat/test_lgb.unloader.R, R-package/tests/testthat/test_metrics.R, R-package/tests/testthat/test_parameters.R, R-package/tests/testthat/test_utils.R, R-package/tests/testthat/test_weighted_loss.R
Older versions of `{testthat}` required the use of a function, `testthat::context()`, to separate tests in reporting output.
`{testthat}` has been moving away from requiring that, instead preferring to group tests results by test file name, the way `pytest` does.
From the testthat docs ([link](https://testthat.r-lib.org/reference/context.html))
> Use of `context()` is no longer recommended. Instead omit it, and messages will use the name of the file instead. This ensures that the context and test file name are always in sync.
And from the vignette describing `{testthat}` 3.x ([link](https://github.com/r-lib/testthat/blob/f8ccf033a74d89e2d1d3cb2ec3c6c4f63ca69055/vignettes/third-edition.Rmd#L75-L76)), which was first released in October 2020 …
=> [R-package] [tests] remove uses of testthat::context()

R-package/R/lgb.cv.R, R-package/R/lgb.train.R, R-package/tests/testthat/test_basic.R
Similar to #4903, this PR proposes changes to ensure that parameter aliases in `lgb.train()` and `lgb.cv()` are handled correctly in the R package.
Currently, internal helper functions access `params$objective` and `params$metric` directly, without considering aliases.
https://github.com/microsoft/LightGBM/blob/ce486e5b45a6f5e67743e14765ed139ff8d532e5/R-package/R/utils.R#L168
https://github.com/microsoft/LightGBM/blob/ce486e5b45a6f5e67743e14765ed139ff8d532e5/R-package/R/utils.R#L194
As a result, it's not possible today to use any of [the aliases for `objective`](https://lightgbm.readthedocs.io/en/latest/Parameters.html#objective) with `lgb.train()` and `lgb.cv()`.
```r
data("agaricus.train", package = "lightgbm")
dtrain <- lgb.Dataset(
data = …
```
=> [R-package] respect aliases for objective and metric and lgb.train() and lgb.cv()

R-package/DESCRIPTION, R-package/README.md, R-package/tests/testthat/test_lgb.unloader.R
Fixes #4919.
See the discussion in #4919, especially https://github.com/microsoft/LightGBM/issues/4919#issuecomment-1003267201, for an explanation of the changes in this PR.
Running the instructions in the R package README as of this branch, I found that the test results from `{covr}` match my expectations and seem correct.
<details><summary>lightgbm coverage - 55.65% (click me)</summary>
```text
lightgbm Coverage: 55.65%
R/lgb.drop_serialized.R: 0.00%
R/lgb.unloader.R: 0.00%
src/boosting/goss.hpp: 0.00%
src/boosting/rf.hpp: 0.00%
src/include/Eigen/src/Core/Map.h: 0.00%
src/include/Eigen/src/Core/products/GeneralMatrixVector.h: 0.00%
src/include/Eigen/src/Core/products/Parallelizer.h: 0.00%
src/include/Eigen/src/Core/Stride.h: 0.00%
src/include/Eigen/src/Core/Transpose.h: 0.00% …
```
=> [R-package] [docs] fix calculation of R test coverage (fixes #4919)

src/network/socket_wrapper.hpp
Recently I've got an email from CRAN. LightGBM needs a small fix to work for updated R-devel/R 4.2 on Windows. I've applied the patch provided by CRAN in this PR.
Maybe we need a minor version update for this patch to update our CRAN package.
=> [R-package] Apply patch for R4.2 on Windows

.github/workflows/cuda.yml
https://catalog.ngc.nvidia.com/orgs/nvidia/containers/cuda/tags
They have finally resolved internal problems with pipelines recently:
> Jesus Alvarez `@jesusa` · 2 months ago
Hey all, we are having some troubles with our test runner that should be resolved next week. Until then we have published the docker scripts for 11.5 images to here ...
https://gitlab.com/nvidia/container-images/cuda/-/issues/142#note_718947207
> Jesus Alvarez `@jesusa` · 2 days ago
Hi all. Was on break last two weeks. We now have our internal pipelines fixed. Cuda images for 11.5.0, 11.5.1, and 11.4.3 will go out in the next few days.
https://gitlab.com/nvidia/container-images/cuda/-/issues/142#note_803578322
=> [ci] bump CUDA version from 11.4.2 to 11.5.0 at CI

R-package/R/lgb.Booster.R, R-package/R/lgb.cv.R, R-package/R/lgb.train.R
As the best of my knowledge, string comparison in R is case-sensitive. I think it's better to use lowercased `"none"` string value for objective parameter to avoid errors.
https://github.com/microsoft/LightGBM/blob/34f949782252d202097539124149e0d5f69000bd/R-package/R/lgb.Booster.R#L247-L250
https://github.com/microsoft/LightGBM/blob/34f949782252d202097539124149e0d5f69000bd/R-package/R/lgb.Booster.R#L864-L866
=> [R-package] Fix custom objective detection in `print.lgb.Booster()`

.github/workflows/r_package.yml
Just to keep the repository codebase consistent. We use either `0` or `-1` as exit code everywhere, see e.g.
https://github.com/microsoft/LightGBM/blob/master/.ci/test.sh
https://github.com/microsoft/LightGBM/blob/master/.github/workflows/cuda.yml
https://github.com/microsoft/LightGBM/blob/master/.github/workflows/r_package.yml
=> [ci] use `-1` for exit code in case of failure

src/objective/regression_objective.hpp
This PR introduces temporaries to save some compuations of `std::exp` in the regression objectives, namely Poisson, Gamma and Tweedie.
=> reduce duplicate computation in poisson, gamma, and tweedie objectives

python-package/lightgbm/basic.py, tests/python_package_test/test_engine.py
**Context**:
This PR aims to close #3038 
**Changes**
* refit method accepts `kwargs_for_dataset` parameter to pass weight parameter to Dataset initialization inside `refit()`.
* refit method accepts `kwargs_for_predict` parameter to pass original params to `predict` method.
**Tests**:
Based on @jtilly example on issue #3038 test that `refit` method returns a valid prediction value when passing `kwargs_for_dataset` or `kwargs_for_predict`.
=> [python-package] support customizing Dataset creation in Booster.refit() (fixes #3038)

.ci/setup.sh, .github/workflows/cuda.yml
https://catalog.ngc.nvidia.com/orgs/nvidia/containers/cuda/tags
Also, revert #4648 according to https://gitlab.com/nvidia/container-images/cuda/-/issues/140#note_806446655.
=> [ci] bump CUDA version from `11.5.0` to `11.5.1` at CI

.appveyor.yml, .ci/test_windows.ps1, .vsts-ci.yml, docker/dockerfile-python, docker/gpu/README.md, docker/gpu/dockerfile.gpu
Continuation of #4953.
Refer to https://github.com/microsoft/LightGBM/pull/4953#issuecomment-1019369234.
=> [ci] use conda-forge in Windows CI jobs and Docker images

tests/python_package_test/test_dask.py, tests/python_package_test/test_engine.py, tests/python_package_test/test_sklearn.py
Compatibility code was needed for versions of dependencies released more than year(s) ago. I think we can decrease maintenance burden by dropping support for quite old versions of dependencies. BTW, new PRs often don't consider support of old versions at all, e.g. #4927.
=> [tests][python] remove compatibility code for old versions in tests

.ci/test.sh, .github/workflows/cuda.yml, .github/workflows/python_package.yml, .vsts-ci.yml, R-package/.Rbuildignore
Refer to #3763.
All dependencies were updated to the latest available stable version.
https://github.com/boostorg/compute/releases/tag/boost-1.78.0
https://gitlab.com/libeigen/eigen/-/releases/3.4.0
~https://github.com/lemire/fast_double_parser/releases/tag/v0.5.0~ see https://github.com/microsoft/LightGBM/pull/4935#issuecomment-1010122490
https://github.com/fmtlib/fmt/releases/tag/8.1.1
=> Update versions of LightGBM dependencies

python-package/setup.py
Fixes #5004.
Replaces #5005.
Add python_requires='>=3.6' for setup().
=> [python] enforce a floor of Python 3.6 (fixes #5004)

python-package/lightgbm/callback.py, python-package/lightgbm/engine.py, tests/python_package_test/test_engine.py
Makes the record_evaluation callback work with the cv function and returns a similar output to the one returned when used with the train function, i.e.
```
{
"train": {"metric1": [...], "metric2": [...]},
"valid": {"metric1": [...], "metric2": [...]}
}
```
Closes #4943.
=> [python-package] make record_evaluation compatible with cv (fixes #4943)

docs/Advanced-Topics.rst, python-package/lightgbm/basic.py, python-package/lightgbm/engine.py, python-package/lightgbm/sklearn.py
Continuation of 2d1caf140a3b0c68f908071277b67c2a842a297b.
Closes #4898.
Similarly to my comment in https://github.com/microsoft/LightGBM/pull/4959#issuecomment-1016996904, there are a lot of places with categorical features description which we should keep in a consistent state.
=> [docs] document rounding behavior of floating point numbers in categorical features

R-package/R/lgb.restore_handle.R, R-package/R/lightgbm.R, R-package/man/lgb.restore_handle.Rd, R-package/man/lightgbm.Rd, R-package/tests/testthat/test_basic.R, R-package/tests/testthat/test_lgb.Booster.R, R-package/tests/testthat/test_parameters.R
ref #4968
The `lightgbm()` function defaults towards dumping the model to disk in a file named `lightgbm.model`. After the last series of changes to the serialization logic, this is perhaps not a reasonable default anymore, since now model objects can be serialized natively and will for example survive session restarts in RStudio and similar, so a user fitting a model would not be prone to inadvertently lose it nor need to use this format for model serialization, thus decreasing the need for having a file in disk.
Among modeling packages, it is rather uncommon to produce a file in disk by default - off the top of my head, the only such R libraries that I can think of are `xgboost` and `catboost`, while most other packages (which rely on Rds for serialization) do not even have the option …
=> [R-package] remove behavior where lightgbm() saves model to disk

src/io/dataset_loader.cpp
Issue: We received [an issue](https://github.com/microsoft/lightgbm-transform/issues/16) in [lightgbm-transform](https://github.com/microsoft/lightgbm-transform), in which user complained that custom parser can not take effect on valid dataset.
Solution: With some investigation, we find it is a bug and could be fixed by passing train dataset parser config to valid dataset loading parser.
=> Pass train dataset parser config to valid dataset loading parser

R-package/R/lgb.cv.R, R-package/R/lgb.train.R, R-package/R/utils.R, R-package/tests/testthat/test_basic.R
From https://github.com/microsoft/LightGBM/pull/4976#discussion_r806384554.
Relates to #4913.
Today, when using `lightgbm::lgb.train()`, if you you pass different values to keyword argument `obj` and parameter `"objective"` in the `params` list, the value passed to the keyword argument will be preferred.
That is inconsistent with the way that the rest of the R package and the Python package works. Across LightGBM language-specific wrapper packages, it's expected that the values from `params` will take precedence over keyword arguments.
This PR proposes changing the R package to ensure that if `objective` or its aliases are passed through `params`, that value takes precedence over the keyword argument.
Normally I'd propose that a change like this go through a deprecation cycle. However, …
=> [R-package] prefer params to keyword argument in lgb.train()

src/objective/regression_objective.hpp, src/treelearner/cuda_tree_learner.cpp
Fixes memory freeing issue described [here](https://github.com/microsoft/LightGBM/issues/4952): allocated GPU memory is not released after training cycle is complete, which leads to constant memory growth while using multiple train() invocations inside the same process (like hyperparameters search).
=> CUDATreeLearner: free GPU memory in destructor if any allocated

docs/Advanced-Topics.rst, docs/Parameters.rst, include/LightGBM/config.h, python-package/lightgbm/basic.py, python-package/lightgbm/engine.py, python-package/lightgbm/sklearn.py
Emphasizes that categorical features **will** be converted to `int` internally, to avoid the confusion that they should be provided as integers in the input data, as was asked in #4932. Also adds information on what will happen if negative values are found.
Here's how that section looks like:
Closes #4932.
=> [docs] clarify that categorical features will be converted to integers internally

.vsts-ci.yml
Workaround for current `master` branch fails.
Almost every Dask test fails with
```
2022-02-20T15:57:32.0565604Z ../tests/python_package_test/test_dask.py:323: 
2022-02-20T15:57:32.0566450Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2022-02-20T15:57:32.0567909Z /home/AzDevOps_azpcontainer/.local/lib/python3.10/site-packages/lightgbm/dask.py:1170: in fit
2022-02-20T15:57:32.0568871Z     return self._lgb_dask_fit(
2022-02-20T15:57:32.0570168Z /home/AzDevOps_azpcontainer/.local/lib/python3.10/site-packages/lightgbm/dask.py:1050: in _lgb_dask_fit
2022-02-20T15:57:32.0571146Z     model = _train(
2022-02-20T15:57:32.0572438Z /home/AzDevOps_azpcontainer/.local/lib/python3.10/site-packages/lightgbm/dask.py:752: in _train
2022-02-20T15:57:32.0573499Z …
```
=> [ci] use Python 3.8 for `bdist` CI job in old Ubuntu container

R-package/R/lgb.cv.R, R-package/R/lgb.train.R, R-package/R/utils.R, R-package/tests/testthat/test_basic.R
Based on https://github.com/microsoft/LightGBM/pull/5007#discussion_r808401098. The R package has an internal function, `lgb.check.obj()`, that has been there since the very beginning of the R package (#168).
All of the things it does or once did are already handled by other parts of the code base.
1. resolve parameter aliases for `objective` and keyword argument
- https://github.com/microsoft/LightGBM/blob/820ae7e65e90860061ec89cc4a1ad0a39b96e051/R-package/R/lgb.train.R#L95-L99
- #4913, #5007
2. extract custom objective functions written in R
- https://github.com/microsoft/LightGBM/blob/820ae7e65e90860061ec89cc4a1ad0a39b96e051/R-package/R/lgb.train.R#L109-L113
3. raise an informative error for unrecognized objectives
- https://github.com/microsoft/LightGBM/blob/d517ba12f2e7862ac533908304d …
=> [R-package] remove internal function lgb.check.obj()

docs/README.rst, docs/conf.py, docs/env.yml
Fixed #4479.
Generated docs for this branch: https://lightgbm.readthedocs.io/en/docs/Python-API.html#scikit-learn-api.
Please note key differences with docs for `master` branch or for b1efc1f5bcf2d85cafe6fad8d2068e7a28d99721 commit (docs for that commit was overwritten by newer version with installed scikit-learn):
=> [docs] improve docs for sklearn wrapper

include/LightGBM/c_api.h
The documentation says that the parameter `nindptr` for `LGBM_BoosterPredictSparseOutput` should be the number of rows plus one, but this is incorrect when the input type is CSC.
It also says that parameter `out_len` will at exit indicate the length of the indices and data, which is also incorrect since the first element it writes is the length of the index pointer.
This PR fixes both.
=> Correct documentation for sparse predictions

python-package/lightgbm/basic.py, python-package/lightgbm/engine.py, python-package/lightgbm/plotting.py, python-package/lightgbm/sklearn.py
I hadn't had a chance to review #4925, so I'm proposing some fixes and my suggestions in a form of a separate follow-up PR. Sorry about that.
=> [python] fixes for supporting 2d numpy arrays for predictions, grads and hess in multiclass custom objective and eval

tests/python_package_test/test_basic.py, tests/python_package_test/test_engine.py
No changes applied to the code, just pure copy-paste.
=> [tests][python] move tests that use `train()` function defined in `engine.py` from `test_basic.py` to `test_engine.py`

.github/workflows/r_package.yml
CI has been blocked for 4 days, due to #5036.
I'm trying to investigate it in #5037, but it's going very slowly because:
1. testing it requires pushing to GitHub and waiting for CI logs (no way to interactively explore the GitHub Actions Windows runners)
2. I'm traveling with limited time to spend on LightGBM
This PR proposes temporarily removing the failing CI job, to unblock development in this repo.
I'll continue working on #5037 to try to restore this job, but I think it's ok to skip it for now.
=> [ci] temporarily remove R3.6 CRAN CI build

docs/Advanced-Topics.rst
Fixed #4676.
Linking #4959.
Unify description with https://lightgbm.readthedocs.io/en/latest/Parameters.html#categorical_feature.
=> [docs] update categorical feature description in Advanced Topics

src/boosting/gbdt.cpp, tests/python_package_test/test_engine.py
In example of #4708, the initial scores can be added twice when for single-leaf trees. This is to fix the duplicate addition.
=> [fix] fix duplicate added initial scores for single-leaf trees

.appveyor.yml, .ci/test_windows.ps1
To workaround the following error on Windows:
```
__________________________ test_create_tree_digraph ___________________________
cmd = ['dot', '-Kdot', '-Tpdf', '-O', 'Tree4.gv'], input_lines = None
encoding = None, capture_output = True, quiet = False
kwargs = {'cwd': None, 'startupinfo': <subprocess.STARTUPINFO object at 0x000000F539A7A988>, 'stderr': -1, 'stdout': -1}
proc = CompletedProcess(args=['dot', '-Kdot', '-Tpdf', '-O', 'Tree4.gv'], returncode=1, stdout=b'', stderr=b'Warning: Could n... json json0 metafile mp pdf pic plain plain-ext png pov ps ps2 svg tif tiff tk vml xdot xdot1.2 xdot1.4 xdot_json\r\n')
def run_check(cmd: typing.Sequence[typing.Union[os.PathLike, str]], *,
input_lines: typing.Optional[BytesOrStrIterator] = None,
encoding: typing.Optional[str] = None, …
```
=> [ci] fix current `master` fails with graphviz-related error

.vsts-ci.yml
Closed #4748.
Refer to https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml and https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md.
I'm not sure but it looks like our new Windows artifacts won't be compatible with VC Redistributable 2015 and 2017.
> Visual Studio versions since Visual Studio 2015 share the same redistributable files. For example, any apps built by the Visual Studio 2015, 2017, 2019, or 2022 toolsets can use the latest Microsoft Visual C++ Redistributable. However, the version of the Microsoft Visual C++ redistributable installed on the machine must be the same or higher than the version of the Visual C++ toolset used to create your application. …
=> Build Windows artifacts in `windows-2019` image instead of `vs2017-win2016`

R-package/R/lgb.cv.R, R-package/tests/testthat/test_basic.R, python-package/lightgbm/engine.py, tests/python_package_test/test_engine.py
This propagates the `best_iteration` attribute in the Python package and the `best_iter` attribute in the R package from the CV Booster to each individual booster in the boosters list. In the Python package this ensures that calling `CVBooster.predict` uses the best iteration in all boosters (closes #4777).
=> [python-package] [R-package] propagate the best iteration of cvbooster into the individual boosters

python-package/lightgbm/basic.py
=> [python-package] Better column dtype logging when column has "bad dtype"

R-package/R/lgb.Dataset.R, R-package/src/lightgbm_R.cpp, R-package/src/lightgbm_R.h, R-package/tests/testthat/test_dataset.R, include/LightGBM/c_api.h, python-package/lightgbm/basic.py, src/c_api.cpp, tests/python_package_test/test_basic.py
This adds the `LGBM_DatasetGetFeatureNumBin` function to the C API to be able to get the number of constructed bins for a feature. I also added this to the Python API as the Dataset method `feature_num_bin` and added a test for it.
Closes #3406.
=> [c-api][python-package][R-package] expose feature num bin

.github/workflows/r_package.yml
Closed #4748.
Related: #5059.
Sorry, I missed in #5059 the point that GitHub Actions shares the same environments with Azure Pipelines.
https://github.com/actions/virtual-environments/issues/4312
https://github.com/actions/virtual-environments/issues/5238
=> [ci] remove Visual Studio 2017 CI job for R-package

src/io/dataset.cpp, tests/python_package_test/test_utilities.py
Fixes #5081.
During `Dataset` construction, LightGBM may drop features for the following reasons:
* all data would end up in one bin (e.g. all missing or otherwise constant)
* not possible to create any bins the satisfy `min_data_in_bin`
* not possible to create any bins that satisfy `min_data_in_leaf`
https://github.com/microsoft/LightGBM/blob/d4cdbcfe1b1db2d48e95665a8b358028c496cdb2/src/io/bin.cpp#L493-L502
If all features in the raw data are dropped for these reasons, the following warning is issued
> [LightGBM] [Warning] There are no meaningful features, as all feature values are constant.
Note that that warning only cites one of the possible reasons a feature is excluded (all values are constant). As a result, sometimes this warning can be confusing or misleading. See the example in …
=> clarify no-meaningful-features warning in Dataset construction (fixes #5081)

src/io/dataset.cpp, src/treelearner/cuda/cuda_histogram_constructor.cu
Currently row-wise histogram construction cannot run successfully with dense data matrix. The check `row_ptr_bit_type` should be skipped here for dense data matrix,
https://github.com/microsoft/LightGBM/blob/60e72d5f4ec5ec2a4d30a53633e1e2d59c81309b/src/treelearner/cuda/cuda_histogram_constructor.cu#L280-L288
In addition, we disable the use of multi-value feature group in `cuda_exp` for now in this PR. Because we don't have an implementation of sparse bin currently, thus using multi-value feature group can be too costly for GPU memory. We force the feature groups to be single-value.
=> [CUDA] Fix row-wise histogram construction with dense data matrix

python-package/lightgbm/callback.py, tests/python_package_test/test_callback.py
Contributes to #5080.
In `master`, `test_log_evaluation_callback_is_picklable()` test fails with
```
============================================================================== FAILURES ==============================================================================
_________________________________________________________ test_log_evaluation_callback_is_picklable[pickle] __________________________________________________________
serializer = 'pickle', tmp_path = WindowsPath('C:/Users/nekit/AppData/Local/Temp/pytest-of-nekit/pytest-26/test_log_evaluation_callback_i0')
@pytest.mark.parametrize('serializer', ["pickle", "joblib", "cloudpickle"])
def test_log_evaluation_callback_is_picklable(serializer, tmp_path):
callback = lgb.log_evaluation(period=42)
tmp_file = tmp_path / …
```
=> [python] make `log_evaluation` callback pickleable

python-package/lightgbm/callback.py, tests/python_package_test/test_callback.py
=> [python] make `record_evaluation` callback pickleable

R-package/tests/testthat/test_basic.R
I noticed the following today in the logs for the R package's tests.
```text
══ Skipped ════════════════════════════════════════════════════════════════════════════════════
1. lightgbm() accepts 'weight' and 'weights' (test_basic.R:2931:1) - Reason: empty test
```
This is coming from a test added recently (#4975). I guess that `{testthat}` skips tests that don't have any `expect_*` calls in them. It looks like this has been the behavior of that package since 2016 (https://github.com/r-lib/testthat/issues/413), I just never noticed it before.
This PR adds assertions to the relevant test, to ensure that it's run.
You can check the `MSVC` R-package CI jobs to see the logs from tests, since for those the CI runs `Rscript testthat.R` instead of `R CMD check`.
=> [R-package] add assertions to test on lightgbm() weights

python-package/lightgbm/callback.py, tests/python_package_test/test_callback.py
=> [python] make `reset_parameter` callback pickleable

R-package/R/lgb.Booster.R, R-package/R/lgb.Dataset.R, R-package/R/lgb.Predictor.R, R-package/demo/multiclass.R, R-package/demo/multiclass_custom_objective.R, R-package/man/predict.lgb.Booster.Rd, R-package/tests/testthat/test_Predictor.R
ref #4968
When requesing a prediction type with several entries per row, the prediction function in the R package by default produces outputs as a 1-D vector in row-major order. This can be quite confusing and lead to user errors when used externally, especially since it is not documented that the output is row-major while R assumes that conversions to matrices are to be done assuming column-major order and uses vectors in column-major order in built-in operators such as `+`, `*`, `[`, or `[<-` and functions such as `sweep`.
What's more, base R's `stats` package and many core R packages for decision tree ensembles such as `ranger` or `randomForest` produce multi-output predictions as a matrix. Examples:
```r
library(ranger)
data(iris)
m <- ranger(Species ~ ., data = iris)
p <- predict(m, …
```
=> [R-package] Remove `reshape` argument in `predict`

.github/workflows/static_analysis.yml, R-package/README.md
Install `RhpcBLASctl` during docs check.
Match list of dependencies in README with one really used in the corresponding CI jobs.
ASAN/UBSAN: https://github.com/microsoft/LightGBM/blob/248fbfa6e8fbf3c284a713681eed4d988e16131d/.github/workflows/r_package.yml#L191
Valgrind: https://github.com/microsoft/LightGBM/blob/248fbfa6e8fbf3c284a713681eed4d988e16131d/.ci/test_r_package_valgrind.sh#L3
=> [R-package] Add missed packages into dependencies list

python-package/lightgbm/basic.py
=> [python-package] remove is_reshape argument in Booster.predict (fixes #5115)

R-package/tests/testthat/test_Predictor.R, R-package/tests/testthat/test_basic.R, R-package/tests/testthat/test_lgb.Booster.R
The R package contains a few tests using the `mtcars` dataset that comes built into R.
That dataset only has 32 observations in it. From `?mtcars`.
```r
data(mtcars)
dim(mtcars)
```
As a result, the calls to `lightgbm()` and `lgb.train()` in tests using that dataset are not currently performing any boosting, for reasons described in #5081.
If setting `verbosity` to something low enough to allow `INFO` and `WARNING` level logs, those tests contain logs like the following:
```text
[LightGBM] [Warning] There are no meaningful features which satisfy the provided configuration. Decreasing Dataset parameters min_data_in_bin or min_data_in_leaf and re-constructing Dataset might resolve this warning.
[LightGBM] [Info] Total Bins 0
[LightGBM] [Info] Number of data points in the train set: 32, …
```
=> [R-package] ensure boosting happens in tests on small datasets

R-package/README.md
This PR proposes adding `--rm` to the `docker run` call in the R package's instructions for re-generating `configure` using `autoconf`.
Per the docs for `docker run` at https://docs.docker.com/engine/reference/run/#clean-up---rm
> By default a container’s file system persists even after the container exits. This makes debugging a lot easier (since you can inspect the final state) and you retain all your data by default. But if you are running short-term foreground processes, these container file systems can really pile up. If instead you’d like Docker to automatically clean up the container and remove the file system when the container exits, you can add the --rm flag
> If you set the `--rm` flag, Docker also removes the anonymous volumes associated with the container when the container …
=> [docs] use 'docker run --rm' in autoconf instructions

R-package/README.md
Adding `--rm` to one more `docker run` instruction in the docs, per https://github.com/microsoft/LightGBM/pull/5125#issuecomment-1088154927.
I ran `git grep 'docker run'` to search for others, and didn't find any more uses in the project that should be updated.
=> [docs] use 'docker run --rm' in valgrind instructions

.github/workflows/no-response.yml
Based on https://github.com/microsoft/LightGBM/issues/5060#issuecomment-1093470783.
Switches the no-response bot to the default GitHub Actions token, so its comments will be posted as the `github-actions` bot user.
=> [ci] have no-response bot post as github-actions user

.ci/test_r_package.sh, .ci/test_r_package_windows.ps1, .github/workflows/r_package.yml, docs/env.yml
Fixes #4990.
Contributes to #3763.
Based on https://github.com/microsoft/LightGBM/pull/5129#issuecomment-1089299960.
Updates R r.x CI jobs to R 4.1.2 ([released last month](https://cran.r-project.org/bin/windows/base/old/)).
Changes R 4.1 Mac CI jobs back to `macOS-latest` environment (reverting a workaround from #4989).
=> [ci] update to R 4.1.3 and use macOS-latest for R jobs (fixes #4990)

R-package/R/aliases.R, R-package/tests/testthat/test_parameters.R
Created in response to https://github.com/microsoft/LightGBM/pull/5122#discussion_r846855854.
For many of LightGBM's supported  parameters (https://lightgbm.readthedocs.io/en/latest/Parameters.html), LightGBM respects multiple *aliases*. For example, `num_iterations=10`, `nrounds=10`, and `num_tree=10` all result in the same behavior.
As a result of this, the R package frequently needs to deal with the possibility that some relevant configuration might be provided via any of these aliases, and sometimes via special keyword arguments in the R package's public API.
Earlier versions of `{lightgbm}` included a hard-coded list of string literals with a mapping from select "main" parameter names to their aliases. To ensure that the package is always in sync with changes on the C++ side, #4829 …
=> [R-package] reduce cost of repeated parameter alias checks

python-package/lightgbm/basic.py
https://github.com/microsoft/LightGBM/blob/b462d0a40f6978c0a66a47af4522c2ae12532316/python-package/lightgbm/basic.py#L453
=> [python] Use predefined constant in feature importance type comparison instead of raw int literal

src/io/dataset_loader.cpp
=> check nullable of bin_mappers in DatasetLoader::CheckCategoricalFeatureNumBin (fix #5145)

.github/workflows/cuda.yml
https://catalog.ngc.nvidia.com/orgs/nvidia/containers/cuda/tags
Linking #3763.
=> [ci] bump CUDA version from `11.5.1` to `11.6.2` at CI

.github/workflows/r_package.yml, .github/workflows/static_analysis.yml
Fixes #5151.
A security vulnerability was recently discovered in `git`, where the use of global git config files like `C:\.git\config`  could allow one user to run arbitrary code as another user. Detailed at https://github.blog/2022-04-12-git-security-vulnerability-announced/.
As reported in https://github.com/actions/checkout/issues/760, something in the combination of how the `checkout` GitHub Action works, how containerized GitHub Actions jobs work, and the security patches published to newer versions of `git` is causing LightGBM's containerized CI jobs on GitHub Actions to fail.
This PR proposes fixing that issue by explicitly telling `git` to trust the directory the `checkout` action clones into.
I hope we'll be able to revert this in the future if/when there is a change to …
=> [ci] fix git checkout for CI jobs (fixes #5151)

.vsts-ci.yml
All `Linux_latest` jobs on Azure Devops started failing a few days ago, because the `ubuntu:latest` tag on DockerHub moved from Ubuntu 20.04 to 22.04.
https://github.com/microsoft/LightGBM/pull/5169#issuecomment-1106413298
https://github.com/microsoft/LightGBM/pull/5169#issuecomment-1107139143
While attempting to fix this on #5169, I ran into the issue from #5106 (https://github.com/microsoft/LightGBM/issues/5106#issuecomment-1107346250). I believe I've identified the root cause there, but I expect fixing it to require significant discussion and effort.
For now, to unblock other development in this project, this PR proposes **temporarily** pinning the `Linux_latest` jobs back to Ubuntu 20.04.
=> [ci] temporarily pin Azure Devops jobs to ubuntu 20.04

src/treelearner/cost_effective_gradient_boosting.hpp, src/treelearner/serial_tree_learner.cpp
Noticed while reviewing #5164.
I suspect that the method `CostEfficientGradientBoosting::DetlaGain()` was supposed to be called `DeltaGain()`. This PR proposes fixing that.
This class isn't part of the library's public API, so this is not a user-facing breaking change.
I used the following to search for all such typos:
```shell
git grep -i detla
```
=> fix typo in CEGB method name

.vsts-ci.yml
I have no idea what is it, but we haven't requested these checks. 😕 
They just increase our overall CI time and are potential places for project-unrelated CI failures.
Taken from here:
https://github.com/achu152/Industrial-IoT/blob/df614129f257dc719369309185b65721906d51ad/tools/templates/ci.yml#L10-L13
Compare:
https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=12641&view=results
https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=12644&view=results
=> [ci] skip auto-injected tasks at Azure Pipelines

src/io/cuda/cuda_row_data.cpp, src/treelearner/cuda/cuda_histogram_constructor.cu
This is to fix integer overflow in `cuda_exp`. When data index is multiplied with the number of features, integer overflow can easily occur if 32-bit integers are used. In this PR, we cast the indices into 64-bit integers whenever necessary.
=> [CUDA] Fix integer overflow in cuda row-wise data

src/c_api.cpp, tests/python_package_test/test_basic.py
When retrieving the number of bins for a given feature the input wasn't checked so if we input an invalid feature index (>= number of features) we could get garbage values or even a segfault, so this adds a check to see if we're in the valid range of feature indices.
=> [c-api] check number of features when retrieving number of bins

R-package/R/lgb.Dataset.R, R-package/tests/testthat/test_dataset.R
=> [R-package] allow use of categorical_features in Dataset when raw data does not have column names (fixes #4374)

src/io/tree.cpp
i found double precision lost in CategoricalDecision, it makes trouble to dump model to a ifelse cpp file for prediction. 
it's my first commit. if some thing make mistake, some advise may be helpful. thanks.
=> fix precision lost in tree's ToIfElse

R-package/DESCRIPTION
Change role of @david-cortes from contributor to author.
David has made [a lot of great contributions](https://github.com/microsoft/LightGBM/commits?author=david-cortes) to the LightGBM project and continues to open new PRs and issues. According to the [following roles description](https://github.com/microsoft/LightGBM/pull/3333#issue-684104863), I believe "aut" is more appropriate role for him.
=> [R-package] update roles in DESCRIPTION

.appveyor.yml, .ci/test_windows.ps1
Fix current `master` failures at Appveyor that happen due to pytest uses `pypy3` as a Python interpreter.
```
The following packages will be DOWNGRADED:
python                        3.7.12-h900ac77_100_cpython --> 3.7.12-0_73_pypy
python_abi                                    3.7-2_cp37m --> 3.7-2_pypy37_pp73
...
============================= test session starts =============================
platform win32 -- Python 3.7.12[pypy-7.3.7-final], pytest-7.1.1, pluggy-1.0.0
...
_________________________________ test_basic __________________________________
self = <class 'ctypes.c_char_p'>, value = 1047415529008
def from_param(self, value):
if isinstance(value, self):
return value
try:
>           as_parameter = value._as_parameter_
E           AttributeError: 'int' object has no attribute …
```
=> [ci] Prevent Python downgrading to pypy on Windows

.appveyor.yml, .ci/test_windows.ps1
Ah, `libxml2` isn't omnipotent as [we thought](https://github.com/microsoft/LightGBM/pull/5197#pullrequestreview-962369155) 🙁 
Appveyor at `master` fails again with the same error as yesterday in #5197 (but only MSVC job this time).
https://ci.appveyor.com/project/guolinke/lightgbm/builds/43451448
=> [ci] Prevent Python downgrading to pypy on Windows (2)

R-package/R/lgb.cv.R, R-package/R/lgb.train.R, R-package/R/lightgbm.R, R-package/tests/testthat/test_basic.R
Contributes to #4862.
Fixes an issue introduced by #4899 .
In the R package, `lightgbm()`, `lgb.train()`, and `lgb.cv()` have a keyword argument `verbose`. #4899 added changes to ensure that that verbosity parameters passed through `params` took precedence over that keyword argument.
However, evaluation and and early stopping callbacks still reference that keyword argument, which can lead to inconsistent behavior where some printed messages' verbosity can only be controlled by the keyword argument.
While working on this, I also discovered another closely-related bug...parameter `verbose` in calls to `cb_early_stop()` is being passed an integer, but that value is then checked with `isTRUE()`...which means that no messages are ever printed from that callback. …
=> [R-package] ensure that callbacks respect verbosity from params

src/boosting/gbdt.h, src/io/dataset_loader.cpp, src/network/linker_topo.cpp, src/objective/binary_objective.hpp, src/objective/multiclass_objective.hpp, src/objective/regression_objective.hpp, src/objective/xentropy_objective.hpp, tests/python_package_test/test_sklearn.py
Reported by https://lgtm.com/projects/g/microsoft/LightGBM?mode=tree&ruleFocus=2157860313.
I used the following suggested workaround:
```cpp
int i = 2000000000;
long l = static_cast<long>(i) * i; //Correct: modern C++
```
https://codeql.github.com/codeql-query-help/cpp/cpp-integer-multiplication-cast-to-long/#example
=> Fix potential overflow "Multiplication result converted to larger type"

R-package/tests/testthat/test_basic.R, R-package/tests/testthat/test_learning_to_rank.R, R-package/tests/testthat/test_lgb.Booster.R
Contributes to #4862.
Silences additional logs produced by the R package's unit tests.
This PR reduces the number of logs printed by the R package's tests from 1616 lines to 636 lines.
```shell
sh build-cran-package --no-build-vignettes
R CMD INSTALL --with-keep.source ./lightgbm_3.3.2.99.tar.gz
cd R-package/tests
Rscript testthat.R > ../../out.log 2>&1
echo "log lines from tests: $(cat ../../out.log | wc -l)"
```
=> [R-package] silence more logs in tests

R-package/demo/weight_param.R
Removes some extra lines that aren't necessary after #5204 and makes minor modifications to the weight descriptions.
=> [R-package] minor improvements on weight demo

.github/CODEOWNERS
Remove inactive persons from the CODEOWNERS file.
Removed persons have been inactive for a long time (or simply never reviewed any PR) and unlikely will return to review new PRs.
CODEOWNERS file is used to automatically assign reviewers for PRs. Keeping this file clean and actual might be important for two reasons:
* outside contributors will be more patient for long delays in reviews when they understand the actual number of persons who are able to give a review;
* active maintainers will be more motivated to provide their reviews and feel greater responsibility for in time replies when they see only a couple of persons among assigned reviewers for a particular PR or that there is no "backup" reviewer for that code changes at all.
However, active maintainers can still ping these removed …
=> Cleanup codeowners

python-package/lightgbm/basic.py, tests/python_package_test/test_basic.py
=> [python-package] make a shallow copy when replacing categorical features with codes (fixes #4596)

.ci/test_r_package.sh, .ci/test_r_package_valgrind.sh, .ci/test_r_package_windows.ps1, .github/workflows/r_package.yml, .github/workflows/static_analysis.yml, .vsts-ci.yml
Created based on https://github.com/microsoft/LightGBM/pull/5227#issuecomment-1133817758.
This project's CI has been blocked for almost a day because cran.r-project.org has been down. According to one of CRAN's maintainers, this is because of an issue with an on-prem apache webserver running in a datacenter in Austria, and it won't be fixed until tomorrow because it's currently the weekend: https://stat.ethz.ch/pipermail/r-devel/2022-May/081750.html.
This PR proposes switching LightGBM's CI to use cran.rstudio.com instead for all its R CI jobs. That mirror is backed by a for-profit company and (I assume) supported by an on-call rotation of engineers who will quickly respond to availability issues. This blog post from 2013 hints how it is architected: …
=> [ci] switch CRAN mirror to RStudio

R-package/R/lgb.Booster.R
Contributes to #5228.
Fixes the following linting issue found by the upcoming v3.0.0 of `{lintr}`:
```text
LightGBM/R-package/R/lgb.Booster.R:723:63: style: Trailing semicolons are not needed.
list with attribute (name, value, higher_better)");
^
```
=> [R-package] remove semicolon in R code

R-package/R/lgb.convert_with_rules.R, R-package/R/utils.R, R-package/tests/testthat/test_learning_to_rank.R, R-package/tests/testthat/test_lgb.Booster.R
In preparation for the release of `{lintr}` 3.0.0 (#5228), this PR proposes changes to the placement of braces in the project's R code.
Without these changes, `{lintr}` 3.0.0 will return the following findings:
```text
LightGBM/R-package/R/lgb.convert_with_rules.R:7:33: style: Opening curly braces should never go on their own line and should always be followed by a new line.
, FUN = function(x) {paste0(class(x), collapse = ",")}
^
LightGBM/R-package/R/lgb.convert_with_rules.R:7:66: style: Closing curly-braces should always be on their own line, unless they are followed by an else.
, FUN = function(x) {paste0(class(x), collapse = ",")}
^
LightGBM/R-package/R/lgb.convert_with_rules.R:43:51: style: Opening curly braces should never go on their own line and should always be followed by a new …
```
=> [R-package] standardize style for placement of braces

python-package/lightgbm/sklearn.py
Adds type hints on the scikit-learn custom objective function and metric function wrappers.
=> [python] add type hints on sklearn metric and eval wrappers

R-package/tests/testthat/test_basic.R, R-package/tests/testthat/test_dataset.R, R-package/tests/testthat/test_lgb.Booster.R
Fixes #4862.
This removes the last remaining log lines from the R tests (other than dots for test statuses).
As described in https://github.com/microsoft/LightGBM/pull/5237#issuecomment-1136142589, when LightGBM's C++ code calls `Log::Fatal()`, the same log message comes through stderr twice:
1. as a log message printed with `REprintf()`
2. as an R exception
I think it makes sense to have both, so that if user code try-catches `{lightgbm}` stuff, suppressing those exceptions, they'll still at least see a log message indicating that the exception happened.
This PR proposes just using `capture.output()` in the R package's tests to keep those logs out of the test output.
=> [R-package] [ci] silence more logs in tests (fixes #4862)

R-package/inst/make-r-def.R, R-package/src/install.libs.R, R-package/tests/testthat/test_basic.R
Contributes to #5228.
Resolves the remaining linter warnings that would be raised by `{lintr}` 3.0.0 once it's released (https://github.com/microsoft/LightGBM/issues/5228#issuecomment-1140355470).
```text
[1] Total linting issues found: 4
[[1]]
/Users/jlamb/repos/LightGBM/R-package/inst/make-r-def.R:74:20: warning: Use file.path() to construct portable file paths.
pattern = "[Ordinal/Name Pointer] Table"
^~~~~~~~~~~~~~~~~~~~~~~~~~~~
[[2]]
/Users/jlamb/repos/LightGBM/R-package/src/install.libs.R:99:4: warning: Use file.path() to construct portable file paths.
"../inst/bin/CMakeLists.txt"
^~~~~~~~~~~~~~~~~~~~~~~~~~
[[3]]
/Users/jlamb/repos/LightGBM/R-package/src/install.libs.R:125:6: warning: Use file.path() to construct portable file paths.
"../../inst/make-r-def.R"
^~~~~~~~~~~~~~~~~~~~~~~ …
```
=> [R-package] address linter warnings about portable paths

python-package/lightgbm/sklearn.py
Adds type hints on some methods in `lightgbm.sklearn.LGBMModel` that don't currently have them.
=> [python] add more type hints on LGBMModel methods

src/io/dataset_loader.cpp
This is to fix #5221. Nullable of `bin_mappers[i]` should be checked. This is a bug introduced by PR #4448 amd was ignored by the fix #5145. Thanks @vollis for finding this out!
=> [c++][fix] check nullable of bin mappers in dataset_loader.cpp (fix #5221)

SECURITY.md
Fixes #5235.
Adds `SECURITY.md` to comply with what appears to be a new Microsoft policy for open source projects (see #5235).
Checking this file in ourselves to prevent granting the bot user `microsoft-github-policy-service` the status of contributor (which would allow it to trigger CI runs by opening PRs).
=> [docs] add Microsoft security policy (fixes #5235)

docs/GPU-Windows.rst
https://github.com/microsoft/LightGBM/runs/6736962389?check_suite_focus=true
```
URL        `http://iweb.dl.sourceforge.net/project/mingw-w64/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/mingw-w64-install.exe'
Name       `this'
Parent URL file:///home/runner/work/LightGBM/LightGBM/docs/_build/html/GPU-Windows.html, line 149, col 47
Real URL   http://iweb.dl.sourceforge.net/project/mingw-w64/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/mingw-w64-install.exe
Check time 120.214 seconds
Result     Error: ConnectionError: HTTPConnectionPool(host='iweb.dl.sourceforge.net', port=80): Max retries exceeded with url: /project/mingw-w64/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/mingw-w64-install.exe (Caused by …
```
=> [docs] Update broken links in docs

python-package/lightgbm/basic.py, tests/python_package_test/test_basic.py
=> [python-package] make a shallow copy on dataframe rename (fixes #4596)

R-package/DESCRIPTION, docs/env.yml
Contributes to #3763.
`{roxygen2}` v 7.2.0 was released 16 days ago (https://cran.r-project.org/web/packages/roxygen2/index.html). This project currently uses v7.1.2.
This PR proposes updating the R package's documentation to use the newest version of `{roxygen2}`.
I regenerated the R package's documentation by running the following.
```shell
Rscript -e "install.packages('roxygen2', repos = 'https://cran.r-project.org')"
R CMD INSTALL --with-keep.source ./lightgbm_3.3.2.tar.gz
cd R-package/
Rscript -e "roxygen2::roxygenize(load = 'installed')"
```
I didn't see this item listed in #3763, so I edited the description there today to include it.
@StrikerRUS could you temporarily enable readthedocs builds for this branch so we can check that this …
=> [R-package] [docs] upgrade docs to roxygen2==7.2.0

python-package/lightgbm/basic.py
Proposes adding a few more hints in `basic.py`. Just quickly scanned through this file tonight and chose a few hints that looked easy to determine just from looking at the code and docstrings, trying to slowly make progress on #3756 as I have time.
=> [python] add more type hints in basic.py

tests/python_package_test/test_basic.py
Sorry, should have proposed that in #5254.
Check that `_data_from_pandas()` doesn't modify column names (doesn't convert int to string) of original data.
Refer to https://github.com/microsoft/LightGBM/pull/5254#pullrequestreview-989794258.
=> [tests][python] Make test that checks original pandas data isn't modified more strict

python-package/lightgbm/basic.py, tests/python_package_test/test_sklearn.py
Proposes removing `Booster.set_attr()` and `Booster.attr()`.
Per https://github.com/microsoft/LightGBM/pull/5255#discussion_r889648818 those functions are not used anywhere. It looks like they may have been copied from `xgboost` around when LightGBM's Python package was first created.
This PR proposes removing them to simplify the interface for `Booster` and reduce the maintenance burden of the project.
=> [python-package] remove Booster.set_attr() and Booster.attr()

.ci/setup.sh, .ci/test.sh, .vsts-ci.yml, docs/GPU-Targets.rst
As discussed in https://github.com/microsoft/LightGBM/pull/5252#discussion_r892772322, I think that using [PoCL](http://portablecl.org) for the Linux `gpu` tests would make a lot of sense, as it is open source and actively maintained, as opposed to the AMD App SDK.
The `dask` tests are currently disabled for the `gpu` task, but they in my local testing the do succeed with PoCL. Should we maybe (re-)enable them?
=> [ci] Run Linux OpenCL tests against POCL instead of the AMD App SDK

R-package/R/lgb.train.R, R-package/R/lightgbm.R, R-package/man/lgb.train.Rd, R-package/man/lightgbm.Rd
Fixes #5203.
This PR proposes making the explanation in https://github.com/microsoft/LightGBM/issues/5203#issuecomment-1124502018 explicit in the R package's documentation.
The main *functional* change proposed in #5203 (decoupling `verbosity` and validation sets in `lightgbm::lightgbm()`) was implemented in #5209.
=> [R-package] [docs] document difference between lightgbm() and lgb.train() (fixes #5203)

.ci/test.sh
Lint jobs started to fail in the CI because a new version of `r-lintr` was released. This PR pins the version to be 2.x.
=> [ci] Pin lintr to <3.0

python-package/lightgbm/compat.py, python-package/lightgbm/dask.py, python-package/lightgbm/sklearn.py, tests/python_package_test/test_consistency.py, tests/python_package_test/test_sklearn.py
The scikit-learn interface for lightgbm has a parameter `n_jobs` with a default value of `-1`, which is interpreted as using the default number of OMP threads.
According to the scikit-learn glossary, a negative `n_jobs` has a different meaning (uses joblib's formula), so `-1` means to use all available threads:
https://scikit-learn.org/stable/glossary.html#term-n_jobs
This PR changes the meaning of negative `n_jobs` to match that of scikit-learn, which I think is how most people would expect scikit-learn compatible libraries to behave.
I'm not sure what kind of requirements are there for the tests that are run on Python. This change *could* be tested, but it would imply fitting models using multiple threads per function call - not sure if there's any issue with that like in the R …
=> [python-package] Use scikit-learn interpretation of negative `n_jobs` and change default to number of cores

python-package/lightgbm/compat.py, python-package/lightgbm/engine.py
This PR proposes adding type hints to `lightgbm.cv()`, to improve `mypy`'s ability to catch issues.
=> [python-package] add type hints on cv()

.ci/setup.sh, .vsts-ci.yml
In cooperation with https://github.com/guolinke/lightgbm-ci-docker/pull/26 (that PR should be merged first, already merged).
=> [ci] Install PoCL in Docker for old Ubuntu 14.04

python-package/lightgbm/basic.py
Proposes adding type hints on a few `Booster` methods. I focused in this PR on the `Booster` constructor and on short, simple methods where the return type was easy to verify just by looking at the code.
=> [python-package] add some type hints on Booster

.ci/lint_r_code.R, R-package/tests/testthat/test_metrics.R
Once merged, closes `any_is_na_linter()` task of #5303
=> [ci] [R-package] Add any_is_na_linter

python-package/lightgbm/sklearn.py
With #5289 merged we can apply the following suggestion: https://github.com/microsoft/LightGBM/pull/5105#discussion_r889631120.
=> [python][sklearn] Simplify params handling in `predict()` with `_choose_param_value()`

.ci/lint_r_code.R, R-package/R/utils.R
Once merged, closes `class_equals_linter()` task of https://github.com/microsoft/LightGBM/issues/5303
Resolves linter warnings raised by {lintr} 3.0.0
``` sh
[[1]]
/home/ccr-gentoo/Projects/LightGBM/R-package/R/utils.R:2:14: warning: [class_equals_linter] Instead of comparing class(x) with %in%, use inherits(x, 'class-name') or is.<class> or is(x, 'class')
return(all(c("R6", "lgb.Booster") %in% class(x)))
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[[2]]
/home/ccr-gentoo/Projects/LightGBM/R-package/R/utils.R:6:14: warning: [class_equals_linter] Instead of comparing class(x) with %in%, use inherits(x, 'class-name') or is.<class> or is(x, 'class')
return(all(c("R6", "lgb.Dataset") %in% class(x)))
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[[3]] …
```
=> [ci] [R-package] Add class_equals linter

.ci/lint_r_code.R
1. Fixes `any_is_na_linter` to `any_is_na` as per rest of the linter convention.
2. Completes following tasks
of #5303
=> [ci] [R-package] Add a few more linters

.ci/lint_r_code.R, R-package/tests/testthat/test_utils.R
Contributes to #5303.
Adds `lintr::duplicate_argument_linter()` to the project's R linting.
=> [ci] [R-package] Add duplicate_argument_linter

docs/conf.py
Noticed on #5320 that the `check-docs` CI job has started failing with the following error.
```text
Warning, treated as error:
Invalid configuration value found: 'language = None'. Update your configuration to a valid langauge code. Falling back to 'en' (English).
make: *** [Makefile:20: html] Error 2
```
Per https://github.com/sphinx-doc/sphinx/pull/10481, it looks like Sphinx no longer accepts `language = None` in configuration. (found that link from https://github.com/rapidsai/cuml/pull/4781, thanks @galipremsagar!).
This PR proposes explicitly setting `language = 'en'` in the project's Sphinx configuration.
=> [docs] set language = 'en' in Sphinx config

python-package/lightgbm/basic.py
Proposes adding type hints on a few Booster methods. Similar to #5302, I focused in this PR on `Booster` methods with simple signatures and return types.
=> [python-package] add more type hints on Booster

.ci/lint_r_code.R, R-package/tests/testthat/test_basic.R, R-package/tests/testthat/test_lgb.Booster.R, build_r.R
Added `string_boundary_linter`.
```
[1] Total linting issues found: 19
[[1]]
/home/r2_gentoo/Projects/LightGBM/build_r.R:407:40: warning: [string_boundary] Use !is.na(x) & startsWith(x, string) to detect a fixed initial substring, or, if missingness is not a concern, just startsWith. Doing so is more readable and more efficient.
c_api_contents <- c_api_contents[grepl("^LIGHTGBM_C_EXPORT", c_api_contents)]
^~~~~~~~~~~~~~~~~~~~
[[2]]
/home/r2_gentoo/Projects/LightGBM/R-package/tests/testthat/test_basic.R:8:13: warning: [string_boundary] Use !is.na(x) & endsWith(x, string) to detect a fixed terminal substring, or, if missingness is not a concern, just endsWith. Doing so is more readable and more efficient.
pattern = "UTF-8$"
^~~~~~~~
[[3]] …
```
=> [ci] [R-package] Add string_boundary_linter

.ci/lint_r_code.R, R-package/R/utils.R
- Use alphabetical order for linters
- Rename `class_equals_linter` -> `class_equals` for the consistency with the rest codebase
=> [ci][R-package] Minor refactoring for `lintr` code

python-package/lightgbm/basic.py
There are no `double` type in Python.
=> [docs][python] Fix return types in docstrings

python-package/lightgbm/basic.py, python-package/lightgbm/sklearn.py
Contributes to #3756 .
Proposes adding type hints on most arguments to `predict()` methods. This PR intentionally skips adding a type hint on argument `X` and the return values...those require a bit of investigation about which subset of "array-like" types are possible (https://github.com/microsoft/LightGBM/issues/3756#issuecomment-907622141), so I think they should be handled in a separate PR narrowly focused on that topic.
=> [python-package] add type hints on predict() methods

python-package/lightgbm/sklearn.py
While working on #3756 (specifically looking at https://github.com/microsoft/LightGBM/issues/3756#issuecomment-907622141), I found that `lightgbm.sklearn.LGBMModel.fit()` contains an inner function, `_construct_dataset()`, which is used to create train and validation `Dataset` objects.
When that function was first introduced back in #113 6 years ago, I believe an internal function was used to ensure that `Dataset.set_init_score()` was called in both placed it's used.
https://github.com/microsoft/LightGBM/blame/c2e94f174824fab42f6cf7affb56484f1f92105f/python-package/lightgbm/sklearn.py#L361-L364
At some point since then, that call has been removed and now this function is just passing values directly through to `Dataset()`.
This PR proposes removing that function in favor of just calling …
=> [python-package] remove inner function _construct_dataset() in LGBMModel.fiit()

python-package/lightgbm/basic.py, tests/python_package_test/test_engine.py
Builds on #4909 adding the `validate_features` argument to the `Booster.refit` method.
=> [python-package] add validate_features argument to refit

python-package/lightgbm/basic.py
This PR adds some type hints on the `lightgbm.basic.Dataset`. For this PR, I focused on adding hints in just a few places where the correct hints seemed very clear (for example, methods that only accept and return `self`).
=> [python-package] add type hints on Dataset

R-package/R/lgb.Booster.R, R-package/tests/testthat/test_custom_objective.R
Adds a check to verify that the shapes of grad and hess are correct (same as the number of predictions) to raise an informative error when they're not. This is similar to the one added in #4815 for the python-package.
Fixes #5323.
=> [R-package] raise an informative error when custom objective produces incorrect output (fixes #5323)

include/LightGBM/c_api.h, include/LightGBM/dataset_loader.h, python-package/lightgbm/basic.py, src/c_api.cpp, src/io/dataset_loader.cpp
This PR adds a new API related to `LGBM_DatasetCreateFromSampledColumn `that splits the current single parameter for "num_total_data" into 2, one for total local data and one for total distributed data.  The new API is called `LGBM_DatasetDistCreateFromSampledColumn`, but that name can be changed.  I kept the old one for back-compat.
See issue here: https://github.com/microsoft/LightGBM/issues/5343
=> fix: Adjust LGBM_DatasetCreateFromSampledColumn to handle distributed data

.ci/test.sh, docs/Experiments.rst, docs/GPU-Windows.rst, docs/Installation-Guide.rst, docs/Parallel-Learning-Guide.rst
The `check-docs` CI job has started failing recently, with the following error ([click here for example failing build](https://github.com/microsoft/LightGBM/runs/7510259313?check_suite_focus=true)).
> Error: No such option: --report Did you mean --report-level?
I believe this is because of some breaking changes included in `rstcheck` 6.0.0. Described in these issues:
* https://github.com/rstcheck/rstcheck/issues/110
* https://github.com/rstcheck/rstcheck/pull/111
According to https://anaconda.org/conda-forge/rstcheck, `rstcheck` v6.0.0 was just published to conda-forge about 3 days ago.
This PR proposes a fix to make LightGBM's CI compatible with that version.
It also proposes putting in a floor of `rstcheck>=6.0.0` so that we'll get a loud, obvious error if a surprising environment solve …
=> [ci] make check-docs job compatible with rstcheck 6.x

R-package/DESCRIPTION, docs/env.yml
`{roxygen2}` v7.2.1 was released today.
This PR updates LightGBM's documentation to use it.
@StrikerRUS could you please enable builds of this branch on readthedocs so we can check that this works there?
=> [docs] [R-package] upgrade to roxygen2 7.2.1

R-package/R/lightgbm.R, R-package/man/lgb.cv.Rd, R-package/man/lgb.train.Rd, R-package/man/lgb_shared_params.Rd, R-package/man/lightgbm.Rd
=> [R-package] [docs] fix typo in documentation on init_model

python-package/lightgbm/basic.py, python-package/lightgbm/libpath.py
Proposes moving the "don't try to load `lib_lightgbm.so` if building the documentation" logic to an import-time concern in `basic.py`, instead of having `libpath.find_lib_path()` and `basic._load_lib()` both have to know about it.
`mypy` is currently catching the fact that `lightgbm.basic._LIB` can be `None`
https://github.com/microsoft/LightGBM/blob/25e32e94636b0d81b77c20d26635914ee330266d/python-package/lightgbm/basic.py#L111-L115
but is accessed unconditionally in many places assuming that it is a `ctypes.CDLL`, e.g.
https://github.com/microsoft/LightGBM/blob/25e32e94636b0d81b77c20d26635914ee330266d/python-package/lightgbm/basic.py#L27-L31
These `mypy` warnings look like this:
```text
python-package/lightgbm/basic.py:3966: error: Item "None" of "Optional[CDLL]" …
```
=> [python-package] make library-loading stricter

R-package/README.md
The R package uses `{roxygen2}` to generate its docs, but because of the way the package is built contributors can't simply run `devtools::document()` or `roxygen2::roxygenize()` as they may be used to in other R projects.
Example of someone running into that: https://github.com/microsoft/LightGBM/pull/5379#issuecomment-1188726525.
This PR proposes adding documentation on how to re-generate the R package's docs.
(p.s. I promised @jmoralez this in maintainer Slack a long time ago but forgot to come do it)
=> [docs] [R-package] document how to regenerate roxygen docs

R-package/R/lgb.Booster.R, R-package/man/predict.lgb.Booster.Rd
In #5223, @mayer79 pointed out that the R package's documentation doesn't currently describe how to interpret `leaf` or `contrib` predictions for multiclass objectives.
This PR proposes adding such documentation to help users and developers creating extensions like `{shapviz}` and `{SHAPforxgboost}`.
See https://github.com/microsoft/LightGBM/issues/5223#issuecomment-1188602396 for specific evidence supporting what's being proposed here.
@mayer79 if you have time, we'd be grateful for a review on this from you as well. No rush on that.... the project's CI is currently broken anyway 😬  (https://github.com/microsoft/LightGBM/pull/5362#issuecomment-1188606982)
=> [R-package] [docs] clarify shape of predictions

R-package/R/utils.R, R-package/tests/testthat/test_parameters.R, R-package/tests/testthat/test_utils.R, helpers/parameter_generator.py, include/LightGBM/config.h, python-package/lightgbm/basic.py, src/io/config.cpp, src/io/config_auto.cpp, tests/python_package_test/test_basic.py
Extracts the current logic on the C++ side to sort aliases to a function `Config::SortAlias` so that `Config::DumpAliases` can use the same criteria to sort them and allow the wrappers to be in sync.
Fixes #5304
=> reproducible parameter alias resolution for wrappers (fixes #5304)

.ci/test.sh, .vsts-ci.yml, python-package/lightgbm/basic.py
Unblock CI in this repo.
Temp workaround for #5390.
=> [ci] temporarily pin scipy version and fix Python linting error

src/treelearner/linear_tree_learner.cpp
Found by https://lgtm.com/projects/g/microsoft/LightGBM?mode=tree&ruleFocus=2157860313.
In #5368 `XTg_by_thread_` and `XTHX_by_thread_` was changed from `float` to `double`: https://github.com/microsoft/LightGBM/commit/44d37184d1718b065140483b95fcce273f714cbe#diff-772d433919ddb14342b8dd8ca225131ebef06689c9f0311f685103b685cb5f6eL123-L124.
=> Fix potential overflow in linear trees

python-package/README.rst, src/boosting/cuda/cuda_score_updater.cu
- Format CUDA-related note in the docs.
- Replace `Warning` level with `Debug` for initial score value and fix `double` formatter.
=> Minor CUDA cleanup

python-package/lightgbm/basic.py
Adds type hints on `Booster.save_model()`.
=> [python-package] add type hints on Booster.save_model()

python-package/lightgbm/basic.py
Adds type hints in a few more places in `basic.py`.
=> [python-package] add more type hints in basic.py

.github/workflows/r_valgrind.yml
`valgrind` checks are timing out after 4 hours.
See, for example, https://github.com/microsoft/LightGBM/pull/5403#issuecomment-1210339118.
It has been a few weeks since we last ran that job, so I'm not sure why it is slower now. Either way, I hope that just giving the job one more hour to finish will help.
This PR proposes that.
This has to be merged to `master` to test it, as the configuration for GitHub Actions jobs is sourced from `master`.
=> [ci] increase valgrind timeout to 5 hours

python-package/lightgbm/basic.py
=> [python] Prefix `basic.is_numeric()` with _

.ci/test_r_package_valgrind.sh
See https://github.com/microsoft/LightGBM/pull/5403#issuecomment-1218836822 for details.
This PR slightly increases the number of "possibly lost bytes" allowed in the `valgrind` CI job. Since this is coming from the exact same place as a previous false positive, I think it's highly likely that CRAN will not complain about this.
=> [ci] increase valgrind bytes lost limit to 352

src/boosting/score_updater.hpp
=> [fix] change the destructor of ScoreUpdater to virtual (fixes #5400)

python-package/lightgbm/basic.py
Adds some more type hints to places in `Dataset` that are missing them.
I intentionally avoided hints on anything "array-like", since those will require some extra research and should be handled separately (https://github.com/microsoft/LightGBM/issues/3756#issuecomment-907622141).
=> [python-package] add more type hints on Dataset

src/io/tree.cpp
Updates the tree to if else code to match the code in `tree.h`:
* Numerical Split: https://github.com/microsoft/LightGBM/blob/6b695c292507571cecf3251be10524c648e73be0/include/LightGBM/tree.h#L335-L353
* Categorical Split: https://github.com/microsoft/LightGBM/blob/6b695c292507571cecf3251be10524c648e73be0/include/LightGBM/tree.h#L372-L388
=> update tree to if-else

python-package/lightgbm/basic.py, python-package/lightgbm/callback.py, python-package/lightgbm/engine.py, python-package/lightgbm/sklearn.py
Contributes to #3756 and #3867.
Adds type hints on the following closely-related methods.
* `Booster.eval()`
* `Booster.eval_train()`
* `Booster.eval_valid()`
* `Booster.__inner_eval()`
Modifies docstrings for those methods to be a bit more informative about the structure of the returned tuples.
Modifies type hints for other methods using the results of these methods so that they share the same definitions imported across different files.
Used the following small sample code to test these return types.
<details><summary>test code (click me)</summary>
```python
from sklearn.datasets import make_blobs
def _single_tuple_metric(preds, ds):
return ("single_tuple", 1.0, True)
def _list_of_tuples_metric(preds, ds):
return [("list_id_0", 2.0, True), ("list_id_1", 2.0, …
```
=> [python-package] add type hints on Booster eval methods

python-package/lightgbm/callback.py, tests/python_package_test/test_engine.py, tests/python_package_test/test_sklearn.py, tests/python_package_test/test_utilities.py
=> [python-package] ignore training set on early stopping callback (fixes #5354)

.github/workflows/cuda.yml
https://catalog.ngc.nvidia.com/orgs/nvidia/containers/cuda/tags
=> [ci] bump CUDA version from `11.7.0` to `11.7.1` at CI

src/io/dataset.cpp, tests/python_package_test/test_basic.py
=> include parameters from reference dataset on subset (fixes #5402)

.ci/test.sh, .github/workflows/cuda.yml, include/LightGBM/cuda/cuda_utils.h, include/LightGBM/tree_learner.h, src/boosting/cuda/cuda_score_updater.cpp, src/boosting/cuda/cuda_score_updater.cu, src/boosting/gbdt.cpp, src/boosting/gbdt.h, src/boosting/rf.hpp, src/io/cuda/cuda_tree.cu, src/objective/objective_function.cpp, src/treelearner/cuda/cuda_single_gpu_tree_learner.cpp, src/treelearner/cuda/cuda_single_gpu_tree_learner.hpp, tests/python_package_test/test_utilities.py
Unfortunately, in a very long time (since the merge of #4630), the ci tests for `cuda_exp` has not actually run.
Since the task name for both `cuda` and `cuda_exp` is `cuda`
https://github.com/microsoft/LightGBM/blob/702db13b01bfb090c3f8f3455790a498f105b28f/.github/workflows/cuda.yml#L14
in `test.sh` the `cuda_exp` option cannot be detected, and it will always run for device `cuda`!
https://github.com/microsoft/LightGBM/blob/702db13b01bfb090c3f8f3455790a498f105b28f/.ci/test.sh#L198-L199
That's a serious mistake. And I think we need to fix it right now for our on-going development of `cuda_exp`.
=> [ci][fix] Fix cuda_exp ci

python-package/lightgbm/basic.py
`mypy` currently raises the following error.
```text
python-package/lightgbm/basic.py:2491: error: Argument 1 to "c_int" has incompatible type "Union[int, str]"; expected "int"
```
This is caused by the fact that `mypy` doesn't allow changing the type of an object after it's initially assigned. This blog post explains it well: https://adamj.eu/tech/2021/05/23/python-type-hints-mypy-doesnt-allow-variables-to-change-type/.
This PR proposes a slight refactoring of `Dataset.feature_num_bin()` to resolve this error. I think this change does also make the code slightly easier to understand.
I tested this by running `mypy` as documented in #3867.
```shell
mypy \ …
```
=> [python-package] fix mypy error about type change in Dataset.feature_num_bin()

python-package/lightgbm/basic.py, python-package/lightgbm/engine.py
`mypy` currently raises the following errors.
```text
python-package/lightgbm/basic.py:2515: error: Need type annotation for "ref_chain" (hint: "ref_chain: Set[<type>] = ...")
python-package/lightgbm/basic.py:2734: error: Need type annotation for "valid_sets" (hint: "valid_sets: List[<type>] = ...")
python-package/lightgbm/basic.py:2735: error: Need type annotation for "name_valid_sets" (hint: "name_valid_sets: List[<type>] = ...")
python-package/lightgbm/engine.py:303: error: Need type annotation for "boosters" (hint: "boosters: List[<type>] = ...")
```
These come from places where an empty container is initialized, then later filled with values. Like this:
https://github.com/microsoft/LightGBM/blob/ef006b788cb2aadd3e827d0d8b44bf879854966e/pytho …
=> [python-package] add type hints on empty initializations

python-package/lightgbm/engine.py
`mypy` currently raises the following errors.
```text
-python-package/lightgbm/engine.py:688: error: Incompatible types in assignment (expression has type "Set[<nothing>]", variable has type "Optional[List[Callable[..., Any]]]")
-python-package/lightgbm/engine.py:692: error: Incompatible types in assignment (expression has type "Set[Callable[..., Any]]", variable has type "Optional[List[Callable[..., Any]]]")
-python-package/lightgbm/engine.py:695: error: Item "List[Callable[..., Any]]" of "Optional[List[Callable[..., Any]]]" has no attribute "add"
-python-package/lightgbm/engine.py:695: error: Item "None" of "Optional[List[Callable[..., Any]]]" has no attribute "add"
-python-package/lightgbm/engine.py:707: error: Item "None" of …
```
=> [python-package] fix mypy errors about callbacks

python-package/lightgbm/basic.py
`mypy` currently raises the following errors.
```text
python-package/lightgbm/basic.py:258: error: Function "ctypes.POINTER" is not valid as a type
python-package/lightgbm/basic.py:258: note: Perhaps you need "Callable[...]" or a callback protocol?
python-package/lightgbm/basic.py:266: error: Function "ctypes.POINTER" is not valid as a type
python-package/lightgbm/basic.py:266: note: Perhaps you need "Callable[...]" or a callback protocol?
python-package/lightgbm/basic.py:274: error: Function "ctypes.POINTER" is not valid as a type
python-package/lightgbm/basic.py:274: note: Perhaps you need "Callable[...]" or a callback protocol?
python-package/lightgbm/basic.py:282: error: Function "ctypes.POINTER" is not valid as a type …
```
=> [python-package] fix type hints on ctypes array converters

R-package/R/lgb.Booster.R, R-package/R/lgb.Dataset.R
Noticed a few places where error messages in the R package reference a function or R6 method, and where that reference is incorrect.
This PR fixes those references.
=> [R-package] fix function references in error messages

include/LightGBM/dataset.h, src/io/metadata.cpp
A recent completed PR (https://github.com/microsoft/LightGBM/pull/5299) created a new Metadata method num_classes(), but this can be confused with the actual num_classes in a Dataset.  It should definitely be the same number, but the new method is specifically returning the num_classes as configured and allocated in Metadata.  Reviewers requested to rename this method to be clearer.  New name is num_init_score_classes().
=> Rename Metadata num_classes to be more clear

src/io/sparse_bin.hpp, tests/cpp_tests/test_stream.cpp, tests/cpp_tests/testutils.cpp, tests/cpp_tests/testutils.h
This PR adds concurrency testing to new streaming APIs added in PR https://github.com/microsoft/LightGBM/pull/5299.
It also attempts to fix a concurrency issue in `SparseBin `PushRow API. WIthout this fix, concurrent calls often fail to the `LGBM_DatasetPushRowsByCSRWithMetadata `API.
=> Add streaming concurrency tests

python-package/lightgbm/basic.py
Adds type hints on some methods in `Dataset` which don't currently have them.
I'm beginning work on the "array-like" inputs in LightGBM's Python API, per https://github.com/microsoft/LightGBM/issues/3756#issuecomment-907622141.
This is a first step towards that.
=> [python-package] add type hints on Dataset constructors

tests/cpp_tests/test_stream.cpp
Some debugging was leftover in some test code recently checked in.  This fixes it.
=> fix: Revert leftover debugging in streaming test

src/boosting/gbdt.cpp, src/boosting/gbdt.h
Proposes changing one log message and one code comment from "object function" to "objective function".
I believe both were intended to be "objective function", and that "object function" is incorrect.
=> fix references to 'object function'

include/LightGBM/cuda/cuda_tree.hpp, src/io/cuda/cuda_tree.cpp, src/treelearner/cuda/cuda_best_split_finder.cpp, src/treelearner/cuda/cuda_best_split_finder.cu, src/treelearner/cuda/cuda_best_split_finder.hpp, src/treelearner/cuda/cuda_single_gpu_tree_learner.cpp, src/treelearner/cuda/cuda_single_gpu_tree_learner.hpp, tests/python_package_test/test_engine.py
Add feature interaction constraint for `cuda_exp`. This is to fix #4785.
=> [CUDA] Add feature interaction constraint for cuda_exp (fix #4785)

src/io/bin.cpp, src/network/socket_wrapper.hpp, src/objective/binary_objective.hpp, src/treelearner/cuda/cuda_data_partition.hpp, src/treelearner/gpu_tree_learner.cpp, src/treelearner/monotone_constraints.hpp
The commit removes redundant whitespaces.
Perhaps adding a linter, specifying a list of rules would be helpful.
=> Remove redundant whitespaces

.github/workflows/r_package.yml, build-cran-package.sh
Fixes #5036.
Replaces #5037.
* changes to `build-cran-package.sh`:
- replaces use of `tar --exclude` with simply `rm`-ing the excluded files prior to re-tarring the source distribution
- removes unnecessary uses of `-f` in `rm` commands deleting files (not directories), for safety
- removes unnecessary use of `-v` in `tar` commands whose output is suppressed anyway by redirection to `/dev/null`
- removes uses of `tar -C`, instead just relying on directory traversal with `cd`
* restores the R 3.6 cran-style Windows CI job
CRAN-style builds of the R package have not been tested against R 3.6 on Windows for the last 7 months. This PR restores the CI job testing that support.
I used #5037 to experiment with different approaches and to try to find a root cause for why this job started failing. …
=> [R-package] [ci] restore R 3.6 Windows cran CI job (fixes #5036)

R-package/R/lgb.plot.importance.R, R-package/R/lgb.plot.interpretation.R
I just observed the `lint` CI job failing on #5484 ([build link](https://github.com/microsoft/LightGBM/actions/runs/3054739687/jobs/4926997471)), with the following errors from R linting.
```text
[[1]]
/home/runner/work/LightGBM/LightGBM/R-package/R/lgb.plot.importance.R:82:12: warning: [seq] .N:1L is likely to be wrong in the empty edge case. Use seq_len(1L) instead.
tree_imp[.N:1L,
^~~~~
[[2]]
/home/runner/work/LightGBM/LightGBM/R-package/R/lgb.plot.interpretation.R:149:23: warning: [seq] .N:1L is likely to be wrong in the empty edge case. Use seq_len(1L) instead.
tree_interpretation[.N:1L,
^~~~~
```
It looks like a new release of `{lintr}` (v3.0.1) just made it to CRAN (https://cran.r-project.org/web/packages/lintr/index.html), and they've added more cases caught by the `seq_linter()`. …
=> [R-package] improve safety of index selection in plotting

.ci/test_r_package.sh, .github/workflows/r_package.yml
Contributes to #4881.
In #5274, I've been working on upgrading R to v 4.2.x in this project's CI jobs. Linux and macOS are working fine there, but adding Windows support has been challenging.
This PR proposes at least upgrading the Linux and macOS CI jobs, so we can start getting more test coverage of `{lightgbm}` on R 4.2.x. If this is merged, then I'll repurpose #5274 to focus only on adding the remaining Windows support.
As of this writing, the latest version of R is v4.2.1 (https://cran.r-project.org/src/base/R-4/).
=> [ci] test against R 4.2 for macOS and Linux CI jobs

python-package/lightgbm/basic.py
`pandas.Series.iteritems` [is being deprecated](https://pandas.pydata.org/docs/reference/api/pandas.Series.iteritems.html) in favor of `pandas.Series.items` ([sample warning link in CI](https://github.com/microsoft/LightGBM/actions/runs/3117214672/jobs/5055714658#step:3:1267)).
The `items` method [exists in pandas version 0.24](https://pandas.pydata.org/pandas-docs/version/0.24.2/reference/api/pandas.Series.items.html#pandas.Series.items) so this shouldn't cause compatibility problems.
=> replace `pandas.Series.iteritems` with `pandas.Series.items`

README.md
The current link to Optuna's example code in README seems to have expired. I fixed it to the right one.
=> [docs] Fix link to Optuna's LightGBMTuner example

R-package/README.md
While checking the R package on [win-builder](https://win-builder.r-project.org/), I saw the following `R CMD check` NOTE:
```text
Found the following (possibly) invalid URLs:
URL: https://cran.r-project.org/web/packages/roxygen2/index.html
From: README.md
Status: 200
Message: OK
CRAN URL not in canonical form
The canonical URL of the CRAN page for a package is 
https://CRAN.R-project.org/package=pkgname
```
This PR proposes accepting that suggestion, to reduce the risk of the next CRAN submission being rejected.
=> [R-package] [docs] use CRAN canonical form for package links

python-package/lightgbm/basic.py
Contributes to https://github.com/microsoft/LightGBM/issues/5313
=> [python-package] prefix is_numpy_1d_array with _

.github/workflows/cuda.yml, .github/workflows/optional_checks.yml, .github/workflows/python_package.yml, .github/workflows/r_package.yml, .github/workflows/static_analysis.yml, .vsts-ci.yml
Based on @guolinke 's suggestion in https://github.com/microsoft/LightGBM/pull/5525#issuecomment-1272332768, I'd like to try targeting PR #5525 at a branch, `release/v3.3.2`, which only contains:
* v3.3.2 of LightGBM
* CI scripts and configs from `master`
That would allow us to try to run all of LightGBM's CI over the potential `v3.3.3` release (we'll see if that works!).
This PR proposes modifying the configs for GitHub Actions and Azure Devops so that CI jobs will be triggered on all ~branches~ PRs targeting branches with a name like `release/*`.
Once this is merged, I'll update #5525.
Documentation for how these configs work:
* GitHub Actions: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
* Azure: …
=> [ci] run CI on pull requests targeting release/ branches

.appveyor.yml
Follow-up to #5527.
Contributes to #5525 .
I was wrong in #5527 ... `.appveyor.yml` in this repo DOES need to be modified to tell Appveyor to build on pull requests that target `release/*` branches.
This PR proposes such a change. 
See https://www.appveyor.com/docs/branches/ for docs on how Appveyor's preferred syntax expects such "match all branches following a pattern".
This change will help with the `v3.3.3` release, and I think it should be kept even after that to make such time-sensitive hotfix types of releases a bit easier in the future.
Pushed a similar change to #5525, and that led to Appveyor successfully building on that PR that targets branch `release/v3.3.2`.
=> [ci] run Appveyor checks on PRs targeting release/ branches

R-package/tests/testthat/test_basic.R
Contributes to #5502.
One test on LightGBM's treatment of non-ASCII features has been failing on the `r-devel-linux-x86_64-debian-clang` CRAN check flavor recently (see #5502).
This PR fixes that test.
These changes do need to make it into the emergency patch release we're preparing (#5525). But this issue exists on `master` as well.
Through the investigation on #5502, I found some evidence that `{testthat}` was somehow modifying R's handling of this one test in non-UTF8 locales: https://github.com/microsoft/LightGBM/issues/5502#issuecomment-1272126313.
I believe that could be related to some combination of:
* `{lightgbm}`'s use of non-ASCII string literals in a test source file
* `{testthat}` changing encodings when reading source code of test files ([testthat code …
=> [R-package] fix test on non-ASCII features in non-UTF8 locales

.ci/test_r_package_windows.ps1, .github/workflows/r_package.yml, R-package/README.md, R-package/configure.win, R-package/tests/testthat/test_dataset.R
Fixes #4881.
Replaces #5274.
* upgrade from R 4.1.3 to R 4.2.1 in Windows CI jobs
* upgrade from Rtools40 to Rtools42 in Windows CI jobs
* explicitly pass version parsed from `VERSION.txt` into `test_r_package_windows.ps1` (instead of relying on wildcards like `lightgbm_*.tar.gz`
* extend "skip one test when compiling with MSVC" fix from #5448 to all MSVC jobs
Compiling the test program used to check for `inet_pton` with the compiler that ships with RTools42 (gcc 10.3), results in the following error.
```text
conftest.cpp: In function 'int main()':
conftest.cpp:3:13: error: invalid conversion from 'INT (*)(INT, LPCSTR, PVOID)' {aka 'int (*)(int, const char*, void*)'} to 'void*' [-fpermissive]
3 |   void* p = inet_pton;
|             ^~~~~~~~~
|             |
|             INT (*)(INT, …
```
=> [ci] [R-package] use R 4.2.1 in Windows CI jobs (fixes #4881)

python-package/lightgbm/basic.py
Contributes to https://github.com/microsoft/LightGBM/issues/5313
=> [python-package] prefix cast_numpy_array_to_dtype with _

src/io/bin.cpp
just for clarity and trying to make it easier to follow the code for those who aren't familiar with the code base.
=> renamed cur_cat => cur_cat_idx and added some comments

python-package/README.rst, python-package/setup.py
According to the [install guide](https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html):
> Users who want to perform benchmarking can make LightGBM output time costs for different internal routines by adding -DUSE_TIMETAG=ON to CMake flags.
This feature was unfortunately not available when installing LightGBM from the Python package. This PR attempts to fix this. :)
=> [python-package] add install option to enable printing of time costs

.vsts-ci.yml
Fixes blocking issue #5569.
Proposes upgrading the `macOS_regular` CI job from Python 3.7 to 3.9, to try to fix CI errors possibly related to `conda-forge` dropping support for Python 3.7.
I don't think so. The only artifact build from this task is the shared library for macOS, `lib_lightgbm.dylib`.
https://github.com/microsoft/LightGBM/blob/d8a6b8871b990950ab37cfa96d83e3bfc87680ba/.ci/test.sh#L259-L261
And that shouldn't be affected by Python version, as we don't produce a shared library that links into any Python stuff.
=> [ci] upgrade macOS_regular job to Python 3.9 (fixes #5569)

.ci/test_r_package_windows.ps1, .github/workflows/r_package.yml
Fixes #5600.
R CI jobs require a LaTeX distribution to build the package documentation. This PR proposes switching from [MiKTeX](https://miktex.org/) to [`{tinytex}`](https://yihui.org/tinytex/) for Windows builds.
The use of MiKTeX has been the source of several multi-day outages in LightGBM's CI over the last few years (and most recently, #5600):
* https://github.com/microsoft/LightGBM/issues/5562
* https://github.com/microsoft/LightGBM/issues/4005
* https://github.com/microsoft/LightGBM/issues/3454
* https://github.com/microsoft/LightGBM/issues/3198
Several of those have had the resolution "wait a few days until changes in CTAN mirrors or other upstream sources are fixed". That's very disruptive to our development here, as it means either skipping R package CI jobs or not merging …
=> [ci] switch from MiKTeX to tinytex on Windows R jobs (fixes #5600)

.ci/test.sh, .vsts-ci.yml
Contributes to #4788.
#5580 switched LightGBM's CI to using an image based on `pypa/manylinux_2_28_x86_64` to produce x86_64 wheels.
In that PR, I forgot to update the platform tag used with those wheels 😬 
This PR contains two fixes:
* updates the tag to `manylinux_2_28_x86_64`
* updates to the image produced from `master` of https://github.com/guolinke/lightgbm-ci-docker, so that future development on the `dev` branch there doesn't disrupt LightGBM's CI
In a future PR, I think we should consider running `auditwheel show` in CI like @tdoublep did in #4788, to prevent this "wrong tag" issue from making it onto `master`.
=> [ci] [python-package] correct tag on x86_64 wheels

helpers/check_dynamic_dependencies.py
While updating #5252 to the new CI image proposed in https://github.com/guolinke/lightgbm-ci-docker/pull/29, I found that the `Linux regular` and `Linux swig` jobs were failing with the following.
> Traceback (most recent call last):
File "/__w/1/s/helpers/check_dynamic_dependencies.py", line 55, in <module>
check_dependencies(Path(sys.argv[1]).read_text(encoding='utf-8'))
File "/__w/1/s/helpers/check_dynamic_dependencies.py", line 30, in check_dependencies
assert len(versions) > 1
AssertionError
I was able to reproduce this locally in a container too.
<details><summary>how to reproduce this (click me)</summary>
```shell
docker run --rm -ti \
-v $PWD/artifacts:/artifacts \
-e AZURE=true \
-e BUILD_DIRECTORY=/vsts/lightgbm \
-e BUILD_SOURCESDIRECTORY=/vsts/lightgbm \
-e …
```
=> [ci] detect non-default dynamic symbols in check_dynamic_dependencies.py

python-package/lightgbm/basic.py
=> [python-package] prefix basic.convert_from_sliced_object with _

.ci/test_r_package.sh, .ci/test_r_package_windows.ps1
Contributes to #3763.
R 4.2.2 was released in October 2022. Changelog: https://cran.r-project.org/bin/windows/base/old/4.2.2/NEWS.R-4.2.2.html.
This PR proposes upgrading from R 4.2.1 to R 4.2.1 in LightGBM's R 4.2.x CI jobs.
This will resolve an `R CMD check` warning I observed on #5563 
> Warning message:
package 'R6' was built under R version 4.2.2 
That can happen when binaries have been built by CRAN with a newer version of R than the one that you're using.
=> [ci] test against R 4.2.2

python-package/lightgbm/basic.py
=> [python-package] prefix c_int_array and c_float_array with _

R-package/cran-comments.md
v3.3.4 of the R package has been released to CRAN (https://github.com/microsoft/LightGBM/pull/5619#issuecomment-1353685486, https://github.com/microsoft/LightGBM/issues/5618#issuecomment-1363292780).
See https://cran.r-project.org/web/checks/check_results_lightgbm.html
This PR proposes updating `cran-comments.md` to reflect that.
=> [docs] update cran-comments.md for v3.3.4 release

.github/workflows/cuda.yml, .github/workflows/optional_checks.yml, .github/workflows/python_package.yml, .github/workflows/r_package.yml, .github/workflows/static_analysis.yml
Fixes #5501.
Following advice in that issue and in https://github.com/orgs/community/discussions/26733#discussioncomment-3253155, this proposes two changes to the project's GitHub Actions jobs.
* use https://github.com/re-actors/alls-green to enforce multiple checks passing without needing to change branch protection settings every time checks are added or removed
* give each of those "all the checks passed" jobs a unique name
This will make use of GitHub auto-merging more reliable, and reduce the risk of accidentally merging PRs where some CI jobs are failing.
@guolinke @shiyu1994 can you please go into the branch protection for `master` at https://github.com/microsoft/LightGBM/settings/branches and modify the section `Require status checks to pass before merging`?
The following should …
=> [ci] make GitHub Actions branch protection stricter (fixes #5501)

.ci/setup.sh, .ci/test.sh, .vsts-ci.yml
Today, the Linux CI jobs on Azure DevOps run in a container using the `ubuntu:22.04` image. Since that image is just a minimal operating system distribution, running LightGBM's CI in it requires a lot of extra configuration.
Here's where much of that happens:
https://github.com/microsoft/LightGBM/blob/a17489328c4f81819b5a4131c9a386b09b90b04f/.ci/setup.sh#L26
I noticed while working on #5638 that one piece of that has been silently failing for a while (unsure how long).
There are a few problems with this bit of configuration that tries to change the locale inside the container to `en_US.UTF-8`:
https://github.com/microsoft/LightGBM/blob/a17489328c4f81819b5a4131c9a386b09b90b04f/.ci/setup.sh#L58-L61
Setting `LC_ALL` environment variable to a locale that doesn't exist yet (i.e. hasn't been …
=> [ci] fix locale-setting in jobs running in ubuntu container

.github/workflows/cuda.yml, .github/workflows/python_package.yml, .github/workflows/r_package.yml, .github/workflows/static_analysis.yml
Proposes modifying the GitHub Actions jobs that run on every commit, such that GitHub automatically cancels in-progress runs on a given branch when a new commit is pushed to that branch.
Once a new commit has been pushed to `master` or to a pull request, it's not important that CI jobs for the previous commit run to completion.
Automatically cancelling those in-progress CI runs that are going to be ignored anyway is helpful because it:
* increases the number of PRs that can be merged in a day
* reduces the impact that one very active PR can have on throughput for the rest of the repo
* reduces the load we place on GitHub Actions and other services the jobs hit
- reduces the risk of triggering `409 - too many requests` types of errors from services like GitHub, PyPI, CRAN, etc.
- makes …
=> [ci] automatically cancel GitHub Actions runs for outdated commits

src/io/dataset.cpp, tests/python_package_test/test_basic.py
Replaces #5434.
Fixes #5410.
Thanks to @EdmondElephant for discovering this bug, investigating it in #5410, and for fixing it in #5434!
I'm just replacing that PR with this one due to lack of response there (it has been more than 3 months since the last comment there).
I ran the following to test that this new unit test segfaults on `master` and passes on this PR.
```shell
mkdir build
cd build
cmake ..
make -j4
cd ../python-package
python setup.py --install
cd tests/python_package_test
pytest 'test_basic.py::test_add_features_does_not_fail_if_initial_dataset_has_zero_informative_features'
```
=> fix feature index in Dataset::AddFeaturesFrom (fixes #5410)

src/boosting/gbdt.cpp, src/boosting/gbdt.h, tests/python_package_test/test_engine.py
When constructing booster, traverse the tree of forced splits and check that all split features have index less than or equal to the maximum feature index in the dataset.
Fixes https://github.com/microsoft/LightGBM/issues/5517
=> Check feature indexes in forced split file (fixes #5517)

python-package/lightgbm/basic.py
Contributes to #5313.
Proposes prefixing the remaining functions and module-level constants listed in #5313 with `_`.
* `basic.ZERO_THRESHOLD`
* `basic.json_default_with_numpy()`
* `basic.param_dict_to_str()`
* `basic.MAX_INT32`
* `basic.C_API_DTYPE_FLOAT32`
* `basic.C_API_DTYPE_FLOAT64`
* `basic.C_API_DTYPE_INT32`
* `basic.C_API_DTYPE_INT64`
* `basic.C_API_IS_ROW_MAJOR`
* `basic.C_API_PREDICT_NORMAL`
* `basic.C_API_PREDICT_RAW_SCORE`
* `basic.C_API_PREDICT_LEAF_INDEX`
* `basic.C_API_PREDICT_CONTRIB`
* `basic.C_API_MATRIX_TYPE_CSR`
* `basic.C_API_MATRIX_TYPE_CSC`
* `basic.C_API_FEATURE_IMPORTANCE_SPLIT`
* `basic.C_API_FEATURE_IMPORTANCE_GAIN`
* `basic.FIELD_TYPE_MAPPER`
* `basic.FEATURE_IMPORTANCE_TYPE_MAPPER`
=> [python-package] prefix internal objects with '_'

python-package/lightgbm/basic.py
Contributes to #5313.
Proposes removing public attribute `Dataset.feature_penalty`. It was added in #2006 to support method `Dataset.get_feature_penalty()`.
`Dataset.get_feature_penalty()` was removed in #2594, which moved `feature_penalty` into `params` (instead of having it be a top-level attribute of `Dataset`).
This is technically "breaking" because it removes a public attribute that user code could reference, but this attribute doesn't actually *do anything* and hasn't since `get_feature_penalty()` was removed back in #2594.
So I chose the label `maintenance`, to not add more noise to the `breaking` section of the release notes for something that I think very few users are likely to be depending on.
=> [python-package] remove `Dataset.feature_penalty`

python-package/lightgbm/basic.py, python-package/lightgbm/callback.py, python-package/lightgbm/compat.py, python-package/lightgbm/dask.py, python-package/lightgbm/engine.py, python-package/lightgbm/libpath.py, python-package/lightgbm/plotting.py, python-package/lightgbm/sklearn.py
Contributes to #5313.
Proposes adding module-level `__all__` blocks in each module in the Python package.
From https://docs.python.org/3/reference/simple_stmts.html#import (thanks @jmoralez for sharing that link in https://github.com/microsoft/LightGBM/issues/5313#issuecomment-1165757690)....
> *The public names defined by a module are determined by checking the module’s namespace for a variable named `__all__`... `__all__` should contain the entire public API.*
>
> *It is intended to avoid accidentally exporting items that are not part of the API (such as library modules which were imported and used within the module).*
Reduces the set of imports pulled in by statements like `from lightgbm.basic import *` to only those that maintainers intend to be part of LightGBM's public API.
That …
=> [python-package] make public API members explicit with module-level __all__ variables

.ci/test.sh, docs/conf.py, python-package/lightgbm/compat.py, python-package/setup.py, tests/python_package_test/test_callback.py, tests/python_package_test/test_dask.py, tests/python_package_test/test_engine.py, tests/python_package_test/test_sklearn.py
Fixes #5566.
Proposes enforcing `flake8` checks on all Python code maintained in this repo, for the reasons described in #5566.
This also fixes the following warnings found by `flake8`
```text
./tests/python_package_test/test_engine.py:2906:9: F841 local variable 'bst' is assigned to but never used
./tests/python_package_test/test_callback.py:6:1: F401 '.utils.pickle_obj' imported but unused
./tests/python_package_test/test_callback.py:6:1: F401 '.utils.unpickle_obj' imported but unused
./tests/python_package_test/test_dask.py:1727:29: F841 local variable 'client' is assigned to but never used
./tests/python_package_test/test_dask.py:1806:29: F841 local variable 'client' is assigned to but never used
./tests/python_package_test/test_sklearn.py:447:5: F841 local variable 'gbm_clone' is …
```
=> [ci] [python-package] enforce flake8 checks (fixes #5566)

python-package/lightgbm/basic.py, python-package/lightgbm/dask.py, python-package/lightgbm/sklearn.py
Moved from https://github.com/microsoft/LightGBM/pull/5672.
Fixes `mypy` errors regarding `eval_at` incompatibility:
```
Argument "eval_at" to "_train" has incompatible type "Optional[Iterable[int]]"; expected "Union[List[int], Tuple[int], None]"  [arg-type]
```
and the following two errors:
```
python-package\lightgbm\engine.py:169: error: Argument 1 to "set_feature_name" of "Dataset" has incompatible type "Union[List[str], str]"; expected "List[str]"  [arg-type]
python-package\lightgbm\engine.py:170: error: Argument 1 to "set_categorical_feature" of "Dataset" has incompatible type "Union[List[str], List[int], str]"; expected "Union[List[int], List[str]]"  [arg-type]
```
This was tested by running mypy as documented in …
=> [python-package] fix mypy errors for eval_at and basic

docs/Installation-Guide.rst
Replaces #5498.
Implements the proposal in https://github.com/microsoft/LightGBM/pull/5498#pullrequestreview-1134818427.
Modifies the installation docs to encourage users who want to install LightGBM using only a GUI to use official releases. I hope this will help to prevent issues like #5495, where GUI-only users see broken builds because the GitHub source archive doesn't pull in git submodules.
=> [docs] encourage use of releases for GUI-only installations

python-package/lightgbm/dask.py
Moved from https://github.com/microsoft/LightGBM/pull/5672.
`mypy` currently raises the following errors regarding predict() method:
```
python-package\lightgbm\dask.py:1224: error: Signature of "predict" incompatible with supertype "LGBMClassifier"  [override]
python-package\lightgbm\dask.py:1224: note:      Superclass:
python-package\lightgbm\dask.py:1224: note:          def predict(self, X: Any, raw_score: bool = ..., start_iteration: int = ..., num_iteration: Optional[int] = ..., pred_leaf: bool = ..., pred_contrib: bool = ..., validate_features: bool = ..., **kwargs: Any) -> Any
python-package\lightgbm\dask.py:1224: note:      Subclass:
python-package\lightgbm\dask.py:1224: note:          def predict(self, X: …
```
=> [python-package] Fix mypy errors for predict() method

.ci/test.sh
In #5648 , I saw that `conda create`-ing an environment in one shot was significantly faster in some situations than `conda  create`-ing an environment and then updating it with `conda install` or `conda update` (https://github.com/microsoft/LightGBM/issues/5647#issuecomment-1373148054).
That PR was for Windows CI jobs.
This PR proposes similar changes to some of the macOS and Linux jobs.
* moves `lint`, `if-else`, and `swig` job code up earlier in `.ci/test.sh`
- *`swig` job doesn't need a conda environment, so time in that job spent waiting for `conda create` is wasted time*
- *`lint` and `if-else` have very different `conda`-installed dependencies than the other jobs, so they can be totally self-contained and just `conda create` their own environment with everything they need*
I …
=> [ci] speed up conda setup for some jobs

.ci/test_r_package.sh, .github/workflows/r_package.yml
Fixes #5688.
The `rhub/debian-*` container images are built from `debian:testing` ([code link](https://github.com/r-hub/rhub-linux-builders/blob/47ba102648e5db3037e100088452c9e8cd440367/debian/Dockerfile#LL3C6-L3C20)).
Seems like a few days ago, that image switched to Debian `bookworm` (the major release that follows `bullseye`).
```shell
docker run \
--rm \
debian:testing \
/bin/bash -c "apt-get update -y && apt-get install -y lsb-release && lsb_release -a"
```
```text
Distributor ID:	Debian
Description:	Debian GNU/Linux bookworm/sid
Release:	n/a
Codename:	bookworm
```
This fixes the R CI job in this project using that image by switching to the package repository that LLVM developers publish bookworm packages to (see https://apt.llvm.org/).
=> [ci] get clang-15 from bookworm repository (fixes #5688)

.ci/lint_r_code.R, R-package/R/utils.R, R-package/inst/make-r-def.R, R-package/tests/testthat/test_basic.R, R-package/tests/testthat/test_learning_to_rank.R, R-package/tests/testthat/test_lgb.Booster.R, build_r.R
This PR proposes two changes for the R package
* using fixed string search instead of regular expressions in string manipulations
* enforcing that practice with `lintr::fixed_regex_linter`
<details><summary>all lintr warnings addressed in this PR (click me)</summary>
```text
[1] Total linting issues found: 39
[[1]]
/Users/jlamb/repos/LightGBM/build_r.R:29:26: warning: [fixed_regex] This regular expression is static, i.e., its matches can be expressed as a fixed substring expression, which is faster to compute. Here, you can use "=" with fixed = TRUE.
} else if (any(grepl("=", arg))) {
^~~
[[2]]
/Users/jlamb/repos/LightGBM/build_r.R:30:34: warning: [fixed_regex] This regular expression is static, i.e., its matches can be expressed as a fixed substring expression, which is faster to …
```
=> [R-package] discourage use of regex for fixed string comparisons

.ci/test.sh
A mistake in fixing merge conflicts in #5668 accidentally removed the `flake8` changes from #5659.
This PR restores those changes.
=> [ci] restore flake8 checks

src/io/cuda/cuda_row_data.cpp
related to https://github.com/microsoft/LightGBM/issues/5705
@shiyu1994
=> cast data_index as size_t in cuda_row_data to avoid integer overflow

python-package/MANIFEST.in, python-package/setup.py
This PR proposes updating the Python package to declare that inline type annotations are used.
* adds trove classifier `Typing :: Typed`
* adds a `py.typed` file
This classifier helps researchers and others summarizing PyPI's contents to identify packages that export type annotations.
See the discussion in https://github.com/pypi/warehouse/issues/4348.
There are 5200+ packages on PyPI using this classifier: https://pypi.org/search/?c=Typing+%3A%3A+Typed.
As described in PEP 561 ([link](https://peps.python.org/pep-0561)), including an empty file named `py.typed` tells tools like `mypy` that a package's source code contains type annotations.
That doesn't matter for `lightgbm` itself, but it's helpful for anyone writing code that depends on …
=> [python-package] declare the use of inline type hints

.ci/check_python_dists.sh, .ci/test.sh, .ci/test_windows.ps1, python-package/setup.py
This PR proposes introducing two new linters that check the contents of Python package distributions (sdists and wheels) for common issues.
* [`twine check`](https://twine.readthedocs.io/en/stable/#twine-check): checks that distributions bundled README will render correctly on PyPI
* [`check-wheel-contents`](https://github.com/jwodder/check-wheel-contents): catches problems like accidentally bundling `.pyc` files into the distribution, or including multiple files with identical content
I think these checks are generically useful in the way that all linters are...putting shared agreements into CI to reduce the scope of things that maintainers and contributors need to remember to check.
But in addition, it contributes to #5061 because these checks will help detect …
=> [ci] [python-package] enforce 'twine check' and 'check-wheel-contents' on Python distributions

python-package/lightgbm/plotting.py
Adds type hints on most other places in `python-package/plotting.py` that were missing them.
Also proposes some other changes that I feel make it easier to follow the flow of data through that module (which I think is closely related to the goal of adding type hints).
* removes defaults in internal function `plotting._to_graphviz()`
- *to prevent "forgot to pass an argument through from the public interface" types of bugs*
* switches to keyword arguments for any function calls passing more than two arguments
- *to prevent "passed these arguments in the wrong order" types of bugs*
I might propose a change similar to #5704 (moving `add()` up to the module level so it isn't redefined every time `_to_graphviz()` is called) in a future PR, but decided not to do that here …
=> [python-package] add type hints on plotting code

python-package/lightgbm/basic.py, python-package/lightgbm/callback.py, python-package/lightgbm/sklearn.py
Adds a few additional type hints in `sklearn.py`, to improve static type checkers' ability to find bugs.
This PR also resolves the following `mypy` warnings:
```text
python-package/lightgbm/sklearn.py:1055: error: Incompatible types in assignment (expression has type "Dict[Any, Any]", variable has type "None")  [assignment]
python-package/lightgbm/sklearn.py:1057: error: Incompatible types in assignment (expression has type "Dict[Any, Any]", variable has type "None")  [assignment]
python-package/lightgbm/sklearn.py:1057: error: Value of type "None" is not indexable  [index]
python-package/lightgbm/sklearn.py:1060: error: Incompatible types in assignment (expression has type "int", variable has type "None")  [assignment] …
```
=> [python-package] add more type hints in sklearn.py

python-package/lightgbm/compat.py, python-package/lightgbm/libpath.py
Fixes the following errors from `mypy`:
```text
python-package/lightgbm/libpath.py:7: error: Need type annotation for "__all__" (hint: "__all__: List[<type>] = ...")  [var-annotated]
python-package/lightgbm/compat.py:150: error: Incompatible types in assignment (expression has type "None", variable has type "Callable[[Any, Any, Any, Any, Any], Any]")  [assignment]
python-package/lightgbm/compat.py:151: error: Incompatible types in assignment (expression has type "None", variable has type "Callable[[Any], Any]")  [assignment]
python-package/lightgbm/compat.py:153: error: Incompatible types in assignment (expression has type "None", variable has type "Callable[[Any], Any]")  [assignment]
python-package/lightgbm/compat.py:154: …
```
=> [python-package] fix mypy errors in compat.py and libpath.py

python-package/lightgbm/basic.py, tests/python_package_test/test_basic.py
Adds the `Booster.set_leaf_output` method to the python API.
Based on #5682.
=> [python-package] add Booster.set_leaf_output method

python-package/lightgbm/basic.py
Fixes the following errors from `mypy`
```text
python-package/lightgbm/basic.py:2117: error: Incompatible types in assignment (expression has type "List[int]", variable has type "None")  [assignment]
python-package/lightgbm/basic.py:2325: error: Item "None" of "Optional[_InnerPredictor]" has no attribute "current_iteration"  [union-attr]
python-package/lightgbm/basic.py:2328: error: Incompatible types in assignment (expression has type "_InnerPredictor", variable has type "None")  [assignment]
```
To make the flow of data through calls to internal function `_set_init_score_by_predictor()`  a bit easier to follow and less susceptible to "forgot to pass through an argument" issues, this PR also removes default values from that function's signature …
=> [python-package] fix mypy errors about _InnerPredictor

python-package/lightgbm/sklearn.py
```text
python-package/lightgbm/sklearn.py:1064: error: List item 0 has incompatible type "Optional[str]"; expected "Union[str, Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]]"  [list-item]
python-package/lightgbm/sklearn.py:1066: error: Argument 1 to "enumerate" has incompatible type "Optional[List[Union[str, Union[Callable[[ndarray[Any, …
```
=> [python-package] fix mypy errors around eval metrics in sklearn.py

python-package/lightgbm/basic.py
```text
python-package/lightgbm/basic.py:149: error: "CDLL" has no attribute "callback"  [attr-defined]
```
=> [python-package] fix mypy error about log callback

python-package/lightgbm/sklearn.py
```text
python-package/lightgbm/sklearn.py:203: error: Incompatible return value type (got "Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]", expected "Tuple[str, float, bool]")  [return-value]
python-package/lightgbm/sklearn.py:205: error: Incompatible return value type (got "Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]", expected "Tuple[str, float, bool]")  [return-value]
python-package/lightgbm/sklearn.py:207: error: Incompatible return value type (got "Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]", expected "Tuple[str, float, bool]")  [return-value]
```
In the `scikit-learn` interface, custom eval functions can return either a tuple of the form …
=> [python-package] fix mypy errors about custom eval functions in sklearn.py

python-package/lightgbm/dask.py
Moved from https://github.com/microsoft/LightGBM/pull/5672.
`mypy` currently raises errors regarding predict_proba() method. This PR proposes a fix for it.
This was tested by running mypy as documented in https://github.com/microsoft/LightGBM/issues/3867.
```
mypy \
```
=> [python-package] [dask] fix mypy errors regarding predict_proba

python-package/lightgbm/sklearn.py
Follow-up to #5672 (thanks @IdoKendo for starting this discussion again!)
```text
python-package/lightgbm/sklearn.py:897: error: Incompatible return value type (got "None", expected "int")  [return-value]
python-package/lightgbm/sklearn.py:904: error: Incompatible return value type (got "None", expected "int")  [return-value]
python-package/lightgbm/sklearn.py:918: error: Incompatible return value type (got "Optional[int]", expected "int")  [return-value]
```
See my description in https://github.com/microsoft/LightGBM/pull/5672#discussion_r1107672623 for the reasoning behind this proposed change.
Besides just running …
=> [python-package] change types in sklearn.py initializations

python-package/lightgbm/engine.py
```text
python-package/lightgbm/engine.py:504: error: Need type annotation for "cvmap"  [var-annotated]
```
=> [python-package] fix mypy errors about cv() internals

python-package/lightgbm/basic.py
Fixed the following `mypy` errors.
```text
python-package/lightgbm/basic.py:1444: error: Incompatible types in assignment (expression has type "c_void_p", variable has type "None")  [assignment]
python-package/lightgbm/basic.py:1448: error: Argument 1 to "byref" has incompatible type "None"; expected "_CData"  [arg-type]
python-package/lightgbm/basic.py:1499: error: Incompatible types in assignment (expression has type "c_void_p", variable has type "None")  [assignment]
python-package/lightgbm/basic.py:1510: error: Argument 1 to "byref" has incompatible type "None"; expected "_CData"  [arg-type]
python-package/lightgbm/basic.py:1689: error: Incompatible types in assignment (expression has type "c_void_p", variable has type "None")  [assignment] …
```
=> [python-package] fix mypy errors about Dataset handle

python-package/lightgbm/engine.py
Fixed custom evaluation function typing according to train documentation: "Each evaluation function should accept two parameters: preds, eval_data, and return (eval_name, eval_result, is_higher_better) or **list of such tuples**."
=> [python-package] fix _LGBM_CustomMetricFunction typing

tests/python_package_test/test_dask.py
Reverts the changes from #5292.
Since I merged that PR, the `test_dask.py` tests have been VERY flaky on GPU builds. My unscientific estimate is that 60% of commits since then have had at least one Azure DevOps GPU job fail.
This PR proposes skipping those tests again, to reduce the required manual effort of re-running jobs and to improve the contribution experience for outside contributors. 
I'm using #5713 to test fixes, but for now I think we should just skip these flaky tests again 😞
=> [ci] skip Dask tests on GPU builds

python-package/lightgbm/basic.py
Sorry, in #5722 I forgot that the Python package already has a type alias, `_DatasetHandle`, that we use for type hints on things that are `Dataset` handles (see https://github.com/microsoft/LightGBM/pull/5458#issuecomment-1235594303).
https://github.com/microsoft/LightGBM/blob/42df0ff3397aabb06f9f6fda2966f16b9cb3b1f6/python-package/lightgbm/basic.py#L32
This PR switches to using that.
=> [python-package] use _DatasetHandle type hint

python-package/lightgbm/basic.py, python-package/lightgbm/callback.py, python-package/lightgbm/engine.py, python-package/lightgbm/plotting.py
Proposes removing default argument values in the following internal functions:
* `Dataset.__init_from_seqs()`
* `Booster.__inner_eval()`
* `_format_eval_result()`
* `_make_n_folds()`
* `_check_not_tuple_of_2_elements()`
* `_float2str()`
Removing defaults helps to prevent "forgot to pass arguments through" types of bugs.
This PR is just about changing reliance on default values, and isn't intended to actually change LightGBM's behavior. If you see any places with a user-facing change, please note them so I can revert them.
=> [python-package] remove default values in internal functions

.ci/test.sh
Follow-up to #5668.
Proposes combining the `conda create` and `conda install` steps run in CI jobs into a single `conda create` step. In #5668 and #5648, we observed that doing that led to less overall time in CI spent waiting for `conda` solves.
I observed the following timing differences in these jobs on this PR, compared to `master`:
| job                                              | latest `master` | this PR   |
|:------------------------------|:---------------:|:--------:|
| (GHA) CUDA 11.7 wheel           |  12m41s             | **12m16s** |
| (GHA) CUDA 10.0 source         |  11m17s              | 11m17s |
| (GHA) CUDA 11.7.1 pip              |  **12m29s**      | 12m35s |
| (GHA) macOS regular               |  16m46s           | **14m49s** |
| (GHA) macOS bdist                  | …
=> [ci] speed up conda setup for macOS and Linux jobs

python-package/lightgbm/basic.py, python-package/lightgbm/engine.py
Adds type hints on `_data_from_pandas()` and `_dump_pandas_categorical()`, internal functions used during `Dataset` construction.
Fixes return type hint on `_load_pandas_categorical()`, which is used to recover information about `pandas` categorical columns from model text files.
=> [python-package] add type hints on Dataset feature processing

python-package/lightgbm/basic.py
Contributes to https://github.com/microsoft/LightGBM/issues/3756
Fixes the following `mypy`.
```text
python-package/lightgbm/basic.py:315: error: "int" not callable  [operator]
python-package/lightgbm/basic.py:315: error: Unsupported operand types for * ("type" and "int")  [operator]
```
Using the `*` operator is the expected way to create a C array using `ctypes`, but `mypy` is confused about it.
Docs: https://docs.python.org/3/library/ctypes.html#arrays
This is a frequently-run code path covered by lots of tests, so I think just ignoring this warning from `mypy` is safe.
=> [python-package] fix mypy error about ctypes array creation

python-package/lightgbm/basic.py
Adds input and return type annotations on `Booster.predict()` and `_InnerPredictor.predict()`.
Based on these docstrings:
https://github.com/microsoft/LightGBM/blob/e8cdc2c99d18e4032ceb943d944618ba70c38394/python-package/lightgbm/basic.py#L842
https://github.com/microsoft/LightGBM/blob/e8cdc2c99d18e4032ceb943d944618ba70c38394/python-package/lightgbm/basic.py#L3958
=> [python-package] add type hints on Booster predict() methods

python-package/lightgbm/sklearn.py
Adds type annotations on `callbacks` argument and `fit()` return type in the scikit-learn interface.
=> [python-package] add type hints on fit() return and callbacks in sklearn.py

python-package/lightgbm/sklearn.py
Follow-up to #5745.
Adds type annotations on `feature_name` and `categorical_feature` in the scikit-learn interface.
=> [python-package] add type hints on feature_name and categorical_feature in sklearn interface

python-package/lightgbm/basic.py
Adds type annotations on `data`, raw data passed to the `Dataset` constructor.
I created this based on this docstring:
https://github.com/microsoft/LightGBM/blob/356a7806882c4aed4f54689d5efe29ae05d5bd6f/python-package/lightgbm/basic.py#L850
This added about 30 new `mypy` warnings. I'm proposing fixing those separately from this PR. There is just SIGNIFICANT complexity here given that `data` can be a path to a file, any of several different array libraries' data types, or a `Sequence` object. I think it'll be easier to work on and fix those new `mypy` warnings in smaller pieces after adding these hints.
=> [python-package] add type hints on raw data passed to Dataset and Booster

python-package/lightgbm/basic.py
Adds type annotations on `group`, `init_score`, and `weight` used throughout `basic.py`.
Created these types based on these docstrings:
https://github.com/microsoft/LightGBM/blob/356a7806882c4aed4f54689d5efe29ae05d5bd6f/python-package/lightgbm/basic.py#L1425-L1434
Similar to #5752, this leads to the introduction of a few new `mypy` warnings. I'm proposing fixing those separately from this PR.
=> [python-package] add type hints on group, init_score, and weight

python-package/lightgbm/basic.py
Contributes to #3756. (we're getting there, slowly!)
Adds a type annotation for `label` passed to `Booster.refit()`, and to function `_list_to_1d_numpy()` which is used to convert lists to `numpy` arrays (including, for example, when processing labels).
=> [python-package] add type hints on label

python-package/lightgbm/basic.py, python-package/lightgbm/sklearn.py
Proposes using keyword arguments for calls to `predict()` methods inside the Python package. This prevents "accidentally passed arguments in the wrong order" types of bugs, and in my opinion makes it a bit easier to read and understand the code when working on it.
=> [python-package] use keyword arguments in predict() calls

python-package/lightgbm/dask.py
Resolves the following `mypy` errors.
```text
python-package/lightgbm/dask.py:1178: error: Incompatible return value type (got "_DaskLGBMModel", expected "DaskLGBMClassifier")  [return-value]
python-package/lightgbm/dask.py:1381: error: Incompatible return value type (got "_DaskLGBMModel", expected "DaskLGBMRegressor")  [return-value]
python-package/lightgbm/dask.py:1553: error: Incompatible return value type (got "_DaskLGBMModel", expected "DaskLGBMRanker")  [return-value]
```
Switches the Dask estimators to returning `self`, so that e.g. `DaskLGBMRegressor.fit()` returns a `DaskLGBMRegressor`. This is useful for other user code and downstream libraries relying on LightGBM, to be able to do `isinstance()` checks and not need to rely on lightgbm-internal details like …
=> [python-package] [dask] fix mypy errors about Dask fit() return types

python-package/lightgbm/dask.py, tests/python_package_test/test_dask.py
Split from #5765.
Proposes replacing the use of `collections.namedtuple` for one internal class in the Dask module with a regular Python class, so that informative type annotations can be added.
This makes it a bit clearer, when reading the code, what the values of that class's attributes should be (unlike `namedtuple`, which is just a collection of attribute names).
I chose to use a regular Python class instead of `dataclasses.dataclass` to preserve support for Python 3.6 (https://github.com/microsoft/LightGBM/pull/5765#issuecomment-1454861675), and chose to avoid `typing.NamedTuple` (https://stackoverflow.com/a/50038614/3986677) to reduce the risk of incompatibilities caused by future updates to `typing`.
=> [python-package] [dask] add type annotations on dask._HostWorkers

tests/c_api_test/test_.py
Contributes to #5061
This repo contains a few tests on LightGBM's C API which are run with `pytest`.
Today, they load `lib_lightgbm.{dll/so}` using a modified copy of the same library-loading code with `ctypes` used in the Python package. LightGBM's CI runs `python setup.py bdist_wheel`, then these C API tests rely on a `lib_lightgbm.{dll/so}` being available in `python-package/compile/`.
https://github.com/microsoft/LightGBM/blob/709ea4cad3ff4c8834bdf389eef8016345d9a1ac/tests/c_api_test/test_.py#L17-L29
This PR proposes removing that reliance on the repo structure + exactly where `lib_lightgbm.so` copies get left behind after building Python wheels.
How does this contribute to #5061? The changes for that (in-progress in #5759) will involve building `lightgbm` wheels in an isolated build …
=> [ci] isolate c_api_test library-loading from Python source tree

python-package/lightgbm/basic.py
Fixes the following errors from `mypy`:
```text
python-package/lightgbm/basic.py:309: error: Argument 2 to "_cast_numpy_array_to_dtype" has incompatible type "type"; expected "dtype[Any]"  [arg-type]
python-package/lightgbm/basic.py:314: error: Argument 2 to "_cast_numpy_array_to_dtype" has incompatible type "type"; expected "dtype[Any]"  [arg-type]
```
=> [python-package] add type hints for functions accepting dtypes

python-package/lightgbm/sklearn.py
Proposes adding type annotations on the remaining sklearn properties that don't have them.
This introduces a few new `mypy` errors, like this:
> python-package/lightgbm/sklearn.py:979: error: Item "None" of "Optional[Booster]" has no attribute "feature_importance"  [union-attr]
python-package/lightgbm/sklearn.py:986: error: Item "None" of "Optional[Booster]" has no attribute "feature_name"  [union-attr]
Those are caused by the fact that some of these attributes are initialized to `None` and we know they'll be non-`None` is `self.__sklearn_is_fitted__()` is `True`...but `mypy` is rightly saying "hey as far as I know, this could be `None` at this point".
I'd like to propose fixes for those in a follow-up PR, so we can continue the conversation …
=> [python-package] add type hints on sklearn properties

python-package/lightgbm/dask.py
```text
python-package/lightgbm/dask.py:47: error: Argument 1 of "__eq__" is incompatible with supertype "object"; supertype defines the argument type as "object"  [override]
python-package/lightgbm/dask.py:47: note: This violates the Liskov substitution principle
python-package/lightgbm/dask.py:47: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
python-package/lightgbm/dask.py:47: note: It is recommended for "__eq__" to work with arbitrary objects, for example:
python-package/lightgbm/dask.py:47: note:     def __eq__(self, other: object) -> bool:
python-package/lightgbm/dask.py:47: …
```
=> [python-package] fix mypy error about dask._HostWorkers.__eq__()

python-package/lightgbm/basic.py
Continued from @IdoKendo 's work on #5731.
Fixes the following `mypy` errors.
```text
python-package/lightgbm/basic.py:1228: error: Incompatible types in assignment (expression has type "_Pointer[c_int64]", variable has type "_Pointer[c_int32]")  [assignment]
python-package/lightgbm/basic.py:1233: error: Incompatible types in assignment (expression has type "_Pointer[c_double]", variable has type "_Pointer[c_float]")  [assignment]
python-package/lightgbm/basic.py:1323: error: Incompatible types in assignment (expression has type "_Pointer[c_int64]", variable has type "_Pointer[c_int32]")  [assignment]
python-package/lightgbm/basic.py:1328: error: Incompatible types in assignment (expression has type "_Pointer[c_double]", variable has type …
```
=> [python-package] fix mypy errors about ctypes pointers

python-package/lightgbm/dask.py
Resolves the following `mypy` errors.
```text
python-package/lightgbm/dask.py:1037: error: "_DaskLGBMModel" has no attribute "_other_params"  [attr-defined]
python-package/lightgbm/dask.py:1066: error: "_DaskLGBMModel" has no attribute "get_params"  [attr-defined]
python-package/lightgbm/dask.py:1089: error: "_DaskLGBMModel" has no attribute "set_params"  [attr-defined]
python-package/lightgbm/dask.py:1095: error: "_DaskLGBMModel" has no attribute "get_params"  [attr-defined]
python-package/lightgbm/dask.py:1104: error: Item "_DaskLGBMModel" of "Union[_DaskLGBMModel, LGBMModel]" has no attribute "get_params"  [union-attr]
```
Those errors all come from the fact that `_DaskLGBMModel` is used as a mixin alongside `lightgbm.sklearn.LGBMModel`... …
=> [python-package] ignore some mypy errors in _DaskLGBMModel

python-package/lightgbm/basic.py
```text
python-package/lightgbm/basic.py:1717: error: Item "None" of "Optional[Dict[str, Any]]" has no attribute "get"  [union-attr]
```
=> [python-package] fix mypy errors about Dataset.params

python-package/lightgbm/compat.py
Fixes the following `mypy` errors.
```text
python-package/lightgbm/sklearn.py:696: error: Incompatible return value type (got "Union[int, Any, None]", expected "int")  [return-value]
```
`lightgbm` tries a few different approaches to determine the number of phyiscal/logical CPUs based on conditional imports. Adding type hints explicitly telling `mypy` that those methods will return integers resolves this issue.
In this case, `mypy` caught a legitimate possible source of bugs 🎉 
If `joblib.cpu_count` can't be imported but `psutil.cpu_count` can, `psutil.cpu_count()` is used to determine the number of available CPUs.
According to the docs at …
=> [python-package] fix mypy error about cpu_count() methods

python-package/lightgbm/basic.py
Fixes the following `mypy` errors.
```text
python-package/lightgbm/basic.py:2753: error: Value of type "Union[str, Path, ndarray[Any, Any], Any, Any, Any, Sequence, List[Sequence], List[ndarray[Any, Any]]]" is not indexable  [index]
python-package/lightgbm/basic.py:2753: error: No overload variant of "__getitem__" of "list" matches argument type "Tuple[List[int], slice]"  [call-overload]
python-package/lightgbm/basic.py:2753: note: Possible overload variants:
python-package/lightgbm/basic.py:2753: note:     def __getitem__(self, SupportsIndex, /) -> Sequence
python-package/lightgbm/basic.py:2753: note:     def __getitem__(self, slice, /) -> List[Sequence] …
```
=> [python-package] replace uses of scipy.sparse.issparse() with isinstance()

python-package/lightgbm/basic.py
```text
python-package/lightgbm/basic.py:2372: error: Incompatible types in assignment (expression has type "Type[number[Any]]", variable has type "Type[floating[Any]]")  [assignment]
```
=> [python-package] add hint on dtypes in Dataset.set_field()

python-package/lightgbm/dask.py, python-package/lightgbm/sklearn.py
Contributes to #3867 .
Follow-up to #5771.
```text
python-package/lightgbm/sklearn.py:884: error: Item "None" of "Optional[Booster]" has no attribute "predict"  [union-attr]
python-package/lightgbm/sklearn.py:959: error: Incompatible return value type (got "Optional[Booster]", expected "Booster")  [return-value]
python-package/lightgbm/sklearn.py:979: error: Item "None" of "Optional[Booster]" has no attribute "feature_importance"  [union-attr]
python-package/lightgbm/sklearn.py:986: error: Item "None" of "Optional[Booster]" has no attribute "feature_name"  [union-attr]
python-package/lightgbm/sklearn.py:1065: error: Argument 1 to "len" has incompatible type "Optional[ndarray[Any, Any]]"; expected "Sized"  [arg-type] …
```
=> [python-package] fix mypy errors about scikit-learn properties

src/io/bin.cpp
Removes unused variables from `bin.cpp`. Addresses the following warnings:
```
io/bin.cpp:165:9: warning: variable 'cnt_zero' set but not used [-Wunused-but-set-variable]
int cnt_zero = 0;
^
io/bin.cpp:164:9: warning: variable 'left_cnt_data' set but not used [-Wunused-but-set-variable]
int left_cnt_data = 0;
^
io/bin.cpp:166:9: warning: variable 'right_cnt_data' set but not used [-Wunused-but-set-variable]
int right_cnt_data = 0;
^
```
[Sample logs](https://github.com/microsoft/LightGBM/actions/runs/4439686426/jobs/7792502161#step:8:500)
=> remove unused variables from bin.cpp

python-package/lightgbm/basic.py
This PR adds type annotations on `basic._c_float_array()` and `basic._c_int_array()`, to make it easier to understand the flow of data through the library and to improve the ability of tools like `mypy` to catch bugs.
Checked with `mypy`, confirmed that no new errors are introduced relative to `master`.
```shell
mypy --ignore-missing-imports python-package/lightgbm
```
=> [python-package] add type annotations on some array methods in basic.py

.ci/test_r_package.sh, .github/workflows/r_package.yml
Reverts part of #5807.
Windows R jobs are failing on `master` with the same error as reported in #5802.
I suspect the root cause is that the changes from https://github.com/r-lib/actions/pull/712 have now made it into `v2` of the `r-lib/setup-tinytex` action.
=> [ci] remove pin on tinytex in R CI jobs

python-package/lightgbm/sklearn.py, tests/python_package_test/test_sklearn.py
Follow-up to #5757.
Adds type annotations on all remaining arguments to `fit()` methods in the scikit-learn interface.
Replaces all remaining uses of "array" or "array-like" in `fit()` docs with specific types, following @StrikerRUS 's suggestion from https://github.com/microsoft/LightGBM/issues/3756#issuecomment-907622141.
This will hopefully make the docs a bit clearer for users, the code a bit easier to understand for contributors, and will improve `mypy`'s ability to catch type issues (both in this project and in upstream projects that depend on `lightgbm`).
Added additional test cases in `test_sklearn.py` adding some other data types for `init_score`, `sample_weight`, and all the `eval_*` equivalents. Those tests don't cover every possible combination of all …
=> [python-package] [docs] complete type annotations for scikit-learn fit() methods

python-package/lightgbm/engine.py
```text
python-package/lightgbm/engine.py:735: error: Unexpected keyword argument "fobj"  [call-arg]
python-package/lightgbm/engine.py:736: error: Too few arguments  [call-arg]
```
I think the way that `CVBooster` customizes `__getattr__()` is just too much dynamic stuff for `mypy` to cleanly resolve.
https://github.com/microsoft/LightGBM/blob/638014d5c56fb92396bd55f344a47e3f651a3cd4/python-package/lightgbm/engine.py#L344-L352
I'm confident in just ignoring these with `#type: ignore` comments because this code is well-covered by tests.
=> [ci] [python-package] fix mypy errors in cv()

python-package/lightgbm/basic.py
Contributes to #3867 .
```text
python-package/lightgbm/basic.py:2038: error: Argument 1 to "c_int" has incompatible type "Optional[int]"; expected "int"  [arg-type]
```
=> [python-package] fix mypy error in Dataset.__init_from_list_np2d()

python-package/lightgbm/dask.py
Contributes to https://github.com/microsoft/LightGBM/issues/3867 .
Fixes the following `mypy` errors.
```text
-python-package/lightgbm/dask.py:1238: error: Argument 1 of "predict" is incompatible with supertype "LGBMClassifier"; supertype defines the argument type as "Union[Any, List[Union[List[float], List[int]]], ndarray[Any, Any], Any, Any]"  [override]
-python-package/lightgbm/dask.py:1238: note: This violates the Liskov substitution principle
-python-package/lightgbm/dask.py:1238: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
-python-package/lightgbm/dask.py:1238: error: Argument 1 of "predict" is incompatible with supertype "LGBMModel"; supertype defines the argument type as "Union[Any, List[Union[List[float], List[int]]], ndarray[Any, …
```
=> [ci] [dask] fix mypy errors about predict() signature

.ci/test.sh
Proposes temporarily pinning `pip` to `<23.1` in CI, to work around this error: https://github.com/microsoft/LightGBM/issues/5061#issuecomment-1510642287
```text
no such option: --install-option
```
`pip` dropped support for `pip install --install-option` in its most recent release: https://pip.pypa.io/en/stable/news/.
We can hopefully revert this shortly after the work for #5061 is done.
=> [ci] put a temporary ceiling on pip

python-package/lightgbm/basic.py
```text
python-package/lightgbm/basic.py:2200: error: Argument "used_indices" to "_set_init_score_by_predictor" of "Dataset" has incompatible type "ndarray[Any, Any]"; expected "Optional[List[int]]"  [arg-type]
```
`Dataset._set_init_score_by_predictor()` is passed a 1-dimensional `numpy` array here:
https://github.com/microsoft/LightGBM/blob/ffb298626e131b9d213b34b3655846be441fdc12/python-package/lightgbm/basic.py#L2175
https://github.com/microsoft/LightGBM/blob/ffb298626e131b9d213b34b3655846be441fdc12/python-package/lightgbm/basic.py#L2197-L2201
And is able to work with it, since the code in that method only does positional subsetting and not any array-specific or list-specific operations.
=> [python-package] fix mypy error about used_indices in Dataset.subset()

python-package/lightgbm/basic.py, python-package/lightgbm/dask.py, python-package/lightgbm/engine.py, tests/python_package_test/test_basic.py
Proposes removing default argument values on the following internal functions in the Python package:
* `_list_to_1d_numpy()`
* `_list_to_2d_numpy()`
* `Dataset._lazy_init()`
Doing this makes the flow of configuration and data through the code a bit easier to understand, and reduces the risk of "silently fell back to a default because an argument accidentally wasn't passed through" types of bugs.
=> [python-package] remove default arguments in internal functions

python-package/lightgbm/engine.py, tests/python_package_test/test_engine.py
Moves some validation up earlier in `cv()` and `train()`, and clarifies some error messages in those functions.
Moving this validation up a bit earlier means that users can get quicker feedback about calls to those functions that are destined to fail *before* incurring the time and computation cost of potentially-expensive operations like loading `init_model` from a file.
=> [python-package] move validation up earlier in cv() and train()

python-package/lightgbm/engine.py
Fixes the following error from `mypy`.
```text
python-package/lightgbm/engine.py:766: error: Incompatible types in assignment (expression has type "CVBooster", target has type "List[float]")  [assignment]
```
That error is raised because `mypy` (correctly) infers that the return value for `cv()` is a `Dict[str, List[float]]` here:
https://github.com/microsoft/LightGBM/blob/f74875ed60e696ee7d223ddb409e66f51bddbb47/python-package/lightgbm/engine.py#L704
https://github.com/microsoft/LightGBM/blob/f74875ed60e696ee7d223ddb409e66f51bddbb47/python-package/lightgbm/engine.py#L746-L748
But then it tries to add an item that is a `CVBooster` here:
https://github.com/microsoft/LightGBM/blob/f74875ed60e696ee7d223ddb409e66f51bddbb47/python-package/lightgbm/engine.py#L765-L766
I …
=> [ci] [python-package] fix mypy error about return_cvbooster in cv()

python-package/lightgbm/dask.py
Fixes the following error from `mypy`.
```text
python-package/lightgbm/dask.py:840: error: Need type annotation for "result"  [var-annotated]
```
=> [ci] [python-package] fix mypy error about dask._predict_part()

tests/python_package_test/test_engine.py
The Python package does not currently have tests covering the case where `cv()` is used with an `init_model` from an in-memory `Booster` or a model text file.
This adds such tests:
<details><summary>how I got those coverage summaries (click me)</summary>
```text
rm -rf ./build
mkdir build
cd build
cmake ..
make -j3
cd ..
cd ./python-package
python setup.py install --precompile
cd ..
pip install pytest-cov
SITE_PACKAGE_DIR=$(
python -c "import site; print(site.getsitepackages()[0])"
)
pytest \
--cov=${SITE_PACKAGE_DIR}/lightgbm \
tests/python_package_test/
coverage html
open ./htmlcov/index.html
```
</details>
=> [ci] add tests on cv() with an init_model

python-package/lightgbm/basic.py
```text
python-package/lightgbm/basic.py:4198: error: Item "List[Any]" of "Union[ndarray[Any, Any], Any, List[Any]]" has no attribute "shape"  [union-attr]
python-package/lightgbm/basic.py:4228: error: Item "List[Any]" of "Union[ndarray[Any, Any], Any, List[Any]]" has no attribute "reshape"  [union-attr]
```
These errors come from the fact that `mypy` thinks it's possible for `_InnerPredictor.predict()` to return a List but in the lines those errors are reported on, the code uses the output of `_InnerPredictor.predict()` as `numpy` array unconditionally.
`mypy` doesn't know that when `pred_leaf=True`, the output of that function will never be a list.
=> [ci] [python-package] fix mypy errors in Booster.refit()

python-package/lightgbm/basic.py
Fixes the following errors `mypy`:
```text
python-package/lightgbm/basic.py:4517: error: No overload variant of "__setitem__" of "list" matches argument types "int", "ndarray[Any, dtype[floating[_64Bit]]]"  [call-overload]
python-package/lightgbm/basic.py:4517: note: Possible overload variants:
python-package/lightgbm/basic.py:4517: note:     def __setitem__(self, SupportsIndex, None, /) -> None
python-package/lightgbm/basic.py:4517: note:     def __setitem__(self, slice, Iterable[None], /) -> None
python-package/lightgbm/basic.py:4521: error: "None" has no attribute "ctypes"  [attr-defined]
python-package/lightgbm/basic.py:4527: error: Argument 1 to "len" has incompatible type "None"; expected "Sized"  [arg-type]
python-package/lightgbm/basic.py:4532: error: "None" …
```
=> [python-package] [ci] fix mypy errors in Booster.__inner_predict()

python-package/lightgbm/basic.py
```text
python-package/lightgbm/basic.py:1750: error: Item "List[Any]" of "Union[ndarray[Any, Any], Any, List[Any]]" has no attribute "ravel"  [union-attr]
python-package/lightgbm/basic.py:1768: error: Item "List[float]" of "Union[List[float], Any, List[List[float]], ndarray[Any, Any]]" has no attribute "shape"  [union-attr]
python-package/lightgbm/basic.py:1768: error: Item "List[List[float]]" of "Union[List[float], Any, List[List[float]], ndarray[Any, Any]]" has no attribute "shape"  [union-attr]
```
=> [ci] [python-package] fix mypy errors about Dataset._set_init_score_by_predictor()

.ci/test_r_package.sh, .github/workflows/r_package.yml
Removes the R 3.6 macOS jobs.
See "Motivation" and https://github.com/microsoft/LightGBM/pull/5859#discussion_r1177331016 for why.
Reasons I think this is ok:
* we still have CI jobs testing the R package against R 3.6 on Windows and Linux
* R 3.6 compatibility isn't required by CRAN any more
* the last release in the 3.6 series, 3.6.3, came out 3+ years ago ([release history](https://cran.r-project.org/bin/windows/base/old/))
Starting recently, I've noticed that the macOS R 3.6 jobs have been failing with the following error.
> installer: Error - the package path specified was invalid: '/Users/runner/work/LightGBM/LightGBM/R.pkg'.
([example build link](https://github.com/microsoft/LightGBM/actions/runs/4803699366/jobs/8548454888))
It looks like RStudio's CRAN changed the download link …
=> [ci] remove R 3.6 macOS CI jobs

.ci/check_python_dists.sh
Proposes adding `pydistcheck` to the set of checks run on Python sdists and wheels (the artifacts this project publishes to PyPI).
`pydistcheck` is a linter for Python distributions, similar with `check-wheel-contents` but with a very different set of checks, including:
* inclusion of debug symbols in `lib_lightgbm.so` / `lib_lightgbm.dll`
* accidental inclusion of unnecessary files
- see #3639 and #3685, for example
* other portability issues documented at https://pydistcheck.readthedocs.io/en/latest/check-reference.html
I believe adding this will improve our confidence in releases of the Python package.
Full disclosure, `pydistcheck` is my own personal side-project: https://github.com/jameslamb/pydistcheck. I started it after a conference talk I gave last year. …
=> [ci] [python-package] check distributions with pydistcheck

python-package/lightgbm/dask.py
Contributes to #3867 .
Fixes the remaining `mypy` errors in `dask.py`.
```text
python-package/lightgbm/dask.py:610: error: Argument 1 to "append" of "list" has incompatible type "Tuple[List[Union[ndarray[Any, Any], Any, None]], List[Union[ndarray[Any, Any], Any, None]]]"; expected "_DatasetNames"  [arg-type]
python-package/lightgbm/dask.py:613: error: Value of type "_DatasetNames" is not indexable  [index]
python-package/lightgbm/dask.py:614: error: Value of type "_DatasetNames" is not indexable  [index]
python-package/lightgbm/dask.py:632: error: Argument 1 to "append" of "list" has incompatible type "List[Union[ndarray[Any, Any], Any, None]]"; expected "_DatasetNames"  [arg-type]
python-package/lightgbm/dask.py:634: error: "_DatasetNames" has no attribute "append" …
```
=> [ci] [python-package] resolve remaining mypy errors in dask.py

.appveyor.yml, .ci/test.sh, .ci/test_windows.ps1, .gitignore, build-python.sh, docker/dockerfile-python, docker/gpu/dockerfile.gpu, docs/FAQ.rst, docs/GPU-Tutorial.rst, python-package/README.rst, python-package/setup.py
This PR proposes replacing all existing direct invocations of `python setup.py` with a shell script, `build-python-package.sh`.
For people using `pip install` or `conda install`, **this PR does not change anything**.
Anyone currently building / installing the Python package from sources here on GitHub using commands like the following:
```shell
cd python-package
python setup.py {command} [OPTIONS]
```
Would now instead run
```shell
sh ./build-python.sh {command} [OPTIONS]
```
Most Python build tools (e.g. `wheel`, `build`, `pip wheel`, `scikit-build`, `hatchling`, etc.) assume a directory structure with all source files at or below the level of where the tool is called from. This repo contains more than just a Python package, and so it can't be directly used that …
=> [ci] [python-package] replace 'python setup.py' with a shell script

build-python.sh
Minor cleanup of `build-python.sh`, introduced in #5837.
=> [ci] minor fixes to build-python.sh

CMakeLists.txt, R-package/src/Makevars.win.in
This change should improve compatibility and consistency with other projects and build tools, and prevent any potential issues arising from the inconsistent capitalization of the library names.
=> [ci] use lowercase library names in linker flags

.github/workflows/static_analysis.yml
Proposes running the `lint` CI task in a Python 3.11 environment, to ensure we continue to be able to install the latest versions of that job's various dependencies together.
I'm hoping it might help with #5746, which in turn might improve `mypy`'s ability to catch bugs.
=> [ci] use Python 3.11 in linting CI job

python-package/lightgbm/basic.py
Fixes the following error from `mypy`.
```text
python-package/lightgbm/basic.py:691: error: Incompatible types in assignment (expression has type "List[object]", variable has type "Union[List[str], List[int], str, None]")  [assignment]
```
For arguments `feature_name` and `categorical_feature`, the Python package supports passing 3 possible non-`None` values:
* list of strings (column names)
* list of ints (0-based positional indexes of the columns)
* string `"auto"` (interpreted as "figure it out automatically" for `pandas` inputs, and as `None` otherwise)
Using the `typing.Literal` annotation, added in Python 3.8, `mypy` is able to understand that if these arguments are not `None` or a list, they must be *literally `"auto"`*, not any arbitrary …
=> [ci] [python-package] tell mypy 'auto' has a special meaning for feature_name and categorical_feature

docs/FAQ.rst, python-package/README.rst
This project's docs currently recommend running the following to force installation of a source distribution (instead of a wheel with a precompiled `lib_lightgbm`):
```shell
pip install --no-binary :all: lightgbm
```
The use of `:all:` is unnecessary... it implies "do not use ANY wheels". That means, for example, that if `numpy` isn't already installed then it will ALSO be built from source.
From `pip --help`.
> --no-binary <format_control>
Do not use binary packages. Can be supplied multiple times, and
each time adds to the existing value. Accepts either ":all:" to
disable all binary packages, ":none:" to empty the set (notice the
colons), or one or more package names with commas between them (no
colons). Note that some packages are tricky to compile and may fail
to install when this …
=> [docs] recommend a more efficient source installation of the python package

.ci/test.sh, .ci/test_windows.ps1
Since #5837, CI jobs on macOS are failing to rename the macOS wheels.
> mv: rename dist/lightgbm-3.3.5.99-py3-none-macosx*.whl to dist/lightgbm-3.3.5.99-py3-none-macosx_10_15_x86_64.macosx_11_6_x86_64.macosx_12_5_x86_64.whl: No such file or directory
([build link](https://github.com/microsoft/LightGBM/actions/runs/4920451551/jobs/8789262420#step:3:652))
This is because the logic in `build-python.sh` doesn't pass `--plat-name=macosx` through when building wheels. Doing that (and adding more logic to detect that it's on macOS) isn't necessary.
In all of LightGBM's CI scripts, we rename wheels manually anyway, like this
https://github.com/microsoft/LightGBM/blob/1c873af9c069ac09afae37a9787ee4f7f0f0ad68/.ci/test.sh#L161-L163
And in #5759, `scikit-build-core` will generate wheels with the …
=> [ci] fix wheel renaming in test.sh

python-package/lightgbm/basic.py
Fixes the following error from `mypy`:
```text
python-package/lightgbm/basic.py:2480: error: Value of type variable "SupportsRichComparisonT" of "sorted" cannot be "object"  [type-var]
```
=> [ci] [python-package] fix mypy error in Dataset.set_categorical_feature()

python-package/lightgbm/sklearn.py
> python-package/lightgbm/sklearn.py:751: error: List item 0 has incompatible type "Union[str, Callable[[Optional[Any], Any], Tuple[str, float, bool]], Callable[[Optional[Any], Any], List[Tuple[str, float, bool]]], Callable[[Optional[Any], Any, Optional[Any]], Tuple[str, float, bool]], Callable[[Optional[Any], Any, Optional[Any]], List[Tuple[str, float, bool]]], Callable[[Optional[Any], Any, Optional[Any], Optional[Any]], Tuple[str, float, bool]], Callable[[Optional[Any], Any, Optional[Any], Optional[Any]], List[Tuple[str, float, bool]]], None]"; expected "Union[str, Callable[[Optional[Any], Any], Tuple[str, float, bool]], Callable[[Optional[Any], Any], List[Tuple[str, float, bool]]], …
=> [ci] [python-package] fix mypy errors in sklearn.py

.ci/lint-python.sh, .ci/test.sh, python-package/lightgbm/basic.py, python-package/lightgbm/callback.py, python-package/lightgbm/dask.py, python-package/pyproject.toml, tests/distributed/_test_distributed.py, tests/python_package_test/test_basic.py, tests/python_package_test/test_dask.py, tests/python_package_test/test_engine.py, tests/python_package_test/test_sklearn.py
Proposes using `ruff` (https://github.com/charliermarsh/ruff) in this project's `lint` task, to enforce the following checks:
* `flake8` (`pyflakes` + `pycodestyle`)
* `flake8-bugbear`
* `flake8-comprehensions`
* `pydocstyle`
Proposes enabling the following `flake8` plugins (via `ruff`):
* `flake8-bugbear` (https://github.com/PyCQA/flake8-bugbear)
* `flake8-comprehensions` (https://github.com/adamchainz/flake8-comprehensions)
This PR also fixes the following types of issues found by `flake8-bugbear`...
```text
B006 Do not use mutable data structures for argument defaults.  They are created during function definition time. All calls to the function reuse this one instance of that data structure, persisting changes between them.
B007 Loop control variable 'k' not used within the loop body. …
```
=> [ci] [python-package] use ruff, enforce flake8-bugbear and flake8-comprehensions checks

.ci/test.sh, CMakeLists.txt, python-package/setup.py
Proposes adding 3 options to `CMakeLists.txt`:
* `__BUILD_FOR_PYTHON` = indicate that lib_lightgbm is being built for use in a Python wheel
* `BUILD_CLI` = do / do not compile the `lightgbm` CLI when running `make` or `make install`
* `INSTALL_HEADERS` = do/do not move LightGBM's headers into `CMAKE_INSTALL_PREFIX` (e.g. `/usr/local/include/LightGBM/*.h`)
Prevents unnecessary compilation of the CLI when building the Python package with `scikit-build-core`.
Prevents unnecessary generation of Makefile code for targets that won't ever be used by the R and Python packages.
LightGBM's `CMakeLists.txt` generates Makefile(s) where `make` / `make install` has 3 effects:
* compile `lib_lightgbm.{dll/so}` + install it
* compile `lightgbm` (the CLI) + install it
* install …
=> add CMakeLists options to disable building CLI, installing headers

.ci/test_r_package.sh, .ci/test_windows.ps1
Fixes #5898.
Fixes #5899.
Proposes switching to an MRAN snapshot ([link](https://mran.microsoft.com/documents/rro/reproducibility)) of CRAN for R 3.6 CI jobs. This ensures that the packages installed are from a frozen moment in time...which should reduce the risk of CI failures caused by trying to install new versions of `{lightgbm}`'s dependencies using old versions of R and old operating systems.
This is most important for Linux, as CRAN doesn't host precompiled binaries for Linux (only Windows and macOS).
=> [ci] use an MRAN snapshot for R 3.6 Linux jobs (fixes #5898)

windows/LightGBM.vcxproj
Fixes #5856.
Tonight I tried compiling LightGBM on latest `master` with `MSBUild` (using Visual Studio 2019), like this:
```pwsh
MSBuild.exe windows/LightGBM.sln /p:Configuration=DLL /p:Platform=x64 /p:PlatformToolset=v142
```
That resulted in this error:
>   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\cstddef(12,10): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory (compiling source file ..\src\treelearner\voting_parallel_tree_learner.cpp) [C:\Users\James\repos\LightGBM\windows\LightGBM.vcxproj]
Updating the target Windows SDK version from 8.1 to 10.0 fixed that.
Then I hit the error reported in #5856. I think that happened because when building without CMake, the test introduced …
=> update MSBuild solution to Windows SDK v10.0, add inet_pton define (fixes #5856)

docs/Quick-Start.rst
Make `lightgbm` command executable on command line
=> [docs] Update Quick Start

.ci/test_r_package.sh
#5903 proposed using an MRAN snapshot to install an old version of `{lattice}` on R 3.6 CI jobs (fixing #5898).
That worked for a few days, but those jobs are again failing today ([click here for an example build](https://github.com/microsoft/LightGBM/actions/runs/5167025882/jobs/9315250012?pr=5818)).
> Warning: unable to access index for repository https://cran.microsoft.com/snapshot/2020-04-23/src/contrib:
cannot open URL 'https://cran.microsoft.com/snapshot/2020-04-23/src/contrib/PACKAGES'
Probably because cran.microsoft.com is unavailable. Looks like Microsoft is permanently taking down MRAN and cran.microsoft.com at the end of the month 🙃 
From https://techcommunity.microsoft.com/t5/azure-sql-blog/microsoft-r-application-network-retirement/ba-p/3707161
> *the retirement process, the …
=> [ci] stop relying on cran.microsoft.com in CI jobs

cmake/IntegratedOpenCL.cmake, docs/Installation-Guide.rst
Adds support for building with `Ninja` instead of `make` on Linux.
This is necessary (or at least, very very helpful) for integrating `scikit-build-core` as the backend for building the Python package (as I'm working on in #5759).
`Ninja` is an open-source alternative to `make`, originally developed to support building Google Chrome on Linux (["Google man open sources Chrome build system"](https://www.theregister.com/2011/02/08/google_ninja_build_system_open_sourced/)).
It's often much faster than `make`, in exchange for being simpler (i.e. supporting a stricter, harder-to-customize API).
Because of its build speeds, `Ninja` is the strongly-preferred default build tool for macOS and Linux in `scikit-build-core`. See https://github.com/scikit-build/scikit-build-core. …
=> [c++] support building with Ninja on Linux

python-package/lightgbm/plotting.py, tests/python_package_test/test_plotting.py
=> [python-package] adding max_category_values parameter to create_tree_digraph method (fixes #5687)

.ci/test_windows.ps1, build-python.sh
Fixes #5906.
On `master`, `build-python.sh install` will not update the installed version of `lightgbm` if that version has already been installed. For example:
```shell
sh build-python.sh install
sh build-python.sh install
```
This PR proposes modifying `build-python.sh` such that it'll always install the version it's just built, regardless of what's already installed. I think that is closer to what is expected when building from sources cloned from GitHub, and it also makes local development a bit more reliable and convenient (no need to `pip uninstall` each time you rebuild).
The relevant code for installing with `--precompile` doesn't need to change, as `python setup.py install` will always reinstall over an existing version. …
=> [python-package] ensure 'build-python.sh' always reinstalls (fixes #5906)

.ci/test_r_package.sh
Fixes #5670 (again).
Fixes the macOS R-package CI jobs by removing a `brew update-reset` (again).
History:
* #4160
* #4161
* #5670
* #5671
* #5807
* https://github.com/microsoft/LightGBM/issues/5670#issuecomment-1590437347
=> [ci] remove brew update-reset again (fixes #5670)

README.md
Contributes to #5606.
Adds the quantized training paper to the README alongside other papers.
@shiyu1994 @guolinke are there any others you'd like me to add?
=> [docs] add quantized training paper to docs

include/LightGBM/cuda/cuda_utils.h, src/metric/cuda/cuda_pointwise_metric.cpp, src/metric/cuda/cuda_pointwise_metric.cu, src/metric/cuda/cuda_regression_metric.cpp, src/metric/cuda/cuda_regression_metric.hpp, src/metric/metric.cpp
add regression metrics for cuda extension
=> [CUDA] Add more CUDA Regression Metrics

docs/.linkcheckerrc, docs/Parallel-Learning-Guide.rst
The `check-links` CI job has been broken for a while. ([most recent build link](https://github.com/microsoft/LightGBM/actions/runs/5343076586/jobs/9685687417)).
This PR fixes the 3 errors:
```text
URL        `https://www.tandfonline.com/doi/abs/10.1080/01621459.1958.10501479'
Name       `Fisher (1958)'
Parent URL file:///home/runner/work/LightGBM/LightGBM/docs/_build/html/Advanced-Topics.html, line 120, col 1
Real URL   https://www.tandfonline.com/doi/abs/10.1080/01621459.1958.10501479
Check time 0.230 seconds
Result     Error: 403 Forbidden
```
```text
URL        `https://docs.pymars.org/en/latest/index.html'
Name       `Mars'
Parent URL file:///home/runner/work/LightGBM/LightGBM/docs/_build/html/Parallel-Learning-Guide.html, line 543, col 4
Real URL …
```
=> [docs] fix broken links in docs

python-package/README.rst, python-package/pyproject.toml, python-package/setup.cfg
While working on #5936, I discovered that `lightgbm` is incompatible with `pandas<0.24.0`. This PR proposes adding a `[pandas]` extra to the Python package to track that floor, so users can run `pip install 'lightgbm[pandas]'` to be guaranteed to either get a compatible version or a big, loud, clear error.
Other changes:
* moves configuration for extras to `pyproject.toml`
- #5759 broke `pip install 'lightgbm[dask]'`, sorry 😬
* moves docs for the extras up under "Install from PyPI" section in the docs
* consolidates the three `dask` dependencies into one
<details><summary>details (click me)</summary>
`lightgbm` can only be used with `pandas` if `CategoricalDType` can be imported...
https://github.com/microsoft/LightGBM/blob/ac57d5a45a3ff3a04fbbcb8fb24f0c60072471e2/python-package/lightgbm/c …
=> [python-package] add 'pandas' extra

python-package/README.rst, python-package/pyproject.toml, python-package/setup.cfg
Today, `pip install lightgbm` absolutely requires that you're able to also install `numpy`, `scipy`, and `scikit-learn` (and therefore all of their recursive dependencies).
This PR proposes removing the hard requirement on `scikit-learn`, so that users who aren't using the `lightgbm.sklearn` interface don't have to pay the download time, disk usage, and incompatibility-risk cost of having to install `scikit-learn`.
`scikit-learn` is already used conditionally throughout the package...
https://github.com/microsoft/LightGBM/blob/2e603f860664d3aaf382059a378f3212049f1c4c/python-package/lightgbm/compat.py#L71-L73
https://github.com/microsoft/LightGBM/blob/2e603f860664d3aaf382059a378f3212049f1c4c/python-package/lightgbm/sklearn.py#L531-L533
... so this is only a change to the Python package's …
=> [python-package] remove hard dependency on 'scikit-learn', fix minimal runtime dependencies

build-python.sh
Follow-up to #5907.
Tells `pip install` in `sh ./build-python.sh install` to:
* not consult the `pip` cache dir (the place `pip` puts `.tar.gz` and `.whl` files it downloads) when installing
* not add the just-locally-build sdist/wheel to that cache dir
This ensures that `build-python.sh install` will overwrite an existing installation of `lightgbm`, even if it had been run previously in the same environment.
=> [python-package] ignore pip cache dir in build-python.sh

docs/conf.py
Fixes https://github.com/microsoft/LightGBM/issues/5954
This PR enables Sphinx's intersphinx extension such that links to scikit-learn's docs can be resolved. Note that the [sphinx.ext.intersphinx](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html) extension comes with Sphinx.
=> [docs] Add scikit-learn for intersphinx (fixes #5954)

.github/workflows/r_valgrind.yml, docs/env.yml
Blocks #5952.
* upgrades the timeout on the `r-valgrind` CI job to 6 hours, to try to fix https://github.com/microsoft/LightGBM/pull/5952#issuecomment-1613764158
As described in #5414, this has to be merged to `master` to be tested, since the valgrind job's configuration is only sourced from `master`.
6 hours is the absolute maximum GitHub Actions allows: https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits.
So if this doesn't work, we'll have to come up with another strategy for running the valgrind tests faster (like maybe finding a source of Linux precompiled binaries for `{lightgbm}`'s dependencies), or will have to rely on running them somewhere else (even maybe just locally on a maintainer's laptop 😬 ).
=> [ci] increase valgrind timeout to 6 hours

docs/FAQ.rst
The `Link Checks` CI job has been failing because apparently the GitHub account `@tongwu-msft` no longer exists.
```text
URL        `https://github.com/tongwu-msft'
Name       `@tongwu-msft'
Parent URL file:///home/runner/work/LightGBM/LightGBM/docs/_build/html/FAQ.html, line 150, col 8
Real URL   https://github.com/tongwu-msft
Check time 2.058 seconds
Size       40B
```
([build link](https://github.com/microsoft/LightGBM/actions/runs/5461860140))
=> [docs] fix broken link to contributor GitHub account

src/treelearner/gradient_discretizer.hpp
This is to fix the compilation warning.
```
/Applications/Xcode_11.7.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2338:5: warning: delete called on non-final 'LightGBM::GradientDiscretizer' that has virtual functions but non-virtual destructor [-Wdelete-non-abstract-non-virtual-dtor]
delete __ptr;
^
/Applications/Xcode_11.7.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2651:7: note: in instantiation of member function 'std::__1::default_delete<LightGBM::GradientDiscretizer>::operator()' requested here
__ptr_.second()(__tmp);
^
/Users/runner/work/1/s/lightgbm-python/src/treelearner/serial_tree_learner.cpp:65:27: note: in instantiation of member function …
```
=> [c++] virtual destructor for gradient discretizer

python-package/lightgbm/basic.py
In the Python package, you can generate predictions on data stored in a delimited text file by passing a filepath to `Booster.predict()`.
That calls `LGBM_BoosterPredictForFile()` in the C API, which takes a boolean argument indicating whether or not the file's first row is a header with feature names.
That argument, `data_has_header`, is a boolean in `Booster.predict()`'s interface but an int in `LGBM_BoosterPredictForFile()`, leading to this conversion:
https://github.com/microsoft/LightGBM/blob/714039681a9502ce6644357d38ec9143bf5a7852/python-package/lightgbm/basic.py#L964
This PR proposes moving that conversion down into the `if-else` block corresponding to "`data` is a file", so it's cost is avoided on all other prediction paths.
I'm sure the cost of that one check is very very very …
=> [python-package] avoid data_has_header check in predict()

docker/dockerfile-python
dockerfile is updated 2 month ago.
there is missed change directory command. (it is originally existed)
=> Fix Python Dockerfile

.ci/test_windows.ps1, R-package/tests/testthat/test_dataset.R
Fixes #5995.
Attempts to force `conda` to use a newer version of `h5py` in tests, to avoid the errors in the linked issue related to the combination of newer `numpy` and older `h5py` being incompatible.
Also fixes the following error caused by the new release of `{lintr}` a few hours ago:
> [1] Total linting issues found: 1
[[1]]
/home/runner/work/LightGBM/LightGBM/R-package/tests/testthat/test_dataset.R:449:16: warning: [paste] strrep(x, times) is better than paste0(rep(x, times), collapse = "").
long_name <- paste0(rep("a", 1000L), collapse = "")
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
([failed R linting job](https://github.com/microsoft/LightGBM/actions/runs/5613432576/job/15209447243?pr=5996))
=> [ci] use newer h5py in AppVeyor jobs (fixes #5995)

R-package/R/lgb.Dataset.R, R-package/R/lgb.Predictor.R, R-package/R/lgb.convert_with_rules.R, R-package/R/lgb.cv.R, R-package/tests/testthat/test_lgb.Booster.R
Removes some unused internal variables in the R package code.
The project's `{lintr}` checks and `R CMD check` don't catch these, but PyCharm did 😁
=> [R-package] remove unused internal variables

R-package/tests/testthat/helper.R, R-package/tests/testthat/test_Predictor.R, R-package/tests/testthat/test_basic.R, R-package/tests/testthat/test_custom_objective.R, R-package/tests/testthat/test_dataset.R, R-package/tests/testthat/test_learning_to_rank.R, R-package/tests/testthat/test_lgb.Booster.R, R-package/tests/testthat/test_lgb.interprete.R, R-package/tests/testthat/test_lgb.plot.importance.R, R-package/tests/testthat/test_lgb.plot.interpretation.R, R-package/tests/testthat/test_weighted_loss.R
Working on #5988, I learned about the `helpers.R` mechanism in `{testthat}`.
That file is sourced before each test file is run (sort of like a `conftest.py` with `pytest` in Python). This PR proposes consolidating some constants that are duplicated across all the tests files into that file, to reduce duplication and encourage consistency across the tests.
For details on how `{testthat}` treats that file specially, see https://r-pkgs.org/testing-design.html#testthat-helper-files.
> *file that is always executed by `load_all()` and at the beginning of automated testing is a helper file, defined as any file below `tests/testthat/` that begins with `helper`.*
=> [R-package] consolidate testing constants in helpers file

python-package/lightgbm/basic.py
Replaces the use of `np.find_common_type` with `np.result_type` to determine the type that should be used when coercing a pandas dataframe to a numpy array.
This function was added in numpy 1.6 ([docs](https://numpy.org/doc/stable/reference/generated/numpy.result_type.html)), which is from [May 2011](https://pypi.org/project/numpy/1.6.0/) and the lowest version we support [is 1.12](https://github.com/microsoft/LightGBM/blob/8967debeb5cb03875eb96a22dbcaa5387b5abaa3/.ci/test-python-oldest.sh#L10) so there shouldn't be any compatibility issues.
Fixes #5990.
=> [python-package] replace np.find_common_type with np.result_type

.ci/test.sh
=> [ci] enforce dask version to be >=2023.5.0 in some builds (fixes #6030)

include/LightGBM/cuda/cuda_column_data.hpp, include/LightGBM/cuda/cuda_metric.hpp, include/LightGBM/cuda/cuda_objective_function.hpp, include/LightGBM/cuda/cuda_utils.h, src/cuda/cuda_utils.cpp, src/io/cuda/cuda_column_data.cpp
This is to fix the issue proposed in #6018. As reported in the issue, currently illegal memory access may arise when using a `gpu_device_id > 0` for `cuda` tree learner. This is because some CUDA memory is allocated in threads. Though the device ID is set in the main thread, it is not set in the newly created threads. The allocated CUDA memory in those threads may reside in GPU 0 by default, which is different with the `gpu_device_id`. Accessing to such memory on `gpu_device_id` may cause illegal memory access.
Here's one example,
https://github.com/microsoft/LightGBM/blob/20975badd7ea3083c89f08a1f4dfda1a9789f6bc/src/io/cuda/cuda_column_data.cpp#L120-L137
=> [CUDA] Set GPU device ID in threads

.github/workflows/lock.yml
#6037 reintroduced a bot for locking discussion on long-inactive closed PRs and issues, to encourage discussions to stay in highly-visible places.
This PR fixes two bugs in that configuration:
* ensures that bot-posted comments have correct text wrapping
* ensures that issues with the label `feature request` are not locked
- *since we close such issues, link to them from #2302, and encourage contributors to comment on them if they want to re-open the discussion and work on them*
What the bot currently produces:
What I want it to look like:
Notice that there isn't an unnecessary line break after the link to the issues page. That'll make the text look a bit better when screens are resized.
To learn how switching from `|` to `>` in the configuration achieves that, see …
=> [ci] prevent lock-threads from locking issues with label 'feature request'

python-package/lightgbm/basic.py, python-package/lightgbm/plotting.py, python-package/pyproject.toml, tests/distributed/_test_distributed.py, tests/python_package_test/test_engine.py, tests/python_package_test/utils.py
Proposes adding a few more linting rules for Python code in this project, to further standardize how the code looks.
* `flake8-print`: encourages the use of the configured logger over `print()` and `pprint()`
* `flake8-return` (just one of the checks): avoid unnecessary assignment immediately before a `return()`
* `flake8-simplify` (just one of the checks): use `dict.get(key. default)` instead of an `if-else` loop
This PR adds those checks to the project's linting config, and modifies the project's code to address these specific warnings:
```text
python-package/lightgbm/basic.py:129:9: T201 `print` found
python-package/lightgbm/basic.py:474:16: RET504 [*] Unnecessary assignment to `aliases` before `return` statement
python-package/lightgbm/basic.py:3213:16: RET504 [*] Unnecessary …
```
=> [ci] [python-package] add more linting checks

build-python.sh, python-package/README.rst
Fixes #5979.
Makes it possible to build wheels with `build-python.sh` in environments without internet access.
That's relevant to repackaging like the creation of FreeBSD ports described in #5979.
On my Mac laptop...
... installed build dependencies
```shell
pip install \
build \
scikit-build-core \
wheel
```
... turned off wifi and build a wheel
```shell
sh ./build-python.sh \
--no-isolation \
bdist_wheel
```
=> [python-package] make it possible to build wheels without internet connection (fixes #5979)

.ci/test-python-oldest.sh, python-package/lightgbm/callback.py, python-package/lightgbm/engine.py, python-package/pyproject.toml
Contributes #3756.
Proposes converting `CallbackEnv` in the Python package to a dataclass.
Also proposes removing uses of `import collections` in favor of importing only exactly what LightGBM needs from that module.
Restating the benefits I mentioned when I last tried this in #5765, `dataclasses` are preferable to `namedtuple` in the following ways:
* easier to set type annotations + default values than named tuples
- makes it easier for both human developers and and tools like `mypy` to understand the expected types of properties
* possible to attach other methods or computed properties with `@property` (just like normal classes)
I realized today that "use `dataclassses`" and "drop Python 3.6 support" don't have to be coupled... I was wrong to suggest that coupling …
=> [python-package] use dataclass for CallbackEnv

python-package/lightgbm/engine.py
Proposes removing `CVBooster._append()`. That method was a one-line wrapper around just appending directly to `CVBooster.boosters`... I don't think the additional indirection is worth it.
This PR proposes removing that method to make the `cv()` code a bit easier to understand.
=> [python-package] remove CVBooster._append()

docs/GPU-Windows.rst, docs/Parallel-Learning-Guide.rst
Fixes broken links in the project's documentation, detected by the `link-checks` CI job: https://github.com/microsoft/LightGBM/actions/runs/5948642832/job/16132829498.
```text
URL        `https://www.rpmfind.net/linux/fedora/linux/releases/36/Everything/x86_64/os/Packages/m/mingw64-boost-static-1.75.0-6.fc36.noarch.rpm'
Name       `Prebuilt Boost x86_64'
Parent URL file:///home/runner/work/LightGBM/LightGBM/docs/_build/html/GPU-Windows.html, line 180, col 14
Real URL   https://www.rpmfind.net/linux/fedora/linux/releases/36/Everything/x86_64/os/Packages/m/mingw64-boost-static-1.75.0-6.fc36.noarch.rpm
URL        `https://www.rpmfind.net/linux/fedora/linux/releases/36/Everything/x86_64/os/Packages/m/mingw32-boost-static-1.75.0-6.fc36.noarch.rpm'
Name …
```
=> [docs] fix broken links

R-package/tests/testthat/test_basic.R, src/c_api.cpp, src/io/dataset.cpp
Running a minimal example of cross-validation in the Python package (https://github.com/microsoft/LightGBM/issues/6072#issuecomment-1703993820), I noticed some warning-level log messages that I believe should only be printed when users request more verbose logging.
```text
[LightGBM] [Warning] Using self-defined objective function
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.006622 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25500
[LightGBM] [Info] Number of data points in the train set: 6666, number of used features: 100
[LightGBM] [Warning] Using self-defined objective function
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005703 seconds.
You can …
```
=> reduce verbosity of some log messages

.ci/test_r_package.sh, .github/workflows/r_package.yml
Tests the R package against R 4.3.1 (the latest release of R) on Linux and macOS.
I'm working on supporting Windows in #6074 and #6061.
=> [ci] [R-package] test against R 4.3 on Linux and macOS

python-package/lightgbm/basic.py, python-package/lightgbm/plotting.py, tests/python_package_test/test_basic.py
The Python package has an internal utility function, `_data_from_pandas()`, which takes in `pandas` DataFrames and extracts from them:
* the raw data in `numpy` format
* list of feature names
* list of categorical feature names
* mappings from raw values to integer encodings for categorical columns
That function is quite complicated (in my opinion), and some logic hidden in there doesn't actually relate to `pandas` Dataframes.
This PR proposes the following to simplify the Python package's code:
* only calling `_data_from_pandas` on `pandas` DataFrames
* adding return type hints to that function
* resolving some duplication in the function's code
* removing internal code paths where `feature_name` and `categorical_feature` could be set to `None` …
=> [python-package] simplify processing of pandas data

docs/.linkcheckerrc
Since #5929 was merged, the link checks job has been failing with the following error:
> URL        https://dl.acm.org/doi/10.1145/3298689.3347033'
Name       PAL: a position-bias aware learning framework for CTR prediction in live recommender systems'
Parent URL file:///home/runner/work/LightGBM/LightGBM/docs/_build/html/Advanced-Topics.html, line 207, col 362
Real URL   https://dl.acm.org/doi/10.1145/3298689.3347033
Check time 0.407 seconds
Result     Error: 403 Forbidden
([build link](https://github.com/microsoft/LightGBM/actions/runs/6107046649/job/16573278047))
I checked, and it seems that page is behind cloudflare.
```shell
curl -I https://dl.acm.org/doi/10.1145/3298689.3347033
```
```text
HTTP/2 403
date: Thu, 07 Sep 2023 19:22:02 GMT
content-type: text/html; charset=UTF-8 …
```
=> [ci] [docs] fix broken ACM links

README.md
`vaex` is a popular Python DataFrame library, offering the ability to work with larger-than-memory datasets on disk (similar to Dask DataFrame or sqlite).
Noticed based on @ddelange's commits referencing #5196 that `vaex` ships an integration to LightGBM, as part of a package called `vaex-ml`.
https://github.com/vaexio/vaex/blob/15245cf4332d4423ac58bd737aee27d911a1b252/packages/vaex-ml/vaex/ml/lightgbm.py#L21
This proposes adding that project to the list of external repositories in the documentation here.
cc @JovanVeljanoski , the original author of this from https://github.com/vaexio/vaex/pull/254
=> [docs] add vaex-ml to list of external repositories

python-package/lightgbm/basic.py, python-package/lightgbm/callback.py, python-package/lightgbm/engine.py
Resolves the following errors from `mypy`:
```text
engine.py:533: error: List comprehension has incompatible type List[Tuple[str, str, floating[Any], bool, floating[Any]]]; expected List[Tuple[str, str, float, bool, float]]  [misc]
engine.py:773: error: Argument "evaluation_result_list" to "CallbackEnv" has incompatible type "List[Tuple[str, str, float, bool, float]]"; expected "Optional[List[Tuple[str, str, float, bool]]]"  [arg-type]
```
These both came from an incorrect type hint on `lightgbm.callback.CallbackEnv.evaluation_result_list`, which failed to include the possibility of eval result tuples that included a 5th element for the across-folds standard …
=> [python-package] fix mypy errors related to eval result tuples

python-package/lightgbm/__init__.py, python-package/lightgbm/callback.py, tests/python_package_test/test_engine.py
Doing some research for another contribution, I found that several large projects rely on importing `lightgbm.callback.EarlyStopException`, and using it to trigger early stopping in LightGBM.
* `autogluon`: https://github.com/autogluon/autogluon/blob/f77a7b4ea2f6140685e73ef41f3b533cea272391/tabular/src/autogluon/tabular/models/lgb/callbacks.py#L8
* `FLAML`: https://github.com/microsoft/FLAML/blob/4886cb56891af6ccf3e6d694bd97f571623fa6f8/flaml/automl/model.py#L1430
This PR proposes formally marking that class (and by extension, that mechanism of triggering early stopping) as a part of the public API, to prevent it from being removed or altered in a non-backward-compatible way in the future.
=> [python-package] mark EarlyStopException as part of public API

python-package/lightgbm/callback.py
Resolves the following errors from `mypy`:
```text
python-package/lightgbm/callback.py:128: error: Item "None" of "Optional[List[Tuple[str, str, float, bool]]]" has no attribute "__iter__" (not iterable)  [union-attr]
python-package/lightgbm/callback.py:143: error: Item "None" of "Optional[List[Tuple[str, str, float, bool]]]" has no attribute "__iter__" (not iterable)  [union-attr]
python-package/lightgbm/callback.py:283: error: Argument 1 to "len" has incompatible type "Optional[List[Tuple[str, str, float, bool]]]"; expected "Sized"  [arg-type]
python-package/lightgbm/callback.py:285: error: Value of type "Optional[List[Tuple[str, str, float, bool]]]" is not indexable  [index]
python-package/lightgbm/callback.py:286: error: Value of type …
```
=> [python-package] fix mypy errors related to eval result parsing in callbacks

python-package/lightgbm/basic.py
Resolves the following error from mypy:
```text
basic.py:1862: error: Incompatible types in assignment (expression has type "List[List[Any]]", variable has type "None")  [assignment]
```
=> [python-package] fix mypy error from Dataset.pandas_categorical

python-package/lightgbm/callback.py
Resolves the following error from mypy:
```text
callback.py:167: error: Tuple index out of range  [misc]
```
That's raised in code that works with eval result tuples, which can be either 4 or 5 elements. Per the discussion in https://github.com/python/mypy/issues/1178, `mypy` can't use branches like `if len(tup)` to figure out which element of a union type it must be working with.
=> [python-package] fix mypy error about eval result tuples

.ci/test_r_package_windows.ps1
Fixes #5640.
Adds checks to the Windows R-package CI jobs to ensure that we're alerted if the jobs accidentally start relying on an unexpected version of R, e.g. the version installed by GitHub Actions in its images.
Started by intentionally breaking this, to be sure it will loudly break builds.
> Wrong R version was found (expected '3.6.3'). Check the build logs.
([build link](https://github.com/microsoft/LightGBM/actions/runs/6231183789/job/16912352494?pr=6107))
Then pushed changes to fix it, and saw them succeed.
([build link](https://github.com/microsoft/LightGBM/actions/runs/6243354759/job/16948642319?pr=6107))
=> [ci] ensure correct R version is used on GitHub Actions (fixes #5640)

python-package/lightgbm/basic.py
Fixes the following errors from `mypy`
```text
basic.py:1922: error: Argument 1 to "__init_from_list_np2d" of "Dataset" has incompatible type "list[Any] | list[Sequence] | list[ndarray[Any, Any]]"; expected "list[ndarray[Any, Any]]"  [arg-type]
basic.py:1924: error: Argument 1 to "__init_from_seqs" of "Dataset" has incompatible type "list[Any] | list[Sequence] | list[ndarray[Any, Any]]"; expected "list[Sequence]"  [arg-type]
basic.py:2874: error: Argument 1 to "_yield_row_from_seqlist" of "Dataset" has incompatible type "list[Any] | list[Sequence] | list[ndarray[Any, Any]]"; expected "list[Sequence]"  [arg-type]
```
These errors all come from the fact that …
=> [python-package] fix mypy errors in Dataset construction

python-package/lightgbm/basic.py
A few places in the Python package use a pattern like the following:
```python
ctypes.c_char_p(*[ctypes.addressof(string_buffer)])
```
That's identical to the following ...
```python
ctypes.c_char_p(ctypes.addressof(string_buffer))
```
... except that it involves allocating, unpacking, and then immediately freeing a list object.
This PR proposes removing those unnecessary allocations, to make those code paths slightly faster and reduce their memory usage a tiny bit.
Docs on `ctypes.c_char_p()` accepting a memory address as an int: https://docs.python.org/3/library/ctypes.html#ctypes.c_char_p
=> [python-package] remove unnecessary allocations in ctypes code

build-cran-package.sh
`build-cran-package.sh` is used to prepare a CRAN-style source distribution of this project's R package.
It's intentionally an `sh` and not `bash` script, to attempt to be as portable as possible.
I noticed tonight that that script is currently using one `bash` feature that isn't supported in at least some implementations of `sh`... `[[` for an `if` condition.
See https://github.com/microsoft/LightGBM/actions/runs/6301758829/job/17107497663#step:7:7057.
> build-cran-package.sh: 135: [[: not found
Or run the following from the root of this repo to reproduce it.
```shell
docker run \
--rm \
-v $(pwd):/opt/LightGBM \
-w /opt/LightGBM \
-it ghcr.io/r-hub/containers/ubuntu-clang:latest \
```
This PR fixes that.
=> [ci] fix sh-compatibility issue in build-cran-package.sh

python-package/lightgbm/basic.py
Private method `Dataset._compare_for_warning()` is used to avoid raising unnecessary warnings when creating a `Dataset` from another `Dataset`.
It's only used in one place:
https://github.com/microsoft/LightGBM/blob/63a882b7400a19485727cc808e4715897e63635a/python-package/lightgbm/basic.py#L2251-L2257
And that place only passes in results from `Dataset.get_params()`.
`Dataset.get_params()` allways returns a dictionary (never `None`)...
https://github.com/microsoft/LightGBM/blob/63a882b7400a19485727cc808e4715897e63635a/python-package/lightgbm/basic.py#L1777
... so code paths in `Dataset._compare_for_warning()` to handle `None` are unnecessary.
This PR proposes removing them.
I found this by checking the statement coverage of the Python package's unit tests, like this: …
=> [python-package] simplify Dataset._compare_params_for_warning()

tests/cpp_tests/test_byte_buffer.cpp, tests/cpp_tests/testutils.cpp
The C++ tests currently raise the following compiler warnings with `clang` 11:
```text
tests/cpp_tests/test_byte_buffer.cpp:33:21: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
for (int i = 0; i < sizeof(int16_t); i++) {
~ ^ ~~~~~~~~~~~~~~~
tests/cpp_tests/test_byte_buffer.cpp:44:21: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
for (int i = 0; i < sizeof(int64_t); i++) {
~ ^ ~~~~~~~~~~~~~~~
tests/cpp_tests/test_byte_buffer.cpp:55:21: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
for (int i = 0; i < sizeof(double); i++) {
tests/cpp_tests/testutils.cpp:268:25: warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call] …
```
=> fix compiler warnings for CPP tests

src/boosting/gbdt.h, tests/python_package_test/test_engine.py
Issues a warning when a parameter type is not found when loading a booster from a model file instead of raising an error.
Fixes #6082
=> ignore unknown parameters when loading from model file

include/LightGBM/bin.h
Contributes to #4705.
`Int32HistogramSumReducer` and `Int16HistogramSumReducer` allocate an `int` and assign to it the value of `OMP_NUM_THREADS()`,  then only use that value immediately after, for one OpenMP for loop.
This PR proposes just directly passing `OMP_NUM_THREADS()` to the configuration for those OpenMP `for` loop pragmas, to avoid the unnecessary allocation.
This also resolves the following compiler warnings that show up on `clang` when OpenMP support is disabled:
```text
LightGBM/include/LightGBM/bin.h:66:13: warning: unused variable 'num_threads' [-Wunused-variable]
const int num_threads = OMP_NUM_THREADS();
^
LightGBM/include/LightGBM/bin.h:77:13: warning: unused variable 'num_threads' [-Wunused-variable]
const int num_threads = OMP_NUM_THREADS();
^
2 warnings generated. …
```
=> remove unnecessary allocations in HistogramSumReducer

src/objective/rank_objective.hpp, src/treelearner/gpu_tree_learner.cpp, src/treelearner/linear_tree_learner.cpp
Contributes to #4705.
Contributes to #5987.
LightGBM uses OpenMP for to parallelize many operations via multi-threading.
It's C/C++ codebase uses some wrapper functions defined in a header file `openmp_wrapper.h` to get and set the number of threads to use in such operations:
https://github.com/microsoft/LightGBM/blob/f901f47141700f01294c6766bd93bcc57ddb1960/include/LightGBM/utils/openmp_wrapper.h#L20-L35
There are a few places in the code which bypass those helpers and instead directly call `omp_get_num_threads()` and `omp_get_max_threads()`.
This PR proposes switching such calls to instead use LightGBM's wrappers. That reduces the number of different code paths that multi-threading configuration goes through, therefore reducing the risk of configuration inconsistencies and issues like …
=> factor out uses of omp_get_num_threads() and omp_get_max_threads() outside of OpenMP wrapper

.ci/test.sh, .github/workflows/python_package.yml
In #6034, the Python package `bdist` build on macOS times out after an hour as the environment for testing cannot be solved in time. This is the result from using conda with its slow solver. Replacing `conda` with `mamba` causes the same CI job to complete successfully in under 20 minutes.
This PR allows to optionally use `mamba` rather than `conda` to allow certain CI jobs to take advantage of `mamba`'s faster solver. The optional usage alleviates the need to build new docker images for the CI for the time being.
=> [ci] use `mamba` instead of `conda` in macOS and Linux CI jobs

tests/python_package_test/test_engine.py
Resolves the following warning raised by `pytest` in the project's Python unit tests.
```text
/Users/runner/work/LightGBM/LightGBM/tests/python_package_test/test_engine.py:856: DeprecationWarning: invalid escape sequence \(
with pytest.raises(lgb.basic.LightGBMError, match="Positions size \(3006\) doesn't match data size"):
```
Also removes some trailing whitespace in those same tests.
That warning could be seen in, for example, the macOS `regular` CI job on GitHub Actions ([example build on master](https://github.com/microsoft/LightGBM/actions/runs/6642162989/job/18046276947)).
=> [ci] resolve warning in tests

.ci/test-python-oldest.sh, .ci/test.sh, .ci/test_windows.ps1, include/LightGBM/arrow.h, include/LightGBM/arrow.tpp, include/LightGBM/c_api.h, include/LightGBM/dataset.h, python-package/lightgbm/basic.py, python-package/lightgbm/compat.py, python-package/pyproject.toml, src/c_api.cpp, tests/cpp_tests/test_arrow.cpp, tests/python_package_test/test_arrow.py
This is the first of a set of replacement PRs to simplify https://github.com/microsoft/LightGBM/pull/6022.
- Allow to Arrow table to `lgb.Dataset.data`
- Add tests for Arrow C++ implementation and Python binding
=> [python-package] Allow to pass Arrow table as training data

.ci/lint_r_code.R, R-package/R/callback.R, R-package/tests/testthat/test_basic.R
This PR modifies the callbacks that print information such as evaluation metrics to use `cat()` instead of `print()`.
When using print on a `character`, since there is no "scalar" version of such class, R adds information about which element of the input vector is each - meaning: if there's only one element, it will always add `[1] ...` as part of the printed output. This is undesirable when looking at messages like evaluation metrics.
=> [R-package] Use `cat()` instead of `print()` for metrics and callbacks

.gitignore
This fixes an unintended behavior in this project's `git` configuration.
The `.gitignore` rule intended to block inclusion of the LightGBM CLI (a binary file named `lightgbm`) also prevents including of any new files in `include/LightGBM`:
```shell
touch include/LightGBM/something.h
git add include/LightGBM/something.h
```
```text
The following paths are ignored by one of your .gitignore files:
include/LightGBM
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"
```
@borchero ran into this here: https://github.com/microsoft/LightGBM/pull/6034#discussion_r1299487404
This PR fixes that by adding a leading `/` to that rule. References explaining why that works:
* https://stackoverflow.com/a/6168768/3986677
* …
=> allow new files in include/LightGBM

R-package/R/lgb.Booster.R
A new version of `{lintr}` was released today ([CRAN link](https://cran.r-project.org/web/packages/lintr/)) and it caught an unreachable line of code in the R package!
> R-package/R/lgb.Booster.R:1465:5: warning: [unreachable_code] Code and comments coming after a return() or stop() should be removed.
>    stop("lgb.get.eval.result: wrong eval name")
This PR fixes that.
Not sure exactly which `{lintr}` change resulted in this being caught, but I think it's https://github.com/r-lib/lintr/pull/2129. Thanks @MEO265 and @MichaelChirico!
=> [R-package] remove unreachable code

python-package/lightgbm/basic.py
A few places in the Python package pre-allocate C char arrays with `ctypes.create_string_buffer()`, then pass a C array of pointers to those buffers through LightGBM's C API.
`mypy` is not happy about the way that's done:
```text
python-package/lightgbm/basic.py:2951: error: Array constructor argument 1 of type "map[int]" is not convertible to the array element type "Iterable[c_char_p]"  [misc]
python-package/lightgbm/basic.py:2965: error: Array constructor argument 1 of type "map[int]" is not convertible to the array element type "Iterable[c_char_p]"  [misc]
python-package/lightgbm/basic.py:4631: error: Array constructor argument 1 of type "map[int]" is not convertible to the array element type "Iterable[c_char_p]"  [misc]
python-package/lightgbm/basic.py:4645: …
```
=> [python-package] ignore mypy errors related to ctypes string buffers

R-package/src/lightgbm_R.cpp
Some functions retrieve data pointers from R objects in a loop. This PR fixes this inefficiency by retrieving them only once before the loop.
=> [R-package] Fix inefficiency in retrieving pointers

python-package/lightgbm/libpath.py
This is to fix a mistake in libpath.py, which causes a wrong candidate library path, as shown by the first one below:
```bash
$ python python-package/lightgbm/libpath.py
/home/shiyu/Test-LightGBM/cuda-obj/LightGBM/python-package/lightgbm/libpath.py/lib_lightgbm.so
/home/shiyu/Test-LightGBM/cuda-obj/LightGBM/python-package/lib_lightgbm.so
/home/shiyu/Test-LightGBM/cuda-obj/LightGBM/python-package/lightgbm/bin/lib_lightgbm.so
/home/shiyu/Test-LightGBM/cuda-obj/LightGBM/python-package/lightgbm/lib/lib_lightgbm.so
```
With this fix, it becomes
```bash
/home/shiyu/Test-LightGBM/cuda-obj/LightGBM/python-package/lightgbm/lib_lightgbm.so
/home/shiyu/Test-LightGBM/cuda-obj/LightGBM/python-package/lib_lightgbm.so
/home/shiyu/Test-LightGBM/cuda-obj/LightGBM/python-package/lightgbm/bin/lib_lightgbm.so …
```
=> [python-package] fix libpath.py

R-package/src/lightgbm_R.cpp
Fixes #6212.
Resolves warning `-Wformat-security` raised with R-devel as of a few days ago and `clang-15`:
> lightgbm_R.cpp:159:3: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
See https://github.com/microsoft/LightGBM/issues/6212#issuecomment-1829182030 for more details informing the changes in this PR.
CRAN has in the past not allowed compiler flags or pragmas in code that suppress warnings.
* https://github.com/microsoft/LightGBM/blob/2ee3ec84b70df1a9e249d3b3bff9458fe3726cd4/build-cran-package.sh#L140-L143
* #3433
I couldn't find that stated explicitly in the CRAN policy (https://cran.r-project.org/web/packages/policies.html) or Writing R Extensions (https://cran.r-project.org/doc/manuals/R-exts.html), although there are some valid things …
=> [R-package] use safer pattern for error formatting (fixes #6212)

README.md, docs/FAQ.rst, docs/Parameters.rst
The content inside https://sites.google.com/view/lauraepp/parameters is no longer available.
Previous conversation about this: https://github.com/microsoft/LightGBM/issues/5385#issuecomment-1192774898
This PR proposes removing links to that now-inactive site.
=> [docs] remove links to Laurae++ site

include/LightGBM/arrow.tpp, tests/cpp_tests/test_arrow.cpp, tests/python_package_test/test_arrow.py
I realized that we didn't add a test for Arrow data with NULLs. Turns out, the condition to identify NULLs was faulty (which wasn't apparent before since no nullability bitmask is created if no element is NULL).
Unfortunately, the existing C++ test (where we built the Arrow array manually) was also faulty which didn't catch the issue in the first place...
=> Fix null handling for Arrow data

R-package/DESCRIPTION
Contributes to #5987.
Contributes to #6221.
Will help with the v4.2.0 release (#6191).
Proposes changing the maintainer ("cre") for the R package from @shiyu1994 to me.
I'd asked about this a few times, most recently in https://github.com/microsoft/LightGBM/issues/6221#issuecomment-1835597885, but we've never really discussed it. I'm opening this PR as a place to have that discussion.
This would mean that the following feedback from CRAN all go to my personal email, instead of @shiyu1994 's work email:
* automated feedback on submissions (like failed CRAN checks, e.g. #5502, #5661, #6221)
* warnings about pending deprecations (like the patches CRAN applied in the R 3-to-4 transition)
* issues that require our attention to keep the package on CRAN (like failing reverse dependency checks)
* …
=> [R-package] change CRAN maintainer

python-package/lightgbm/basic.py, tests/python_package_test/test_basic.py
Takes a shallow copy of the dataframe in the `_data_from_pandas` function to avoid modifying it when converting categorical features to their codes. This used to always be done (implicitly) for predict until #6066, since the function is called with `feature_name='auto'` and the `copy` argument of `pandas.DataFrame.rename` is passed as the `deep` argument to `pandas.DataFrame.copy`, however that behavior wasn't obvious.
Fixes #6195.
Also updates the test that verifies the original dataframe isn't modified to now consider the case of unseen categories, which fails in the current master and should prevent #6195 from happening again.
=> [python-package] take shallow copy of dataframe in predict (fixes #6195)

include/LightGBM/arrow.h
Fixes #6230
Add stdexcept header file to fix `error C2039: 'invalid_argument': is not a member of 'std'` under option /permissive-.
=> fix errors from MSVC '/permissive-' mode (fixes #6230)

CMakeLists.txt
From https://github.com/microsoft/LightGBM/pull/6232#issuecomment-1853234696.
Add option `/permissive-` for MSVC conformance check.
=> Add msvc conformance check

.ci/test_r_package_valgrind.sh
Contributes to the `v4.2.0` release (#6191).
The latest `valgrind` build showed 1,056 bytes "possibly lost", all from code paths that create threads w/ `pthread_create`. (https://github.com/microsoft/LightGBM/pull/6191#issuecomment-1846240329)
In the past, CRAN has allowed some of these as false positives. (https://github.com/microsoft/LightGBM/pull/6191#issuecomment-1846502740)
This PR proposes modifying the test script for that job to acknowledge that this set of findings from `valgrind` are allowed.
It would be better to suppress *specific* cases instead of do text-parsing to enforce a maximum number of "possibly lost" reported bytes... but that will take a bit more time to develop. I've documented it in #6231 and put `good first issue` on it to try to increase the likelihood that …
=> [ci] [R-package] allow more possibly-lost warnings from valgrind

.github/CODEOWNERS, docs/FAQ.rst
Adds LightGBM's newest maintainer, @borchero , to CODEOWNERs.
Removes some unnecessary and out-of-date information from https://lightgbm.readthedocs.io/en/latest/FAQ.html.
=> [ci] [docs] add Oliver to CODEOWNERS

.github/workflows/lock.yml
Proposes a few changes to the GitHub Actions workflow we use to close issues and labels:
* changes time-til-locking from 90 to 365 days after issues/PRs are closed
* removes extra double quotes (originally added in #6047)
* updates to `v5` of `dessant/lock-threads`
@dessant, the author of `lock-threads`, tagged me to tell me that extra double quotes are no longer necessary: https://github.com/dessant/lock-threads/issues/40#issuecomment-1835711406.
I've found that locking a PR / issue prevents GitHub from generating these annotations showing that the PR / issue was mentioned somewhere else.
I've found those annotations really useful, for example to discover problems in other projects that were caused by changes here.
I'd like to extend the time-til-locking so that we can see more of those …
=> [ci] update issue-locking workflow

python-package/lightgbm/basic.py
Fixes the following error from `mypy`:
```text
python-package/lightgbm/basic.py:824: error:
Incompatible return value type (got "tuple[ndarray[Any, Any], list[str], list[str] | list[int], list[list[Any]]]", expected "tuple[ndarray[Any, Any], list[str], list[str], list[list[Any]]]")  [return-value]
```
=> [python-package] fix mypy error about pandas categorical features

CMakeLists.txt
As described in #5972, the use of `COMMAND cp` in this project's `CMake` code leads to errors when the project is built in environments where `cp` is not available (for example, the Windows `CMD` shell by default).
This proposes replacing all of those uses with `COMMAND cmake -e copy_if_different`, so that `cp` isn't strictly required to build LightGBM.
=> [cmake] [swig] use CMake's built-in file-copying mechanisms instead of 'cp'

.ci/test_r_package.sh, .ci/test_r_package_windows.ps1, .github/workflows/r_package.yml, .github/workflows/static_analysis.yml, .vsts-ci.yml, R-package/DESCRIPTION, R-package/README.md, R-package/vignettes/basic_walkthrough.Rmd, docs/env.yml
Related to #1944.
Proposes switching from `{rmarkdown}` to `{markdown}` for the R package's vignettes.
Reduces the set of dependencies that have to build successfully to run `R CMD check --as-cran` against `{lightgbm}`, leading to:
* faster CI builds
* lower risk of CI failures
* lower risk of failed builds and disruptions on CRAN
* slightly reduced reverse-dependency burden for CRAN and maintainers of `{rmarkdown}`
<details><summary>this change results in 14 fewer packages needing to be installed in CI</summary>
R code I used (with R 4.2.3) to calculate that:
```r
CRAN_DB <- tools::CRAN_package_db()
.get_strong_deps <- function(packages) {
ret <- tools::package_dependencies(
packages = packages
, db = CRAN_DB
, which = c("Depends", "Imports", "LinkingTo")
, recursive = TRUE
)
ret_vec <- …
```
=> [R-package] [ci] switch vignettes from 'rmarkdown' to 'markdown'

CMakeLists.txt, docs/GPU-Windows.rst, docs/Installation-Guide.rst, python-package/pyproject.toml
Fixes #5642.
Might help with the following:
* #5775
* #5785
* #5955
* #6249
* #6252
Proposes the following:
* moving this project's minimum `CMake` version up to `v3.18`
* removing `CMake` version ranges from docs
This should reduce the risk of build failures with newer compilers, operating systems, architectures.
I'm especially hoping it'll help with M1/M2/M3 macOS support and supporting newer versions of CUDA.
Per the `CMake` docs ([link](https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html#policy-settings)):
> *The `cmake_minimum_required(VERSION)` command implicitly invokes the [`cmake_policy(VERSION)`](https://cmake.org/cmake/help/latest/command/cmake_policy.html#version) command to specify that the current project code is written for the given range of CMake …
=> [cmake] [c++] require CMake 3.18+

CMakeLists.txt
LightGBM's CMake is not properly filtering the list of sources based on `USE_CUDA`.  This commit fixes the CMake.
This pull request fixes #6267
=> [cmake] [CUDA] ignore CUDA-specific source files in non-CUDA builds (fixes #6267)

.ci/test.sh
Fixes #6282
We install a package `dask-core` but then in CI later uninstall one called `dask`. That might not have been caught before because `dask` was being pulled in as a transitive dependency of something else (unsure).
Anyway, now that it isn't, `conda uninstall dask` fails with the error shown in the linked issue.
This resolves it by explicitly uninstalling `dask-core`.
=> [ci] fix conda env creation in 'regular' CI job (fixes #6282)

.ci/install-clang-devel.sh
Fixes #6306
These modifications are based on the "Debian" section at https://apt.llvm.org/.
=> [ci] fix installation of clang-18 (fixes #6306)

.ci/append_comment.sh, .ci/check_python_dists.sh, .ci/install-clang-devel.sh, .ci/install_opencl.ps1, .ci/lint-cpp.sh, .ci/lint-python.sh, .ci/rerun_workflow.sh, .ci/set_commit_status.sh, .ci/setup.sh, .ci/test-python-oldest.sh, .ci/test.sh, .ci/test_r_package.sh, .ci/test_r_package_valgrind.sh, .ci/test_windows.ps1, .ci/trigger_dispatch_run.sh, .github/workflows/cuda.yml, .github/workflows/linkchecker.yml, .github/workflows/optional_checks.yml, .github/workflows/python_package.yml, .github/workflows/r_configure.yml, .github/workflows/r_package.yml, .github/workflows/static_analysis.yml, .vsts-ci.yml, R-package/recreate-configure.sh, build-cran-package.sh, build-python.sh, docs/build-docs.sh, docs/conf.py
This PR proposes replacing uses of `exit -1` in shell scripts with `exit 1`.
Removes reliance on shells correctly handling `exit -1` (which is technically not recommended by e.g. `bash`) in the project's scripts.
From the `bash` docs ([link](https://www.gnu.org/software/bash/manual/html_node/Exit-Status.html))
> *Exit statuses fall between 0 and 255*
And from the `shellcheck` docs ([SC2242](https://www.shellcheck.net/wiki/SC2242)) 
> Note in particular that exit -1 is equivalent to exit 255, but that exit 1 is the more canonical way of expressing the first possible error code.
This change resolves the following error from `shellcheck`:
```text
SC2242 (error): Can only exit with status 0-255. Other data should be written to stdout/stderr.
```
=> [ci] ensure shell script exit codes are in range 0-255

.github/workflows/no-response.yml
Contributes to #6313
I think we'll have to merge this PR to test, since `workflow_dispatch` (the thing that lets you click a button and run it from an arbitrary branch) isn't set up for this workflow.
In this PR, I'm also proposing adding a `workflow_dispatch` trigger, so we can do that type of testing in the future if needed.
Looks like the lock-bot config already uses this:
https://github.com/microsoft/LightGBM/blob/6330d6269c81dfd4c96e664b99239b8ff39ccf91/.github/workflows/lock.yml#L10-L12
And it shouldn't affect triggering-comments stuff like the `valgrind` checks, as those use a different secret:
https://github.com/microsoft/LightGBM/blob/6330d6269c81dfd4c96e664b99239b8ff39ccf91/.github/workflows/triggering_comments.yml#L11-L12
=> [ci] fix no-response permissions

.github/workflows/no-response.yml
I just learned that GitHub Action `lee-dohm/no-response` doesn't support `workflow_dispatch` events: https://github.com/microsoft/LightGBM/issues/6313#issuecomment-1953111798
This reverts that addition from #6323.
=> [ci] remove workflow_dispatch from no-response configuration

.ci/test.sh, python-package/lightgbm/basic.py
Fixes the following error from `mypy`:
```text
python-package/lightgbm/basic.py:2889: error: Incompatible types in assignment (expression has type "list[float] | list[int] | ndarray[Any, Any] | Any | Any | Any | Any | None", variable has type "ndarray[Any, dtype[Any]]")  [assignment]
```
For more details on how `typing.TypeGuard` helps with this, see #6106.
=> [python-package] fix mypy error about pyarrow data

python-package/lightgbm/basic.py
Not sure when this happened, but type alias `basic._ArrayLike` is no longer used anywhere in the library.
```shell
git grep _ArrayLike
```
This proposes removing it.
=> [python-package] remove unused type alias

python-package/lightgbm/__init__.py, python-package/lightgbm/basic.py, python-package/lightgbm/callback.py, python-package/lightgbm/compat.py, python-package/lightgbm/dask.py, python-package/lightgbm/engine.py, python-package/lightgbm/libpath.py, python-package/lightgbm/plotting.py, python-package/lightgbm/sklearn.py, python-package/pyproject.toml
Contributes to #6304.
Proposes enforcing `ruff-format` on all of the Python code checked into source control in this project.
This only has changes in `python-package/` because previous PRs touched other files:
* #6308
* #6317
I made a few manual changes. I've added comments on the relevant parts of the diff explaining those.
After this, I'll put up one more PR with a `.git-blame-ignore-revs` file, dropping all these large reformatting changes from the git blame.
Relevant docs:
* https://github.com/astral-sh/ruff-pre-commit
* https://docs.astral.sh/ruff/formatter/black/
=> [ci] [python-package] enable ruff-format on all Python code

src/main.cpp
The CLI's main implementation file, `src/main.cpp`, only needs `LightGBM::Linkers` methods when compiled for use with MPI (`-DUSE_MPI`).
This proposes guarding the relevant includes with `#ifdef USE_MPI`, to make compilation a little faster for non-MPI use cases.
=> [c++] remove unnecessary include in CLI

.git-blame-ignore-revs
Fixes #6304.
Adds the recent `ruff-format` commits to a `.git-blame-ignore-revs` file, so those changes that touched a LOT of lines are ignored in the `git blame`.
For details on that, see https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view
Look at the blame view on this branch: https://github.com/microsoft/LightGBM/blame/git-blame-ignore/python-package/lightgbm/basic.py.
Scrolled through there and did not see any of the formatting changes in the blame.
=> [ci] ignore ruff-format changes in git blame (fixes #6304)

.ci/test.sh, python-package/lightgbm/basic.py, python-package/lightgbm/compat.py, python-package/lightgbm/plotting.py, python-package/lightgbm/sklearn.py, python-package/pyproject.toml
Contributes to #3867
Proposes adding `--disallow-untyped-defs` to this project's `mypy` configuration. Once `mypy` is enforced here, that'll prevent new Python code without type hints from being committed to the repo.
Adding this identified several places that are still missing type hints, so this PR also fixes those.
<details><summary>errors (click me)</summary>
```text
python-package/lightgbm/compat.py:22: error: Function is missing a type annotation  [no-untyped-def]
python-package/lightgbm/compat.py:28: error: Function is missing a type annotation  [no-untyped-def]
python-package/lightgbm/compat.py:34: error: Function is missing a type annotation  [no-untyped-def]
python-package/lightgbm/compat.py:46: error: Function is missing a type annotation  [no-untyped-def] …
```
=> [ci] [python-package] check for untyped definitions with mypy

.ci/setup.sh, .ci/test.sh, .ci/test_r_package.sh, .ci/test_r_package_windows.ps1, .github/workflows/r_package.yml, python-package/lightgbm/compat.py, tests/python_package_test/test_dask.py
Fixes multiple CI-blocking issues that have all come up in the last few days:
* RStudio no longer hosting R 3.6 (https://github.com/microsoft/LightGBM/pull/6353#issuecomment-1983746071)
* `dask.dataframe` now requiring `dask-expr` (#6365)
* basictex / mactex being updated and mirrors now longer hosting the old version: #6366
* installation of `clang-18` failing in the `r-debian-clang-devel` CI jobs (#6369)
* `r-sanitizers` jobs failing with install-time segfaults (#6367)
=> [ci] Fix R 3.6 tests, dask tests, compatibility with dask>=2024.3.1

.ci/test.sh
Python 3.7 CI jobs are failing with this error:
```text
../../../.local/lib/python3.7/site-packages/lightgbm/compat.py:62: in <module>
import graphviz  # noqa: F401
../../../miniforge/envs/test-env/lib/python3.7/site-packages/graphviz/__init__.py:31: in <module>
from .backend import (DOT_BINARY, UNFLATTEN_BINARY,
../../../miniforge/envs/test-env/lib/python3.7/site-packages/graphviz/backend/__init__.py:5: in <module>
from .mixins import Render, Pipe, Unflatten, View
../../../miniforge/envs/test-env/lib/python3.7/site-packages/graphviz/backend/mixins.py:8: in <module>
from . import piping
../../../miniforge/envs/test-env/lib/python3.7/site-packages/graphviz/backend/piping.py:5: in <module>
from .. import _tools
E     File "/Users/runner/miniforge/envs/test-env/lib/python3.7/site-packages/gra …
```
=> [ci] put ceiling on graphviz in Python 3.7 jobs

docs/Installation-Guide.rst, docs/_static/js/script.js, python-package/README.rst
Fixes #6340.
Removes language in the docs about the CUDA version being considered "experimental".
Also fixes some links in docs to point to the correct section of the installation guide.
=> [docs] remove language about CUDA version being experimental (fixes #6340)

.clang-format, include/LightGBM/arrow.h, include/LightGBM/arrow.tpp, python-package/lightgbm/basic.py, python-package/lightgbm/compat.py, tests/cpp_tests/test_arrow.cpp, tests/python_package_test/test_arrow.py
Currently, LightGBM's interface only supports integer and floating point types in the columns of Arrow tables. As a result, columns that are represented as booleans in Arrow cannot be passed to LightGBM without converting them to `uint8` and increasing the column's memory consumption eightfold (as Arrow bit-packs booleans).
The pandas interface already supports passing boolean columns to LightGBM although -- due to the way pandas handles null values -- these columns must be non-nullable. Hence, there is no reason not to include support for boolean columns in Arrow.
- Extend the C++ Arrow implementation to handle boolean Arrow arrays with bit-packaged values (this requires template specialization...)
- Re-write the C++ Arrow tests to more closely align with the [Arrow producer …
=> [python-package] Allow to pass Arrow table with boolean columns to dataset

.ci/test.sh, docs/env.yml
Proposes updating the following dependencies to their latest versions:
* libraries (and Python and R versions) used to create the docs hosted at https://lightgbm.readthedocs.io/en/latest/
* static analyzers like `cpplint` and `mypy`
* faster conda environment solves = faster builds
* extends further into the future the time til we have to upgrade these language versions on readthedocs again
Even though the latest release of `sphinx` is the 7.x series, I'm proposing using `sphinx>=6.0` because LightGBM'ss docs rely on `breathe`, and as of this writing the `breathe` conda-forge package has a ceiling of `breathe<7.0`.
* https://github.com/breathe-doc/breathe/issues/943
* https://github.com/conda-forge/breathe-feedstock/blob/5d9908bf915d15abbb4fe6d768a694f53e305d72/recipe/meta.yaml#L28 …
=> [ci] [docs] update some docs and CI dependencies

.vsts-ci.yml
Azure pipeline agents are failing. See https://github.com/microsoft/LightGBM/issues/6316#issuecomment-2028535274 for the details.
=> [ci] Fix Azure Pipeline Agents

.github/workflows/r_package.yml, src/network/linkers_socket.cpp
`clang++` complains about this variable in `linkers_socket.cpp` being unused.
```text
.../src/network/linkers_socket.cpp:174:7: warning: variable 'need_connect_cnt' set but not used [-Wunused-but-set-variable]
int need_connect_cnt = 0;
```
That looks correct to me, based on the output of this:
```shell
git grep need_connect_cnt
```
Seems that that variable is being incremented but not used for anything. I suspect that's left over from some previous refactoring.
This proposes removing that unused variable.
=> [c++] remove unused variable 'need_connect_cnt'

.ci/setup.sh, .ci/test.sh, .ci/test_r_package.sh, .github/workflows/r_package.yml
Contributes to #5328.
Contributes to #5035.
There are a couple of hard-coded `x86_64` references in CI scripts. This updates those to instead be whatever `uname -m` evaluates to. Doing this in a separate PR to keep the diff smaller for
=> [ci] reduce hard-coding of host architecture

build-python.sh
The recommended workflow for building the Python package from source here uses the `build-python.sh` script, like this:
```shell
cmake -B build -S .
cmake --build build --target _lightgbm -j4
sh ./build-python.sh install --precompile
```
The version for the library from any two unreleased commits is the same (e.g. `4.3.0.99`). To ensure that `pip` does not give up on successive runs and say "oh `lightgbm==4.3.0.99` is already installed, I'm not installing this wheel", in #5907 we added `--force-reinstall` to the `pip install dist/*` in `build-python.sh`.
That has the unfortunate side-effect of also force-reinstalling *all of `lightgbm`'s strong runtime dependencies* (`numpy` and `scipy`). That's undesirable for 2 reasons:
* it's surprising to get your environment's `numpy` version …
=> [python-package] prevent build-python.sh from modifying already-installed dependencies

python-package/lightgbm/callback.py, python-package/lightgbm/engine.py, tests/python_package_test/test_callback.py, tests/python_package_test/test_engine.py
Fixes #6401
The early stopping callback was instantiated if `early_stopping_round` was found in the parameter list, even its values was <=0 (which should disable early stopping).  The code was modified to only instantiate the early stopping callback if `early_stopping_round` was both an integer and >0.  
Various error messages were updated and unit tests were added.
=> [python-package] allow use of early_stopping_round<=0 to turn off early stopping (fixes #6401)

docs/Parameters.rst, include/LightGBM/config.h, src/boosting/gbdt.cpp
Follow-up to #6393.
Clarifies that `objective=custom` must be provided via `parameters` in the C API if you want to use a custom objective function and provide gradients/hessians manually.
=> [docs] document how to use a custom objective function via the C API

src/utils/openmp_wrapper.cpp, tests/python_package_test/test_basic.py
fixes #6273
omp single clause has implicit barrier, which waits for all threads, including threads that did not execute omp single block.
Therefore, if omp single clause is used conditionally inside omp parallel, it will cause a deadlock (explanation below).
I think it is safe to remove omp single clause from `omp_get_max_threads()` (introuduced in #6226). 
- `omp_get_max_threads()` is thread-safe https://www.openmp.org/spec-html/5.1/openmpse6.html#x27-260001.6
- omp single does not affect the current team (threads participating in the execution of a parallel region) from which `omp_get_max_threads()` gets its value.
I digged into #6273.
```python
import numpy as np
import pandas as pd
X = np.random.randint(0, 5000, 10000)
X = pd.DataFrame({"x1": X})
y = …
```
=> remove unnecessary omp single that cause deadlock (fixes #6273)

.ci/test.sh, CMakeLists.txt, R-package/.Rbuildignore, R-package/README.md, R-package/src/install.libs.R, build-cran-package.sh, build-python.sh, docs/Installation-Guide.rst, python-package/lightgbm/libpath.py
Proposes the following changes to CMake-based builds of LightGBM:
* remove `APPLE_OUTPUT_DYLIB` CMake option
* always produce `lib_lightgbm.dylib` on macOS
* simplifies CMake configuration
* improves the probability of `lib_lightgbm` working correctly with tools that use string matching on file extensions to guess file format (instead of examining the [magic bytes](https://en.wikipedia.org/wiki/List_of_file_signatures)) 
- _for example, I think this makes it more likely that CMake `find_library()` calls or custom `find_*()` CMake scripts in other projects would be able to find `lib_lightgbm` on macOS_
* might help with some of the mac-specific packaging work I'm focusing on (e.g. #5328)
The shared library LightGBM currently produces on macOS is actually in mach-o format, not ELF. The …
=> [cmake] [c++] use .dylib extension unconditionally on macOS

docker/dockerfile-cli
```
$ docker build -t lightgbm-cli -f dockerfile-cli .
14.05 CMake Error at CMakeLists.txt:30 (cmake_minimum_required):
14.05   CMake 3.18 or higher is required.  You are running version 3.16.3
```
This PR upgrades CMake to the newest version.
=> upgrade CMake in dockerfile-cli (fixes #6420)

R-package/pkgdown/_pkgdown.yml
Fixes #6444.
Fixes LightGBM's documentation builds. These were failing because `{pkgdown}`, the tool used to generate the R docs site, now raises errors under the following conditions:
* objects mentioned in its config don't exist in the library
* site index is missing any objects exported by the library
Enabled readthedocs builds and saw them succeed:
* build link: https://readthedocs.org/projects/lightgbm/builds/24286998/
* docs: https://lightgbm.readthedocs.io/en/docs-pkgdown-docs/R/reference/
=> [docs] ensure pkgdown site index accurately reflects R-package public API (fixes #6444)

CMakeLists.txt, docs/Installation-Guide.rst, python-package/README.rst
Contributes to #6436. See that issue for much more discussion.
This proposes deprecating HDFS support, for the reasons described in #6436. I'd like to get this into the next release (#6439) and then fully **remove** this support in a future release of LightGBM.
Since this is a proposal to eventually break a part of the public API, I would especially like a review on this (and #6436) from either @guolinke or @shiyu1994 .
I searched for these places like this:
```shell
git grep -i hdfs
```
And tested the deprecation warning like this:
```shell
cmake -B build -S . -DUSE_HDFS=ON
```
Saw it generated correctly.
```text
CMake Deprecation Warning at CMakeLists.txt:289 (message):
HDFS support in LightGBM is deprecated, and will be removed in a future
release.  See …
```
=> deprecate HDFS support

.github/dependabot.yml
Follow-up to https://github.com/microsoft/LightGBM/pull/6438#issuecomment-2095013759. This should automate updates in the future by opening <= 1 PR per month updating all relevant actions in bulk.
=> [ci] Add dependabot configuration

R-package/R/lgb.cv.R, R-package/R/lgb.train.R, R-package/R/lightgbm.R, R-package/R/utils.R, R-package/man/lgb.cv.Rd, R-package/man/lgb.train.Rd, R-package/man/lightgbm.Rd, R-package/tests/testthat/test_basic.R, examples/python-guide/advanced_example.py, examples/python-guide/notebooks/interactive_plot_example.ipynb, examples/python-guide/plot_example.py, python-package/lightgbm/engine.py, python-package/lightgbm/sklearn.py, tests/python_package_test/test_engine.py, tests/python_package_test/test_utilities.py
Contributes to #6435.
Adds deprecation warnings for all the cases mentioned in #6435, and some other changes that flow from that:
* promotes `categorical_feature` and `colnames` to top-level arguments of `lightgbm()` in the R package
- *so it stops relying on `lgb.train()`'s support for setting those on the `Dataset`*
* modifies examples and tests to no longer use the deprecated pattern
* updates relevant docs
I'd like to get these warnings out in the v4.4.0 release (#6439), and then leave them there for at least 2 more releases.
copying some others who may be interested: @mayer79 @david-cortes @simonpcouch
Ran the R tests and Python tests, and checked for these warnings.
```shell
R CMD INSTALL ./lightgbm_4.3.0.99.tar.gz
cd R-package/tests …
```
=> [R-package] [python-package] deprecate Dataset arguments to cv() and train()

.appveyor.yml, .ci/test.sh, .ci/test_windows.ps1, .github/workflows/cuda.yml, .github/workflows/linkchecker.yml, .github/workflows/python_package.yml, .github/workflows/r_package.yml, .github/workflows/static_analysis.yml, .vsts-ci.yml
Proposes the following changes to the CI setup:
In the CUDA jobs:
* add support for triggering a build by clicking a button in the UI ([workflow dispatch](https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs))
* removes code running *"set up `nvidia-docker` and restart the docker daemon"* on every CUDA build
- *to save a bit of CI time on each CUDA build*
- *added an option to do this on the manual runs, so that can be done by every maintainer but*
* upgrades Ubuntu versions
- *to Ubuntu 20.04 for CUDA 11.x, Ubuntu 22.04 for CUDA 12.x (see Notes)*
* uses GitHub Actions container support directly instead of calling `docker run` in a `script:` block
* writes miniforge to `/tmp` instead of a directory that's …
=> [ci] simplify CI configurations, parallelize compilation, test CUDA on Ubuntu 22.04

.ci/check_python_dists.sh, .ci/conda-envs/ci-core-py38.txt, .ci/test-python-oldest.sh, .ci/test.sh, .ci/test_windows.ps1, .github/workflows/cuda.yml, .github/workflows/linkchecker.yml, .github/workflows/python_package.yml, .github/workflows/static_analysis.yml, .vsts-ci.yml, python-package/pyproject.toml
Inspired by this discussion: https://github.com/microsoft/LightGBM/pull/6375#issuecomment-2018388889
Proposes the following:
* bump `python-requires` to  `>= 3.7`
* run the one "oldest versions of everything" job on Python 3.7 instead of Python 3.6
* run most CI jobs on 1 minor version of Python newer than what it's currently on
- *which includes adding the first Python 3.12 jobs here!*
* narrowly pin dependencies in Python 3.8 jobs to a specific, known-working environment
I picked the oldest versions where `pip install` run in the `python:3.7` docker image found a wheel. Found that building those old versions `scipy` and `pandas` from their sdists failed with a variety of errors.
Summary:
* `cffi` = unchanged at `1.15.1` ([Jun 2022](https://pypi.org/project/cffi/1.15.1/))
* `numpy` = …
=> [python-package] drop Python 3.6 support, add Python 3.12

.appveyor.yml, .ci/check_python_dists.sh, .ci/get_workflow_status.py, .ci/setup.sh, .ci/test.sh, .ci/test_r_package_valgrind.sh, .ci/test_windows.ps1, .github/workflows/cuda.yml, .github/workflows/linkchecker.yml, .github/workflows/optional_checks.yml, .github/workflows/python_package.yml, .github/workflows/r_package.yml, .github/workflows/static_analysis.yml, .vsts-ci.yml
Follow-up to #6458
Proposes the following simplifications to CI configurations and scripts:
* removes `CONDA_ENV` environment variable and just hard-codes it in scripts
* removes configurations to run CI on PRs targeting any branch matching the pattern `release/*`
- *this was added back when we were releasing from branches not targeting `master`, to avoid releasing the breaking changes building up there in anticipation of 4.0... but that's not the state this project is in any more*
* consolidates `conda`-setup code in `test.sh`
* reduces duplication of image URI in CUDA CI job config
* removes a Python 2.7 try-catch import in `.ci/get_workflow_status.py`
* stops writing an env file in QEMU_multiarch job, in favor of just using `docker run --env`
Also increases the valgrind …
=> [ci] further simplify CI configurations

python-package/lightgbm/basic.py
Contributes to #6435 .
`LGBMDeprecationWarning` was added 7 years ago, in #1046. That was done because Python's builtin `DeprecationWarning` is not shown by default.
PEP 565, accepted in November 2017, offers a different prescription for this.
> *For library and framework authors that want to ensure their API compatibility warnings are more reliably seen by their users, the recommendation is to use a custom warning class that derives from `DeprecationWarning` in Python 3.7+, and from FutureWarning in earlier versions.*
([PEP-565](https://peps.python.org/pep-0565/#additional-use-case-for-futurewarning))
This change will also ensure such warnings show up in tests of anything using `lightgbm` which use `pytest` to run their tests.
From the `pytest` docs:
> *By default pytest will display …
=> [python-package] make LGBMDeprecationWarning inherit from FutureWarning

.ci/get_workflow_status.py, .nuget/create_nuget.py, .pre-commit-config.yaml, docs/conf.py, helpers/check_dynamic_dependencies.py, helpers/parameter_generator.py, python-package/lightgbm/__init__.py, python-package/lightgbm/basic.py, python-package/lightgbm/callback.py, python-package/lightgbm/dask.py, python-package/lightgbm/engine.py, python-package/lightgbm/libpath.py, python-package/lightgbm/plotting.py, python-package/lightgbm/sklearn.py
Proposes upgrading `pre-commit` hooks to their latest versions. I did that by running this from the root of the repo:
```shell
pre-commit autoupdate
```
The other formatting changes in this PR were made by `ruff`.
```shell
pre-commit run --all-files
```
=> [ci] upgrade linters to latest version

.gitignore, docs/Python-Intro.rst, examples/python-guide/logistic_regression.py, python-package/lightgbm/compat.py, python-package/lightgbm/sklearn.py, python-package/pyproject.toml, tests/python_package_test/conftest.py, tests/python_package_test/test_basic.py, tests/python_package_test/test_engine.py, tests/python_package_test/test_sklearn.py
Contributes to #6454
This PR moves `lightgbm` closer to compatibility with `numpy` 2.x
* adds the NumPy 2.0 deprecation `ruff` rules to linting config ([ruff docs](https://docs.astral.sh/ruff/rules/#numpy-specific-rules-npy))
* removes all uses of `np.random.{method}` convenience functions (which are deprecated) in favor of the corresponding `np.random.Generator.{method}` calls
And to accompany that:
* adds a floor of `numpy>1.17.0`
That `ruff` rule identified 95 instances of the following.
```text
NPY002 Replace legacy `np.random.choice` call with `np.random.Generator`
NPY002 Replace legacy `np.random.normal` call with `np.random.Generator`
NPY002 Replace legacy `np.random.rand` call with `np.random.Generator`
NPY002 Replace legacy `np.random.randint` call with `np.random.Generator` …
```
=> [python-package] remove uses of deprecated NumPy random number generation APIs, require 'numpy>=1.17.0'

src/io/dataset_loader.cpp
=> chore: update dataset_loader.cpp

.ci/test_windows.ps1, README.md, pmml/README.md, python-package/README.rst
I'm planning to invest heavily in the project's documentation for the next release. I think there are some opportunities to make things simpler and to make it more likely that people are able to find the information they need without turning to Stack Overflow or the issues pages.
This proposes the following:
* removing the `pmml/` folder
- *it's just there to preserve a link to https://github.com/jpmml/jpmml-lightgbm, but that project is already linked to from the main README*
* removes language about preferred style in the Python README
- *this is enforced via linters and doesn't need to also be documented in the README (which, remember, is also the homepage at https://pypi.org/project/lightgbm/)*
* other small removals
=> [docs] remove pmml redirect, simplify some other docs

.github/workflows/cuda.yml, .github/workflows/python_package.yml, .vsts-ci.yml, python-package/pyproject.toml
[Setuptools](https://setuptools.pypa.io) recently introduced a new way for editable installations. Unfortunately, that does not work well with many tools at this moment in time, nor does it work well with a mono-repo. For that reason we choose to stick with the old way of doing editable installations which is shown [here on setuptools docs](https://setuptools.pypa.io/en/latest/userguide/development_mode.html#strict-editable-installs).
```
pip install -e . --config-settings editable_mode=strict
```
(You will most likely see this appear on more places as people upgrade `pip` versions and the new way of editable installations becomes the default.)
Our code-base, of which we have 20+ different teams with different ML tooling, works as expected with this approach. Unfortunately, `lightgbm` is …
=> [python-package] Change build settings to set strict-config to false

.github/workflows/linkchecker.yml, docs/FAQ.rst, docs/GPU-Windows.rst
The link-checks CI job is failing, like this:
```text
/home/runner/work/LightGBM/LightGBM/.ci/test.sh: line 19: COMPILER: unbound variable
```
([build link](https://github.com/microsoft/LightGBM/actions/runs/9593794916/job/26454997974))
I suspect that's a result of the changes in #6266. This fixes that.
Also fixes some broken links (404s) and "anchor-not-found" issues.
Manually triggered a run on this branch, saw it pass: https://github.com/microsoft/LightGBM/actions/runs/9608163802/job/26500497894
=> [ci] [docs] fix link-checks job

R-package/cran-comments.md
v4.4.0 (#6439) of the R package was accepted to CRAN: https://github.com/microsoft/LightGBM/pull/6439#issuecomment-2182084085
This updated `cran-comments.md` accordingly.
=> [docs] [R-package] update cran-comments.md

.ci/test.sh, .ci/test_r_package.sh, .ci/test_windows.ps1
For a long time, this project's CI scripts have used mostly the following combinations:
* lots of absolute paths to source files
* repetitive uses of `cd` to reset the working directory
With the changes in #6266, I believe that these patterns are unnecessary and that builds will fail if instead these scripts use relative paths that end up pointing to files that don't exist.
In the interest of making the CI configuration easier for contributors to read and understand, this proposes:
* removing unnecessary `cd` calls
* replacing most uses of absolute paths with relative paths
=> [ci] reduce repetition of BUILD_DIRECTORY in CI scripts

R-package/src/lightgbm_R.cpp
From similar PR in XGBoost: https://github.com/dmlc/xgboost/pull/10465
This PR modifies the R C-level function code to call the versions of protect/unprotect that have `Rf_` prefixes. This is currently not required by CRAN as their non-Rf equivalents `PROTECT`/`UNPROTECT` are simple defines aliasing to `Rf_protect`/`Rf_unprotect`, but the situation might change in the future.
=> [R-package] Use `Rf_`-prefixed versions of protect/unprotect

R-package/R/lgb.Booster.R, R-package/src/lightgbm_R.cpp, R-package/src/lightgbm_R.h, R-package/tests/testthat/test_lgb.Booster.R
This PR adds to the R Booster class the following methods:
- num_trees_per_iter(),
- num_trees(), and
- num_iter()
Two functions from the C API are required:
- `LGBM_BoosterNumModelPerIteration_R()` via `LGBM_BoosterNumModelPerIteration()` and
- `LGBM_BoosterNumberOfTotalModel_R()` via `LGBM_BoosterNumberOfTotalModel()`
This additionally helps to solve https://github.com/microsoft/LightGBM/issues/6380.
Note: With early stopping, the number of (relevant) iterations is kept in `Booster$best_iter`, while `num_trees()` and `num_iter()` are higher.
=> [R-package]: add num_trees_per_iter, num_trees, and num_iter methods

CMakeLists.txt
A PR [ [cmake] [swig] use CMake's built-in file-copying mechanisms instead of 'cp' #6259 ](https://github.com/microsoft/LightGBM/pull/6259) introduced a small build regression:
* before: for Linux, both `lib_lightgbm.so` and `lib_lightgbm_swig.so` were included into the JAR
* after: only `lib_lightgbm.so` is part of the JAR.
Lack of the SWIG wrapper makes it impossible to link to the library from the JVM. Mac and Windows builds do include the SWIG wrapper properly and are not affected by this regression.
This PR adds back the `lib_lightgbm_swig.so` library to the JAR build process on Linux. I'm maintaining the [lightgbm4j](https://github.com/metarank/lightgbm4j) library and find it very convenient to re-use your build artifacts :)
=> cmake: add missing lib_lightgbm_swig.so to lightgbmlib.jar on linux

.ci/check_python_dists.sh
Contributing to #6498 , So in the file ```.ci/check_python_dists.sh``` the errors raise by shellcheck were
```
In .ci/check_python_dists.sh line 3:
set -e -E -u
^-- SC3041 (warning): In POSIX sh, set flag -E is undefined.
```
So I changes the shebang line from ```#!/bin/sh``` to ```#!/bin/bash``` 
Then shellcheck was giving errors based on [SC2086](https://www.shellcheck.net/wiki/SC2086) i.e. 
```
In .ci/check_python_dists.sh line 23:
check-wheel-contents ${DIST_DIR}/*.whl || exit 1
^---------^ SC2086 (info): Double quote to prevent globbing and word splitting.
```
The same errors were also on line 19,37,45,52 which can be resolved by changing ```${DIST_DIR}/*``` to ```"${DIST_DIR}/*"```
=> [ci] resolve shellcheck errors in .ci/check_python_dists.sh

.ci/test_r_package.sh
Contributes to #6498
4 years ago, this project was running a lot of its R-package testing on Travis CI. We experienced an issue where `R CMD check` would run for too long without emitting a new log line, and as a result Travis killed jobs.
A workaround was introduced in #3092 ... running `R CMD check` as a background task and polling for the status of it's process ID.
I strongly suspect this is no longer necessary:
* we are not on Travis any more (and I suspect that GitHub Actions does not have a similar timeout based on log output)
* the R package compiles faster in CI than it did 4 years ago
This proposes removing that workaround, to hopefully make it a bit easier to understand the CI setup. It also fixes some `shellcheck` errors, mentioned in …
=> [ci] [R-package] run 'R CMD check' as a foreground task

docs/FAQ.rst
Fix markdown and increase error message discoverability from search engines.
<details>
<summary>Before:</summary>
</details>
<details>
<summary>After:</summary>
</details>
=> [docs] fix FAQ markdown

tests/python_package_test/test_engine.py, tests/python_package_test/test_sklearn.py
contributes to: #6361
Specificially prevents `lgb.pkl` and `lgb.model` files from being left behind after running tests by using pytest's `tmp_path` fixture. One can use the reprex described in https://github.com/microsoft/LightGBM/issues/6361#issue-2187570183 to confirm these files are no longer left behind after these changes.
=> [ci] prevent `lgb.model` and `lgb.pkl` files being left behind after testing

src/io/dense_bin.hpp, src/io/multi_val_dense_bin.hpp, src/io/multi_val_sparse_bin.hpp, src/io/sparse_bin.hpp
Contributes to #6033
C++23 no longer allow template parameters in constructor
=> Remove template parameters from copy constructor

docs/Parameters.rst, include/LightGBM/config.h
Clarify in the parameter description of quantized training to indicate that it is compatible with `device_type=cuda`.
=> [doc] fix documentation for quantized training

tests/python_package_test/test_engine.py
Unblock CI.
Fix for recent pandas error
```
E           TypeError: Invalid value 'nan' for dtype 'bool'
```
For example, https://github.com/microsoft/LightGBM/actions/runs/9863990666/job/27237966034?pr=6526#step:4:546
Everything is OK with `boolean` dtype later in this test:
https://github.com/microsoft/LightGBM/blob/fc788a51b61368f78246e5c450f0ea77d263eb2b/tests/python_package_test/test_engine.py#L4175
=> [tests][python]  fix nan in pandas bool column

build-python.sh
Building a Python wheel + installing it like this:
```shell
sh build-python.sh bdist_wheel install
```
Will also overwrite `numpy` and `scipy` in the installation environment. When working in a conda environment, that'll also replace conda's `numpy` / `scipy` with a wheel from PyPI... which can sometimes lead to undesirable consequences like failed imports.
This could be avoided by just building a wheel yourself and then installing it + telling `pip` not to overwrite any dependencies, like this:
```shell
sh build-python.sh bdist_wheel
pip install --no-deps dist/*.whl
```
This PR proposes just making that the default behavior, to make local development a bit easier.
It also proposes remove the `pip uninstall lightgbm` in that script with passing `--ignore-installed` to `pip install`... …
=> [python-package] avoid overwriting dependencies via 'build-python.sh install'

tests/python_package_test/test_engine.py, tests/python_package_test/test_sklearn.py
Fix the following error:
```
DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
```
LightGBM requires pandas>=0.24.0
https://github.com/microsoft/LightGBM/blob/6c76b6b72ad77ba85285053b8aae209f3a5060ad/python-package/pyproject.toml#L44-L46
So I checked that `pd.SparseDtype` is available in that version:
https://pandas.pydata.org/pandas-docs/version/0.24/reference/api/pandas.SparseDtype.html
Also, they've been performing `isinstance` check under the hood since the begging:
https://github.com/pandas-dev/pandas/blob/83eb2428ceb6257042173582f3f436c2c887aa69/pandas/core/dtypes/common.py#L216-L219
=> [test][python] fix pandas DeprecationWarning about `is_sparse` function

.ci/test_r_package.sh, .github/workflows/r_package.yml
Fixes #6481
Proposes adding an arm64 macOS CI job testing the R package. CRAN checks every submission on an arm64 Mac (https://cran.r-project.org/web/checks/check_flavors.html), so hopefully this will help catch issues before attempting submissions to CRAN.
To avoid further growing the CI matrix, this proposes dropping the job that tests the R package compiled with `clang` on Linux with R 3.6.  I think that's ok, because there are others covering compiling the R package with `gcc` on Linux
https://github.com/microsoft/LightGBM/blob/fc788a51b61368f78246e5c450f0ea77d263eb2b/.github/workflows/r_package.yml#L58-L63
And because we're planning to move away from supporting R 3.6: https://github.com/microsoft/LightGBM/pull/6442#issuecomment-2159162313
This should also reduce the manual testing …
=> [ci] [R-package] add arm64 macOS R-package CI job (fixes #6481)

CMakeLists.txt, build-python.sh, docs/Installation-Guide.rst, docs/_static/js/script.js, python-package/README.rst, src/io/file_io.cpp
Follow-up to #6443.
Fixes #6436
Proposes fully removing HDFS support.
See #6443 for the reasons that I think it's safe to drop this support in LightGBM, and for suggestions of other ways that people with data in HDFS could train LightGBM models on that data.
cc @imatiach-msft @mhamilton723
=> [c++] remove HDFS support (fixes #6436)

R-package/README.md, docs/FAQ.rst, docs/Installation-Guide.rst, python-package/README.rst
Proposes the following changes to installation docs:
The overall goals of this PR are:
* document the CUDA / GPU support in `conda-forge` packages
* reduce maintenance burden, complexity, and the risk of outdated information in installation docs
Specific changes:
* add docs about using the `conda-forge` package to get CUDA/GPU builds, and remove language about it not being maintained by us
- *I am a maintainer there now: ([recipe link](https://github.com/conda-forge/lightgbm-feedstock/blob/efcb026fc9d9d7947f52aa68da9f1097983c84b2/recipe/meta.yaml#L92))*
- *ref: https://github.com/conda-forge/lightgbm-feedstock/pull/55*
* remove language about needing to install `CMake` to build the Python package
- *`scikit-build-core` does this automatically ([code …
=> [docs] update and simplify installation docs

build-cran-package.sh
On my M2 Mac, with R 4.3.3 installed from CRAN, I found that the following:
```shell
sh build-cran-package.sh
R CMD INSTALL --with-keep.source ./lightgbm_4.4.0.99.tar.gz
```
Fails like this:
```text
Error in rawToChar(info) : 
embedded nul in string: '30 mtime=1720906116.345798869\n57 LIBARCHIVE.xattr.com.apple.provenance=AQAAf4WY23sneC8\n49 SCHILY.xattr.com.apple.provenance=\001\0\0\177\x85\x98\xdb{'x/\n'
```
Based on https://stackoverflow.com/a/74373784/3986677 and similar, it seems that the root cause is that BSD `tar` (the one available on my mac) copies "extra file attributes" into archives it creates. This is the opposite of what GNU tar does. From https://www.gnu.org/software/tar/manual/tar.html#Extended-File-Attributes
```text
‘--no-xattrs’
Disable extended attributes support. …
```
=> [ci] [R-package] use --no-xattrs when re-tarring CRAN-style package

python-package/README.rst
I'd like to add conda version badge as well, but it's currently broken: https://github.com/conda-forge/lightgbm-feedstock/issues/59.
=> [docs] Add conda downloads badge

.github/CODEOWNERS
Proposes adding @StrikerRUS back to `CODEOWNERS`, to be automatically added as a reviewer on PRs.
@StrikerRUS since #5998, we've stopped having specialization in the `CODEOWNERS` file (no more "these people are R reviewers", "these people are Python reviewers", etc.) and switched to just having everyone added to every PR by default. That more closely matched the current state of the project and abilities/interests of the reviewers.
If you don't want to be added as a reviewer on every PR by default let me know, and we can close this.
=> [ci] update codeowners

python-package/lightgbm/basic.py, python-package/lightgbm/sklearn.py, tests/python_package_test/test_sklearn.py
fixes #6519
fixes #3636
I created a pull request addressing issue [#6519](https://github.com/microsoft/LightGBM/issues/6519), which I've also encountered. 
I modified the code to use `np.vstack` only when `result.shape` look like `(num_data,)`, and some typos.
=> [python-package] Correctly recognize LGBMClassifier(num_class=2, objective="multiclass") as multiclass classification

.github/workflows/r_package.yml
fixes #6553
As I mentioned there... I'll report this upstream as well, and hopefully we can remove the workaround soon.
=> [ci] [R-package] help linker find libstdc++.so.1 in clang18 job (fixes #6553)

.github/workflows/r_package.yml
Reverts the change from #6554. It seems that the issue reported in #6553 was already fixed upstream 😁 
ref: https://github.com/r-hub/containers/issues/70#issuecomment-2238089905
=> [ci] revert clang-18 LD_LIBRARY_PATH workaround

docs/FAQ.rst
Fix flaky error 
```
URL        `https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md#user-content-workarounds-for-intel-openmp-and-llvm-openmp-case'
Name       `here'
Parent URL file:///home/runner/work/LightGBM/LightGBM/docs/_build/html/FAQ.html, line 307, col 396
Real URL   https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md#user-content-workarounds-for-intel-openmp-and-llvm-openmp-case
Check time 2.337 seconds
D/L time   0.003 seconds
Size       178.06KB
Warning    [None] Anchor
`user-content-workarounds-for-intel-openmp-and-llvm-openmp-case'
(decoded:
`user-content-workarounds-for-intel-openmp-and-llvm-openmp-case')
not found. Available anchors:
`action-menu-7bcd7c74-3a41-4bfd-8d70-cfb51e70[764](https://github.com/microsoft/LightGBM/actions/runs/99 …
```
=> [docs] fix link to multiple OpenMP issue description

.vsts-ci.yml
For the last few days, we've observed 2 CI issues which happen on every build triggered by a merge to `master`... but which do not happen on PRs.
* #6543
* #6544
Comparing logs between those types of builds, I found only 1 seemingly-significant difference between them... on builds triggered by merges to `master`, tasks called `Initialize CodeQL` and `Finalize CodeQL` are automatically injected.
This proposes trying to prevent those tasks from being injected. If we do that and see a few builds on `master` succeed, we'll be able to say with confidence that the CodeQL jobs were the issue.
More context on how these jobs might cause the CI failures we've observed https://github.com/microsoft/LightGBM/issues/6544#issuecomment-2241487432
I couldn't really find any. "Configure GitHub Advanced …
=> [ci] modify CodeQL settings

README.md
@jameslamb 
This your comment led me to the thought that all our GitHub Actions badges are actually broken and are constantly green.
> I had looked into this a few weeks ago and couldn't figure out how to make it actually reflect the latest run.
https://github.com/microsoft/LightGBM/pull/6568#pullrequestreview-2196750434
So I believe it's better re-create them with new syntax proposed by the GUI badge creation wizzard.
=> [docs] update GitHub Actions badges in README

build-python.sh
Initially I was trying to use the following pip flag:
> --no-index
>> Ignore package index (only looking at --find-links URLs instead).
https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-no-index
to prohibit pip to install LightGBM from PyPI like [here](https://github.com/microsoft/LightGBM/actions/runs/10115054441/job/27975015979#step:5:1042):
```
Successfully built lightgbm-4.5.0.tar.gz
--- installing lightgbm ---
Looking in links: .
Collecting lightgbm
Downloading lightgbm-4.5.0-py3-none-manylinux_2_28_x86_64.whl.metadata (17 kB)
Downloading lightgbm-4.5.0-py3-none-manylinux_2_28_x86_64.whl (3.6 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 97.6 MB/s eta 0:00:00
Installing collected packages: lightgbm
Successfully installed lightgbm-4.5.0
```
But unfortunately that flag …
=> [ci] ask pip to always install local artifact but not download package from PyPI

.ci/test_r_package_windows.ps1, .ci/test_windows.ps1
Currently this fix is applied only to R-package builds.
This PR proposes adding this fix to all Windows builds.
```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(400,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build.
```
https://ci.appveyor.com/project/guolinke/lightgbm/builds/50283647/job/bo2wb8ejurn0b0k6#L798
=> [ci] fix MSVC warning about builds in temp directory

README.md, python-package/README.rst
Seems that `latest_version` field is correct now: https://github.com/conda-forge/lightgbm-feedstock/issues/59#issuecomment-2256378397
=> [docs] add conda version badge

CMakeLists.txt
Proposes the following changes to CMake files here:
* using variable name `LGBM_SOURCES` instead of `SOURCES`
- *(to reduce the risk of possible conflicts with CMake... "SOURCES" is just a very generic name and I could see it having a special meaning in CMake in the future)*
* explicitly listing sources instead of using `file(GLOB)`
* reduces the risk of accidentally including files from local development that shouldn't be included
* helps `CMake` to detect when it needs to change the generated build system
This is explicitly recommended in the CMake docs for `file()` ([link](https://cmake.org/cmake/help/latest/command/file.html#filesystem)).
> *Note We do not recommend using `GLOB `to collect a list of source files from your source tree. If no `CMakeLists.txt` file changes when a source …
=> [cmake] stop using file(GLOB)

R-package/src/install.libs.R
Proposes some small simplifications to `install.libs.R`, the R script that runs `cmake --build` in CMake-based builds of the R package.
* removes references to `.Internal(internalsID())`
- *this is no longer necessary now that we link against R.so directly: #3016*
- *ref: https://github.com/wch/r-source/blob/0986e80068addc5c884d06580412ff2331436814/src/include/Defn.h#L106-L108*
* removes unnecessary assignments in setting up CMake defines that are always, unconditionally used
=> [R-package] [cmake] simplify CMake-based R builds

.ci/create-nuget.py, .vsts-ci.yml
I'm sorry, I somehow overlooked one `nuget` occurrence in #6581. It resulted in empty NuGet artifact.
`NuGetCommand` job before #6581:
```
Starting: NuGetCommand
==============================================================================
Task         : NuGet
Description  : Restore, pack, or push NuGet packages, or run a NuGet command. Supports NuGet.org and authenticated feeds like Azure Artifacts and MyGet. Uses NuGet.exe and works with .NET Framework apps. For .NET Core and .NET Standard apps, use the .NET Core task.
Version      : 2.238.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/nuget
==============================================================================
Caching tool: NuGet 4.9.6 x64
Found tool in …
```
=> [ci] restore nuget artifact creation

python-package/pyproject.toml
There is a new `sckit-build-core` minor version with lots of nice improvements. This proposes updating to it here in LightGBM.
See https://iscinumpy.dev/post/scikit-build-core-0-10/ for details.
=> [python-package] update to scikit-build-core 0.10

.ci/test.sh, .github/workflows/static_analysis.yml, .pre-commit-config.yaml, tests/python_package_test/test_sklearn.py
Contributes to #3763.
Updates some linting versions.
* newest versions of all `conda install`'d stuff for the `lint` and `check-docs` tests
* newest `pre-commit` hook versions from `pre-commit autoupdate`
Happy to say the newest version of `ruff` caught a bug... a Python test that could accidentally not raise an exception because of a missing `raise` statement! This fixes that as well.
=> [ci] update some linting versions

CMakeLists.txt
Fixes #6601 with `-DBUILD_STATIC_LIB=ON` on macos with `USE_OPENMP` enabled
=> [cmake] fixes static build for macos with OpenMP enabled (fixes #6601)

tests/c_api_test/test_.py, tests/python_package_test/test_engine.py
Contributes to #6361.
Same fix as #6590.
This PR prevents `train.binary.bin` and `lgb_train_data.bin` being left after executing pytest.
=> [ci] prevent `train.binary.bin` and `lgb_train_data.bin` files being left behind after testing

CMakeLists.txt
Another step towards simplifying this project's CMake configuration (are you sensing a theme in my recent PRs? 😂 ).
CMake's `set_target_properties()` accepts multiple targets and multiple properties ([CMake docs](https://cmake.org/cmake/help/latest/command/set_target_properties.html)).
This proposes taking advantage of that to consolidate a few calls.
=> [cmake] consolidate set_target_properties() calls

R-package/R/lgb.cv.R, R-package/R/lgb.train.R, R-package/tests/testthat/test_parameters.R
Fixes #6612
* Fix: The associated functions have been fixed by adding a nested if-statement that only triggers if the dart-booster is specified with early_stopping_rounds != NULL.
* Unittests: The unit-test in test_parameters.R have been rewritten in the following way
* The lightgbm()-test have had a expect_no_warning()-clause added if the model is correctly specified.
* A new unittest have been created that checks wether lgb.cv() throws a warning errorneously.
This commit closes https://github.com/microsoft/LightGBM/issues/6612. :wrench:
=> [R-package] only warn about early stopping and DART boosting being incompatible if early stopping was requested

python-package/setup.cfg
I don't think `python-package/setup.cfg` serves any purpose in this project any more. This proposes removing it it.
The configuration in `setup.cfg` doesn't affect `scikit-build-core` based builds ([see docs here](https://github.com/scikit-build/scikit-build-core/blob/a6f954a0f477269ea43f6804fe57d76316a89e24/docs/migration_guide.md?plain=1#L22-L30)), so I just tested the `--precompile` option where a `setuptools` build backend is substituted in:
https://github.com/microsoft/LightGBM/blob/a9df7f113f7e603ed06dcc04baf2bc55f28ba090/build-python.sh#L308-L316
```shell
cmake -B build -S .
cmake --build build --target _lightgbm -j4
sh build-python.sh install --precompile
```
Saw the unit tests pass
```shell
pytest tests/python_package_test
```
And the package contained the expected files: …
=> [python-package] remove setup.cfg

CMakeLists.txt, cmake/modules/FindLibR.cmake
Fixes #6628
The background for this is described in much greater detail in https://github.com/microsoft/LightGBM/issues/6628#issuecomment-2316773793.
In short:
* `{data.table}` recently put up a new release (v1.16.0)
* CRAN's macOS binaries for that release are linked to `libomp.dylib`
* the way that linking was done causes `{data.table}` and a CMake + clang version of `{lightgbm}` to load 2 different copies of `libomp.dylib`, causing segfaults
* as a result, R + CMake + clang macOS builds of `{lightgbm}` are broken
This fixes it by ensuring that the place where R vendors third-party libraries is searched for `libomp.dylib` first when `library(lightgbm)` is called (so that the same libraries used by CRAN will be found).
Other relevant discussions:
* #6391
* #6489
* #6595
=> [cmake] [R-package] include R-for-macOS vendored libs dir in OpenMP search path (fixes #6628)

README.md
Hi LightGBM Team!
I've added in readme a new package for decision tree visualization - `supertree`. It works with `LGBMClassifier` and `LGBMRegressor`. The package can be used in notebook environment (Jupyter, Colab) or in Python script. I hope it will be useful for LightGBM users. Thank you!
=> [docs] add supertree in README

tests/c_api_test/test_.py
fixes #6361
I was testing whether #6361 could be closed by recent PRs, and realized that I'd missed one local file when listing the test files there... `"preb.txt"`, created by the C API tests.
This does the following:
* ensures that file isn't left behind
* changes all uses of "preb" to "preds" (it always refers to predictions, so I think "preb" was just a typo)
Ran all the tests locally (on my Mac, with all optional dependencies installed)
```shell
sh build-python.sh install
pytest tests/
MAKEFLAGS="-j4" R CMD INSTALL --with-keep.source ./lightgbm*.tar.gz
cd R-package/tests
Rscript testthat.R
rm -rf ./build
cmake -B build -S . -DBUILD_CPP_TEST=ON -DUSE_OPENMP=OFF
cmake --build build --target testlightgbm -j4
./testlightgbm
```
Checked that …
=> [ci] prevent C API tests from leaving files behind (fixes #6361)

.ci/conda-envs/ci-core.txt, .ci/test-python-latest.sh, docs/FAQ.rst, python-package/lightgbm/__init__.py, python-package/lightgbm/basic.py, python-package/lightgbm/libpath.py
As described in https://github.com/microsoft/LightGBM/issues/6653, `lightgbm` is currently failing scikit-learn compatibility tests against the latest `scikit-learn` nightlies (1.6.0dev0).
That's being worked on in https://github.com/microsoft/LightGBM/pull/6651.
This PR proposes temporarily dropping `scikit-learn` from the list of projects whose nightlies `lightgbm` is tested against, to unblock CI here.
**Update (Sep 22)**
While working on this, CI for the Python package started failing in another way:
```text
libgomp.so.1: cannot allocate memory in static TLS block
```
This proposes a permanent fix for that as well... trying to `dlopen()` load_lightgbm as early as possible when running `import lightgbm`.
=> [ci] [python-package] temporarily stop testing against scikit-learn nightlies, load lib_lightgbm earlier

CMakeLists.txt
Usage of `variables` list was removed in fb96b717a82688c920a61d813be8f8051243632d.
=> [cmake] remove unused variable

.github/workflows/r_package.yml
Checking if #6607 has been resolved by changes to R-devel or the container images used for that test.
(edited): fixes #6607 😁
=> [ci] [R-package] re-enable R-devel clang16 job (fixes #6607)

CMakeLists.txt
Speed up CI by not compiling executable target.
Test CI run with SWIG artifacts to ensure they hadn't been changed by refactoring: https://lightgbm-ci.visualstudio.com/lightgbm-ci/_build/results?buildId=17039&view=results.
=> [cmake] simplify SWIG config

README.md, docs/Parameters.rst, include/LightGBM/config.h, include/LightGBM/cuda/cuda_objective_function.hpp, include/LightGBM/objective_function.h, include/LightGBM/sample_strategy.h, src/boosting/bagging.hpp, src/boosting/gbdt.cpp, src/io/config.cpp, src/io/config_auto.cpp, src/objective/rank_objective.hpp, tests/python_package_test/test_engine.py
Add bagging by query instead of by items in lambdarank, suggested by @metpavel. This should be more reasonable for bagging in ranking tasks. For a comparison of performance, on MS LTR dataset:
With `bagging_freq=1` and `bagging_fraction=0.1`, if `bagging_by_query=true`
```
[LightGBM] [Info] Iteration:100, training ndcg@1 : 0.528525
[LightGBM] [Info] Iteration:100, training ndcg@3 : 0.502271
[LightGBM] [Info] Iteration:100, training ndcg@5 : 0.5034
[LightGBM] [Info] 23.123690 seconds elapsed, finished iteration 100
[LightGBM] [Info] Finished training
```
and if `bagging_by_query=false`
```
[LightGBM] [Info] Iteration:100, training ndcg@1 : 0.524889
[LightGBM] [Info] Iteration:100, training ndcg@3 : 0.502272
[LightGBM] [Info] Iteration:100, training ndcg@5 : 0.502838
[LightGBM] [Info] …
```
=> [c++] Add Bagging by Query for Lambdarank

.ci/test.sh, .github/workflows/python_package.yml
Trying to fix https://github.com/microsoft/LightGBM/pull/6539#issuecomment-2392516473
Starting with the `23.10` release of `conda` (about a year ago), the `conda` executable now uses the mamba solver by default... so there's no need to invoke the `mamba` executable any more:
* https://docs.conda.io/projects/conda/en/latest/release-notes.html#id55
* https://conda.org/blog/2023-11-06-conda-23-10-0-release/
We should be able to use `conda {command}` instead of `mamba {command}` without any loss of performance now, and I'm hoping it will fix the issue with `mamba` reported in the linked comment above.
Searched for all uses of `mamba` like this:
```shell
git grep 'mamba'
```
=> [ci] replace uses of 'mamba' with 'conda', use Python 12 for test-python-latest-job

.ci/setup.sh, .ci/test-r-package.sh, .ci/test.sh, tests/c_api_test/test_.py
Fixing shellcheck warnings in .ci/test.sh .ci/test-r-package.sh .ci/setup.sh continuing [!6641](https://github.com/microsoft/LightGBM/pull/6641)
=> [ci] fix shellcheck warnings in CI scripts

.ci/conda-envs/ci-core-py38.txt, python-package/lightgbm/sklearn.py
Fixes #6678
Fixes #6680
As of https://github.com/scikit-learn/scikit-learn/pull/29818 (which will be in `scikit-learn` 1.6), `scikit-learn` contains an estimator check that enforces the following behavior:
> *check that setting sample_weight to zero / integer is equivalent to removing / repeating corresponding samples*
This new check is breaking CI here... LightGBM does not work that way.
* `weight=0.0` samples' feature values still contribute to feature distributions and therefore bin boundaries in `Dataset` histograms (https://github.com/microsoft/LightGBM/issues/5553)
* every sample counts as exactly `1` sample for the perspective of count-based hyper-parameters like `min_data_in_leaf` (https://github.com/microsoft/LightGBM/issues/5626#issuecomment-1712706678)
This PR proposes skipping …
=> [python-package] ignore scikit-learn 'check_sample_weight_equivalence' estimator check (fixes #6678)

.ci/test-windows.ps1, .ci/test.sh
As #4125 was fixed we don't need to disable OpenMP support in cpp tests anymore. 🎉
=> [ci] enable OpenMP support in cpp tests

docs/Python-Intro.rst, python-package/lightgbm/basic.py, python-package/lightgbm/sklearn.py
Contributes to #6662
Deprecates support for H2O's `datatable` in the Python package. See the linked issue for details.
=> [python-package] deprecate support for H2O 'datatable'

.pre-commit-config.yaml, python-package/lightgbm/basic.py
Contributes to #6498
* enforces `shellcheck` checks in CI
* updates all pre-commit hooks to their latest versions (via `pre-commit autoupdate`)
Fixes 1 new warning found by `ruff`
```text
python-package/lightgbm/basic.py:879:17: PLR1730 [*] Replace `if` statement with `offset = max(offset, max_offset)
```
Double-checked, and `shellcheck-py` ships wheels for Linux, Windows, and macOS ... so everyone working on the project should be able to keep running `pre-commit` without issue.
ref: https://pypi.org/project/shellcheck-py/#files
=> [ci] add shellcheck, use latest pre-commit hook versions

windows/LightGBM.sln
Version was taken from here: https://omwtm.blog/2014/12/03/visual-studio-2013-version-numbers-and-updates/.
=> [ci] set `MinimumVisualStudioVersion` to MSVS 2015

src/io/config.cpp
With CUDA, `force_row_wise` is used.
https://github.com/microsoft/LightGBM/blob/d2b4e7374957e0d05a3a7d5ec695940287d4dc36/src/io/config.cpp#L410-L413
=> [docs] fix inaccurate comment for `force_col_wise` param with CUDA version

docs/Parameters.rst, include/LightGBM/config.h
I updated the documentation note of 'linear_tree' due to the introduced support of 'device_type=gpu' in pull request  (https://github.com/microsoft/LightGBM/issues/6555).
=> [docs] Remove only cpu note due to gpu support for linear trees

build-python.sh
Based on my understanding from https://github.com/microsoft/LightGBM/pull/6689#issuecomment-2437371601, the `.sln` and `.vcxproj` files in the `windows/` directory are intended for use in the Visual Studio GUI, and don't need to be included in the source distribution of the Python package ("sdist").
This proposes removing them, to make the sdist on PyPI slightly smaller.
=> [python-package] remove MSVS solution files from sdist

docs/_static/js/script.js, docs/conf.py
~I believe this element selectors are quite unreliable and subject to frequent changes.~
OK, it's shadow DOM, so we simply cannot access it.
Unfortunately, this fix will be active only with next release and is not backported to previous versions.
=> [ci] Fix version matching between RTD pages and R-package pages

.ci/lint-powershell.ps1, .ci/lint-r-code.R, .ci/test-r-package-windows.ps1, .ci/test-windows.ps1, .ci/test.sh, .editorconfig, .github/workflows/static_analysis.yml
Linking full original PR: #6700.
This PR fixes all warnings about our own functions (`PSUseApprovedVerbs`, `PSUseShouldProcessForStateChangingFunctions`, `PSUseSingularNouns`).
Also this PR makes params in our own functions mandatory where needed.
List of available rules: https://github.com/PowerShell/PSScriptAnalyzer/blob/main/docs/Rules/README.md.
List of Approved Verbs for PowerShell Commands: https://learn.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands?view=powershell-7.4.
=> [ci] check PowerShell scripts with PSScriptAnalyzer (part 1)

python-package/lightgbm/engine.py, tests/python_package_test/test_engine.py
Contributes to #6435
Removes the following keyword arguments from `train()` and `cv()` in the Python package:
* `categorical_feature`
* `feature_name`
Simplifies the project's public API, to avoid confusion like https://stackoverflow.com/questions/78383840/in-lightgbm-why-do-the-train-and-the-cv-apis-accept-categorical-feature-argument.
Deprecation warnings about these changes have been in `lightgbm` since v4.4.0 ([June 2024](https://github.com/microsoft/LightGBM/releases/tag/v4.4.0)). I expect it will be *at least* another month until another release of LightGBM is published, so by then it will have been multiple releases and close to 6 months. I think that's long enough.
The corresponding R package changes are a bit more extensive and will generate a bit more discussion, I think. …
=> [python-package] remove support for passing 'feature_name' and 'categorical_feature' through train() and cv()

.ci/install-opencl.ps1, .ci/test-r-package-windows.ps1, .ci/test-windows.ps1, .ci/test.sh, .github/workflows/static_analysis.yml
Linking full original PR: #6700.
Continuation of #6704.
This PR fixes only all `PSUseConsistentIndentation` warnings, so it can be skimmed fast without attention.
=> [ci] check PowerShell scripts with PSScriptAnalyzer (part 2)

.ci/install-opencl.ps1, .ci/lint-powershell.ps1, .ci/test-r-package-windows.ps1, .ci/test-windows.ps1, .ci/test.sh, .github/workflows/static_analysis.yml
Linking full original PR: #6700.
Continuation of #6709.
Closed #6498.
Closed #6700.
This PR fixes all remaining PowerShell linting issues (`PSAvoidLongLines`, `PSAvoidUsingCmdletAliases`, `PSPlaceCloseBrace`, `PSPossibleIncorrectComparisonWithNull`).
Helpful links with info about splitting long lines:
- https://stackoverflow.com/questions/2608144/how-to-split-long-commands-over-multiple-lines-in-powershell
- https://get-powershellblog.blogspot.com/2017/07/bye-bye-backtick-natural-line.html
=> [ci] check PowerShell scripts with PSScriptAnalyzer (part 3)

README.md
This is SO COOL .... I learned tonight that Pyodide is building a version of the `lightgbm` Python package that runs in a web browser.
https://github.com/pyodide/pyodide/tree/main/packages/lightgbm
Try it yourself.... go to https://pyodide.org/en/stable/console.html (recommended from https://pyodide.org/en/stable/usage/index.html), and run the following:
```python
from sklearn.datasets import make_regression
from sklearn.metrics import r2_score
X, y = make_regression(n_samples=10_000, n_features=5, n_informative=5)
bst = lgb.train(
train_set=lgb.Dataset(X, label=y),
params={"objective": "regression", "verbose": -1}
)
print(r2_score(y, bst.predict(X)))
```
🤯 🤯 🤯 🤯 
This proposes adding a note about that to the README.
=> [docs] add note about pyodide support

python-package/lightgbm/compat.py, python-package/lightgbm/sklearn.py, tests/python_package_test/test_sklearn.py
Follow-up to #6718
In that PR, I'd skipped the method resolution order ("MRO") for `__sklearn_tags__()` in the `scikit-learn` estimators, to provide compatibility with earlier versions of that library. During development, we switched to having e.g. `LGBMClassifier.__sklearn_tags__()` raise an `AttributeError` if run on a too-new version of `scikit-learn`, making that unnecessary... but never went back to just using inheritance to get `__sklearn_tags__()`.
This fixes that.
Inspired by https://github.com/dmlc/xgboost/pull/11021#discussion_r1860044450
=> [python-package] simplify scikit-learn 1.6+ tags support

include/LightGBM/bin.h, include/LightGBM/cuda/cuda_column_data.hpp, include/LightGBM/cuda/cuda_row_data.hpp, include/LightGBM/dataset.h, include/LightGBM/feature_group.h, include/LightGBM/train_share_states.h, include/LightGBM/tree.h, src/c_api.cpp, src/io/cuda/cuda_column_data.cpp, src/io/json11.cpp
Earlier today, I got an email from Prof. Brian Ripley (from CRAN):
> _**subject:** CRAN packages missing `<cstint>` header_
>
> _**body:** Current snapshots of g++ 15 are complaining that you have omitted the header <cstdint>.  Please follow the advice in the log at your next update.  (We would contact you again if this persists when a release date for GCC 15 is known, but they tend to give only a week's notice.)_
Linking to these logs for a build of `lightgbm` with gcc-15: https://www.stats.ox.ac.uk/pub/bdr/gcc15/lightgbm.out
It contains compilation errors like this:
```text
io/json11.cpp: In function 'void json11_internal_lightgbm::dump(const std::string&, std::string*)':
io/json11.cpp:93:28: error: 'uint8_t' does not name a type
93 |     } else if (static_cast<uint8_t>(ch) <= 0x1f) {
| …
```
=> [c++] include <cstdint> wherever uint8_t is used

.ci/conda-envs/ci-core.txt
Sets an upper bound on dask to unblock the CI jobs until #6739 is resolved.
=> [ci] set upper bound on dask

src/treelearner/split_info.hpp
#6491 (comment)
This code is used for computing the buffer size of the communicating the split info the in distributed training. But lost the two most recently added parameters(right_sum_gradient_and_hessian, left_sum_gradient_and_hessian) size. When use parallel_tree_learner method with number of categories of one feature larger than 28 (default max_cat_to_onehot(32)-2*2), it will resut in an Segmentation fault.
=> [c++] fix parallel_tree_learner_split_info

R-package/configure, R-package/configure.ac
On systems that did not have bash as /bin/sh this would end up causing strange compilation errors.
Fixes #6743.
=> [R-package] Avoid bashisms (non-POSIX code) in R-package/configure

src/network/linkers_socket.cpp
This is to resolve potential attack when building a connection in the initialization of distributed training. An attacker could send a malicious rank through the listener, causing an out of bound write. This was found by our secure research team.
=> [fix] resolve potential attack in linker connection building

python-package/lightgbm/basic.py, tests/python_package_test/test_engine.py
Follow up to #6721. This prevents copying the data array when predicting if it's column-major.
=> [python-package] do not copy column-major numpy arrays when predicting

.vsts-ci.yml
I believe we don't need preserving anonymous volumes during cleanup.
Refer to https://depot.dev/blog/docker-clear-cache#removing-everything-with-docker-system-prune and https://docs.docker.com/reference/cli/docker/system/prune/.
> By default, volumes aren't removed to prevent important data from being deleted if there is currently no container using the volume. Use the `--volumes` flag when running the command to prune anonymous volumes as well:
=> [ci] remove Docker volumes during Azure cleanup

.ci/test.sh, docs/.linkcheckerrc
Fixes #6756
The relative path we pass to its config file needs to be updated (I think I broke this in #6497).
Manually triggered the link check workflow from this branch: 
* first build: https://github.com/microsoft/LightGBM/actions/runs/12335479058
* after config changes from https://github.com/microsoft/LightGBM/pull/6757#pullrequestreview-2504292757: https://github.com/microsoft/LightGBM/actions/runs/12335867947
* setting `threads=10`: https://github.com/microsoft/LightGBM/actions/runs/12336243590
* setting `threads=4`: https://github.com/microsoft/LightGBM/actions/runs/12336463177
=> [ci] fix linkchecker job

python-package/lightgbm/engine.py
Change requested by @jameslamb in https://github.com/microsoft/LightGBM/pull/5808#discussion_r1885522968.
Renaming the variable into `cvbooster` would be more correct and it would make it more coherent with the returned result.
=> [python-package] Rename `cvfolds` variable into `cvbooster` in `engine.cv` function

python-package/lightgbm/callback.py, python-package/lightgbm/engine.py, tests/python_package_test/test_engine.py
Contributes to #6748
There are a few activities where `lightgbm` (the Python package) needs to inspect the output of one or more evaluation metrics on one or more datasets.
For example:
* early stopping
* printing evaluation results
* recording evaluation results in memory (e.g. in a dictionary) for use after training
For `train()` and other APIs that end up using it, it tracks those using a list of tuples like this (pseudocode):
```python:
[
({dataset_name}, {metric_name}, {is_higher_better}, {metric_value}).
...
]
```
`cv()` does something similar. However, its "metric value" is actually a mean of such values taken over all cross-validation folds. Because multiple values are being aggregated, it appends a 5th item with the standard deviation.
```text
[
({dataset_name}, {metric_name}, …
```
=> [python-package] stop relying on string concatenation / splitting for cv() eval results

python-package/lightgbm/basic.py, tests/python_package_test/test_engine.py
Fixes https://github.com/microsoft/LightGBM/issues/6737
=> [python-package] Fix inconsistency in `predict()` output shape for 1-tree models

.ci/conda-envs/ci-core-py38.txt
Fixes #6772
See that issue for details. In short: pins even more things in the Python 3.8 conda environment.
As a reminder... `conda-forge` does not support Python 3.8 builds any more ([Python 3.8 is past its end-of-life](https://devguide.python.org/versions/)), so here in CI we use tight pins to get a known-working Python 3.8 environment.
=> [ci] pin more dependencies in Python 3.8 environment

python-package/lightgbm/basic.py, tests/python_package_test/test_arrow.py
=> [python-package] Infer feature names from `pyarrow.Table`

.github/workflows/cuda.yml, .github/workflows/python_package.yml, .github/workflows/r_package.yml, .github/workflows/static_analysis.yml, .github/workflows/triggering_comments.yml, .vsts-ci.yml, .yamllint.yml, R-package/pkgdown/_pkgdown.yml
Second PR in series of PRs for linting yaml files.
This PR contains only additional whitespace characters.
Continuation of #6763.
See #6758 for background and future PRs' content required to fix all errors with the proposed config.
=> [ci] fix errors about indentation in yaml files (Part 2)

src/boosting/gbdt.h, src/c_api.cpp, tests/cpp_tests/test_single_row.cpp
1) Fixed Predictor lifecycle
2) Fixed Boosting trees initialization
Fixed #5482
=> [c++] Fixed Predictor lifecycle and trees initialization in Contrib mode

.github/workflows/static_analysis.yml, .vsts-ci.yml, .yamllint.yml
Third PR in series of PRs for linting yaml files.
Continuation of #6789.
See #6758 for background and future PRs' content required to fix all errors with the proposed config.
=> [ci] fix errors about comments indentation in yaml files (Part 3)

include/LightGBM/c_api.h, python-package/lightgbm/basic.py, src/c_api.cpp, tests/python_package_test/test_basic.py
Following the suggestion in https://github.com/microsoft/LightGBM/pull/6751#issuecomment-2543153272 this changes the signature of the C API `LGBM_DatasetCreateFromMats` function to take an array of integers as `is_row_major`, indicating the layout of each matrix. Also updates the `lightgbm.Dataset.__init_from_list_np2d` method to provide this setting and avoid copying the arrays in the list.
=> [python-package] do not copy column-major numpy arrays when creating Dataset from list of arrays

.github/workflows/cuda.yml, .github/workflows/lock.yml, .github/workflows/no_response.yml, .github/workflows/optional_checks.yml, .github/workflows/r_package.yml, .github/workflows/r_valgrind.yml, .github/workflows/static_analysis.yml, .github/workflows/triggering_comments.yml, .vsts-ci.yml, .yamllint.yml
Last PR in series of PRs for linting yaml files.
This PR fixes long lines error.
Continuation of #6794.
See #6758 for background and future PRs' content required to fix all errors with the proposed config.
Closed #6758.
=> [ci] fix errors about comments indentation in yaml files (Part 4)

python-package/lightgbm/basic.py, python-package/lightgbm/compat.py, tests/python_package_test/conftest.py, tests/python_package_test/test_arrow.py
The only tests I can think of would require a runner with `pyarrow` but not `cffi` installed.
Note that the `LightGBMErrors` will only raise when `pyarrow` is installed, but `cffi` is not. If `pyarrow` is not installed, `pa_Table` is a dummy class and `isinstance(data, pa_Table)` returns `False`.
This is a breaking change for users who didn't install `lightgbm[arrow]`, but rather just installed `lightgbm` and `pyarrow` separately. Even if not intended, they could previously train a model on a `pyarrow.Table`, as this was converted via to a `scipy.sparse.csr_matrix(data)`. The fix is simply to install `cffi` or to transform manually with `scipy.sparse.csr_matrix`. 
Still, it is good to inform people that they are not "natively" training from a `pyarrow.Table`, incurring an unnecessary …
=> [python-package] Separately check whether `pyarrow` and `cffi` are installed

.github/workflows/optional_checks.yml, .github/workflows/r_valgrind.yml
Replaces #6815
The valgrind CI job is failing like this:
```text
/__w/_temp/a09e15f1-9453-4607-9d54-66e1c2404ea4.sh: 6: comment+=https://github.com/microsoft/LightGBM/actions/runs/13159252384: not found
```
([build link](https://github.com/microsoft/LightGBM/actions/runs/13159252384/job/36723582045))
This attempts to fix that.
As described in #6743, `+=` is a non-POSIX behavior.
My guess is that using it in `run:` in GitHub Actions steps is problematic if the shell is not one that recognizes `+=`.
It *should* be the case that GitHub Actions is using `bash` in these jobs, which shouldn't be a problem. Per https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#defaultsrunshell
> **`shell` unspecified**
>
> _[`bash -e {0}` is] the default shell on non-Windows …
=> [ci] fix valgrind workflow

R-package/R/lightgbm.R, R-package/man/lgb.cv.Rd, R-package/man/lgb.train.Rd, R-package/man/lgb_shared_params.Rd, R-package/man/lightgbm.Rd, python-package/lightgbm/callback.py
fixes #6244
Adds a note about DART boosting disabling early stopping in the `callback.early_stopping()` docstring, to make that a bit more visible (especially for people running Python with warnings filtered out).
I activated this branch on readthedocs so we can see how this renders.
build link: https://readthedocs.org/projects/lightgbm/builds/27344381/
=> [docs] add a note about DART in early_stopping docstring

tests/python_package_test/test_engine.py
contributes to: https://github.com/microsoft/LightGBM/issues/6860
Adds specific error messages to `test_get_split_value_histogram`.
=> [python-package] Add more specific error messages to `test_engine`

.ci/test-r-package-windows.ps1, .github/workflows/r_package.yml, R-package/DESCRIPTION, R-package/R/lgb.Dataset.R, R-package/README.md, R-package/configure.win, R-package/tests/testthat/helper.R, build-cran-package.sh, build_r.R, docker/README.md
Fixes #7023
Proposes the following:
* moving floor for the R package to `R (>= 4.0)`
* using C++17 unconditionally in the R package
- *this change only affects build from source on Windows*
- *all other builds (and all CRAN builds) have been using C++17 since January 2023 (#5690)*
In an earlier attempt (#7025), I also tried to update to testing on both R 4.0 and R 4.5.
Ran into some issues there on Windows... I think that Rtools have changed in significant ways between R minor versions.
So proposing this PR to get the easier-to-implement "just drop R 3.x" changes merged, to help unblock #7016
=> [R-package] [ci] drop support for R 3.x (fixes #7023)

docs/Installation-Guide.rst, windows/LightGBM.vcxproj, windows/LightGBM.vcxproj.filters
LightGBM can be built successfully from this branch with fresh VS2017 (https://aka.ms/vs/15/release/vs_community.exe) on very old Windows Server 2012 R2 Datacenter.
See https://github.com/microsoft/LightGBM/pull/7022#issuecomment-3351720297.
=> [ci] some additional changes to drop VS2015 and make it work from solution file

.ci/setup.sh, .ci/test-windows.ps1, docs/build-docs.sh
Just faced this issue in #7027.
```
Error while loading conda entry point: conda-libmamba-solver (cannot import name 'Spinner' from 'conda.common.io' (/Users/runner/miniforge/lib/python3.12/site-packages/conda/common/io.py))
CondaValueError: You have chosen a non-default solver backend (libmamba) but it was not recognized. Choose one of: classic
```
Refer to https://github.com/ilastik/ilastik/pull/3077.
=> [ci] fix recent conda and mamba matching error

.appveyor.yml, tests/python_package_test/test_arrow.py
After dropping support for VS2015 in #7022 we can run Arrow tests at Appveyor with VS2017.
=> [ci] stop skipping Arrow test at Appveyor
